### ISSUE TITLE
Add an e4 way to register a command/handler as an "open action"

### ISSUE THREAD

**Issue by sewe** [eclipse-platform/eclipse.platform.ui#10]
In the e4 programming model, I can do something like this to register a menu contribution declared in my `.e4xmi` with a control:

```java
eMenuService.registerContextMenu(control, MENU_ID);
```

Unfortunately, I cannot find a similar functionality for associating an "open action" (think `org.eclipse.jface.viewers.IOpenListener`) with a control. Could such a functionality be added? Or am I simply missing it?

**Comment by vogella** [comment]
@sewe currently not supported by the e4 model, I think the reason for this is that is not a frequent use case (at least I have never used this with my clilents so far). Currently you have to provide your own service for this and could use persitedState in the model to define this, or use the JFace API to do so.
