### ISSUE TITLE
SoftLimit: provide support for "Show in ..." & "Link with Editor"

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1014]
regression from https://github.com/eclipse-platform/eclipse.platform.ui/issues/818

When i use "Show in ... "/ "Project Explorer" or the "Link with Editor" button in the Project Explorer with a File that is currently not visible in the Tree those actions do nothing. They must reveal the selected item!
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/5879a818-98a9-4ed6-82db-7994154d4883)

Package Explorer at least asks
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/474c0b7a-ca81-44e7-971d-faa58d82330e)

... but that does not work either :-(

Example 
org.eclipse.ui.internal.views.markers.ExtendedMarkersView with default Increment set to 10
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/847a4112-9f79-4624-b298-85f82912c214)

"Show in .. Outline" at least jumps to "Show .... (more)" but also does not reveal anything.

**Comment by iloveeclipse** [comment]
Jörg, this is expected side effect, because selecting editor means expand **all** children up to the selected one would hang UI again assuming the number of hidden items (== limit) is high enough.

Note, that the limit of 10 is not default. So I tend to close this issue as "won't fix".

Actually this use case is one of the most prominent "hang" reasons we've got reported by users.

**Comment by laeubi** [comment]
>  because selecting editor means expand all children up to the selected one would hang UI again

As the viewer actually has all element loaded it would be possible to find this element and only show this (e.g. temporary) single element.

> Note, that the limit of 10 is not default. So I tend to close this issue as "won't fix".

does it matter if it is the 10 or 1000 element that is not shown? How would a user recover from this case? Expand all elements by hand and hope to find the one of interest in reasonable time?

**Comment by iloveeclipse** [comment]
> it would be possible to find this element and only show this (e.g. temporary) single element.

In theory yes, in practice the problem would be that these elements will appear "unsorted" once user clicks "show more.." to see more elements. But we can evaluate if we can remember elements shown "out of order" to remove them later on. 

> does it matter if it is the 10 or 1000 element that is not shown?

Yes, most users will be not affected by the limit of 1000 elements. So we are talking here about not common use case.

> How would a user recover from this case? Expand all elements by hand and hope to find the one of interest in reasonable time?

Yes, but compared to UI hanging for indefinite time without further way to stop hanging this gives the user opportunity to stop clicking at any time.

**Comment by laeubi** [comment]
As an alternative, a dialog might be show asking the user to reveal all elements up to the requested one...

**Comment by iloveeclipse** [comment]
> As an alternative, a dialog might be show asking the user to reveal all elements up to the requested one...

This makes sense, a **cancellable** progress dialog...

**Comment by jukzi** [comment]
I favor a question as Package Explorer does to reveal Element.

Would **also** be cool if revealing could be cancel able, but that requires die UI to be responsive during that action. When swt/OS is so damn slow to view a million items, it won't be possible to cancel during that. But if it is only that the UI is so slow because one element after another is added it would be better to improve that pattern for performance.

for comparison: In VisualVm such action is not a problem because they just (de)collapse the node where the other elements are in.

**Comment by jukzi** [comment]
For me having actions that just do nothing, without feedback to user, is a show-stopper.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/issues/1041 would make this issue less critical or even not relevant.

**Comment by PyvesB** [comment]
> For me having actions that just do nothing, without feedback to user, is a show-stopper.

I fully agree with this. Right now `Link with Editor` and `Show In` features are regularly broken in the IDE because of the new Viewer Limit feature, I've effectively had to disable it.

**Comment by iloveeclipse** [comment]
> > For me having actions that just do nothing, without feedback to user, is a show-stopper.
> 
> I fully agree with this. Right now `Link with Editor` and `Show In` features are regularly broken in the IDE because of the new Viewer Limit feature, I've effectively had to disable it.

First of all: you **can** disable it (or just set a higher limit) but you would be unable to disable UI freezes without the limit. So we have a choice now.

Second: it is an open source project. Please consider to contribute if you believe there is a possibility to improve.
