### ISSUE TITLE
SoftLimit: "Show Next" problems in Search Result

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1024]
from https://github.com/eclipse-platform/eclipse.platform.ui/issues/818
 "Show Next" in the Search View does not work as i expect.
It reveals the next item (good) 
but does not remove the "Show ..." node, leading to nested "Show ..." nodes.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/0d8b132e-1d79-4cce-a928-b55f53915ac4)

**Comment by iloveeclipse** [comment]
@raghucssit will look into that.

**Comment by iloveeclipse** [comment]
Fixed by disabling soft limit for the Search view via https://github.com/eclipse-platform/eclipse.platform.ui/issues/1024.

**Comment by jukzi** [comment]
> via #1024.

#1039
