### ISSUE TITLE
set viewer limit to 0 and mark ColumnViewer#setDisplayIncrementally(int incrementSize) as provisional

### ISSUE THREAD

**Issue by raghucssit** [eclipse-platform/eclipse.platform.ui#1030]
As we have observed many issues after enabling viewer limit on platform we will disable the viewer limit for all the viewers configured.
Also mark the ColumnViewer#setDisplayIncrementally(int incrementSize) as provisional

See discussion on https://github.com/eclipse-platform/eclipse.platform.ui/issues/818

**Comment by iloveeclipse** [comment]
@raghucssit please don't disable in viewers, only set preference to zero by default

**Comment by raghucssit** [comment]
> @raghucssit please don't disable in viewers, only set preference to zero by default

yes. i have set preference to zero
