### ISSUE TITLE
SoftLimit: changing limit collapses all view

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1033]
1. expand nodes in package explorer/problems
2. change the limit in the preference
-> package explorer, problems view are collapsed, selection lost.

Even if limit was increased. Example 10->100:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/a8471b22-9524-4989-b9b9-cbd38c4c69d6)

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/22dce424-d539-476c-a1cf-b1e6e2db2d44)

**Comment by iloveeclipse** [comment]
Jörg, changing limit changes viewer, and one can't keep previous state. So a full refresh/reset is needed.
