### ISSUE TITLE
Multiselection: lost after restart

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#1047]
# How to reproduce
1) Press Ctrl+F
2) Enter a search term for a word that is contained multiple times in the file
3) Press "Select All"
4) Immediately close eclipse
5) Reopen eclipse
 
I am not sure if there are other way to select multiple words at once in eclipse. If that mechanism exists, it would be interesting to see if the same behaviour still applies.

# Expected behaviour
After restarting eclipse, I expect the same - multiple - areas to still be part of my selection, instead of having one selection that spans from the first to the last selection.

# Screenshots
After Step 3)
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/2249e12b-5454-4141-8fc2-fe081cc51d0b)
After step 5)
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/68a84df0-863c-4b0d-b1f1-4ddd34d8f22a)

# My setup
Eclipse IDE for RCP and RAP Developers (includes Incubating components)

Version: 2023-06 (4.28.0)
Build id: 20230608-1333

**Comment by jukzi** [comment]
@mickaelistria  caused by implementing multiselection: https://github.com/eclipse-platform/eclipse.platform.ui/commit/13e3e7a5866fb13f479253382030907238a54ee2

@Wittmaxi If you need that feature please contribute a PR for saving multiselection

**Comment by mickaelistria** [comment]
It indeed looks like the editor only persists simple selections properly: block selection is discarded and multi-selection is joined (as described in this issue).
We would need a way to improve how the workspace persists the selections to better cover the various type. This would happen in a combination of changes in `AbstractTextEditor#saveState` and `AbstractTextEditor#doRestoreState` to support multiple selections. A PR would be welcome (note that backward compatibiity must be guaranteed, so `doRestoreState` would need to still be able to part legacy memento.
