### ISSUE TITLE
SoftLimit: org.eclipse.ui should bump version because of updated API in reexported org.eclipse.jface and org.eclipse.ui.workbench bundles

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1051]
When i OOmph product "Eclipse IDE for Eclipse Committers" + project "Platform" then i end up in a workspace with this error:
![image](https://github.com/eclipse-platform/.github/assets/51790620/9e1294d3-b23b-4f66-af3f-448f045cfab0)
```
Failed to create the part's controls
java.lang.NoClassDefFoundError: org/eclipse/ui/views/WorkbenchViewerSetup
	at org.eclipse.jdt.internal.ui.packageview.PackageExplorerPart.createPartControl(PackageExplorerPart.java:499)

```	
@iloveeclipse some dependency missing?

**Comment by iloveeclipse** [comment]
> some dependency missing?

Most likely not missing but wrong (too old) version. I will check, should be just range update needed.

**Comment by jukzi** [comment]
The NoClassDef issue was solved, but i wonder, why the Preferences do NOT show the SoftLimit Option:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/c6eb05d6-2bfa-47fa-b28d-140edf7e850f)
probably still not all current versions used

**Comment by laeubi** [comment]
@vik-chand would it be possible to have an error in API tools if code uses a method/class that has a higher `@since` than is currently imported to the bundle?

**Comment by iloveeclipse** [comment]
@jukzi : which version your `org.eclipse.ui.workbench` bundle shows? Note, the preference was added with the very first merged patch, so if you saw it before but do not see it now, you are using **older** `org.eclipse.ui.workbench` bundle!

It is not about dependencies in versions - preference in `org.eclipse.ui.workbench` bundle is "built in", it is about your Oomph installation.

Could it be you are using 4.28 Oomph install or update site?

See what we have in "default" 4.29 SDK I20230822-1800 build: 
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/28fae7f9-0926-438a-b4ba-08af6852e25a)

**Comment by iloveeclipse** [comment]
What I can imagine, is that you have your .p2 bundle pool containing an "older" `org.eclipse.ui.workbench` bundle from an early 4.29 I build and for whatever reason Oomph/p2 do not update the bundle (probably because only qualifier changed).
Cleaning up or deleting .p2 bundle pool would get rid of that artifact and Oomph will most likely take latest one.

**If** this above is the case, it would be probably Oomph or p2 bug, which most likely assumed that bundles need to change any of major.minor.service segment to be updated. For nightly builds this is not the case, once any segment is changed in the release time, it will stay "as is" (untile might be higher segment will be touched).

**Comment by jukzi** [comment]
I got an old version:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/dfa4df1a-e508-4003-95c5-722ab2dfbfbf)
I used OOmph product "Eclipse IDE for Eclipse Committers" + project "Platform", i disabled p2 pooling.

When i instead use the PlatformSDKConfiguration https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true then i do see the preference.

**Comment by iloveeclipse** [comment]
OK, @merks should know what's difference between profiles mentioned and if something need to be fixed there.

**Comment by merks** [comment]
Sometimes I get the impression that the server is returning time stamps that make caches not non-stale.  When in doubt remove all cached (Clear Cache...) information:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/c64dd164-665f-4f6e-9e5b-a244362aaacd)

I did that first...

I see these being loaded:

Fetching content.xml from https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230821-2010/
Fetching content.xml from https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230822-0600/
Fetching content.xml from https://download.eclipse.org/eclipse/updates/4.29-I-builds/I20230822-1800/

And I see this installed:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/49ff32d7-e57e-4000-a8db-a323608c9833)

Probably I should have first tried without flushing the caches first...  Sorry...

**Comment by jukzi** [comment]
i tried clear cache and even cleanup agent and still get workbench 3.129

```
Executing bootstrap tasks
OpenJDK Runtime Environment 17.0.7+7
Product org.eclipse.products.epp.package.committers.latest
Bundle org.eclipse.oomph.setup 1.26.0.v20230416-0656, build=5945, branch=c5558820f367665758d4d719b7553a02ff4954e0
Bundle org.eclipse.oomph.setup.core 1.27.0.v20230402-0730, build=5945, branch=c5558820f367665758d4d719b7553a02ff4954e0
Bundle org.eclipse.oomph.setup.installer 1.29.0.v20230607-0524, build=5945, branch=c5558820f367665758d4d719b7553a02ff4954e0
Bundle org.eclipse.oomph.setup.p2 1.19.0.v20230416-1150, build=5945, branch=c5558820f367665758d4d719b7553a02ff4954e0
Performing P2 Director (Eclipse IDE for Eclipse Committers (2023-09))
Offline = false
Mirrors = true
Resolving 57 requirements from 3 repositories to C:\Users\jkubitz\committers-latest2023-08-23\eclipse
Requirement org.eclipse.equinox.p2.iu:epp.package.committers [4.29.0,5.0.0) (filter=(|(&(osgi.arch=aarch64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=aarch64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=linux)(osgi.ws=gtk))(&(osgi.arch=x86_64)(osgi.os=macosx)(osgi.ws=cocoa))(&(osgi.arch=x86_64)(osgi.os=win32)(osgi.ws=win32))))
Requirement org.eclipse.equinox.p2.iu:org.eclipse.platform.feature.group [4.29.0,5.0.0)
Requirement org.eclipse.equinox.p2.iu:org.eclipse.rcp.feature.group [4.29.0,5.0.0)

....

Installing org.eclipse.ui.workbench [3.129.100.v20230711-1827]
Installing org.eclipse.ui.workbench.source [3.129.100.v20230711-1827]

```

**Comment by merks** [comment]
You've installed an EPP package and that locks in a specific version of the Platform.  That will not be updated until M3 is available on Friday.  The SDK setup configuration installs the Platform SDK product and only with that can you update to the latest I-Build.

I.e., this is the eat-your-own-dogfood version that allows updates to the most recent I-Build:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/a8826d14-0afd-4240-be7e-cdc000ba8a31)

**Comment by jukzi** [comment]
i'l wait till next week

**Comment by merks** [comment]
Note that at that point, you will see the m3 version of the Platform, not the (soon to be current) rc1 version, which you won't see until the following Friday...

**Comment by jukzi** [comment]
> Note that at that point, you will see the m3 version of the Platform, not the (soon to be current) rc1 version, which you won't see until the following Friday...

Works now. I wonder why the installation says M3
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/5c0d2243-2935-4862-ab85-91422a905913)

**Comment by merks** [comment]
I made the updated catalogs for m3 visible about 1.5 hours ago so all the EPP products will show that.
