### ISSUE TITLE
ECLIPSE Deadlocks when CLOSING (!) an editor when some 10 editors are open.

### ISSUE THREAD

**Issue by Sciuriware** [eclipse-platform/eclipse.platform.ui#1079]
This issue was introduced in version 4.28 (never seen it before).
Situation: 10 or more editors are open, I close one or two and get a busy cursor.
The only thing to do is kill it: unsaved text lost.
(some text could be saved by making a screen shot before killing; there is no other way).
Restart goes without problem, more editors can be closed without deadlock.

Current version: 4.28, Language JAVA 20.02, OS=MacOS 11.7.9 (BigSur).
;JOOP!

**Comment by iloveeclipse** [comment]
Please attach jstack from the deadlock, and exact steps to reproduce.

**Comment by Sciuriware** [comment]
Please tell me: what is jstack and where to find it.

New info: I just had a deadlock when closing the last of only 6 editors.
I had not been editing, only viewing.
;JOOP!

**Comment by merks** [comment]
You can Google "what is jstack".    You'll find it in the same  folder where the java executable is located, i.e., in the JDK's bin folder.

This article might help:

https://www.baeldung.com/java-thread-dump

**Comment by Sciuriware** [comment]
Sorry, I never had to use jstack in 22 years, so I did not know it.
Well, I upgraded Eclipse to 4.29RC2a to be sure pending problems were mended, then I opened 20 sources,
edited some, started closing those editors. When closing number 14 (leaving 13 editors open) Eclipse deadlocked.
Attached the Activity Monitor output revealing more than one CPU core involved and the jstack dump.
;JOOP!
<img width="967" alt="ActivityMonitorOutput" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/121790387/c3cf2058-285f-4336-8ee2-cbd44ca23aa6">
[JstackOutput.txt](https://github.com/eclipse-platform/eclipse.platform.ui/files/12535061/JstackOutput.txt)

**Comment by iloveeclipse** [comment]
Looking on jstack I assume this could be Mac specific SWT issue related to the focus handling, but might be also related to some e4 context switch issues, I see `org.eclipse.e4.core.internal.contexts.EclipseContext.activateBranch(EclipseContext.java:670)` many timmes on stack.

**Comment by Sciuriware** [comment]
It happened again with the latest release (4.29) and this time it was AFTER saving (lucky me) all editors and closing some.
So, not the same situation: I started with 10 sources open and it deadlocked (beachbal) after closing number 7.
;JOOP!

**Comment by laeubi** [comment]
Closing many editors fells also slow on Linux ... for me it seems as if it is not a batch operation (what should be fast) but happens that one editor is closed, now the next gets focus, what triggers some actions (e.g. update views that listen for a selection change like Outline View), then closes the next, another gets focus and so on...

**Comment by Sciuriware** [comment]
If only there was some indication WHERE it loops ...
;JOOP!

**Comment by laeubi** [comment]
Usually you can try to sample multiple JStacks at different times, then compare them to see if there is some progress/change (infinite loop) or if it *always* is the same (deadlock).

**Comment by Sciuriware** [comment]
Until now I did not seem to have this problem with 4.30M1. But I will continue testing.
;JOOP!

**Comment by Sciuriware** [comment]
It happened again with 4.30M1.
Continued ...
;JOOP!

**Comment by Sciuriware** [comment]
Today the lock and beach ball happened with only 8 editors open and not by closing one but by addressing a hidden one.
With 'hidden' I mean the little drop down list of editors when their tabs do not fit on the pane header.
;JOOP!

**Comment by vogella** [comment]
can you run jstack on the frozen Eclipse and post the stack traces here?

**Comment by Sciuriware** [comment]
I had Eclipse already killed (Forced!); I will send jstacks of all future lock-downs.
Surely they will occur.
;JOOP!

**Comment by Sciuriware** [comment]
With 13 (!) editors open (1 hidden) when opening the hidden editor ...
;JOOP!
[jstack.txt](https://github.com/eclipse-platform/eclipse.platform.ui/files/12858993/jstack.txt)

**Comment by iloveeclipse** [comment]
Same stack as [before](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1079#issuecomment-1728110555).

**Comment by Sciuriware** [comment]
On the contrary: I compared and found 115 differences.
Continued ...
;JOOP!

**Comment by szarnekow** [comment]
Does the slowness reproduce if you disable the Java Breadcrump view?

**Comment by Sciuriware** [comment]
Slowness? It remains in lock down for a long time (I didn't wait for hours ... ); I gave it a Force Quit on the Dock.
Do you think that Eclipse won't lock when the breadcrumb is disabled?
We'll try.
;JOOP!

**Comment by Sciuriware** [comment]
I tested intensively on 2 machines, INTEL and SILICON, both with Breadcrumb disabled ... no lock down yet.
Continued ...
;JOOP!

**Comment by Sciuriware** [comment]
I overloaded Eclipse several times with editors but since I disabled Breadcrumb no lockdowns occurred.
I'm surprised that this would solve the case. Anyway, I think I can live without the crumbs.
;JOOP!

**Comment by szarnekow** [comment]
Thank you for reporting back. This ticket can be moved to jdt.ui by someone who has the necessary rights.

**Comment by mickaelistria** [comment]
@szarnekow Unfortunately, I don't think it's a matter of rights, but more that it's not possible to move an issue between 2 different repositories if they are from different organizations.
@Sciuriware Please open a ticket to JDT UI mentioning that this issue happens with the breadcrumbs enabled in the Java editor only

**Comment by Sciuriware** [comment]
DONE: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/860
Thanks to all of you for contributing.
;JOOP!
