### ISSUE TITLE
[Eclipse 4.28] Toggled State for view menu actions with Icon not visible in Win 11

### ISSUE THREAD

**Issue by stockbal** [eclipse-platform/eclipse.platform.ui#1083]
There currently seems to be an issue with view menu actions of type "check" (i.e. toggle actions), that I noticed in Windows 11. In Windows 10 every worked fine.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/35834861/7dd22297-3d4f-4677-9223-578827309fc7)

As you can see in the above view menu of the Project Explorer view, the toggle state is correctly displayed for actions in the toolbar of the view (1 in the screenshot). It is also visible for toggle actions that do not have an Icon (see 2 in the screenshot).
But for toggle actions with Icons there is no colored background (3 in the screenshot).

**Comment by merks** [comment]
I think this is the same (very annoying!) issue as this one:

https://github.com/eclipse-platform/eclipse.platform.swt/issues/501
