### ISSUE TITLE
How to develop / debug the Workspace Chooser?

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#11]
I'd like to debug some things related to the workspace chooser (especially the problem with plugins starting "too early") but when I launch an IDE from my workspace the workspace chooser never appears (what seems a perquisite to trigger the problem).

So what is the recommended way to do so? Exporting a product and using remote debugging seems like it will slow-down such testings a lot...

**Comment by merks** [comment]
Use `@noDefault` as the Workspace Location on the Main tab of the launch configuration.

https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fmisc%2Fruntime-options.html&anchor=locations

**Comment by laeubi** [comment]
Many thanks I haven't even considered that these are valid values in the UI!

**Comment by iloveeclipse** [comment]
Just leave the workspace location field empty in the launch config :)
