### ISSUE TITLE
Javadoc for o.e.ui.workbench cannot be generated

### ISSUE THREAD

**Issue by marcushoepfner** [eclipse-platform/eclipse.platform.ui#1103]
Refer to PR #964.
The build fails due to unknown tags.
See the log: https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-964/5/consoleFull

E.g. 
09:03:07.765 [ERROR] MavenReportException: Error while generating Javadoc: 
Exit code: 1 - /home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/IWorkbenchHelpContextIds.java:28: error: unknown tag: issue
 * @issue this class has been xcloned to org.eclipse.ui.internal.ide package;
   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/menus/DynamicMenuContributionItem.java:35: warning: empty <p> tag
 * <p>
   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/menus/DynamicToolBarContributionItem.java:35: warning: empty <p> tag
 * <p>
   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/misc/StatusUtil.java:31: error: unknown tag: private
 * @private - This class is an internal implementation class and should not be
   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/registry/ActionSetDescriptor.java:124: warning: empty <p> tag
	 * <p>
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/registry/IWorkbenchRegistryConstants.java:815: error: reference not found
	 * {@link SOrder#POSITION_AFTER}.
	          ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/registry/IWorkbenchRegistryConstants.java:821: error: reference not found
	 * {@link SOrder#POSITION_BEFORE}.
	          ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/registry/IWorkbenchRegistryConstants.java:827: error: reference not found
	 * {@link SOrder#POSITION_END}.
	          ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/registry/IWorkbenchRegistryConstants.java:833: error: reference not found
	 * {@link SOrder#POSITION_START}.
	          ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/registry/EditorDescriptor.java:562: error: unknown tag: issue
	 * @issue this method is public as a temporary fix for bug 47600
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/IPreferenceConstants.java:232: error: unexpected end tag: </p>
	 * </p>
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/misc/TestPartListener.java:27: error: unknown tag: issue
	 * @issue seems like garbage - no one using it
	   ^
/home/jenkins/agent/workspace/eclipse.platform.ui_PR-964/bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/WorkbenchPlugin.java:164: error: unknown tag: issue
	 * @issue we should just drop this constant and use PlatformUI.PLUGIN_ID instead
	   ^
10 errors
3 warnings

**Comment by iloveeclipse** [comment]
Thanks Marcus, really appreciating your work!
