### ISSUE TITLE
File Search should offer to search in all opened editors

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1116]
In the dialog below I miss the possibility to search & replace in **all** opened editors, not only in the currently active one.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/6b494c32-7d67-4c17-ab9e-1e3c2f1e2322)

I do not see any good reason why we should allow to search / replace in only the currently opened editor, so I would propose to change the dialog above and 
- either change the option "Resource in active editor" to "Resources in opened editors"
- or just add the option "Resources in opened editors"

**Comment by mickaelistria** [comment]
I think it makes sense to remove this option and allow "Resources in opened editors".
Some things to consider:
* this option depends on the currently active view. Eg if in Project Explorer, it usually shows "Selected resources in Project Explorer" (which is located at the same place, but maybe not the same option, so maybe not so relevant)
* Editors that do not have a resource would not be searched

**Comment by iloveeclipse** [comment]
> * this option depends on the currently active view. Eg if in Project Explorer, it usually shows "Selected resources in Project Explorer" (which is located at the same place, but maybe not the same option, so maybe not so relevant)

But then I would really want a dedicated option to search all opened editors that doesn't need to take care about any possible active view/editor selection.

> Editors that do not have a resource would not be searched

Sure.

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/1133 with proposal.
