### ISSUE TITLE
org.eclipse.platform.doc.isv help can't be indexed

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1120]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1105.

I see following error after opening Help & starting search:
```
eclipse.buildId=4.30.0.I20230915-0520
java.version=17.0.6

org.eclipse.help.base
Error
Fri Sep 15 13:27:12 CEST 2023
Help document /org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_search_textSearchEngine.html cannot be opened.
```

**Comment by iloveeclipse** [comment]
@mickaelistria: please take a look.

**Comment by mickaelistria** [comment]
I suspect https://github.com/eclipse-platform/eclipse.platform.ui/pull/1119 will fix it.

**Comment by mickaelistria** [comment]
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1374 should actually be the right fix now.

**Comment by mickaelistria** [comment]
Seems working now. Feel free to reopen if not.
