### ISSUE TITLE
[e4] support new jakarta.inject

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#1129]
Currently E4 supports `javax.*` but this is replaced by new `jakarta.*` namespace:

- https://jakarta.ee/specifications/dependency-injection/2.0/apidocs/
- https://jakarta.ee/specifications/annotations/2.0/apidocs/jakarta.annotation/jakarta/annotation/package-summary

E4 should allow uses to simply use both annotations in parallel (and maybe even warn in the IDE or at runtime if the "old" namespace is used).

**Comment by akurtakov** [comment]
That would be very nice work!

**Comment by HannesWell** [comment]
See also https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056.

In general I think it should not be too complicated and the injector should simply look for the new and old annotations and the bundle could import both as optional dependencies and should be prepared that both are potentially absent.

**Comment by HannesWell** [comment]
With https://github.com/eclipse-platform/eclipse.platform/pull/696 merged, I think we can consider this done.
