### ISSUE TITLE
git synchronize overwrite, shows and overwrites with wrong version of file

### ISSUE THREAD

**Issue by r6squeegee** [eclipse-platform/eclipse.platform.ui#1134]
I have an old branch which was never merged into "main", the branch has 2 commits :

- oldbranch-commit1
- oldbranch-commit2

I'm on my main branch now which is much newer, I'm trying to retrieve some files which currently don't exist, but they existed in the oldbranch.

- right click on my project -> compare with -> branch tag or reference
- select oldbranch-commit2
- open synchronization prespective

I find the file which currently does not exist on my main branch
- double click on it, and the compare editor shows the file from oldbranch-commit1 not oldbranch-commit2.
- right click on the set of files and select "overwrite" results in oldbranch-commit1 files, not oldbranch-commit2 files.

since I selected compare with oldbranch-commit2, I would have expected it to compare with, and overwrite with, oldbranch-commit2.

This will eventually get what I want if I just keep clicking overwrite, but it was entirely unexpected and took a while for me to figure this out. This would also be difficult if some one was trying to overwrite from a branch that had a lot of commits (imaging 20 commits) they would have to click overwrite 20 times.

eclipse version : 2023-06 4.28.0
build id : 20230608-1333

git integration for eclipse : 6.6.0.20230530101

**Comment by merks** [comment]
Please look on this page for where to report a problem about git integration 

https://projects.eclipse.org/projects/technology.egit/developer
