### ISSUE TITLE
Remove MultiPageEditor API

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.ui#1155]
Deprecated in 2002 and marked for deletion after 2023-03 with https://bugs.eclipse.org/bugs/show_bug.cgi?id=547018

**Comment by merks** [comment]
I was so scared 😱 but confused org.eclipse.ui.part.MultiPageEditor with org.eclipse.ui.part.MultiPageEditorPart. 😌

**Comment by akurtakov** [comment]
Yeah, I know. There are so many such cases that confuse us (long time contributors) so I don't want to even imagine what happens for someone trying to write an eclipse plugin without this being his full time job.
