### ISSUE TITLE
Error during Java Build

### ISSUE THREAD

**Issue by MyhreAndersen** [eclipse-platform/eclipse.platform.ui#1157]
I got an error during build:

Errors occurred during the build.
Errors running builder 'Java Builder' on project 'JavaClassFile_Glavo'.
Cannot invoke "org.eclipse.jdt.internal.compiler.lookup.TypeBinding.needsUncheckedConversion(org.eclipse.jdt.internal.compiler.lookup.TypeBinding)" because "argumentType" is null.

The error occurs when I compile a pre-release of java.lang.classfile.
Seems to have something to do with switch-expression:

	default CodeBuilder constantInstruction(Opcode opcode, ConstantDesc value) {
        BytecodeHelpers.validateValue(opcode, value);
        return with(switch (opcode) {
            case SIPUSH, BIPUSH -> ConstantInstruction.ofArgument(opcode, ((Number)value).intValue());
            case LDC, LDC_W, LDC2_W -> ConstantInstruction.ofLoad(opcode, BytecodeHelpers.constantEntry(constantPool(), value));
            default -> ConstantInstruction.ofIntrinsic(opcode);
        });
    }

SEE: https://github.com/Glavo/classfile/tree/main

System used:

Eclipse IDE for Java Developers (includes Incubating components)

Version: 2023-06 (4.28.0)
Build id: 20230608-1333

Works perfectly fine with IntelliJ IDEA 2023.2 (Community Edition)

**Comment by iloveeclipse** [comment]
> Version: 2023-06 (4.28.0)

Can you please try with **latest** Eclipse version?

**Comment by MyhreAndersen** [comment]
Tried again with Version: 2023-09 (4.29.0) Build id: 20230907-1323
I have tested with Java Jdk21 and Jdk22-ea

The error is gone but I get a long list of errors from the underlying Java compiler.
- Cycle detected: a cycle exists in the type hierarchy between CustomAttribute<T> and UnboundAttribute<T>
- ChainedClassBuilder cannot be resolved to a variable
- The hierarchy of the type CodeImpl is inconsistent

Could it be an Eclipse or Java option that I have overlooked?

It would be nice if someone else tried to compile https://github.com/Glavo/classfile/tree/main

It still works perfectly fine with IntelliJ IDEA 2023.2 (Community Edition)

**Comment by iloveeclipse** [comment]
Could you please report the problem here: https://github.com/eclipse-jdt/eclipse.jdt.core/issues
In the new bug, please attach workspace log.
