### ISSUE TITLE
Option to center the message in PlainMessageDialog

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#116]
Currently PlainMessageDialog provides a builder pattern for message dialogs but does not allow to center the message text, the text is way to the left alligned.

Example: 

![image](https://user-images.githubusercontent.com/139910/172818526-0164f0ce-f657-460c-ad07-3667702d911c.png)

See https://github.com/eclipse-pde/eclipse.pde/issues/149 for screenshots of OS dialogs

We should add an option to the builder to center the text of the message. 

@marcushoepfner WDYT?

**Comment by vogella** [comment]
Another dialog which would look "too left" without the icon.

![image](https://user-images.githubusercontent.com/139910/172822486-9432ca31-198f-466e-b716-75722c135889.png)

**Comment by vogella** [comment]
Tbh centering the text looks IMHO bad

![image](https://user-images.githubusercontent.com/139910/172888102-e47448ff-794a-4e4a-8bf3-0e9d6f3effe4.png)

**Comment by vogella** [comment]
For reference add this to PlainMessageDialog if you want to test it.

	
	@Override
	protected int getMessageLabelStyle() {
		int messageLabelStyle = super.getMessageLabelStyle();
		if (getImage()==null) {
			messageLabelStyle = messageLabelStyle | SWT.CENTER;
		}
		return messageLabelStyle;
	}


I close this, I don't think it is a good way forward.

**Comment by mickaelistria** [comment]
> Tbh centering the text looks IMHO bad

I personally don't find it bad, and I find it looks more familiar with what I usually see from other apps.
You recently linked https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts/ , https://developer.gnome.org/hig/patterns/feedback/dialogs.html  and https://docs.microsoft.com/en-us/windows/apps/design/controls/dialogs-and-flyouts/dialogs . 2 of them do center the content in alert popups.
So it's not objectively bad to center it; however it's there is no unanimous input to tell whether to switch it or not.

**Comment by akurtakov** [comment]
It looks bad because of word wrap on "-" symbol which makes the information look broken (path being on 2 lines).

**Comment by mickaelistria** [comment]
> t looks bad because of word wrap on "-" symbol which makes the information look broken (path being on 2 lines).

OK. But I think this is more an issue for consumers to add the right line break, or -is it possible?- to instruct SWT that a range is not wrappable. In such case, we could change the PlainMessageDialog right now and leave time for consumers to adapt.

About this being different on different OS, maybe we could decide of the style according to the OS.
