### ISSUE TITLE
Consume new IResourceSnapshot API in place of ResourceDescription

### ISSUE THREAD

**Issue by robstryker** [eclipse-platform/eclipse.platform.ui#1162]
platform.core has a new IResourceSnapshot API which replaces the ResourceDescription classes. This should be consumed by ui.ide if at all possible to clean up and remove old code and standardize on the new classes.

**Comment by vogella** [comment]
Can you also put the new Resource API in to the N&N 4.30? I did not follow the commits in platform.core and would like to read what this new API is about.

**Comment by robstryker** [comment]
@vogella  where does one add to n&n? 

These are classes that were previously inside the `org.eclipse.ui.ide` plugin and relate primarily to undo operations. It seems JDT was making extensive use of these in some of their operations. JDT underwent a refactor to move large swaths of code into bundles not dependent on UI. The presence of these classes in ui.ide, instead of in a core bundle, meant that jdt would either need to duplicate these classes, or the classes would need to be moved down to a core bundle. After some discussion, moving them down into platform.core and giving them a package name that made their purpose more clear was agreed upon. 

I'll be happy to add to n&n if someone can point me how to do so.

**Comment by mickaelistria** [comment]
Adding content to the N&N is achieved by sending a PR to https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/ ( 4.30/platform_isv.html in this case).
