### ISSUE TITLE
[Dark Theme] Text.setMessage: Message text barely visible

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#1171]
## Description
When in dark-theme, the message-string of a Text-widget is barely visible

## Reproducing
Using this code, create a Text-Widget.
```
searchBar = new Text(searchContainer, SWT.SINGLE);
searchBar.setMessage(" 🔎 Find"); //$NON-NLS-1$
```

In light mode: 
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/dfdb8a79-299a-4d85-91a6-ff6449ca7c47)

In dark mode:
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/fb0f7af4-3910-410d-949c-20a83f8f7967)

## Expected behaviour
I expect the input bar to clearly display the message-text in both themes. Additionally, the "bounding box" of the bar is not visible in dark mode - possibly subject to a second issue.

## System Information
Eclipse SDK

Version: 2023-12 (4.30)
Build id: I20230913-1800

## MISC
When I apply the `SWT.SEARCH`-stylebit, the background is more visible, also rendering the message-string visible.
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/13c42441-ffc4-47a7-bda6-af61209cf00f)

**Comment by vogella** [comment]
Isn't that handled in SWT? I don't think we can style this message in platform

**Comment by Wittmaxi** [comment]
My rationale for putting this issue here is that the I believe that the different themes are defined in Platform (I might be wrong about this).
If you believe it makes more sense to have it in SWT, I will duplicate this issue.

**Comment by vogella** [comment]
@Wittmaxi Try to reproduce with the SWT widget examples and see if it is the same in SWT before creating a SWT issue.  I close it here, unless you have an idea on how to handle it in platform styling.
