### ISSUE TITLE
Bad UI on MacOS for merge viewer

### ISSUE THREAD

**Issue by zulus** [eclipse-platform/eclipse.platform.ui#1173]
I'm able to reproduce with any viewer, for example java:

1. Rename file in Project Explorer
2. Show change preview
3. Switch between files via mouse (via keyboard works fine), not always appear on first time

Result on screen, viewer is extremely small (see screen)
<img width="1127" alt="Screenshot 2023-09-26 at 12 40 33" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/549039/e85aacc6-b828-4acd-8cac-c381ae9fb5d8">

**Comment by iloveeclipse** [comment]
Is this a regression? If yes, in which version?

Note: there aren't many contributors with Mac access, so if you can reproduce & fix, patch is welcome.

**Comment by zulus** [comment]
> Is this a regression? If yes, in which version?

Regression definitely, but at least 4 releases, today this just driving me crazy :P (I saw this on JDT, PDT and GenericEditor)

> Note: there aren't many contributors with Mac access, so if you can reproduce & fix, patch is welcome.

First I have to find correct UI classes

In general I have a lot of small but sometimes annoying UI issues on MacOS, I'll see what I can do ;)

**Comment by iloveeclipse** [comment]
> First I have to find correct UI classes

CompareEditor, StructureDiffViewer, DiffTreeViewer

**Comment by vogella** [comment]
Cool to see someone else using the dark theme @zulus Thanks for looking into this issue.

**Comment by zulus** [comment]
> CompareEditor, StructureDiffViewer, DiffTreeViewer

Look like problem is earlier, on SWT Tree:

When works correctly I see SWT events:

* down
* select
* up

Is broken when eclipse receive

* down
* up
* mouse exit (why???)
* up (duplicated event)
* select 

I have no idea why :( Display sends exit event because Display.findControl return null (this is checked inside applicationSendTrackingEvent)

**Comment by akurtakov** [comment]
@Phillipus maybe you can manage to give some hints here

**Comment by Phillipus** [comment]
> @Phillipus maybe you can manage to give some hints here

~I can't reproduce this.~

I'm on macOS Ventura M1 Silicon with hi-dpi screen. Eclipse 4.28, Java 17.

Maybe I'm missing a step to reproduce this?

**Comment by Phillipus** [comment]
Update. I tried on my MacBook Air, Intel, macOS Ventura with track pad and I'm seeing this too. Not sure if this is an Intel vs Silicon thing or a mouse vs trackpad thing. Resizing the dialog window forces proper display.

Edit: Can now see this behaviour on Mac M1 with mouse.

**Comment by zulus** [comment]
> @zulus It would help if you could provide more details for macOS version, Mac version, Eclipse version, Java version etc...

Java 17 Temurin, Ventura 13.5.2 (m1 max), Eclipse 2023-09, I see this with magic mouse and trackpad

**Comment by Phillipus** [comment]
> Java 17 Temurin, Ventura 13.5.2 (m1 max), Eclipse 2023-09, I see this with magic mouse and trackpad

Thanks. Since my previous messages I'm also able to reproduce this with mouse or trackpad on Intel and Mac Silicon.

**Comment by zulus** [comment]
I think I understand what happens:

1. Mouse down (if don't up immediately you will always see this behaviour until up), it firesSelectionEvent
2. Select has been sent (if you keep mouse clicked will see same as on screen)
3. Mouse up (normally during this layout is relcalculated (event open), but if it hapen before select finish his job "up" event isn't able to detect view, because durin changing page, focus is updated, so "mouse select"/open have invalid data

Its due busy indicator, starts always during feedInput when documents are created  (it makes user interface inactive for a moment, so all layouts are suspended and wrongly calculated). If you move feedInput after showPage, UI looks a little bit better but it's still unusable.

**Comment by zulus** [comment]
I implemented workaround on LTK level: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/844

**Comment by iloveeclipse** [comment]
> I implemented workaround on LTK level: [eclipse-jdt/eclipse.jdt.ui#844](https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/844)

I believe this is not the right place to fix such (OS specific) issues. I would assume this is something on lower level, like SWT or Platform UI.

**Comment by zulus** [comment]
To be honest, platform issue is suspended layout. But in general, IChangePreviewViewers aren't correctly created, their merge viewers aren't connected to ICompareContainer, so in moment when DocumentMergeViewer prepare ranges during "doDiff" extra popup is created

**Comment by zulus** [comment]
OK, so now platform lvl fix https://github.com/eclipse-platform/eclipse.platform/pull/732 ;)

**Comment by zulus** [comment]
PR merged

**Comment by iloveeclipse** [comment]
Fix was reverted via https://github.com/eclipse-platform/eclipse.platform/pull/869 , see https://github.com/eclipse-platform/eclipse.platform/issues/868.

**Comment by BeckerWdf** [comment]
@tobiasmelcher:
Does your PR https://github.com/eclipse-platform/eclipse.platform/pull/1625 fix this UI glitch?

**Comment by tobiasmelcher** [comment]
> eclipse-platform/eclipse.platform#1625

No, org.eclipse.ltk.internal.ui.refactoring.PreviewWizardPage needs to be modified the similar way like in #1625 . Method showPreview cannot be called on selectionChanged but needs to be delayed to onMouseUp. I can do the change if you want.
