### ISSUE TITLE
Random failing VirtualLazyTreeViewerTest.testContains

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.ui#1183]
The test case `org.eclipse.jface.tests.viewers.VirtualLazyTreeViewerTest.testContains` is randomly failing, e.g., here: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1086/checks?check_run_id=17254557444

```
element must be available on the viewer
junit.framework.AssertionFailedError: element must be available on the viewer
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.TestCase.assertTrue(TestCase.java:192)
	at org.eclipse.jface.tests.viewers.AbstractTreeViewerTest.testContains(AbstractTreeViewerTest.java:318)
```

May be related to #1005.

**Comment by fedejeanne** [comment]
Failed again in [this build](https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/6772043819/job/18403747805?pr=1280) of #1280

**Comment by jukzi** [comment]
seems to fail on mac reproducible
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1537/checks?check_run_id=20724274542

```
element must be available on the viewer
java.lang.AssertionError: element must be available on the viewer
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.jface.tests.viewers.AbstractTreeViewerTest.testContains(AbstractTreeViewerTest.java:342)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

**Comment by HeikoKlare** [comment]
I did some debugging of the issue on Mac but since the issue occurs randomly, it is hard to reproduce (in particular in debug mode).

Several other test cases have been disabled for trees with lazy content providers on Mac (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=347491). When comparing the involved functionality of those tests with the one in the this random failing test, the failures seem to have the same root cause. Thus, I propose to disable this test case on Mac just like the others. The complete functionality for lazy content providers seems to somehow be broken on Mac anyway (as can be seen by all the other test cases being disabled).

**Comment by HeikoKlare** [comment]
Since the error message is not unique and line numbers change, just for the record: The assertions that fails it the first within the test case that expects the viewer to contains something, i.e.:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e6a807224d960b89b8747a0ce79dcc713ce42123/tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/viewers/AbstractTreeViewerTest.java#L341-L343
