### ISSUE TITLE
Move LTK from JDT to Platform?

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.ui#1195]
Platform counter-part of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/851

**Comment by mickaelistria** [comment]
Work on ongoing at https://github.com/eclipse-platform/eclipse.platform.ui/pull/1197

**Comment by vogella** [comment]
Is this done? Please add to N&N

**Comment by mickaelistria** [comment]
Yes, done. I don't think it's noteworthy as no new value was created nor nothing broken here. This change won't affect consumers of Platform.

**Comment by vogella** [comment]
So extenders like @zulus don't have to do anything? 

And thanks for this move, feels like parts are re-sorted to the correct place these days in almost no time.

**Comment by zulus** [comment]
Fortunately PDT, DLTK and even LSP4E rely on simrel. So as long as plugin/feature name remain untouched, everything should work correctly :)

**Comment by mickaelistria** [comment]
Even if relying on Platform repo, it wouldn't change anything as Platform and JDT are always shipped together there too.
