### ISSUE TITLE
Welcome page cuts off "Hide" label

### ISSUE THREAD

**Issue by kysmith-csg** [eclipse-platform/eclipse.platform.ui#1210]
On Mac as least, the "Hide" button text is cut off by the welcome content.
![Screenshot 2023-10-11 at 09 54 58](https://github.com/eclipse-platform/eclipse.platform.ui/assets/136501322/bdfd0314-eb07-4a30-9186-8e9f04091748)

This screenshot was taken on a 2560x1440 monitor, but having it on different screens doesn't affect it.
macOS Sonoma 14.0, M1 Max

This is not a regression since we have a ticket open to fix this in our product since 2018, but the issue lies elsewhere.

I think it may be font related? Increasing/decreasing the font size causes the button to move down, but no text on the header bar actually changes.
![fonts](https://github.com/eclipse-platform/eclipse.platform.ui/assets/136501322/9828d57e-7176-4e27-b2f0-f5b32cc66cc2)

**Comment by BeckerWdf** [comment]
We had to revert the fix.
