### ISSUE TITLE
Allow a dialog that uses CheckedTreeSelectionDialog to have empty tree

### ISSUE THREAD

**Issue by jjohnstn** [eclipse-platform/eclipse.platform.ui#1215]
A number of JDT dialogs use SourceActionDialog which sub-classes CheckedTreeSelectionDialog.  In some cases, such as Generate Constructor from Fields... it is possible to deselect all fields and the operation succeeds, however, if a user has a class that has no fields, the dialog is not opened and fails with an error dialog.  Opening the dialog with an empty tree does not work because the CheckedTreeSelectionDialog will change the status to error.

This issue proposes allowing a sub-class of CheckedTreeSelectionDialog to specify if an empty tree is allowed with the default being no.

This is to fix: https://bugs.eclipse.org/bugs/show_bug.cgi?id=552556

**Comment by mickaelistria** [comment]
I see your PR adds a flag to enable empty tree, but I'm curious: do you think this flag is a must have? Is the current behavior for empty tree something that is guaranteed by an API contract and that we can't change? Or are we happy overall with this default behavior to not change it?
