### ISSUE TITLE
NotificationBuilder API does not allow to position the notification on the bottom of the Shell

### ISSUE THREAD

**Issue by marcushoepfner** [eclipse-platform/eclipse.platform.ui#1226]
Refer to issue https://github.com/eclipse-platform/eclipse.platform/issues/740

The shell cannot be given to the builder in NotificationPopup

**Comment by marcushoepfner** [comment]
Snippets should be adapted as well:

> Note: It looks like the new builder snippets are also not added to the JFace Snippet page, https://wiki.eclipse.org/JFaceSnippets. We should do this and potentially migrate this page to source control as the wiki will disagree soon.

**Comment by marcushoepfner** [comment]
@vogella I have changed the Snippet081AbstractNotificationPopup you have mentioned.
Look how short this has become with all the new APIs. But is not about AbstractNotificationPopup anymore, so I'm not sure whether this one should be changed. WDYT? just rename the class? 
I don't see a reason to propose older APIs when we have nice new ones.
```java
package org.eclipse.jface.notifications;

import org.eclipse.jface.widgets.WidgetFactory;
import org.eclipse.swt.SWT;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.layout.FillLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class Snippet081AbstractNotificationPopup {

	private Display display = new Display();
	private final Shell shell = WidgetFactory.shell(SWT.NONE).layout(new FillLayout(SWT.VERTICAL)).create(display);

	public static void main(String[] args) {
		new Snippet081AbstractNotificationPopup().start();
	}

	private void start() {
		WidgetFactory.button(SWT.PUSH).text("Hello World").onSelect(this::select).create(shell);
		WidgetFactory.button(SWT.PUSH).text("I am a notification popup").onSelect(this::select).create(shell);
		WidgetFactory.button(SWT.PUSH).text("Press me!").onSelect(this::select).create(shell);

		shell.setSize(500, 500);
		shell.open();

		while (!shell.isDisposed()) {
			if (!display.readAndDispatch())
				display.sleep();
		}
		display.dispose();
	}

	private void select(SelectionEvent event) {
		String text = ((Button) event.widget).getText();
		NotificationPopup.forShell(shell).delay(10000).text(text).build().open();
	}
}
```

**Comment by vogella** [comment]
Thanks @marcushoepfner, looks really good. I would also change and rename the snippet. If you do, please update the link in the wiki.

**Comment by BeckerWdf** [comment]
> Thanks @marcushoepfner, looks really good. I would also change and rename the snippet. If you do, please update the link in the wiki.

Which Wiki? Isn't Eclipse Wiki planned to be shut down?

**Comment by marcushoepfner** [comment]
> > Thanks @marcushoepfner, looks really good. I would also change and rename the snippet. If you do, please update the link in the wiki.
> 
> Which Wiki? Isn't Eclipse Wiki planned to be shut down?

https://wiki.eclipse.org/JFaceSnippets

Yes. It is going to shut down. But since it is still there, I'll change it.

Do you think I can merge this commit?

**Comment by BeckerWdf** [comment]
> Yes. It is going to shut down. But since it is still there, I'll change it.

To where will we migrate this page(s)?

**Comment by marcushoepfner** [comment]
> > Yes. It is going to shut down. But since it is still there, I'll change it.
> 
> To where will we migrate this page(s)?

Not a real answer, but at least a direction maybe. See Lars' comment in https://github.com/eclipse-platform/eclipse.platform/issues/740#issuecomment-1757831459

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform/issues/747.

Wiki on eclipse.org is "dead" and shouldn't be used.

**Comment by marcushoepfner** [comment]
> See [eclipse-platform/eclipse.platform#747](https://github.com/eclipse-platform/eclipse.platform/issues/747).
> 
> Wiki on eclipse.org is "dead" and shouldn't be used.

I nevertheless changed the link to the new file. I thought, this is better than a dead link, since the page is still publicly available.

Has this wiki page been moved to something else already?
If so, I can fix the link there also
If not, it's been a good idea to fix it in the wiki because when it moves, the link is already working and don't needs additional effort to correct.

**Comment by laeubi** [comment]
Th Eclipse Help seem to contain some of content also placed in the wiki... so probably this would be a good way to migrate this stuff to.

**Comment by marcushoepfner** [comment]
> Th Eclipse Help seem to contain some of content also placed in the wiki... so probably this would be a good way to migrate this stuff to.

What do you mean?

**Comment by laeubi** [comment]
https://help.eclipse.org/latest/index.jsp is generated from the project code.

**Comment by marcushoepfner** [comment]
> https://help.eclipse.org/latest/index.jsp is generated from the project code.

I neither find Snippet081AbstractNotificationPopup or Snippet081AbstractNotificationPopup.java, nor the new names Snippet081NotificationPopup or Snippet081NotificationPopup.java in the help. So I guess nothing has to be done.

I close this issue.
