### ISSUE TITLE
[macOS] Update Eclipse.icns to match Apple UI Guideline

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-platform/eclipse.platform.ui#1247]
https://developer.apple.com/design/human-interface-guidelines/app-icons defines how app Icons should look but Eclipse.icns do not follow this guideline.

**Comment by BeckerWdf** [comment]
Hi Frank,
thanks for report. Can you please be a bit more precise- what exactly is not correct?

**Comment by BeckerFrank** [comment]
App icons use a square image with rounded corners.

Here you can find some more Informations https://developer.apple.com/design/resources/ .
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/13169360/bbbb3a41-cb6d-424a-9575-713eb723af86)

**Comment by marcushoepfner** [comment]
Are you talking about the Eclipse app icon or the icons within Eclipse (e.g. in the toolbar)?

**Comment by BeckerWdf** [comment]
I think the app icon....

**Comment by BeckerFrank** [comment]
Yes I talk about the App Icon.

**Comment by BeckerWdf** [comment]
So what we need to change is the following file: https://github.com/eclipse-packaging/packages/blob/master/icons/Eclipse.icns
Correct?

**Comment by BeckerWdf** [comment]
Inside the ICNS are multiple PNGs (in difference resolutions). Does anybody know where the responding SVGs version of this PNGs are?

**Comment by BeckerWdf** [comment]
What do you think about the following design:

<img src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/28338612/82be6b68-c75a-4d56-8c66-a2627d12be9c" width=50% height=50%>

I made the background grey just for demo purposes. In the final icon this will be plain white.

**Comment by vogella** [comment]
We should also update the icon for the Eclipse SDK, not only for the package solutions. These are stored in the aggregator repo IIRC.

**Comment by BeckerWdf** [comment]
> We should also update the icon for the Eclipse SDK, not only for the package solutions. These are stored in the aggregator repo IIRC.

Where exactly?

**Comment by vogella** [comment]
> Where exactly?

I think here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/780a8d23c5782d79f1a332e29e3d5a8bc04e09a3/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/icons but I never did the icon updates in the past. @sravanlakkimsetti is this the right place?

**Comment by BeckerWdf** [comment]
> > Where exactly?
> 
> I think here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/780a8d23c5782d79f1a332e29e3d5a8bc04e09a3/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/icons but I never did the icon updates in the past. @sravanlakkimsetti is this the right place?

Ok no problem. This is the same file as in the package solutions. Once we have a new icns file we can simply copy that to the different locations.

**Comment by merks** [comment]
I'm surprised the "master" image isn't in the images repo...

**Comment by BeckerWdf** [comment]
> I'm surprised the "master" image isn't in the images repo...

At least I did not find it there.

**Comment by BeckerWdf** [comment]
[Eclipse.icns.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/13250075/Eclipse.icns.zip)

Here is a first version of the icns file (inside a zip to that github accepts it). Does this look good to you? If yes: I will create PRs for the various repos.

**Comment by BeckerWdf** [comment]
> > > Where exactly?
> > 
> > 
> > I think here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/tree/780a8d23c5782d79f1a332e29e3d5a8bc04e09a3/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/icons but I never did the icon updates in the past. @sravanlakkimsetti is this the right place?
> 
> Ok no problem. This is the same file as in the package solutions. Once we have a new icns file we can simply copy that to the different locations.

@merks : If I provide a PR for this. Can we then see the result of it in an i-build? Or how can we test changes to the icon file?

**Comment by merks** [comment]
That's a good question.  The PR builds don't produce an update site and an I-Build only builds what's in the master branches.  So it seems there is not a good way to test it...

**Comment by BeckerWdf** [comment]
> That's a good question. The PR builds don't produce an update site and an I-Build only builds what's in the master branches. So it seems there is not a good way to test it...

One really has to see icon change "in real life" so see if it looks good. I think I will try to simply replace the icns file inside of one of the existing macOS bundle I have on my hard disk.

**Comment by BeckerWdf** [comment]
> One really has to see icon change "in real life" so see if it looks good. I think I will try to simply replace the icns file inside of one of the existing macOS bundle I have on my hard disk.

Thats how it looks like compare the the current icon and compared to icons of other apps:

<img width="403" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/28338612/9467433f-1e88-4bb7-accc-2ab5e826e9f7">

Any comments? How do you like it?

**Comment by marcushoepfner** [comment]
> > One really has to see icon change "in real life" so see if it looks good. I think I will try to simply replace the icns file inside of one of the existing macOS bundle I have on my hard disk.
> 
> Thats how it looks like compare the the current icon and compared to icons of other apps:
> <img alt="image" width="403" src="https://user-images.githubusercontent.com/28338612/280991127-9467433f-1e88-4bb7-accc-2ab5e826e9f7.png">
> 
> Any comments? How do you like it?

It looks like the icon is horizontally not in the middle of the white box. Are you going to change this? Or am I wrong?

**Comment by BeckerWdf** [comment]
> It looks like the icon is horizontally not in the middle of the white box. Are you going to change this? Or am I wrong?

Yes you are right. But I did this by intention. The bluish circle is in the middle and the orange moon-like shape adds to it to the left. Putting the complete icon horizontally into the middle looked "not right" to me.

Just look at the "outlook" icon. It does the same.

**Comment by BeckerWdf** [comment]
Let's wait until also the packages changes are merged.
