### ISSUE TITLE
invisible content in Welcome page, tip of the day,javadoc view and javadoc assist

### ISSUE THREAD

**Issue by dabicho** [eclipse-platform/eclipse.platform.ui#1248]
This is on a fresh install of eclipse jee 2023 09 R for linux x86 64

The welcome tab, the tip of the day window, javadoc view and javadoc assist (hovers) appear emtpy, but in reality the content is there as I see the cursor change shape when hovering over links, and I can select content and dragi it around or copy and paste it somewhere else.

Selecting content does not make it visible.

![CursorChange](https://github.com/eclipse-platform/eclipse.platform.ui/assets/7672628/6ad2949f-d1b4-4420-bec6-5f0eb7f5ba40)

![SelectAndDragContent](https://github.com/eclipse-platform/eclipse.platform.ui/assets/7672628/21452d46-6b26-4b38-8c2a-e859c68161b7)

**Comment by Phillipus** [comment]
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/843

**Comment by dabicho** [comment]
Closing because its the same issue as the one opened by Phillipus in  comment above
