### ISSUE TITLE
Regression: Eclipse Platform is no longer trustworthy

### ISSUE THREAD

**Issue by ewillink** [eclipse-platform/eclipse.platform.ui#1250]
From: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3887

Unzip Eclipse 2.30M1 on Windows 11. Edit Eclipse.ini to use a jdk-17.0.8. Start Eclipse.
Help->Install New Software...
Remove all pre-configured sites., Work with https://download.eclipse.org/releases/2023-12/202310271000/
Install OCL Examples and Editors

A Trust Dialog shows three untrustworthy PGPs for seven bundles including com.google.guava 32.1.3.jre, com.google.inject 7.0.0

In the past kinstalling did not clobber the user with marginally intelligible dialogs.

The text at the top of the trust dialog suggests that the PGP keys should be verified with a trusted server. If I Googled a bit I could perhaps find out how to do this at the risk that Google might serve me up a fake page.

Clearly users cannot be expected to do this quickly or reliably, whereas surely the platform could have a built-in list of trusted servers so that the user is unaware of the trust verification behind the scenes.

**Comment by akurtakov** [comment]
This is not platform issue . You should report it against "OCL Examples and Editors" provider so they ship signed dependencies in their repository. There is nothing Eclipse Platform can do here. As it can be seen guava and google inject are not even part of our p2 repo - https://download.eclipse.org/eclipse/updates/4.30-I-builds/I20231025-1800/plugins/ .

**Comment by ewillink** [comment]
OCL does not provide com.google.guava so it cannot be an OCL issue.

If it's not for the platform then perhaps its a SimRel issue since SimRel provides com.google.guava.

But since this is a generic problem of ensuring that PGP signatures are trustworthy, it seems to me that is should be resolved by what the user regards as 'platform' even if a platform committer might regard it as the 'platform-trust' subsystem.

**Comment by mickaelistria** [comment]
> OCL does not provide com.google.guava so it cannot be an OCL issue.

Platform doesn't ship com.google.guava either (see https://download.eclipse.org/eclipse/updates/4.30-I-builds/I20231025-1800/plugins/ if you want to verify). All artifacts part of Platform deliveries are signed (eiter with jarsigner or PGP), Platform is trustworthy.
Please investigate where the OCL feature gets guava from, and report the issue to the provider. The provider of guava here seems to have missed the steps to make this particular artifact trustworthy.

> But since this is a generic problem of ensuring that PGP signatures are trustworthy,

It is not a problem, but a solution. A trust check that tells that are artifact is not trustworthy is an issue of the artifact, not of the check.

**Comment by ewillink** [comment]
A simpler repo using just eclipse-SDK-4.30RC1-win32-x86_64.zip and EMF-Updates-2.36.0.zip

Unzip Eclipse platform, configure eclipse.ini for a Java 17.0.8 and start Eclipse
Work with EMF-Updates-2.36.0.zip to install "EMF - Eclipse Modeling Framework SDK"

org.apache.commons.jxpath appears in a Trust Artefacts popup.

org.apache.commons.jxpath is not present in EMF-Updates-2.36.0.zip
org.apache.commons.jxpath is present in eclipse-SDK-4.30RC1-win32-x86_64.zip

Therefore this is a platform problem.

**Comment by akurtakov** [comment]
So what is the exact complain about jxpath? Not signed? Expired certificate? Else?

**Comment by merks** [comment]
FYI, the following is the artifact metadata for org.apache.commons.jxpath in the artifacts.xml in the zip.  Note the fact that it has a PGP signature and key.
```
    <artifact classifier='osgi.bundle' id='org.apache.commons.jxpath' version='1.3.0'>
      <properties size='3'>
        <property name='pgp.signatures' value='-----BEGIN PGP SIGNATURE-----&#xA;&#xA;iQIzBAABCAAdBQJlVVneFiEEnjBEBxt1jry35FZzcA5PObwFNksACgkQcA5PObwF&#xA;Nkt3SA//SyezOXnyMMLgOc9HoDJi0lJ/tvh+5dGb2HGX8uFGKNIKvOBG1azY91wb&#xA;yIoumSWbQMj6BM6qF4sYme3g3CApFHxpMfEEHR5GkoiVJwXeKvz5doMt6wP/3Hou&#xA;qHyfjjrEWXr0PBx+W9/AvNh0PK03wIa/8TA+2n3BrJYtSqj/99A2GgXCYGF+o3Wn&#xA;zOnQ6tnyciWKzf3jBI1j1Wq0MAxoqrtSHXhTZDP8XkFvdnEMBbl2SGLTjoD9FOc7&#xA;eD3MBq7hVqdaAnDtO++1gnyJr33uM7Pkr/eOgyMGpXvbiPr0G8gnlpwnrWN1ZjNJ&#xA;Ge0ppE1Ezp4qtF5c0nfvvG9HcOmdwyjv/vMjvNHTAqmNpXTJNhB3lP4v9+rvIvdx&#xA;cJC8eA67XqwX0HhawetX5G97ekxTTibs9hMhUTkoim1mVS7kjObqxXfAASpjM5AE&#xA;aiZ1kfnvf/qxEsjzo6d8VzfFa+X5Uv8Cq1sPAxZZwtZCy0ldCVb3L8LYXoo9OKmF&#xA;SVeJOt4wb092blKE9Ad4cvSqnsYuOzO7qM4I4eZ2U2/D72ZJr44L2o4Xu/hLdUs8&#xA;SkL5+KF4k1XKEkwPUcfgh6xH7CkWhD1oDbBtxZaZwU0B8aMubDtU9TidXy6fzoLU&#xA;lLo6+GH1m9JsV30nH1aVDnsWrPwhGetXTy5rOmXOO/m4zNZzVWI=&#xA;=JwxQ&#xA;-----END PGP SIGNATURE-----'/>
        <property name='pgp.publicKeys' value='-----BEGIN PGP MESSAGE-----&#xA;Version: BCPG v1.76.0&#xA;&#xA;uQINBFhaXPsBEAC3bR7f5euHbpIDDTuFYHPI0+S5X0DhuqcGBUL2HSFhWMwIlfsA&#xA;aO+pt7GyfXLUkTmzugwmwO+sOW2QmwEZQcK2z3BrcjytZophZ9AUajbAjnadSH6U&#xA;XCMmfExVVnaYSfl/+Uub42szQE/r3gCRIz6M6clVVAjpFv4G/mumfQUV/XzLoUEY&#xA;XTgwTokFJ97R+hDbHvBEBrUT8M6zHP5DhN3EBug3qb6wZVOa/+HEX3M+7k4jVT/p&#xA;pNumw0acg0DDoSNQ13VsRV6sV0XE4zr3Zfs84f8xCgXpEMs4U6DZGqs3iJVVtbRf&#xA;0oL0fgcxNgRrmbCrBfbXYfrS4u+fJ0vB+Wrflv9eNA3i6TtVL6uYpZy9uO2B1olK&#xA;VzfEhsgB3QrULB4jVHZjIXGe4ILn45ndMtAeY4M91wyobgG99Xl+1vPHrxV0+2zR&#xA;P66J3puyxiKE2B7gd7hib54CB3lYyrG1S+K1kZGCI1IFKCnqmTJXY0tKoLAASS3v&#xA;tDcknXenzR5RVSpWTDuxtusekfL0Bw8pCBoz9L4Hex8Q1j//D5CZlqcg1NKFfmBZ&#xA;7ta9PTuJcpOsz/LaPG/0VHYt/QAv5o4eeZESl7iZyM4/0NFh2s/rq0R8Z9yVSSkI&#xA;vvO8d8XGZ65NTm3T4NFuEihn+AEm+zg4KiGdYBEZvs8QQoW9e1+MMN8xnwARAQAB&#xA;iQREBBgBCAAPAhsCBQJhuzR9BQkSxtkCAinBXSAEGQEIAAYFAlhaXPsACgkQcA5P&#xA;ObwFNkunSw//SRR1tGS1pDj2jonLpR0wPilCphS6ANv895yvlg6rHG4nKi4hQ0Jz&#xA;ZxhGCwkgxEkRaKiyLfEiTihETkF161AqLPhyvE8LuQ1AG+A+tUnR8/T3gKE8t/m2&#xA;/UtScZwN1QEQVc/uG7MTrbZ2ngXfH65k3fzhjy95AnJHAswu2vic1hzDi77HlQpN&#xA;0O3adJuU/jfdu1RxNE0MRt8MFEjsTFwSBVm6lDxgcZV+qjRLGQznTyLF5/AyCI7Z&#xA;4z9xHZPKFq1eHzqevifNiqfb8KX22sHKOSdnVBzBq/UxbT5jIbNSRhD91FjtZD7Z&#xA;6wi3POsB/9RWZBldCov4ZEajmxFzxpx4RAqYOSIkEor9ZtRGbZuWvTie4vFIur7T&#xA;f543mE6nxKcggExNp4MTyOd1scMc9oyczH561OTdHOCYEyoCwpG9N2Hb1/MDnWSi&#xA;HKG451CvdrE5FHcPZKjp/nHUcRw/WQC3bgj6ScAay64EKC5S9tW+Wp85Oyyvj+M7&#xA;lBzOxp19nESpfC++fzBAQPMxtD8EvrZTxqFSJxMOH9bhzB8+MFt08tmYb5SwoYi4&#xA;C8JJ+wZgNetJKK+j07fvyMUChH/SbkCVszMiiSEjHA2Kk0LMVYKS/OLJU7i7tZXV&#xA;aJ078QEeTDy5hSzsutd+orlFkR9+mgr1HUh0UgYlofTfEi7bLDeSr0cJELbTq5vM&#xA;ZBKCicIP/irazYBVKw0SluhHtjzRcs5WIdH5bVPsEE87+iUc4daONWdVIhLdokxt&#xA;OWlrEmZFLKqq9Z8fzvlf5LAQMOBkMAkl0z2ej4KG7zrjWyqDgysEI2WBlqTAFSeL&#xA;+89Kc9BzJE9heYW8EfpXbNfOnKnAYWsbhcomSxVQ/jBIuyLBg/0gYKpBNx8HC6v9&#xA;xNH0Ja+wM/7w3JC1aIwMYJn1yF2ykUYS+BoTCU7TA8r43pHg4I4Fz+Y2P5RLk+RJ&#xA;I4kJezDNiJOpIcr/nKTPxMGUzMtWlGyAJ7LkyOZCtQXhtXwaT8grjtHzlwlGrpgD&#xA;Rtf7wWjzEWeaQSegTFM9Mid+09kCp0PkJvveg8wJCuoVboNOto0O5rQsUczjXxiW&#xA;kXYlHGeQL4rWc1zP7F1n4DEwDbVZC7jOn/80l3x4LcKuhc86gP4L5HKbdjn5GcQ0&#xA;3RVLl1WVTQCdpr0+am28hl9XpyHdlWwSEmqqoUnjGv5B8RClocBRS4ECPPZCVSBl&#xA;yK8eDgRww9Fu1EFq4xkq5fGj4YUOAIm756iW41NQ3VnPYbom/J27iFFN8+h92CSb&#xA;KAqhmRwQh+GGo0eGCXmPHyQ/KCHTvnTZCFBUvabm3rVNFaDO+RvmwPwNCRz0DYzG&#xA;paeMOGo4nMMGbzdhgfJ/X5Ed1/Mqz8egHhGIO94ebKEN5ZtJjAOK&#xA;=xtSl&#xA;-----END PGP MESSAGE-----&#xA;'/>
        <property name='download.size' value='299994'/>
      </properties>
    </artifact>
```

**Comment by ewillink** [comment]
I'm not sure what the problem is, since the Trust Artefacts pop-up is no doubt a good pop-up for the purposes of developers struggling with obtuse trust chains. It is not helpful for unfamiliar users who just want an install to work. The incliniation is to just trust-all and have done with it; totally undermines the whole purpose.

There is a single PGP line with a fingerprint with a tick and a valid, expires 2027-11...

My naive understanding is that it is signed but unfortunately Eclipse (or Java utility) code is unable to validate the transitive trust chain. OOMPH appears to be much better, but not perfect, possibly because it has a hardcoded cache of intermediate 'trusts'. IMHO such a cache is a useful accelerator, but there should be a fall-back that validates from scratch.
