### ISSUE TITLE
Redundant specification of type arguments errors in org.eclipse.e4.tools.emf.ui with I20231102-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1267]
I see 8 errors of same type on `org.eclipse.e4.tools.emf.ui` bundle in the workspace using I20231102-1800 build.

```
Redundant specification of type arguments <Boolean, ItemType>	MenuItemEditor.java	/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/component	line 268	Java Problem
```

I believe this is due the recent fix in JDT https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1542.

@srikanth-sankaran: however, we seem to have a problem with the change.
I can't solve the error on `/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/component/MenuEditor.java`.

With the type argument (as is on master) I get `Redundant specification of type arguments <MMenuElement>` on this line:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/5800f1d1d1fde12b96f48a20f7a4b4bc866f2c9c/tools/bundles/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/component/MenuEditor.java#L386

after removing type argument I get:
`Type ListDiffVisitor<capture#5-of ? extends MMenuElement> inferred for ListDiffVisitor<>, is not valid for an anonymous class with '<>'`.

I will push a PR fixing the errors I can fix, except `MenuEditor`.

**Comment by iloveeclipse** [comment]
Note: the errors are visible only in the IDE, maven build shows no errors:

See the https://download.eclipse.org/eclipse/downloads/drops4/I20231103-0420/buildlogs/mb220_buildSdkPatch.sh.log
```
[INFO] Building org.eclipse.e4.tools.emf.ui 4.8.200-SNAPSHOT          [306/520]
[INFO]   from eclipse.platform.ui/tools/bundles/org.eclipse.e4.tools.emf.ui/pom.xml
```

This is because of this line:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/5800f1d1d1fde12b96f48a20f7a4b4bc866f2c9c/tools/bundles/org.eclipse.e4.tools.emf.ui/pom.xml#L39

**Comment by srikanth-sankaran** [comment]
> I see 8 errors of same type on `org.eclipse.e4.tools.emf.ui` bundle in the workspace using I20231102-1800 build.

Hmm. I see only 7 - 6 which this PR fixes - by inspecting the inferred types when <> is used, I am able to confirm the explicit types can be elided.

> @srikanth-sankaran: however, we seem to have a problem with the change. I can't solve the error on `/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/component/MenuEditor.java`.
> 
> With the type argument (as is on master) I get `Redundant specification of type arguments <MMenuElement>` on this line:
> 
> https://github.com/eclipse-platform/eclipse.platform.ui/blob/5800f1d1d1fde12b96f48a20f7a4b4bc866f2c9c/tools/bundles/org.eclipse.e4.tools.emf.ui/src/org/eclipse/e4/tools/emf/ui/internal/common/component/MenuEditor.java#L386
> 
> after removing type argument I get: `Type ListDiffVisitor<capture#5-of ? extends MMenuElement> inferred for ListDiffVisitor<>, is not valid for an anonymous class with '<>'`.
> 
> I will push a PR fixing the errors I can fix, except `MenuEditor`.

I am studying this one. As discussed a non-essential change made to https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1542 is likely triggering open defects in this area, perhaps one of 
```
https://bugs.eclipse.org/bugs/show_bug.cgi?id=579314 or
https://bugs.eclipse.org/bugs/show_bug.cgi?id=576002
```

**Comment by iloveeclipse** [comment]
See also https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1560 & https://github.com/eclipse-jdt/eclipse.jdt.core/pull/1563

**Comment by iloveeclipse** [comment]
Fixed in  I20231106-1800
