### ISSUE TITLE
UI CI build very slow

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1278]
Almost 1h for a CI build on platform.ui now
https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/master/
17 min alone on org.eclipse.jface.tests.viewers
i sampled CheckboxTreeViewerTest:
Almost all time is wasted in a sleep on tearDown() introduced with https://github.com/eclipse-platform/eclipse.platform.ui/pull/810
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/c863c2f0-5cc2-48b1-9d8d-f7d85dec9e44)

**Comment by iloveeclipse** [comment]
Fixed by #1279
