### ISSUE TITLE
NPE during WizardNewFolderMainPage dispose

### ISSUE THREAD

**Issue by tivervac** [eclipse-platform/eclipse.platform.ui#1310]
We got this automated stacktrace in our product (no reproducer) and looking at the code it makes sense. The `filterButton` is only initialized when a button is clicked, yet it is always disposed.

```
java.lang.NullPointerException:Cannot invoke "org.eclipse.swt.widgets.Button.dispose()" because "this.filterButton" is null
    at org.eclipse.ui.dialogs.WizardNewFolderMainPage.disposeAdvancedControls(WizardNewFolderMainPage.java:616)
    at org.eclipse.ui.dialogs.WizardNewFolderMainPage.handleAdvancedButtonSelect(WizardNewFolderMainPage.java:490)
    at org.eclipse.ui.dialogs.WizardNewFolderMainPage$1.widgetSelected(WizardNewFolderMainPage.java:176)
```

Lines are slightly off because of a different Eclipse version, nowadays it's line 611 being the `filterButton.dispose();`

**Comment by laeubi** [comment]
@tivervac as you have already analyzed, do you like to propose a patch?

**Comment by tivervac** [comment]
> @tivervac as you have already analyzed, do you like to propose a patch?

I'll try to have a look

**Comment by tivervac** [comment]
Actually, my initial research wasn't thorough enough. From what I can see, this can't happen during happy paths. Also seems to me like the init/dispose code all happens on the UI thread, so no threading issues are possible. The only thing that can go wrong then is that an exception is produced after the creation of the `linkedResourceComposite` but before the `filterButton` creation. That would cause the former to be non-null, while the latter would be null causing said exception.

**Comment by BeckerWdf** [comment]
@tivervac : Do you still want to propose a pull request?

**Comment by tivervac** [comment]
> @tivervac : Do you still want to propose a pull request?

Sadly I do not

**Comment by laeubi** [comment]
see
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/1378
