### ISSUE TITLE
Eclipse text search mostNestedProject should not include closed projects when detecting which files to open

### ISSUE THREAD

**Issue by MKamelEJ** [eclipse-platform/eclipse.platform.ui#1322]
Summary

When having nested projects some are open and some are closed when searching for textual content:
- the textual search shows the results of the open projects only
- but when you double click on the search results it will send you to the mostNestedProject which may be closed
- Resulting in opening an empty editor

Steps to reproduce

- Import a project from existing workspace (A)
- Create another project (B)
- Drag folder from A project into B
- Select Link to files and folders
- Search for a keyword in that folder then click to open it

What is the current bug behavior?
The result is resource "A/file.txt" doesn't exist

What is the expected correct behavior?
It should open the file in the open projects only.

Relevant logs and/or screenshots
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/151730767/d7783712-a549-4d5e-9b9f-0ffdd4c2ae4a)

org.eclipse.search.internal.ui.text.FileSearchPage.mostNestedEquivalent(IFile)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/151730767/0cad6684-3d72-4cf6-9caf-b453dbdcfe36)

This should check the file exists in an open projects only

**Comment by mickaelistria** [comment]
Your analysis seems correct, can you please submit a pull request with the suggested change?
