### ISSUE TITLE
org.eclipse.e4.ui.css.core v0.14.200 references invalid xml-apis-ext version

### ISSUE THREAD

**Issue by otbutz** [eclipse-platform/eclipse.platform.ui#1377]
Source: https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.e4.ui.css.core/0.14.200/org.eclipse.e4.ui.css.core-0.14.200.pom

The following dependency doesn't seem to be resolvable:

```xml
    <dependency>
      <groupId>xml-apis</groupId>
      <artifactId>xml-apis-ext</artifactId>
      <version>1.0.0.v20230923-0644</version>
      <optional>false</optional>
    </dependency>
```

**Comment by merks** [comment]
Yes, it's an error.  It should reference this:

 https://repo1.maven.org/maven2/xml-apis/xml-apis-ext/1.3.04/

**Comment by laeubi** [comment]
@otbutz you can add 

```
<dependency>
    <groupId>xml-apis</groupId>
    <artifactId>xml-apis-ext</artifactId>
    <version>1.3.04</version>
</dependency>
```

to your pom to fix the issue for now.

**Comment by merks** [comment]
@otbutz 

Sorry about the hassle and my mistake.  I thought I can carefully validated all this.  I should have noticed that the analysis view was showing a bad version

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/b2ff3a4c-7f55-4135-bcfd-43d4ff0fc56e)

**Comment by merks** [comment]
FYI, I fixed (locally) the mapping rules to map correctly:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/e6fdcddd-6659-4230-a739-a3df34ea65b5)

But before I commit the fix, I will fix the validation build that it properly fails when there are validation errors to ensure that this never happens again...

**Comment by merks** [comment]
I first make sure the validator https://ci.eclipse.org/releng/view/Publish%20to%20Maven/job/RepositoryValidator/ fails:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/e289c044-b742-49da-9a7a-3b9eb730923e)

And then made sure it doesn't fail after fixing the mapping.

So this type of problem should not happen again....
