### ISSUE TITLE
Add "Generic Text Editor" strategy to the list of possible strategies

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1380]
I'm trying to use tm4e as a lightweight universal syntax highlighting addon for generic editor for all possible file types one can see flying around, but I'm hindered by the fact that I have to associate each and every "unassociated" file type with generic editor manually.

Platform provides a way to do so, but currently it only provides a choice between "Text Editor", "System Text Editor", "System or Text ..." and "Ask...".

So the easiest way to get "generic" syntax support for most of the used file types is to extend the options provided in this selection box to "Generic Text Editor", which offers more functionality as "Text".

I think this shouldn't harm anyone to have more available choices:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/776e730c-4e16-4d02-a15b-7d7bc8a4a923)

I will push a PR with proposal. With that one, opening python files with nothing else installed in the SDK shows immediately syntax (and of course for many other supported files).

**Comment by akurtakov** [comment]
I honestly can't see why would someone prefer "Text Editor" over "Generic Text Editor" . It's pretty good to have  the option but IMHO we should consider even removing Text Editor from this combo.

**Comment by laeubi** [comment]
> I honestly can't see why would someone prefer "Text Editor" over "Generic Text Editor" . It's pretty good to have the option but IMHO we should consider even removing Text Editor from this combo.

I agree with @akurtakov  that one simply should use generic editor (what IS a text editor anyways) I think a normal user can't really decide what is the difference between  a Text and a Generic Editor (is a text editor not generic?), beside that the actual "generic" Editor is an Extensible (!) Text editor...

**Comment by iloveeclipse** [comment]
> but IMHO we should consider even removing Text Editor from this combo.

The extra option in the combo doesn't harm, and if someone set this as default in the preferences, it will be most likely broken (haven't checked yet what happens if user choice is gone from the list).

But don't think this decision (remove or not default "Text" option) is blocking this enhancement request, one can work on that in parallel.

**Comment by laeubi** [comment]
> But don't think this decision (remove or not default "Text" option) is blocking this enhancement request, one can work on that in parallel.

I think the suggestion is to simply not add *new* options but let the existing one use GenericEditor _instead_, so no UI change no preference change but better user experience.

**Comment by iloveeclipse** [comment]
I'm not sure about removal of something that was long time default. 
Also there might be RCP's that don't include generic editor at all in the target platform.

**Comment by laeubi** [comment]
> Also there might be RCP's that don't include generic editor at all in the target platform.

~How does the new option then work?~ (just see it in the PR) If its just an ID, maybe one can try generic editor first and then that second...

**Comment by iloveeclipse** [comment]
> maybe one can try generic editor first and then that second...

Once again: for the sake of compatibility with billions of existing workspaces & users in the world I prefer NOT to change behavior of the currently defined strategy, only to add new one.

Once it is considered useful & shows no unexpected side effects, we might discuss how the old one could be removed/migrated to the new one.

**Comment by laeubi** [comment]
But then please choose another name, "Generic Editor" is only something eclipse platform committers will understand and even they do not all might know what a "Generic Text Editor" versus a "Text Editor" is ...

**Comment by laeubi** [comment]
Maybe "Content Type Aware Text Editor" or similar even though I find it a bit lengthy @mickaelistria do you have an idea?

Maybe even if it is only different in context of TM4E one better contribute it there as a "TM4E Editor" ....

**Comment by laeubi** [comment]
Maybe even as simple as "Advanced Text Editor" ...

**Comment by iloveeclipse** [comment]
> Maybe even if it is only different in context of TM4E one better contribute it there as a "TM4E Editor" ....

TM4E can contribute whatever strategy they want & use whatever name they want. SDK doesn't contain TM4E so we can't suggest here this name, especially the contribution here is **only indirectly** targeting TM4E but can be also used without it with something else like "TM42E++".

> But then please choose another name, "Generic Editor"

Come on, lot of naming discussions were there while "Generic Editor" was chosen and "Generic" won the battle. Let don't start it again please.

**Comment by iloveeclipse** [comment]
> Maybe even as simple as "Advanced Text Editor" ...

So should I change it now to "Advanced Text Editor" or not? But please no other naming proposals.

**Comment by laeubi** [comment]
> > Maybe even as simple as "Advanced Text Editor" ...
> 
> So should I change it now to "Advanced Text Editor" or not? But please no other naming proposals.

If you don't mind I would be thankful for that but you are Project Lead so final decision is on you :-)

**Comment by akurtakov** [comment]
> > Maybe even as simple as "Advanced Text Editor" ...
> 
> So should I change it now to "Advanced Text Editor" or not? But please no other naming proposals.

Please do. It's better information IMO.

**Comment by iloveeclipse** [comment]
OK, this will be it for now:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/fd58cc64-b4a2-4e8d-b5c6-5becc7cc9b0c)

**Comment by mickaelistria** [comment]
I submitted https://github.com/eclipse-platform/eclipse.platform.ui/issues/1385 about finding a more explict name for the editor
