### ISSUE TITLE
Relabel "Generic Editor" (or "Advanced Text Editor")

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.ui#1385]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

Here and there, we see references to "Generic Editor" or "Advanced Text Editor". The first one is not really user-oriented as the name is more related to the internals of the Editor and it doesn't tell much about what it can do better; the second tries to emphasize that it should be preferred, but it doesn't tell much about what cases it's supposed to serve better.
So I would recommend that we consider a better label for this editor.
I currently have 2 suggestions:
* Generic Code Editor
* Generic Source Editor

I like keeping the "Generic" to emphasize that there can be some better specialized editors, but telling "Code" or "Source" also tells that some convenience features for developers (brackets matching, collapse range...) can already be available for this editor.

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by vogella** [comment]
I think we should keep it simple. Proposal:

- Generic Editor / Advanced Text Editor -> Text Editor or Code Text Editor
-  Text Editor -> Simple Text Editor

This should make it clear that "Simple" should not be used

**Comment by vogella** [comment]
@laeubi WDYT?

**Comment by mickaelistria** [comment]
> I think we should keep it simple.

I'm not convinced your proposal is substantially simpler than other ones. I even fear it may introduce some confusion if "Text Editor" suddenly start pointing at something else. IMO we should keep the "Text Editor" as it since it's not a bad name and it's a long established one, and only focus on the "Generic Editor" which is less good and less established.

**Comment by vogella** [comment]
What about "Code Text Editor"?

**Comment by laeubi** [comment]
`Generic Code Editor` seems good for me form the point of an IDE, maybe one should relabel the other to `Plain Text Editor` then.

More important I think for any Eclipse EPP package the default should be the code editor (as one likes to edit code most of the time) and if tm4e support generic syntax highlight in such case tm4e should be included in all EPPs as well (/CC @jonahgraham )

**Comment by laeubi** [comment]
> Here and there, we see references to "Generic Editor"

By the way in code it is even named [ExtensionBasedTextEditor](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/ExtensionBasedTextEditor.java).

Another thing should we convert this into a discussion?

**Comment by Dinesh0723** [comment]
Proposal:
Rename "**Generic Text Editor**" to "**Advance Text Editor**".

**Comment by mickaelistria** [comment]
I would rather avoid the plain "Text" term here, because this editor is really designed to serve "Code": there are hardcoded default behavior such as collapsed blocks, indentation, bracket matching & completion... which are not desired for plain text edition.

**Comment by Dinesh0723** [comment]
> I would rather avoid the plain "Text" term here, because this editor is really designed to serve "Code": there are hardcoded default behavior such as collapsed blocks, indentation, bracket matching & completion... which are not desired for plain text edition.

Then, my suggestion -> "**Generic Text Editor**" to "**Generic Code Editor**".

**Comment by vogella** [comment]
I changed my mind and now like "Code Editor"

**Comment by humphreygao** [comment]
just "Editor"

**Comment by arsenalzp** [comment]
Hello,
Is it possible to pick up this issue?
What is the implementation deadline for it?

**Comment by mickaelistria** [comment]
There is no deadline; but the absence of a consensual name makes it hard to provide a satisfying "solution" (if there is even a problem...)

**Comment by arsenalzp** [comment]
> There is no deadline; but the absence of a consensual name makes it hard to provide a satisfying "solution" (if there is even a problem...)

It's alright.
I can take any suitable issue to work for this amazing Eclipse project.

**Comment by iloveeclipse** [comment]
Please check https://github.com/eclipse-platform/eclipse.platform.ui/issues/1532 for a different proposal...

**Comment by nlisker** [comment]
My recommendation is to change the default "Text Editor" to "Old Text Editor" to signal that it shouldn't be used (and hopefully phase out).
Then "Generic Text Editor" can stay as it is, change to "Text Editor", or "Default Text Editor", or something else.
I oppose to "Code Editor" because it isn't always used for code. Java code files are opened with the Java editor, C/C++ are opened with CDT's editor etc. This name will imply that any code file should be opened with it, while instead it's a default/generic one that is used until a more specialized one overrides it.

**Comment by mickaelistria** [comment]
GEtting back to this topic, I think the best proposal here is https://github.com/eclipse-platform/eclipse.platform.ui/issues/1385#issuecomment-1843503013

**Comment by mickaelistria** [comment]
Done with https://github.com/eclipse-platform/eclipse.platform.ui/pull/2278

**Comment by jonahgraham** [comment]
> GEtting back to this topic, I think the best proposal here is [#1385 (comment)](https://github.com/eclipse-platform/eclipse.platform.ui/issues/1385#issuecomment-1843503013)

Issue raised: https://github.com/eclipse-packaging/packages/issues/222
