### ISSUE TITLE
Is not possible export Working Sets into an empty directory without .wst file

### ISSUE THREAD

**Issue by manueljordan** [eclipse-platform/eclipse.platform.ui#1393]
Hello

When I try to export `Working Sets`

```
File
 Export
  General
   Working Sets
```
is not possible export, the `Browse` button is useless. 

The current solution and is mandatory is create first an empty `.wsf` file in the target directory to use the `Browse` button to select the mentioned file and do possible the exportation.

Thanks for your understanding.

**Comment by merks** [comment]
When I look there, I only see these:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/a6584b74-481c-43f8-ab88-352c1e4ef5cb)

Can you please turn to that wizard page and use the Plug-in Spy Alt-Shift-F1 to determine what is contributing that page?

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/f05f4b5f-9383-46ac-8cd2-a2b9dd725763)

**Comment by iloveeclipse** [comment]
I guess [Anyedit](https://github.com/iloveeclipse/anyedittools), at least I remember to contribute something like this long time ago. 
The "fix" is simply to specify the path to the file manually.

**Comment by manueljordan** [comment]
Yes, I've that plugin installed. But it seems the "fix" is first create the empty file and include finally the file manually
