### ISSUE TITLE
The fix for #1210 breaks image styling on intro pages

### ISSUE THREAD

**Issue by wiresketch** [eclipse-platform/eclipse.platform.ui#1408]
As stated in the title, version 4.30 of Eclipse has no images on intro pages. This was broken by the fix for #1210 which removes the blank.gif image. The css styling uses this image element to show the actual image using code like this:

```
a#pde img { background-image : url(../../images/topiclabel/ov_eclplugindev48.svg); }
a#pde:hover img { background-image : url(../../images/topiclabel/ov_eclplugindev48.svg); }

```

Since the image element is missing now, now images are displayed.

Here's what the Eclipse SDK 4.29's Welcome Page looked like:
![before](https://github.com/eclipse-platform/eclipse.platform.ui/assets/906911/fbed8804-7a13-4424-b89e-a57c09634135)

Here's what the Eclipse SDK 4.30's Welcome Page looked like now:
![after](https://github.com/eclipse-platform/eclipse.platform.ui/assets/906911/657c85ae-d2c3-4a2a-a4fb-8765cc081618)

**Comment by BeckerWdf** [comment]
@wiresketch: Do you have an idea how to fix the issue https://github.com/eclipse-platform/eclipse.platform.ui/issues/1210 without causing this regression?

**Comment by wiresketch** [comment]
@BeckerWdf Sorry, I don't have a good handle on this code. I've just noticed the problem and tried to identify the commit that caused it.

**Comment by wiresketch** [comment]
@BeckerWdf Perhaps a better place to fix this would be in the CSS that styles those pages. Since those pages are HTML it makes sense to debug them in a browser. There is no obvious way to do it, but what I did to investigate this issue was to put a breakpoint in BrowserIntroPartImplementation#generateContentForPage, extract the generated HTML content using the debug view, put it in a html file and then open it in a browser. Since all resource references are absolute, this works and you can play with CSS styling and see where the original padding issue comes from.

**Comment by wiresketch** [comment]
Looking more into it, it looks like the change must be made in this file:
https://github.com/eclipse-platform/eclipse.platform/blob/master/ua/org.eclipse.ui.intro.universal/themes/solstice/html/root.css

Specifically line 210 this style:

```
#page-links a#workbench,
#action-links a#workbench {
    position : absolute;
    right : 20px;
    top : 5px;
    width : auto;
    text-align:center;
    margin-bottom : 0px;
}

```

Removing the top margin of 5px improves things.

What I've noticed is that the page looks fine in quirks mode (no DOCTYPE). The DOCTYPE generation is controlled by a theme property. Specifically for soltice this was enabled in this commit 7 years ago: https://github.com/eclipse-platform/eclipse.platform/commit/13c830c52c10111f4e49972e9468bcb3e19b9860 . Perhaps it went unnoticed that the DOCTYPE change influences the rendering.

**Comment by BeckerWdf** [comment]
> What I've noticed is that the page looks fine in quirks mode (no DOCTYPE). The DOCTYPE generation is controlled by a theme property. Specifically for soltice this was enabled in this commit 7 years ago: [eclipse-platform/eclipse.platform@13c830c](https://github.com/eclipse-platform/eclipse.platform/commit/13c830c52c10111f4e49972e9468bcb3e19b9860) . Perhaps it went unnoticed that the DOCTYPE change influences the rendering.

Yes. I also notices this while doing the initial fix.

**Comment by BeckerWdf** [comment]
@wiresketch: Thanks for your hints.
I have created a PR that should not correctly address this issue. See: https://github.com/eclipse-platform/eclipse.platform/pull/1025

Do you have the possibility to manually test with my PR?

**Comment by BeckerWdf** [comment]
This is fixed with the above PR.
