### ISSUE TITLE
Too many unrelated branches pushed to main repository

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1409]
See this picture after fetching from main github repo:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/5a05a602-79c5-445c-a054-2a2ade8f04ae)

It is full of `origin/something_bla_bla` branches pushed by @vogella to the main repository.

This makes reading history harder, and it simply provides no value for anyone, polluting list of remote branches with irrelevant entries.

Lars, it would be nice if you could remove all your branches from all eclipse.org main github repositories (not only from platform ui) and use forks for future work, as everyone else in platform does.

See recommended workflow at https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md

**Comment by vogella** [comment]
I`ll have a look

**Comment by laeubi** [comment]
@iloveeclipse just wanted to note that every committer can delete a branch:

https://github.com/eclipse-platform/eclipse.platform.ui/branches

beside that PRs offer an option to delete the branch after the PR was merged from the github UI as well.

@vogella I use the following "script" to disable pushes to the main repo and always use my fork:

```
git remote add fork <your fork url>
git remote set-url --push origin no_push
```

you just need to enable it once for a repository and should use the jgit option "always show push dialog" so you can select your origin to push for.

**Comment by vogella** [comment]
@laeubi thanks, the no push option will be helpful.

**Comment by iloveeclipse** [comment]
> just wanted to note that every committer can delete a branch:

Sure, I wanted to be polite and not delete branches without a note. Beside this, it costs time to go over repositories and cleanup the mess, and I have higher prio tasks as cleaning up branches...

**Comment by elsazac** [comment]
looks like this is actioned now? if so, can this be closed?

**Comment by HannesWell** [comment]
> looks like this is actioned now? if so, can this be closed?

Not entirly. The branches of the following PRs still exists:
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/659
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/668

**Comment by vogella** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/pull/659
https://github.com/eclipse-platform/eclipse.platform.ui/pull/668 branches deleted. 

Thanks @elsazac and @HannesWell
