### ISSUE TITLE
SearchPattern: API Returns an Invalid Match Result

### ISSUE THREAD

**Issue by ahmad2702** [eclipse-platform/eclipse.platform.ui#1434]
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Introduction

Eclipse Platform provides a class `org.eclipse.ui.dialogs.SearchPattern` that can match String objects according to a given pattern.

This class can be found in the current repository:
[eclipse.platform.ui](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master)/[bundles](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles)/[org.eclipse.ui.workbench](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.workbench)/[Eclipse UI](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI)/[org](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org)/[eclipse](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse)/[ui](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui)/[dialogs](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/dialogs)
/[SearchPattern.java](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/dialogs/SearchPattern.java)

## Problem

Calling the public method `org.eclipse.ui.dialogs.SearchPattern#matches(String)` returns an invalid match result (for example, it returns "true" when it should be "false"). 

## Steps to reproduce

From a fresh installation and clean workspace and new class:

```
import org.eclipse.ui.dialogs.SearchPattern;

...

final SearchPattern pattern1 = new SearchPattern();
pattern1.setPattern("ABC-123-321.F-DEFG-10");
		
final boolean pattern1Result1 = pattern1.matches("ABC-123-321.F-DEFG-100");  // expected 'true' and it's 'true'
final boolean pattern1Result2 = pattern1.matches("ABC-123-321.F-DEFG-110");  // expected 'false' but it's 'true'
final boolean pattern1Result3 = pattern1.matches("ABC-123-321.F-DEFG-120");  // expected 'false' but it's 'true'
final boolean pattern1Result4 = pattern1.matches("ABC-123-321.F-DEFG-130");  // expected 'false' but it's 'true'
final boolean pattern1Result5 = pattern1.matches("ABC-123-321.F-DEFG-140");  // expected 'false' but it's 'true'
final boolean pattern1Result6 = pattern1.matches("ABC-123-321.F-DEFG-150");  // expected 'false' but it's 'true'
final boolean pattern1Result7 = pattern1.matches("ABC-123-321.F-DEFG-160");  // expected 'false' but it's 'true'
final boolean pattern1Result8 = pattern1.matches("ABC-123-321.F-DEFG-170");  // expected 'false' but it's 'true'
final boolean pattern1Result9 = pattern1.matches("ABC-123-321.F-DEFG-180");  // expected 'false' but it's 'true'
final boolean pattern1Result10 = pattern1.matches("ABC-123-321.F-DEFG-190"); // expected 'false' but it's 'true

...
```

## Tested under this environment:
* OS & version: Windows 10
* Eclipse IDE/Platform version (as shown in *Help > About*): 4.29.0

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by mickaelistria** [comment]
Thanks for the report. Would you mind trying to add a unit test that reproduce the issue as you describe and submit it in a Pull Request?

**Comment by mickaelistria** [comment]
On 2nd thought, that seems to be working as designed: the SearchPattern isn't just a regexp patch, it can also detect is a string is a split-substring of the match. For example ABC-123-321.F-DEFG-10 does match the bold  parts in **ABC-123-321.F-DEFG-1***9***0** (everything except "9")
