### ISSUE TITLE
Toggle buttons with the dark theme on Linux

### ISSUE THREAD

**Issue by igorlash** [eclipse-platform/eclipse.platform.ui#1452]
Environment:

- OS Linux Mint 21.2 Cinnamon.
- Eclipse IDE for Enterprise Java and Web Developers Version 2023-12 (4.30.0)

When using dark theme in Linux there is no way of telling whether the toggle buttons are on or off.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/31065075/c08a537a-05cc-4ea3-8a77-cbf88585f12f)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/31065075/1c0c9739-235c-4109-9f51-868fc95a9ab8)

Whereas when using light theme it can be easily distinguished:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/31065075/e36ccce4-ede1-47a4-8242-d531c79e8f34)

In Windows 11 it is very easy to see the difference between the two states
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/31065075/f4f596ce-1503-471b-a5cf-57ecbe90efeb)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/31065075/c451af78-c2b1-49db-bd4f-1d1c39dfb541)

**Comment by BeckerWdf** [comment]
is this the same as reported in https://github.com/eclipse-platform/eclipse.platform.ui/issues/467 ?

**Comment by igorlash** [comment]
Yes, it looks like the same, but this problem has been solved for Windows and still reproducible on Linux.

**Comment by vogella** [comment]
With the update dark theme for 2025-03 from @mvm-sap this should be fixed 

To test please use latest I-Build https://download.eclipse.org/eclipse/downloads/
