### ISSUE TITLE
Supply all the changes from all RefactoringParticipant to RefactoringProcessor in ProcessorBasedRefactoring

### ISSUE THREAD

**Issue by raghucssit** [eclipse-platform/eclipse.platform.ui#1481]
## Description

Clients can create `RefactoringProcessor` and use `ProcessorBasedRefactoring` to execute the refactoring.
For example `JavaMoveProcessor` is handles the moving of java elements on the platform.
`RefactoringProcessor` processor loads the `RefactoringParticipants` thoseare contributed for specific refactoring.
In case of JavaMoveProcessor, it loads contributions from `org.eclipse.ltk.core.refactoring.moveParticipants` extension point.

Participants can give the pre-changes and changes to refactoring through `RefactoringParticipant#createPreChange(IProgressMonitor pm) ` and `RefactoringParticipant#createChange(IProgressMonitor pm)` respectively.

`ProcessorBasedRefactoring` gives an opportunity to RefactoringProcessor to add/modify any changes through `RefactoringProcessor#postCreateChange(Change[] participantChanges, IProgressMonitor pm)`.
The supplied changes to this method is expected to contain all the changes(pre-changes and changes) from participants.

But currently it supplies only `changes` from participants not `pre-changes`.

## Background
There can be participants which contribite duplicate `TextChange`. For example `XtextMoveResourceParticipant` supplies `TextChange` to update qualified names of classes in all xtext files. But JDT also supplies exactly same `TextChange` to updates qualified names.
This will result in applying same `TextChange` twice.

`JavaMoveProcessor#postCreateChange(Change[] participantChanges, IProgressMonitor pm)` actually checks for the alreday existing `TextChange` before adding it's own. As we have did not supply some `pre-changes` from other participants to  `postCreateChange` at `ProcessorBasedRefactoring`.

Other possible solution to avoid such duplicate changes can be handles locally in `RefactoringProcessor`  as it knows all the participants.
In the above scenario `JavaMoveProcessor` can read all the `TextChange` from it's `participant's` and prepare a `post-change`.

However it is good to supply `pre-changes` to `RefactoringProcessor#postCreateChange(Change[] participantChanges, IProgressMonitor pm)`.

**Comment by iloveeclipse** [comment]
Bit of history: the change that added "rre-changes" is c3733c14f6789db21987905f5ff1fb7eacc47526 and related ticket is https://bugs.eclipse.org/bugs/show_bug.cgi?id=63149.

In c3733c14f6789db21987905f5ff1fb7eacc47526 the `preChanges` were not considered to be passed to `RefactoringProcessor.postCreateChange(Change[])`, not that is fixed with proposed PR.
This also matches the javadoc of the `postCreateChange()` that expects the processor to see **all** the changes made before:

```
	 * Additional hook allowing processors to add changes to the set of workspace
	 * modifications after all participant changes have been created.
	 *
	 * @param participantChanges an array containing the changes created by the
	 *  participants
```
