### ISSUE TITLE
Contribute GH build action

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#150]
Would be nice to add a GH build action to platform.ui

**Comment by vogella** [comment]
@laeubi @Bananeweizen something for you?

**Comment by laeubi** [comment]
@vogella "thanks" to the multiple repos, there are already numerous examples (e.g. https://github.com/eclipse-equinox/equinox/tree/master/.github/workflows ) that could be used by anyone, just a few steps:

1. copy everything
2. adjust the names of the build
3. check if the Jenkinsfile has special build steps to take into account
4. open PR

**Comment by vogella** [comment]
@laeubi would be nice to reduce the numbers of repo further. We have pending work items for eclipse.platform.resources and eclipse.platform.team to merge into eclipse.platfrom, I think the ticket was opened by you.

**Comment by laeubi** [comment]
> We have pending work items for eclipse.platform.resources and eclipse.platform.team to merge into eclipse.platfrom, I think the ticket was opened by you.

Yep, so maybe we can add GH action to `eclipse.platfrom` and then just wait for all the merges, at least its a bit cumbersome to add the same to each and every "sub repository"....

**Comment by vogella** [comment]
Sometimes doing the actual work is faster than talking a lot about it, so....https://github.com/vogellacompany/eclipse.platform.ui/commit/9ae413216093ffbca17cab09b8d7a30909ae2178
