### ISSUE TITLE
Copy and paste of a folder currently requires moving the cursor to the top folder

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#1523]
I use Eclipse for text editing and this task requires frequently to create a copy of a folder.

To copy a folder I have to move to the top-level folder to paste it. This is not common in other tools.

Example:

FolderTop
-> Subfolder1
-> Lots of other folders
-> Subfolders99

Mouse click on Subfolder99, Ctrl+C on it, Ctrl+V-> nothing happens

To move Subfolder99 the following process is required: Mouse click on Subfolder99, Ctrl+C on it, Scroll to toplevel folder, mouse click on FolderTop and Ctrl+V.

Scrolling can be quite time-consuming if you have lots of folders, as for example here:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/139910/bfb0b6f2-2f20-4b82-9258-340859d2b482)

Other tools like VsCode support this, in this screenshot I copyied the lib folder.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/139910/9a45c144-dd2e-433a-898e-1359f2fc045a)

**Comment by merks** [comment]
I suppose one could specialize "copying to self" to be "copy to parent".  One could also click the left arrow key before pasting.

**Comment by alexanderKononov-sap** [comment]
Hi all, 🙋‍♂️ I am new here, I'm from SAP ADT team and would like to start contributing to eclipse too. Lack of this feature was bugging me too. I'd like to try and fix it if it's ok with everyone :)

**Comment by vogella** [comment]
That would be great @alexanderKononov-sap

**Comment by BeckerWdf** [comment]
Thanks @alexanderKononov-sap for providing a fix for this.
