### ISSUE TITLE
Replace/Find button skips every second occurrence

### ISSUE THREAD

**Issue by basilevs** [eclipse-platform/eclipse.platform.ui#1540]
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

- Create an "Untitled Text Document"
- Enter following content:
```
﻿﻿testa!
testb!
testc!
```
- Set the cursor to the start of the document
- Hit Command+F
- Fill "Find" field with `(\w)!`
- Fill "Replace with" field with `\1 !`
- Set checkbox "Regular expressions"
- Hit Find button
- Hit Replace/Find button

<img width="578" alt="Screenshot 2024-01-22 at 21 34 03" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/650857/70a93dc6-c57c-44b6-8642-b937adc66d83">

I expected:
```
﻿﻿testa !
testb!
testc!
```

But got:
```
﻿﻿testa!
testb !
testc!
```
<img width="626" alt="Screenshot 2024-01-22 at 21 34 28" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/650857/22db0096-5df5-4d12-8c01-6a35c935203e">

## Tested under this environment:
* Ubuntu 22.04.3 LTS
* Eclipse SDK: Version: 2024-03 (4.31) Build id: I20240121-1800

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HeikoKlare** [comment]
Thanks for reporting, @basilevs! I've proposed a fix in #1541. I've successfully tested your scenario with the fix.
