### ISSUE TITLE
Dirty editors do not save the file

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-platform/eclipse.platform.ui#1542]
Since I switched to 2023-04 Version: 2024-03 M1 (4.31.0 M1) Build id: 20240111-1612 I started to almost consistently experience an annoying and critical bug.

I open a Java file, make some changes, the editor becomes dirty, (try to) save the editor (it does not matter whether I use Ctrl+S, Save menu, Save toolbar button, Save All, etc.) and the editor is still dirty, and the file is not saved. When that happens, **I see nothing in the Error Log**. I try to close the editor and it asks whether I want to save before closing. I say yes, the editor closes, I reopen the file and the modified contents have not been saved! If I reopen the same file, I get the same behavior. Sometimes opening another file restores the correct behavior. Sometimes it does not. "Cleaning" sometimes helps. Restarting Eclipse sometimes help.

We noted something similar in some of our Xtext UI tests (https://github.com/eclipse/xtext/issues/2895) and we tracked down our randomly failing tests to the same behavior I described above. In those tests, we programmatically close an open and dirty editor with `org.eclipse.ui.IWorkbenchPage.closeEditor(IEditorPart, boolean)`, passing false, or programmatically save a dirty editor with `org.eclipse.ui.IWorkbenchPage.saveEditor(IEditorPart, boolean)`, passing false. The call succeeds but the editor stays open (and dirty).

I experience these behaviors in all my Linux machines (Ubuntu and Arch) and in my macOS m1.

**Comment by iloveeclipse** [comment]
Please update to latest build, the problem was fixed already.
See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1051
