### ISSUE TITLE
Remove deprecated show-close CSS support

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#159]
Since 2012 we are issuing a warning if the deprecated swt-close CSS property is used. We should remove this property.

**Comment by elsazac** [comment]
@vogella - could you pls elaborate a little on this? where do I see the warning?

**Comment by vogella** [comment]
That @elsazac for showing interest in this issue.


In org.eclipse.e4.ui.css.swt we have 
````
      <handler
            adapter="org.eclipse.e4.ui.css.swt.dom.CTabItemElement"
            composite="false"
            handler="org.eclipse.e4.ui.css.swt.properties.custom.CSSPropertyShowCloseHandler">
         <property-name
               name="swt-show-close">
         </property-name>
             <property-name
               name="show-close" deprecated="renamed as swt-show-close">
         </property-name>
      </handler>
````

And the code in CSSPropertyShowCloseHandler, CTabFolderTest, CTabItemTest

So the plug-in xml and the code needs to be removed.
