### ISSUE TITLE
org.eclipse.ui.ide requires bundle org.eclipse.jdt.annotation

### ISSUE THREAD

**Issue by PatrickTasse** [eclipse-platform/eclipse.platform.ui#1607]
This commit added a requirement on the org.eclipse.jdt.annotation bundle.

https://github.com/eclipse-platform/eclipse.platform.ui/pull/1538/commits/d2b3cace305881c92cae3a676ad96c5f45f7cd7d#diff-c4df1bf28183cd43d51097d82a3f2bd91c7db0cd3ec893bd07ae9d4dfc2894cb

The requirement propagates to users of the Eclipse Platform feature.

Is this intentional? Should it be an optional dependency since it is not required at runtime?

**Comment by iloveeclipse** [comment]
> Is this intentional? 

I hope not.

> Should it be an optional dependency since it is not required at runtime?

Yes

@jukzi : could you please check?

**Comment by jukzi** [comment]
annotations could be optional as in /org.eclipse.ui.editors/META-INF/MANIFEST.MF  - or removed as using the new resource annotation did not help
