### ISSUE TITLE
Jenkins ECJ plugin detects way too less warnings 

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1628]
same as for jdt.ui  (https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1169):
Jenkins show only 423 issues (https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/master/314/eclipse/), while workspace shows many more:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/3c75459a-0dfe-4237-8881-9c8a3c4f64f1)

**Comment by akurtakov** [comment]
The parent pom still overrides the warnings https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/15b58fce6c38cd475a541e2cf41b5a274194cfd5/eclipse-platform-parent/pom.xml#L96 . Please try removing this line and see the results.

**Comment by akurtakov** [comment]
Even https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/15b58fce6c38cd475a541e2cf41b5a274194cfd5/eclipse-platform-parent/pom.xml#L105 has to be removed so test bundles warnings are the same too.
