### ISSUE TITLE
Allow to resize launcher dialog

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#165]
We have OS  / users which cannot use Eclipse due to an incorrectly sized laucher.

https://twitter.com/dadadom/status/1537124038069321729

Any drawbacks in allow the dialog to be re-sized by the user? 

![image](https://user-images.githubusercontent.com/139910/174763314-511c7144-171e-4202-953c-bfe405261e9c.png)

**Comment by laeubi** [comment]
If it is resizable we probably need a different layout (RowLayout?) to account for smaller width.

**Comment by laeubi** [comment]
Beside that I really wonder if it makes any sense to use a IDE for such a small screen... but anyways if it makes users happy... why not.

**Comment by merks** [comment]
That just seems silly!  Try to shrink the IDE down to that size and then imagine all the fonts are way bigger:

![image](https://user-images.githubusercontent.com/208716/174775667-cafa6e5f-de6c-45d5-8dd2-e71cf5522f3d.png)

**Comment by mickaelistria** [comment]
> That just seems silly! Try to shrink the IDE down to that size and then imagine all the fonts are way bigger:

Remove toolbar & status bar, make fullscreen, expand the editor area so other views are hidden; imagine user uses some voice control application to navigate the IDE and it's actually decent.

**Comment by merks** [comment]
I can also imagine trolls making up excuses just to have something to rag about and to see if they can make other people ask "how high?" when they say "jump". 

I'm not sure why we'd put weight into something this marginal when there are literally so many bugs/issues we want to auto close them...

**Comment by mickaelistria** [comment]
> I'm not sure why we'd put weight into something this marginal when there are literally so many bugs/issues we want to auto close them...

It's up to contributors to decide where they put priority. I personally value things like "being able to develop on a phone or a small tablet" more than supporting older versions of Java or other frameworks. YMMV.

**Comment by ronso0** [comment]
Would you mind re-opeing this issue?

I'd love to make the dialog wider because with my workspace paths I'm never able to see the entire name, the trailing part is almost always hidden, exactly like the OP illustrates:
![image](https://user-images.githubusercontent.com/139910/174763314-511c7144-171e-4202-953c-bfe405261e9c.png)

Possible solutions:
* allow resizing
* if that is not feasible, make better use of the available space:
  * remove the space(r) at the right so the path combobox can expand
  * move the path combobox and the "Browse..." button below "Workspace:"

**Comment by laeubi** [comment]
> Would you mind re-opeing this issue?

Do you plan to provide a patch for this?

>     * allow resizing

I don't see a reason not to allow this...

> 
>     * if that is not feasible, make better use of the available space:

We should actually apply both, don't see a reason to not use the available space.

>       * remove the space(r) at the right so the path combobox can expand

This sounds reasonable

>       * move the path combobox and the "Browse..." button below "Workspace:"

As there is nothing else to select I question if we need the label at all, the description of the dialog gives a quite good explanation what is selected here, so probably we can:

1. remove the "Workspace" label completely
2. move the combobox "use this as default" (I think and do not ask again is superfluous) to the button bar, this is how usually such things are presented to the user
3. always expand the "Recent Workspaces" and move that directly under the Workspace selection

**Comment by vogella** [comment]
It is resizable in the next release, can be tested with the latest I-build from https://download.eclipse.org/eclipse/downloads/drops4/I20220828-1800/ 

![image](https://user-images.githubusercontent.com/139910/187146385-73e55f62-2127-43a1-9da1-05490d17b75d.png)

Please open a new issue for new requirements.

**Comment by szarnekow** [comment]
> It is resizable in the next release

Is the screenshot legit? How does it solve the problem in comment 9:

> I'd love to make the dialog wider because with my workspace paths I'm never able to see the entire name, the trailing part is almost always hidden

**Comment by vogella** [comment]
@szarnekow It solves the poblem I reported in the original issue report (by me).

**Comment by laeubi** [comment]
> How does it solve the problem in comment 9:

It all boils down how you define "resizable", as I agree without that it does not really "resizes" from a user POV, technically the dialog itself can be resized (even though the resize is quite useless when you make it larger) so one might argue it is solved...

Anyways, one can simply open a new issue for this, maybe with a more general definition what "resize" means, in web-development one most often refers to "responsive" if a website can adapt to different screensize and/or orientations.

**Comment by vogella** [comment]
The original problem was that the dialog was to small to see the login button in some configurations, that is solved

Resizing the widgets is definitely desired but should be happend in a separate issue.

**Comment by laeubi** [comment]
> Resizing the widgets is definitely desired but should be happend in a separate issue.

This would be a good example where one can use [BorderLayout](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/common/org/eclipse/swt/layout/BorderLayout.java) i'll try to propose a patch...

**Comment by ronso0** [comment]
Thanks @laeubi for poining out _my_ issue with the dialog.
So are you working on this or should I open a separate issue nonetheless? (Or is there already one? Am not tracking this repo..)
