### ISSUE TITLE
Extend editor specification with editor precedence based on content type bindings

### ISSUE THREAD

**Issue by travkin79** [eclipse-platform/eclipse.platform.ui#1659]
## Issue

It seems, the Eclipse platform does not provide any way of specifying when to prefer which editor in case we have multiple editors bound to the same content type. For example, having two C++ editors registered for the C++ content type (e.g. content type ID org.eclipse.cdt.core.cxxSource) and trying to find the preferred (or "default") editor for a cpp file with `IDE.getEditorDescriptor(path, true, false)`, the Eclipse platform will just [select the first compatible editor that if finds](https://github.com/eclipse-platform/eclipse.platform.ui/blob/d7676d31c86c5ff586a9fa091b2cb81981ffd754/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/registry/EditorRegistry.java#L1341).

When specifying an editor in an editor extension, we can set the default attribute to true, but that value seems not to be considered when selecting editors by content type bindings.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10887297/060df71d-e5d6-4ad4-a06f-8959ce0eefd8)

This issue might be related to #1532.

## Suggestion

It would be nice if there were an extension point where we can specify an editor precedence based on the content type binding, e.g. prefer LSP-based C++ editor over the classical C++ editor from CDT or prefer the generic text editor over the default text editor. The extension point should provide default settings that can be changed via preferences based on the user needs.

Having this, the Eclipse Platform's editor choice based on the content type should consider the specified / configured editor precedence. I.e. in case of multiple editors registered for the same content type `IDE.getEditorDescriptor(path, true, false)` would not just return an arbitrary editor that matches the content type, but return the one preferred by the user (or plugin specifications).

**Comment by iloveeclipse** [comment]
Comparing that to the "File associations" page that allows select which editor should be default if multiple register for "txt", we miss "Default" button and a preference behind:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/bb49df58-abf1-430f-a823-b7edd5fad882)

**Comment by iloveeclipse** [comment]
Not sure if we need extension point here, as we will have same dilemma if multiple editors will register themselves as "default_for_XYZ".


I **believe** (without digging into code) it could be easy - we need new preference key, lookup & UI change.
At the place where we have multiple editors and select first one, we should lookup for the `defaultEditor_<content_type>=<editor_id>` and if there is a match, use that.
Defaults for SDK could be set in IDE initializer.
Defaults for product in product preferences.
Default for user via Oomph.

@travkin79 : I offer review if you contribute that.

**Comment by travkin79** [comment]
My idea of a precedence specification in an extension point was not to flag an editor as a default editor for content type X, but to specify a partial precedence order like "for content type X the editor with ID A is to be preferred over editor with ID B". The most "preferred" editor wins in that case.

But maybe that's more complicated than it needs to be. Maybe a preference like `defaultEditor_<content_type>=<editor_id>` as suggested by @iloveeclipse is good enough and if no default is set by the user (or by SDK/product defaults preferences or by Oomph installer) the first match wins (as it is now).

I'm not sure if I have the time to contribute a PR for that.

**Comment by mickaelistria** [comment]
Having "default" on an editor in indeed an anti-pattern: the provider of the editor cannot really claim whether it applies as default in all clients.
I agree with @iloveeclipse that similarly, what you suggest here would lead to the same issue: why would allow a plugin provider to override the "preferred" extension-point reliably for all clients? It's not obvious, and with both LSP4E and CDT install, one may want an editor or another. There is nothing obvious that allows to tell in a general case that one content-type is better than another (unless one is a child/specialization of the other, which is then already preferred IIRC).

I also agree the preference-based approach has the benefit of 1. being overridable by product providers, 2. being overridable by end-users and 3. being potentially modified programatically by a plugin. So I would favor this approach too.

**Comment by travkin79** [comment]
How would you handle hierarchies of content types and their default editor preference settings, just take the most specific content type preference (deepest in content type hierarchy)?

**Comment by iloveeclipse** [comment]
Yes.

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/1665

**Comment by iloveeclipse** [comment]
> I **believe** (without digging into code) it could be easy - we need new preference key, lookup & UI change.

That was easy, so I would assume we can merge that to M3.

**Comment by iloveeclipse** [comment]
TODO: add N&N.
@travkin79 : could you do that?

**Comment by BeckerWdf** [comment]
> #1665

The documentation of that preference page should also be updated.

**Comment by iloveeclipse** [comment]
> The documentation of that preference page should also be updated.

@BeckerWdf : thanks for reminder, I saw you were fixing quite a lot in the documentation area recently - could you give me a pointer where the related documentation is located?

**Comment by BeckerWdf** [comment]
> > The documentation of that preference page should also be updated.
> 
> @BeckerWdf : thanks for reminder, I saw you were fixing quite a lot in the documentation area recently - could you give me a pointer where the related documentation is located?

Sure. It's ref-content-type.htm in the org.eclipse.platform.doc.user bundle in the eclipse.platform.releng.aggregator repo:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/867f22b082e11c8b31c9a239c7781c8729a0cdcb/eclipse.platform.common/bundles/org.eclipse.platform.doc.user/reference/ref-content-type.htm

**Comment by travkin79** [comment]
I added a PR with the documentation update
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1803

**Comment by travkin79** [comment]
I added a PR with N&N
https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/119

**Comment by iloveeclipse** [comment]
@travkin79 & @BeckerWdf : thanks!
