### ISSUE TITLE
Add convinient method for creating a LocalResourceManager

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#167]
To handle images I frequently create a LocalResourceManager.

LocalResourceManager manager = new LocalResourceManager(JFaceResources.getResources(), mycontrol);

I suggest to add a static method which makes this easier.

LocalResourceManager.for(myControl)

Any objections? Seems like the most common pattern I see in code. Adding @laeubi as he typically like API discussions.

**Comment by vogella** [comment]
On second though, not worth it....

**Comment by laeubi** [comment]
I must confess its often hard to "find" things (an not to search for @vogella tutorial first ;-))

So why not `ResourceManager.for(Control)` ... it can even cache the instance inside the Controls data to not create many of them...
