### ISSUE TITLE
Splash Screen no longer shown when launching child Eclipse

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.ui#1677]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

1. Set up a launch configuration to launch a child Eclipse instance
2. Launch child Eclipse
3. Note that the Eclipse splash screen is not shown

## Tested under this environment:
* OS & version: Mac 13.6.4
* Eclipse IDE/Platform version (as shown in *Help > About*): Version: 2024-03 (4.31) Build id: I20240212-1800

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by laeubi** [comment]
@Phillipus there is a "native" and a "program" splash where the native one is never shown and the programmatic one need special setup as far as I know (I never got it working) ... so was this working before (what version?) and how did you configured it in the launch config?

**Comment by Phillipus** [comment]
My bad. My launch config was set to "Run a product: org.eclipse.sdk.ide". If I set it to "Run a product: org.eclipse.platform.ide" I see the splash screen.
