### ISSUE TITLE
IOException in WindowsDefenderConfigurator on startup

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform.ui#1696]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

I'm in the unfortunate situation where we use an anti-virus program with even worse performance problems than the Windows Defender. The WindowsDefenderAutofix which was merged recently doesn't seem to handle this tool very well.

Unless explicitly disabled in the preferences, starting the Eclipse now always also shows the following popup:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/41fed1da-9911-4d12-9dbc-746a41661cab)

## Steps to reproduce

From a fresh installation and clean workspace:

- Install Cortex XDR and use it instead of the Windows Defender
- Restart the Eclipse IDE

I tried:
Not much, given that I'm not able to configure Cortex in any capacity.

I expected:
The startup task to be skipped, as Windows Defender is inactive.

But got: 
The error dialog shown above.

## Here is some relevant log output

```
java.io.IOException: Process terminated with unexpected result:

	at org.eclipse.ui.internal.WindowsDefenderConfigurator.isWindowsDefenderActive(WindowsDefenderConfigurator.java:289)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.runExclusionCheck(WindowsDefenderConfigurator.java:153)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.lambda$0(WindowsDefenderConfigurator.java:100)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

The problem seems to be the value of the `AMRunningMode` property. Given the configuration described above, I would expect it to be "Passive Mode", but instead it is an empty string. I assume that this is because the following criteria is not satisfied: 
[Passive mode is only available for devices that are onboarded to Microsoft Defender for Endpoint and that meet certain requirements.](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-antivirus-windows?view=o365-worldwide#use-powershell-to-check-the-status-of-microsoft-defender-antivirus)

Any thoughts on this?

## Tested under this environment:
* OS & version:
  - Windows 10 PRO
  - Version10.0.19045 Build 19045
* Eclipse IDE/Platform version : 
  -   eclipse.buildId=4.31.0.I20240218-1800
  -   java.version=21.0.1
  -   java.vendor=Eclipse Adoptium

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by ptziegler** [comment]
The Eclipse processes the content of `Get-MpComputerStatus`. This command already doesn't work. Reason being that the process isn't running in the first place.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/2fd9bad2-24be-400d-b5e0-ce00ad4ceac3)

My suggestion would be to first check wherer WindowsDefender is running and only then try to load its status.

**Comment by vogella** [comment]
cc @HannesWell

**Comment by HannesWell** [comment]
Thank you @ptziegler for the report and @vogella for linking me.

> The Eclipse processes the content of Get-MpComputerStatus. This command already doesn't work. Reason being that the process isn't running in the first place.

That's interesting. I wasn't aware of that. Even when I had another AV-software installed this was working for me.

Based on your suggestion I'll add an invocation of `(Get-Service 'WinDefend').Status` as very first check and assume that win-defender is inactive if that doesn't return `running`or fails (who knows what else can go wrong).

I'll create a PR later this evening and will submit it on time for tonight's I-build.

**Comment by ptziegler** [comment]
> That's interesting. I wasn't aware of that. Even when I had another AV-software installed this was working for me.

To be honest, I'm not 100% sure whether those errors are related and only something I found while looking for possible reasons for the error message of `Get-MpComputerStatus`:

https://techcommunity.microsoft.com/t5/windows-powershell/powershell-get-mpcomputerstatus/m-p/305684

More specifically:
> However, if you have another anti-malware product installed e.g. McAfee, Norton, etc., these may/will disable Windows Defender and prevent the service from starting.

Which I believe to be the case. One could probably try to temporarily disable Windows Defender via `Stop-Service windefend` and then see how `Get-MpComputerStatus` behaves but I don't really have a Windows installation where I could easily do that... :/

**Comment by ptziegler** [comment]
It might even be that `Get-MpComputerStatus` is simply not implemented for Cortex.
In any case, checking the status of Windows Defender should still be the way to go.

**Comment by HannesWell** [comment]
> > However, if you have another anti-malware product installed e.g. McAfee, Norton, etc., these may/will disable Windows Defender and prevent the service from starting.
> 
> Which I believe to be the case. One could probably try to temporarily disable Windows Defender via `Stop-Service windefend` and then see how `Get-MpComputerStatus` behaves but I don't really have a Windows installation where I could easily do that... :/

I tried that on my personal Windows Computer where I actually have all permission and not even in a powershell started with admin privileges this call succeeds:
```
C:\Windows\system32> Stop-Service 'WinDefend'
In Zeile:1 Zeichen:1
+ Stop-Service 'WinDefend'
+ ~~~~~~~~~~~~~~~~~~~~~~~~
Das Skript enthält schädliche Daten und wurde von Ihrer Antivirensoftware blockiert.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent
```

> In any case, checking the status of Windows Defender should still be the way to go.

I think that as well. Will continue with that approach.

**Comment by HannesWell** [comment]
I tried out a little bit more, but didn't find a better solution and just created https://github.com/eclipse-platform/eclipse.platform.ui/pull/1701.

**Comment by ptziegler** [comment]
I just installed the I20240219-1800 and neither is the dialog shown, nor does any exception show up in the error log.
@HannesWell Thanks for the quick fix!

**Comment by ptziegler** [comment]
Trying to run the task manually also behaves as expected 👍 

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/a79df690-8da8-4fcc-80c5-f49a1b4d9e69)

**Comment by merks** [comment]
It's great to get such timely feedback and then to get such timely fixes!  ❤️

**Comment by HannesWell** [comment]
> I just installed the I20240219-1800 and neither is the dialog shown, nor does any exception show up in the error log. @HannesWell Thanks for the quick fix!

Great! Thanks for the fast feedback.

**Comment by HannesWell** [comment]
I just want to take this issue as a good example to emphasize the importance of early testing the I-builds.
Not only will it reduce the probability of bugs in the final releases, one also gets fixes quicker since it is often just one nightly I-build away in contrast to three months or four weeks (if one only uses releases or milestone).
And last but not least it also makes it easier to identify the source of bugs if done regularly and it is easier to fix if the person who introduced it worked on the topic only a few days ago instead of maybe even months.

So thanks again for your early testing. :)
