### ISSUE TITLE
org.eclipse.pde.api.tools.annotations cannot be resolved when bundle is imported into workspace

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.ui#1700]
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Since https://github.com/eclipse-platform/eclipse.platform.ui/commit/c81c48d5e855f9f2bde493e9797ab133b16ffe9b when I import the `org.eclipse.jface` source bundle into my workspace to test something I get hundreds of errors because `org.eclipse.pde.api.tools.annotations.*` cannot be resolved.

1. In Eclipse workspace import the `org.eclipse.jface` source bundle
2. Note lots of errors because `org.eclipse.pde.api.tools.annotations` cannot be resolved

The workaround is to add `additional.bundles = org.eclipse.pde.api.tools.annotations` to the `build.properties` file.

Is there some other way to resolve the dependency in the workspace?

**Comment by laeubi** [comment]
@Phillipus I'm not sure what "I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)" means but if you are using the Eclipse SDK IDE as described here:
https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

it should give you no errors. If you use some other setup make sure the annotations bundle is in your target platform.

**Comment by Phillipus** [comment]
@laeubi I'm using Eclipse 4.30 as IDE and a target platform of 4.31 (latest I build). I guess i need 4.31 as IDE.

**Comment by laeubi** [comment]
> @laeubi I'm using Eclipse 4.30 as IDE and a target platform of 4.31 (latest I build). I guess i need 4.31 as IDE.

Yes, otherwise you are not really using [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) but only targeting it.
