### ISSUE TITLE
Internal browser fails to render contents and images on some Windows 11 configurations

### ISSUE THREAD

**Issue by Yuri-Blankenstein-TNO** [eclipse-platform/eclipse.platform.ui#1704]
Dear support,

I'm facing an issue on Windows 11 64-bit where Eclipse fails to render the help contents and images when using the internal help browser, see screenshot below. This is only the case on some Windows 11 configurations as I have seen it working on other Windows 11 machines. Also, when I choose to use the external webbrowser, the help pages are loaded correctly.

<img width="781" alt="Eclipse Help Windows 11 problem" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/72129129/6d26ed14-10d1-407d-ae89-a8bb2bda4d02">

**Comment by akurtakov** [comment]
Please try https://www.eclipse.org/swt/faq.php#howuseedge . I don't have access to Windows but AFAIK IE is gone in Windows11 thus one has to rely on edge.

**Comment by Yuri-Blankenstein-TNO** [comment]
Thank you so much! Adding `-Dorg.eclipse.swt.browser.DefaultType=edge` to the `eclipse.ini` under -vmargs did the trick.

**Comment by akurtakov** [comment]
SWT should be modified to load Edge when on Windows 11 by default in this case. Maybe you would like to open a PR that does that (what exactly has to be done is something I can't help with).

**Comment by Yuri-Blankenstein-TNO** [comment]
I also don't know how to adapt SWT to use Edge by default. As we are building an RCP, I can easily add the system property as vmarg in the product, only for Windows.

**Comment by akurtakov** [comment]
@elsazac Maybe you'll be interested in that ?

**Comment by HeikoKlare** [comment]
I am fully in favor of using the Edge browser on Windows as default and appreciate every effort on achieving that. However, there are some further things to consider and to do when/before switching to Edge as default. First, not every view relying on a browser does already work with Edge. The most prominent one is the Welcome view. This is how it looks like:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/d2f990e2-f13a-4aa7-926f-88bf323e4148)

I do not completely remember the cause but it is related to the page being composed of links to file system contents, which is not supported by browsers like Edge for security reasons. So at least the welcome page has to be reworked as well.

In addition, my impression is that the Edge browser is still far from stable as it is not commonly used, as you can also see on recent fixes:
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1015
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1016
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1017
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1018

Currently, it is also _not_ automatically tested at all. My attempts to enable the tests failed so far: https://github.com/eclipse-platform/eclipse.platform.swt/pull/672

**Comment by akurtakov** [comment]
Even with these problems if IE fails entirely it makes sense to try Edge - some broken rendering is better than no rendering at all. We had that state with different versions of webkitgtk under linux.

**Comment by merks** [comment]
I'm not sure it's safe to conclude that IE fails entirely on all/most Windows 11 systems; I think we would have heard more of an outcry in that case.  Of course moving forward, we must move away from IE!

**Comment by akurtakov** [comment]
Well, clearly in the case of this user Edge gives better results for him so it's a call which group of people should be left (more) broken - not an easy choice. As I have zero access and interest in windows I consider that I've already overdone my part here thus stepping out :).

**Comment by HeikoKlare** [comment]
I think we are actually all on the same line 🙂 

In SWT, Edge browser should replace IE as default as soon as possible. With my comment, I only wanted to point out that there are things that will break when doing so. And in my opinion, things like the welcome screen are kind of essential. What will a user think of the Eclipse IDE when it starts with a completely broken welcome screen? 😉 But I also think that this is something that will be quite easy to fix. It should just be on the list of things to do when changing default browser to Edge.
Probably other bugs will occur afterwards, but rolling it out to more users by making it default will at least provide us the required feedback to find them.

**Comment by merks** [comment]
I think we all agree,  IE is dead or dying and edge is the only via path forward right now.   Probably we should have an issue to track making it the default and tracking all the things that need to be done related to that...

**Comment by Yuri-Blankenstein-TNO** [comment]
I'm indeed suffering from the same problem with the welcome screen as mentioned by @HeikoKlare. Because of this, the proposed patch is not a solution for us. So there seems to be a kind of impasse that limits the use of Eclipse on some Windows 11 systems.

Does anyone of you know what difference in the Windows 11 configuration prevents the Eclipse Help from rendering? I see many Windows 11 installations for which it works perfectly (and thus also the welcome page), but for some configurations it fails, and I'm wondering what is the difference in these configurations.

**Comment by HeikoKlare** [comment]
> Does anyone of you know what difference in the Windows 11 configuration prevents the Eclipse Help from rendering?

Unfortunately, I have no idea. We have the Edge browser in use for some specific views, for which the IE is insufficient, but everywhere else the IE is still in use. I have not yet heard of anyone having problems with the IE in Eclipse so far, in particular not in the Eclipse help. We use Windows 10 and Windows 11 systems in our company and I also use a Windows 11 system with latest updates privately without having IE issues.
