### ISSUE TITLE
Number of recent workspaces to remember doesn't change (in the UI) when less than 10

### ISSUE THREAD

**Issue by andrew-tram** [eclipse-platform/eclipse.platform.ui#1711]
In the preferences, when changing the number to less than 10 and apply/close, the number reverts back to 10 in the UI. Changing it to something greater than 10 seems to persist from the Preferences. 

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/106191140/188ac4c2-4752-41ea-82b8-afe3b975fb35)

Manually changing the number in configuration\.settings\org.eclipse.ui.ide.prefs doesn't seem to make a difference.

`MAX_RECENT_WORKSPACES=2` reverts the UI to show 10
`MAX_RECENT_WORKSPACES=19` uses the value defined

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/106191140/e0eac941-05f8-49da-9c4f-401c3c1092d3)

- [X ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Tried on Eclipse 4.30 and Eclipse 4.24 with the same results.

## Steps to reproduce

From a fresh installation and clean workspace:

Scenario A: From Windows > Preferences
- Navigate to General > Startup and Shutdown > Workspaces
- Change the number dial to less than 10, apply /close, reopen the same Preference area and observe it stays 10
- Change the number dial to great than 10, apply/close, reopen and observe the number chosen persists

Scenario B: From configuration\.settings\org.eclipse.ui.ide.prefs
- Open to edit the file and adjust the MAX_RECENT_WORKSPACES property to something less than 10, relaunch Eclipse and 10 is used
- Edit to something greater than 10 and that number is used

I'm guessing it has to do with this in `org.eclipse.ui.ide`

```
	/**
	 * The default max length of the recent workspace mru list.
	 */
	private static final int RECENT_MAX_LENGTH = 10;
```

Which is a little confusing to me, because I think it'd make more sense for it to read as the **minimum**?

## Tested under this environment:
* OS & version: ...
* Eclipse IDE/Platform version (as shown in *Help > About*): ...
* ...Anything else that can be useful...

## Community

- [x ] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by andrew-tram** [comment]
Still looking for some assistance on this

**Comment by merks** [comment]
I can't explain the design, but it is working as designed:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/04dd9a1bf255b0af610082a38d79ccd4fa861084/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/ChooseWorkspaceData.java#L434-L436

where this value is 10:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/04dd9a1bf255b0af610082a38d79ccd4fa861084/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/ChooseWorkspaceData.java#L44-L47

At some point in time it was like this:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/f0596209-baf6-4d4b-815e-29ceecb8368e)

And with that change, instead of being the default that value became also a minimum.

**Comment by andrew-tram** [comment]
Okay, thanks for confirming that 10 is for sure designed to be the minimum. Not a deal breaker, but we had one user on our RCP app ask us why changing the number (to something less than 10 in their case) didn't work, which lead me to here. But that's fine and I'll let them know it's all good and 10 is the min.
