### ISSUE TITLE
Navigator view is missing

### ISSUE THREAD

**Issue by YSavanier** [eclipse-platform/eclipse.platform.ui#1729]
Hello

I know that this view was deprecated for a long time but since last Eclipse version I can't find this view anywhere in the view selector.

Was it removed or is it just not correctly referenced ?

If it was removed then, can you just please tell me how we are suppposed to look at both at ours project's files during coding which are ordered and filtered for obvious reasons AND at the real filesystem files tree, for whatever reason like checking binaries in target folder, while staying in the eclipse IDE without resorting to constantly changing the project view's filters or opening Windows Explorer/Linux equivalent outside Eclipse which can't then open up the overlooked files in eclipse editor ?

Is there any existing plugin re-enabling such a basic view (being able to simply see all the project's files but not by altering the main view permanently !) or should I tell the remeaning members of my team still using eclipse to stay in 2022 version before switching to another IDE ?

Thank you for you concern

Regards,

**Comment by mickaelistria** [comment]
The navigator view was removed after long deprecation.
Please see https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Ftasks%2Ftasks-48b.htm and https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.user/reference/ref-27.htm about using the Project Explorer to desactivate filters/show more files.

**Comment by YSavanier** [comment]
Thank you for your quick, even if unsatifying, answer. Indeed I just found the offending PR at #644 

Ok then, it is the final nail in the coffin for us as, even if it pains me, we are clearly not going to keep altering the main project's view to mimic the removed fs view...

To be honest, there were little grounds left to keep migrating all our projects to IntelliJ, but with that and the project's quick launcher menu removal I will not argue with my colleagues anymore about staying on the old IDE for the sake of isofunctionality.

Have a nice day.

Regards,
