### ISSUE TITLE
reproducible Bug 371586: broken comparator

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1731]
in current platform workspace sort Problems in this order:
1. click on Resource
2. click on Path
3. click on Location

=> wrong result and error log entry
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/0daa5e1c-674a-4a25-aac5-5b507837d96f)

```
Bug 371586: broken comparator. MarkerCategory [name=Warnings, severity=1, start=0, end=5247], 
fields: [Location (org.eclipse.ui.internal.views.markers.MarkerLocationField), 
Path (org.eclipse.ui.internal.views.markers.MarkerPathField), 
Resource (org.eclipse.ui.internal.views.markers.MarkerResourceField), 
Type (org.eclipse.ui.internal.views.markers.MarkerTypeField), 
Description (org.eclipse.ui.internal.views.markers.MarkerProblemSeverityAndMessageField), 
ID (org.eclipse.ui.internal.views.markers.MarkerIDField), 
Creation Time (org.eclipse.ui.internal.views.markers.MarkerCreationTimeField)]

java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.base/java.util.TimSort.mergeHi(TimSort.java:903)
	at java.base/java.util.TimSort.mergeAt(TimSort.java:520)
	at java.base/java.util.TimSort.mergeForceCollapse(TimSort.java:461)
	at java.base/java.util.TimSort.sort(TimSort.java:254)
	at java.base/java.util.Arrays.sort(Arrays.java:1308)
	at org.eclipse.ui.internal.views.markers.MarkerSortUtil.sortStartingKElement(MarkerSortUtil.java:284)
	at org.eclipse.ui.internal.views.markers.Markers.sortMarkerEntries(Markers.java:161)
	at org.eclipse.ui.internal.views.markers.SortingJob.run(MarkerUpdateJob.java:184)
	at org.eclipse.ui.internal.views.markers.CachedMarkerBuilder.lambda$0(CachedMarkerBuilder.java:256)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)

eclipse.buildId=4.31.0.I20240229-0520
java.version=21.0.2
```

**Comment by laeubi** [comment]
@jukzi if you can reproduce it, please do the following:

1. Surround the code block where the exception occurs with try catch
2. In the catch block you then can insert one of the codes suggested here https://stackoverflow.com/questions/11441666/java-error-comparison-method-violates-its-general-contract
3. This should give an insight what contract is violated and one then needs to watch out for asymetries, in the comparators used

**Comment by jukzi** [comment]
Even if i get no Exception the ordering of the Location column is currently wrong when it does not contain a linenumber:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/495806da-003f-46eb-998b-3203c40ec491)
As soon as i change that org.eclipse.ui.internal.views.markers.MarkerLocationField.compare(MarkerItem, MarkerItem) to sort either numbers or locationfirst and then the other the order is fine and i don't get Exception anymore.
But i did not understand why that `location1.isEmpty() || location2.isEmpty()` is evil.
Anyway i will just submit a fix.

**Comment by laeubi** [comment]
> But i did not understand why that location1.isEmpty() || location2.isEmpty() is evil.

This might violate the total / transitive ordering e.g. that a>b & b > c implies that a > c because depending on the location is empty different secondary attributes are compared.

Because of that I would for comparators always avoid having deeper nesting or conditions but always a linear flow like in your PR:

1. Always fetch the same attribute and if it is not available assume a comparable default (e.g. null -> "", unknown positive number -> -1 and so on)
2. Always compare and only use others if the compare == 0

To make such things easier and more save, the `Comparator.comparing(..).thenComparing(...)` functions (and there int/long/doubl/ ... variants) are a great help to write good comparators instead of hand-crafting a compare method..
