### ISSUE TITLE
[Find/Replace] Search-scopes don't update

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#1740]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

1) Open a file
2) select any area of text
3) Open the Find/Replace-Dialog
4) select another area of text
5) press "selected lines" in the Find/Replace-Dialog
6) see that the old area is used as search-scope, instead of using the new scope

I expected the search-scope to update with the new selection

But got the old search-scope that was first deactivated and re-activated again.

## Tested under this environment:
Eclipse SDK

Version: 2024-03 (4.31)
Build id: I20240229-0520

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by jukzi** [comment]
i wonder why i can not reproduce that bug

**Comment by Wittmaxi** [comment]
@jukzi This is the behavior on my end:
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/b4764fe5-b396-4da3-8286-c55b90910bc2)
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/2cae8bcc-edcd-41c4-8833-540f1816783e)
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/e69f0801-91b1-458b-af9b-93f64f7dc8b6)
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/57e97108-da77-43a1-8961-5a6fce1c6bb0)

I have implemented a Fix+Regression-Test [here](https://github.com/Wittmaxi/eclipse.platform.ui/commit/6ebfd8a03f1b7e9f97786cc1d86bb1653d410fb7)

**Comment by jukzi** [comment]
tried to reproduce again: this time i faced this:
1. activate "Selected lines"
2. select other lines (without closing dialog)
=> "Selected lines" is deselect and Scope=All is set. WTF

**Comment by HeikoKlare** [comment]
I can reproduce the bug:
![Animation](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/a98fed00-7921-4cb5-8a7e-fbb614cb9355)

> * activate "Selected lines"
> * select other lines (without closing dialog)
>   => "Selected lines" is deselect and Scope=All is set. WTF

That is existing behavior and, if I am not mistaken, has always been like this.

**Comment by jukzi** [comment]
> 2\. select any area of text

can only reproduce if select a multiline text in step 2.

**Comment by Wittmaxi** [comment]
> That is existing behavior and, if I am not mistaken, has always been like this.

Yes, that is correct. See [this](https://github.com/eclipse-platform/eclipse.platform.ui/blob/a441f984fb25d26386fbe032e0c6b0a8c6d606f4/bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/texteditor/FindReplaceDialog.java#L113) listener that handles when the Dialog is left.

**Comment by Wittmaxi** [comment]
I cannot reproduce this issue anymore, I believe it to be closed @HeikoKlare

**Comment by HeikoKlare** [comment]
Yes, it has been fixed via #1741.
