### ISSUE TITLE
Consider to add support to create multiple types at once through the Dialog Window

### ISSUE THREAD

**Issue by manueljordan** [eclipse-platform/eclipse.platform.ui#1744]
Hello 

At the `src/main/java` location for any custom package, when we arrive to the `New Java Class` dialog window we can put the name of the class in the `Name` field. Could you consider to enable to put multiple names to create a set of classes together at once? I mean something like:

```
Car,Computer,Airplane,Book
```

It to avoid open 3 more times the mentioned dialog window. Currently is not possible through neither `,` nor `;`

Consider the same request for Interfaces, Enums and .properties (it at `src/main/resources` and `src/test/resources`)

Of course considering that all these types should be created within the same package.

Thanks for your understanding.

**Comment by mickaelistria** [comment]
This dialog comes from Eclipse JDT project, not Eclipse Platform. Can you please send this request to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues ?

**Comment by manueljordan** [comment]
Oh, I see. I didn't know that. Thanks for the guidance
