### ISSUE TITLE
ProgressBar from org.eclipse.jface.action.IStatusLineManager do not stop when required.

### ISSUE THREAD

**Issue by MirceaEnachescu** [eclipse-platform/eclipse.platform.ui#1745]
I start a new task on the StausLineManager's Progress Monitor like this:
`statusLineManager.getProgressMonitor().beginTask(status.getText(), IProgressMonitor.UNKNOWN);`
When I finish the operation, then call to: `statusLineManager.getProgressMonitor().done();` it does fail to stop and hide the ProgressMonitor as it used to do.
Noticed this behavior since version 4.30

**Comment by jukzi** [comment]
getProgressMonitor() may return another instance each call. please make sure you use the same instance for calling done()

**Comment by jukzi** [comment]
see org.eclipse.jface.action.IStatusLineManager.getProgressMonitor()
`Creates a new progress monitor which reports progress in the status line.`

**Comment by MirceaEnachescu** [comment]
Hello, `getProgressMonitor()` create a new one every time indeed, but it wraps over the nested `org.eclipse.jface.action.StatusLine` progress monitor, which is constant.
I have to say that this problem was not encountered since Eclipse 3.4 when we started our implementations. Only from 4.30 and 4.31 is not working.
I will try to keep the instance, and let you know about it.
