### ISSUE TITLE
[RFE] Add support for "editor" content types for compare editor / contentViewers extension

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1747]
Moved from https://github.com/eclipse/tm4e/issues/730.

Currently textmate (and generic editor) based editors seem not support syntax highlighting in compare editor.

Example: in 4.31 Eclipse, set "Generic Text Editor" as default for XML content type, select two `.project` files in Package Explorer and via right click run "Compare With... -> Each Other" command.

That would show both parts of the editor without syntax highlighting:

![image](https://github.com/eclipse/tm4e/assets/964108/a03a20ff-bc4d-404d-9202-c1fb0a18eb42)

That is of course not working for any other content type with textmate syntax support, XML here was chosen as it is simple to reproduce.

It would be nice if the syntax highlighting for all supported content types of generic editor also would be supported in compare editor.

During the discussion of this request, Mickael mentioned that:

> Enabling (some) generic editor features in the compare viewer has to be declared per content-type, ideally by the same bundle as the one that defines the content-type association with generic editor. Eg from Wild Web Developer https://github.com/eclipse-wildwebdeveloper/wildwebdeveloper/blob/13c104d642e17156c7308ce43a78ccb04edcb55e/org.eclipse.wildwebdeveloper/plugin.xml#L1273C4-L1286C16
> 
> ```
> <extension
>          point="org.eclipse.compare.contentViewers">
>       <contentTypeBinding
>             contentTypeId="org.eclipse.wildwebdeveloper.parent"
>             contentViewerId="org.eclipse.ui.genericeditor.compareViewer">
>       </contentTypeBinding>
>    </extension>
>    <extension
>          point="org.eclipse.compare.contentMergeViewers">
>       <contentTypeBinding
>             contentMergeViewerId="org.eclipse.ui.genericeditor.compareViewer"
>             contentTypeId="org.eclipse.wildwebdeveloper.parent">
>       </contentTypeBinding>
>    </extension>
> ```

and also:

> Note that the generic editor isn't referenced directly here, it's a separate id/object that is assigned to the compare viewer, and there is no declarative mapping between this object and the underlying text editor.
> So it's not trivial to infer the proper compare viewer from the editor association.
> But if you think it's doable, that would indeed be an interesting improvement for Platform.

The problem we have is that editor associations could be manually updated by user, but contentViewers/contentMergeViewers cannot, even if that would technically work (like in generic editor case), because they share same underlying implementation.

So my proposal would be to extend contentViewers/contentMergeViewers extension point and add an attribute to consider "linked" editor content type associations. The code could check if contentViewers/contentMergeViewers contribution refers to such "linked" editor id in extension, and check if editor supports other content types. In case there are more content types supported by same "linked" editor, these would be automatically considered as valid contentTypeBinding for the contentViewers/contentMergeViewers.

This shouldn't be that complicated. From compatibility point of view, since the extra extension attribute would be not set by default, none of existing code would be affected. For the generic text editor that would mean to mark its contentViewers/contentMergeViewers contributions "linked" to "org.eclipse.ui.genericeditor.GenericEditor" and that's it. Any "specialized" editor versions of generic editor (with dedicated editor id) shouldn't be affected either.

Once I have some time, I would try to provide a PR for that idea, but any comments / contributions welcome.

**Comment by iloveeclipse** [comment]
See
- main change: https://github.com/eclipse-platform/eclipse.platform/pull/1277
- generic editor link: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1786

**Comment by iloveeclipse** [comment]
@mickaelistria : would be nice if you could review the proposals.

**Comment by iloveeclipse** [comment]
> @mickaelistria : would be nice if you could review the proposals.

Here is how it looks like on Windows, comparing .project or .classpath files with each other with installed Textmate and no extra configuration needed:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/f696289a-4e17-4afa-9e72-3cd645fabc5a)

I would like to merge for M1, if there is any objections, please comment on PR's.

- main change: https://github.com/eclipse-platform/eclipse.platform/pull/1277
- generic editor link: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1786

**Comment by merks** [comment]
If no one finds time to review, you should use your own best judgment and feel empowered to proceed.

**Comment by iloveeclipse** [comment]
I see that new feature only works in some cases, I've missed read-only diffs => need additional changes.

**Comment by iloveeclipse** [comment]
Ok, with latest changes merged I see this picture on latest SDK I20240409-1800 + latest Textmate installed (and no extra options used):
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/540e3bd1-dd6f-4d1c-85e0-34e8a0804db8)

That works now for all file types supported by TextMate, both for files in the workspace or diffs coming from git (History view).
