### ISSUE TITLE
The Windows Defender guard appears not to function for "strange" paths

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.ui#1757]
I often test that the installer works with strange paths, so I do things like `-Duser.home="D:\Users\tëst 35\"`, i.e., non-ASCII and a space, and hope that everything works well.  I noticed that for such an installation, the defender dialog pops up each time I start.  I tell it yes please exclude this installation but it asks me again each time I start so I assume something has gone wrong.  I can tell it to stop checking and it remembers that, so it's not super annoying, but it's worth checking what's going wrong.

**Comment by BeckerWdf** [comment]
@HannesWell: Can you pls. have a look at this?

**Comment by HannesWell** [comment]
Will take care of it. I assume something is not encoding the path correctly.

**Comment by HannesWell** [comment]
> I often test that the installer works with strange paths

Looks like the space was already too strange and the URL returned by the location didn't encode it correct which made the entire retrieval fail.
A fix is at https://github.com/eclipse-platform/eclipse.platform.ui/pull/1772.

When launching a secondary eclipse non-ascii characters in the install location were handled correctly, but in that case the persisting does not work.
Unless Ed you or somebody else has already verify that it is only with spaces (i.e. non-ascii chars without spaces work fine), I'll test that tomorrow.

**Comment by HannesWell** [comment]
> > I often test that the installer works with strange paths
> 
> Looks like the space was already too strange and the URL returned by the location didn't encode it correct which made the entire retrieval fail.

Just verified locally that only the space breaks persisting the applied exclusions. Using one of the following paths works as expected
- C:\pathWithë
- C:\pathWithÖ

So https://github.com/eclipse-platform/eclipse.platform.ui/pull/1772 as it is should be sufficient.
