### ISSUE TITLE
Windows defender popup is shown even though exclusion was added already

### ISSUE THREAD

**Issue by mderveeuw** [eclipse-platform/eclipse.platform.ui#1770]
- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh JDT installation and clean workspace:

* Launch JDT
* Click `Exclude Eclipse IDE from being scanned to improve performance.`  in `Windows Defender Exclusion Check` that pops up, and proceed
* Exit JDT
* Launch JDT again

I expected:

The `Windows Defender Exclusion Check` to not show

But got:

The popup shows every time

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/15202343/3eb5be39-24b0-4e35-8198-d0f37435ed57)

## Tested under this environment:

* Windows 11 Pro 10.0.22631 Build 22631
* Eclipse IDE for Java Developers (includes Incubating components)

Version: 2024-03 (4.31.0)
Build id: 20240307-1437

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by merks** [comment]
Does the absolute path of the installation or the user home folder contain spaces or non-ascii characters?

**Comment by mderveeuw** [comment]
@merks it does indeed, I see now that this is likely a duplicate of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1757

**Comment by merks** [comment]
Yes, that’s why I ask.  Could you share an anonymized sample of the path so we can be sure that case is covered?

**Comment by HannesWell** [comment]
Thanks for the report. Looking at the shared screenshot the white-space in the path is probably the cause of the problem, just like in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1757

The PR https://github.com/eclipse-platform/eclipse.platform.ui/pull/1772 should also fix this.

**Comment by HannesWell** [comment]
Just verified locally that only space in the path breaks persisting the applied exclusions. Using one of the following paths works as expected
- C:\pathWithë
- C:\pathWithÖ

So https://github.com/eclipse-platform/eclipse.platform.ui/pull/1772 as it is should be sufficient.

**Comment by HannesWell** [comment]
@mderveeuw if you are interested you can try out tomorrows `Integration build` from https://download.eclipse.org/eclipse/downloads/ in order to verify it really works as expected.

**Comment by mderveeuw** [comment]
@HannesWell the latest build works for me, thanks for the fix!
