### ISSUE TITLE
switching scheme in runtime workbench doesn't work

### ISSUE THREAD

**Issue by martinlippert** [eclipse-platform/eclipse.platform.ui#1790]
Switching to a different scheme in a runtime workbench doesn't work.

I am running this on a macOS 14.4.1, OS is set to dark mode, Eclipse starts up in dark mode as well (all fine).
Then starting up a runtime workbench, switching to light scheme, press restart. Result is a somewhat broken UI (mixed dark and light scheme).

Steps to reproduce:
- macOS 14.4.1, running in dark mode
- download Eclipse SDK 4.31 release
- startup Eclipse with empty workspace (runs in dark mode, looks fine)
- create a new runtime workbench launch config and start that
- runtime workbench starts up in dark mode (looks fine)
- go to preferences and switch to light scheme
- press restart -> restarted runtime workbench has broken UI (mixed dark and light scheme)

Shutting the runtime workbench down and restarting it from the Eclipse environment doesn't fix the problem, the runtime workbench continues to be in a mixed dark and light scheme.

**Comment by martinlippert** [comment]
Is there maybe a workaround to force the runtime workbench to use a specific scheme? I am looking for always running the runtime workbench in light mode... :-)

**Comment by Phillipus** [comment]
Eclipse itself is launched using an `Info.plist` file (in `Eclipse.app/Contents/`). It contains this important entry:

```
<key>NSRequiresAquaSystemAppearance</key>
<true/>
```

So you need to set your launch config to run with this.

1. Edit the runtime Eclipse launch config
2. Add an Environment variable of `CFProcessPath` and set its value to `<pathto>/Eclipse.app/Contents`

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=540357#c1
and https://bugs.eclipse.org/bugs/show_bug.cgi?id=578893

(Edit - corrected to `CFProcessPath`)

**Comment by martinlippert** [comment]
Hmmm... This issue is really weird on my end. I have switched my OS setting to light mode (macOS on ARM). Using Eclipse 4.31 SDK, I can start a runtime workbench just fine and it shows up just fine in light mode, even without the extra ENV param that you mentioned.

When I do the same using the JEE package, the runtime workbench UI is completely broken (only a few icons show up, nothing else, more or less a blank workbench window). The UI elements are there, but they are not being rendered. Looks really weird.

When switching the OS to dark mode, the SDK test starts up the runtime workbench just fine (in dark mode), but switching that to light mode results in a UI that is half dark mode, half light-mode. Setting the ENV var that you mentioned (with the slight fix calling it `CFProcessPath` instead of `CFProcess`) fixes this behavior. The runtime workbench starts up in dark mode and can be correctly switched to light mode.

When I again switch to the JEE package, it starts up in dark mode, but launching a runtime workbench results in a completely broken UI. Setting the ENV var doesn't help here.

When I switch the host JEE package instance to light mode, the runtime workbench starts up fine (in dark mode, which is somewhat expected).

When running a different product package (using the Spring Tools distribution), those steps don't work.

I can't reproduce this on my older machine running macOS on Intel, but I doubt that this is related to Intel vs. ARM. Maybe something is broken on my machine specifically, but I have no idea where to look. All those packages that I used were fresh installs from the corresponding DMG files. I am somewhat running out of ideas here. Any suggestion?

**Comment by Phillipus** [comment]
What's your target JDK version when you come across the broken UI? Is it [this bug](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012)?

**Comment by martinlippert** [comment]
> What's your target JDK version when you come across the broken UI? Is it [this bug](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012)?

OMG, yes, that seems to be the issue indeed. MANY MANY MANY MANY MANY THANKS!!!
So much appreciated.

**Comment by Phillipus** [comment]
> OMG, yes, that seems to be the issue indeed. MANY MANY MANY MANY MANY THANKS!!!
So much appreciated.

You're welcome.

A side note relating to this issue, [that](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012) issue, other Mac issues, and the infamous Mac row height issue - Apple is changing so many things in its SDK with each annual release that the day will come when SWT will simply no longer work on Mac. That day is coming sooner than you think...

**Comment by martinlippert** [comment]
> A side note relating to this issue, [that](https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012) issue, other Mac issues, and the infamous Mac row height issue - Apple is changing so many things in its SDK with each annual release that the day will come when SWT will simply no longer work on Mac. That day is coming sooner than you think...

Yeah, agree. Exactly one of the reasons why I am (and many others) trying to push this topic (long-term maintenance of SWT across platforms) forward in the IDE WG... :-)

**Comment by Phillipus** [comment]
> Yeah, agree. Exactly one of the reasons why I am (and many others) trying to push this topic (long-term maintenance of SWT across platforms) forward in the IDE WG... :-)

![dependency](https://github.com/eclipse-platform/eclipse.platform.ui/assets/600504/4cce37f6-78f9-4073-aeb3-9edcf71a0693)
