### ISSUE TITLE
Incorrect error markers in Java text editor for "missing types"

### ISSUE THREAD

**Issue by D14-03** [eclipse-platform/eclipse.platform.ui#1799]
Maven Java project uses separate artifact, jar-library, local.
Everything woks fine, but Java text editor shows odd errors, "The method ... from the type ... refers to the missing type ...", see screenshots. The method and type defined in the library. Type of the metod's parameter is exactly the same in library and in caller. In that case it happens for types **java.awt.Image**, **javax.swing.JFrame** and **java.util.prefs.Preferences**.
The markers present _only in text editor_, in the markdown column. Not in project or package or problems view or error log.
Does not prevent program build or execution. 
![ss](https://github.com/eclipse-platform/eclipse.platform.ui/assets/107688694/60bd3b63-b342-4e98-97ff-21afc7ebfeb2)
[eclipse.txt](https://github.com/eclipse-platform/eclipse.platform.ui/files/14904048/eclipse.txt)

**Comment by merks** [comment]
If this is  really purely a JDT problem it should be reported here:

https://github.com/eclipse-jdt/eclipse.jdt.ui/issues

But it sounds like it can only be reproduced with m2e involved, in which case it should be reported here:

https://github.com/eclipse-m2e/m2e-core/issues

That's where I wouldn't personally start.   In either case, no one is likely to likely spend time trying to produce a test case from scratch, so if you really want someone to look at your problem, you need to make that especially easy, i.e., you should attach a zip file with a small project that reproduces.

I cannot move this issue, so you'll need to open one, with more details, yourself.
