### ISSUE TITLE
Cursor multi-select doesn't work with Ctrl+Shift to select larger parts of text

### ISSUE THREAD

**Issue by zhro** [eclipse-platform/eclipse.platform.ui#1811]
Multi-cursor selection works to increase the size of the selection with Shift but drops back to single-cursor selection when using Ctrl+Shift to select larger portions of text. This makes it largely useless, because I want to select whole variables or camel case portions at a time, not just a single character.

See here for an example video:

https://www.youtube.com/watch?v=xhgaE_LE3KI

I am using the key bind "Multi selection down relative to anchor selection" to make my selection, placing the cursor on the right side of the variable, and then Ctrl+Shift+Left Arrow to try and select a larger portion of the variable. This drops back to single-cursor, instead of selecting across all cursors, as expected.

**Comment by mickaelistria** [comment]
This does work for me on plain text. Can you please try the same case in another (non *.java) file/editor?
If you can get it working on plain editor, but not with Java Editor, please report this issue to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/

**Comment by zhro** [comment]
Confirmed. It seems to break due to JDT's "smart caret positioning" feature to move the cursor between camel case words.

https://www.youtube.com/watch?v=lq-8kfnj8Ic

New report submitted, as requested:

https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1323

**Comment by mickaelistria** [comment]
Thanks for reporting to JDT, let's close it here then.
