### ISSUE TITLE
Components which are disabled via Activities are accessible via Quick Access (Ctrl + 3)

### ISSUE THREAD

**Issue by raghucssit** [eclipse-platform/eclipse.platform.ui#1828]
We can disable specific component via Preference -> General -> Capabilities as shown below.
Component means set of eclipse functionalities like Views, Editors, Commands, Menu Items etc.
 
![CapabilityPref](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10301131/ed39a81e-e9bc-4898-989d-846b0538e637)

This kind of disablement/enablement of components are achieved through extension called `org.eclipse.ui.activities`
Functionalities disabled via activities are still accessible via Quick Access Dialog.
For example in the below example, We can access `Javadoc View` using command `Show View (Javadoc)`.
 
![QuickAccessDiff](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10301131/04f88aa6-23c3-4d4c-9e85-ebc2378f9511)

The problem here is, Commands shown in the list are not filtered through Activity Support.

**Comment by raghucssit** [comment]
By default `org.eclipse.ui.activities.WorkbenchActivityHelper.filterItem(Object)` [here](https://github.com/eclipse-platform/eclipse.platform.ui/blob/316aec2cd102e71dd9284ea91445af9c27aa3f32/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/activities/WorkbenchActivityHelper.java#L199) supports only filtering of `org.eclipse.ui.IPluginContribution`. I have improved it to support `org.eclipse.core.commands.Command`.
And i have introduced filtering at `org.eclipse.ui.internal.quickaccess.providers.CommandProvider.retrieveCommand(String)` [here](https://github.com/eclipse-platform/eclipse.platform.ui/blob/316aec2cd102e71dd9284ea91445af9c27aa3f32/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/quickaccess/providers/CommandProvider.java#L103).
But this is not enough like `ViewProvider` [here](https://github.com/eclipse-platform/eclipse.platform.ui/blob/316aec2cd102e71dd9284ea91445af9c27aa3f32/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/quickaccess/providers/ViewProvider.java#L84) because `CommandProvider` creates `Parameterised Command`s for commands like `org.eclipse.ui.views.showView`, `org.eclipse.ui.navigate.showIn`, `org.eclipse.ui.file.export` etc.
So here we need to consider if all the parameters for each of the `ParameterisedCommand` is also hidden by `ActivitySupport` seems to be **expensive(But easily doable)** considering many parameterisable commands available.

Second part is there may be components which are not defined by ActivitySupport.
For example `org.eclipse.jdt.ui.generate.javadoc : [[],**true**,org.eclipse.jdt.ui.generate.javadoc]`. This command shows up list of commands because it has `true` flag inside at `org.eclipse.ui.internal.activities.MutableActivityManager.getIdentifier(org.eclipse.jdt.ui.generate.javadoc)` [here](https://github.com/eclipse-platform/eclipse.platform.ui/blob/316aec2cd102e71dd9284ea91445af9c27aa3f32/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/activities/MutableActivityManager.java#L201)

**Comment by mickaelistria** [comment]
Anything else to do here or can we close?

**Comment by iloveeclipse** [comment]
We should be done.
