### ISSUE TITLE
Compare-View: Cannot click to open folders

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#1838]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce
When double-clicking on a folder, the folder doesn't expand/collapse. Instead, I need to use the "drop-down"-arrow.
I expected:
the folder to open like in other views:
![2](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/5c24b6f4-7ebb-4969-a039-cb24582adaaf)

But got:
nothing happened:
![1](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/61e60e4a-51e3-420d-a42b-6f1331fae126)

## Tested under this environment:
**Operating System**
Windows
**Eclipse version**
Build id: I20240416-0300

## Community
- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by DenisUngemach** [comment]
Hello, 

i have checked the code. It seems that the double click action has never been implemented in the structure compare view. 

In the DiffTreeViewer in line 283 a mouse listener on tree which checks on the double click action and expands if possible should solve this.

eclipse.platform
team\bundles\org.eclipse.compare\compare\org\eclipse\compare\structuremergeviewer\DiffTreeViewer.java

I will add a Pull Request in time.

Best regards,
Denis

**Comment by DenisUngemach** [comment]
There is also a double click handler somewhere, which changes the compare editor "perspective" on the double clicked element.

It is also the question whether a combination of the currently working double click feature and the expand actions is desired.

**Comment by DenisUngemach** [comment]
Also in the project explorer double click can mean dependent on the element different things. 
Double click on a folder expands the folder and doulel click on a file opens the file.

So doing the same for the compare view is valid.

@BeckerWdf 
What is your opinion.

**Comment by DenisUngemach** [comment]
@BeckerWdf 
Hi Matthias, can you check the PR?

It works, but i don't know whether this position in the code is absolutly right to use.

**Comment by BeckerWdf** [comment]
this is implemented with https://github.com/eclipse-platform/eclipse.platform/pull/1493
