### ISSUE TITLE
Metaspace memory leak in ClassUtils

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform.ui#1859]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

Ever since the M1 went live, I am no longer able to run our test suite without the process getting shot down, due to a significant increase in required memory. After a two week investigation, it turned out that the problem was not caused by the _heapspace_, as initially thought, but rather the _metaspace_. 

The following graph illustrates the evolution of the metaspace while executing our test suite. I think the memory leak is quite obvious. Honorary mention to the "plateau", which is where the Swing test suite is executed, indicating that this leak is exclusive to SWT.

![MemLeak-01](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/b7d68b5e-3d98-4d8e-8b18-4318db3c1154)

The problem doesn't show up when testing _the same code_ against the 2024-03. While there are moments where up to 90000 classes are loaded, the process always drops down to 30000-40000 classes shortly after.

![MemLeak-01-2024-03](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/67842428-9bd6-4ccb-9fb1-84d947ef9fbf)

To briefly summarize how our tests (and WindowBuilder in general works): For each test, a subclass of an SWT widget is created. This can be a Shell, Table, Composite etc. After analyzing the heapdump corresponding to the first graph, I noticed that those classes are kept in memory via a reference to the CSS Engine, which is what led me here in the first place.

![MemLeak-HeapDump](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/ffb4fdde-1a52-4a3b-a03a-b2ff978e6c27)

To be more specific, the memory leak is introduced by https://github.com/eclipse-platform/eclipse.platform.ui/commit/4e9942b470908591e06ca6ee9c4bf10eb9efbc5f. Or to be even more concrete, the following line is a **very** bad idea:

> private static final Map<Class<?>, String> simpleNames = new ConcurrentHashMap<>();

As mentioned, WindowBuilder creates several subclasses for widgets. Because they are widgets, a CSS style is applied and via several steps, they end up in this map. Because each subclass is unique, a new entry is added to the map for each instance. Because this map is never cleared, those classes (and by extend all class loaded by the same classloader) remain in memory indefinitely, even though the tests that created them have long succeeded. 

I haven't tested yet whether the issue can be avoided by using a WeakHashMap but that's something I wanted to try within the next few days. If it doesn't, then I propose reverting the problematic revision, as it doesn't achieve the intended goal of improving memory utilization, but instead introduces a crippling memory leak.

To prove my point, this is what the memory looks like if I clear this cache after each test. I think the similarity to the 2024-03 graph is obvious:

![MemLeak-01-fix](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/adb7b4cc-9143-43a6-be63-c0092f46dbbf)

## Steps to reproduce

From a fresh installation and clean workspace:

- Checkout the [WindowBuilder](https://github.com/eclipse-windowbuilder/windowbuilder.git) project.
- Remove the following line in DesignerTestCase:
  - `((Map<?, ?>) ReflectionUtils.getFieldObject(ClassUtils.class, "simpleNames")).clear();`
- Execute the tests via the command line: `mvn clean verify -fae`.
- Attach a profiler to the Surefire process and observe the metaspace and/or the number of loaded classes.

## Here is some relevant log output

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:4.0.4:test (default-test) on project org.eclipse.wb.tests: An unexpected error occurred while launching the test runtime (process returned error code 137(SIGKILL received?)). The process logfile /home/jenkins/agent/workspace/build_PR-750/org.eclipse.wb.tests/target/work/data/.metadata/.log might contain further details. Command-line used to launch the sub-process was /opt/tools/java/openjdk/jdk-17/latest/bin/java -Dosgi.noShutdown=false -Dosgi.os=linux -Dosgi.ws=gtk -Dosgi.arch=x86_64 -XX:MaxRAMPercentage=40.0 -Dosgi.clean=true -jar /home/jenkins/agent/workspace/build_PR-750/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.800.v20240330-1250/org.eclipse.equinox.launcher-1.6.800.v20240330-1250.jar -data /home/jenkins/agent/workspace/build_PR-750/org.eclipse.wb.tests/target/work/data -install /home/jenkins/agent/workspace/build_PR-750/org.eclipse.wb.tests/target/work -configuration /home/jenkins/agent/workspace/build_PR-750/org.eclipse.wb.tests/target/work/configuration -application org.eclipse.tycho.surefire.osgibooter.uitest -testproperties /home/jenkins/agent/workspace/build_PR-750/org.eclipse.wb.tests/target/surefire.properties -testApplication org.eclipse.ui.ide.workbench -nl de -clearPersistedState -consoleLog in working directory /home/jenkins/agent/workspace/build_PR-750/org.eclipse.wb.tests -> [Help 1]
```

## Tested under this environment:
* OS & version: Linux
* Eclipse IDE/Platform version (as shown in *Help > About*): Eclipse 4.32 M1

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by ptziegler** [comment]
Now that I think about it... using classes as key only works as long as a single classloader is used. If the same class is loaded by multiple classloaders, an entry is created for each instance (as classes are compared by identity). So you still end up with duplicate strings.

**Comment by laeubi** [comment]
@ptziegler nice finding!

Instead of making the Map weak and alike I wonder if the method can simply be replaced by:

```
private static String computeSimpleName(Class<?> c) {
		return c.getSimpleName().replace('$', '-').intern();
}
```

this would prevent duplicate strings and don't require a map and maybe even the JVM can optimize the getSimpleName call internally already.

**Comment by laeubi** [comment]
I created
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/1860

**Comment by ptziegler** [comment]
> @ptziegler nice finding!
> 
> Instead of making the Map weak and alike I wonder if the method can simply be replaced by:
> 
> ```
> private static String computeSimpleName(Class<?> c) {
> 		return c.getSimpleName().replace('$', '-').intern();
> }
> ```
> 
> this would prevent duplicate strings and don't require a map and maybe even the JVM can optimize the getSimpleName call internally already.

I think that should work. My idea was to store the class name, rather than the class. But after reading through the documentation the same effect is already achieved, just by calling `intern()`.

You still have the overhead of the string manipulation, but this was also the case in the previous implementation and seemingly never an issue.

**Comment by laeubi** [comment]
Yes all callers are caching the actual value and this change was due to duplicate strings not performance.
