### ISSUE TITLE
The label for internet exporer is missing

### ISSUE THREAD

**Issue by lak-proddev** [eclipse-platform/eclipse.platform.ui#1870]
The label of Internet Explorer in the browser list on the preference page is wrong. It's due to the regression of the old commit

commit https://github.com/eclipse-platform/eclipse.platform.ui/commit/21add1aaf9e11ce8c092f6d981d2775cfb2eefb8
Deleted both Camino and Internet Explorer from Plugin.properties file and Plugin.xml file.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/39690425/74101825-2368-40e3-bab6-40222a5953bc)

**Comment by Bananeweizen** [comment]
I still experience the missing label, both in 2024-06, as well as in 2024-09 M1. Might this need some additional plugin version bumping or similar?

**Comment by elsazac** [comment]
I made this commit https://github.com/eclipse-platform/eclipse.platform.ui/commit/21add1aaf9e11ce8c092f6d981d2775cfb2eefb8 . As per [link](https://support.microsoft.com/en-us/windows/internet-explorer-help-23360e49-9cd3-4dda-ba52-705336cc0de2) , support for IE was ended in 2022. Not sure why this is still required.

**Comment by HeikoKlare** [comment]
IE is still the default browser used by Eclipse (SWT) and thus also the Platform. The Edge adaptation is not ready for productive use yet (even though currently some efforts are put into changing that), so we have to keep IE for now.

The removal of the label has been reverted here: 
- #1871

In my SDK setups (and in downloaded EPP products) I have this version of the `org.eclipse.ui.browser` bundle: 3.8.300.v20240524-2010
In that bundle, the correct plugin.properties containing the label are embedded.

When I start a fresh product (2024-09 RC1 for Java Developers), the label is properly shown:
![image](https://github.com/user-attachments/assets/f13c3a14-61e3-40b0-809e-6fcd7dc615ad)

Still, my development SDK had the broken label as I had set it up while the label was removed. This will never refresh on updates, but is initialized only once during setup. That may be the reason why you still see the broken label, @Bananeweizen. Can you confirm whether you can still reproduce the issue?

**Comment by Bananeweizen** [comment]
@HeikoKlare that explains it. I was also wondering, as I did not immediately see a good reason in code/versioning/similar why that fix wouldn't change anything.
I can't reproduce the issue in other IDEs that I set up now. Thanks a lot.
