### ISSUE TITLE
e4: Add a way to provide translations to ProgressMessages

### ISSUE THREAD

**Issue by selundqma** [eclipse-platform/eclipse.platform.ui#1897]
In our team we have a need to provide Chinese translations to all our strings shown in the application GUI. In Eclipse RCP apps this is done by adding additional files (besides the already provided messages.properties):

messages_sv.properties
messages_zh.properties
etc

The preferred way would of course to have all these translation files (in all supported languages == many! AI translated?) provided in the org.eclipse.e4.ui.progress bundle. OR ... add a way for the users to provide their own translation file(s).

**Comment by selundqma** [comment]
Additional "fix".. Provide a way to translate "Cancel" in the ProgressMonitorFocusJobDialog:

ProgressMonitorFocusJobDialog_CancelButton=Cancel

```
		cancel = createButton(parent, IDialogConstants.CANCEL_ID,
				IDialogConstants.CANCEL_LABEL, false);
```

		```
		cancel = createButton(parent, IDialogConstants.CANCEL_ID,
				ProgressMessages.ProgressMonitorFocusJobDialog_CancelButton, false);
```

**Comment by BeckerWdf** [comment]
Translations for Eclipse IDE SimRel are provided by the Babel Project. See https://projects.eclipse.org/projects/technology.babel/releases/0.20.0 and https://eclipse.dev/babel/
You can contribute translations there

Platform itself only contains the original English strings.

**Comment by BeckerWdf** [comment]
> Additional "fix".. Provide a way to translate "Cancel" in the ProgressMonitorFocusJobDialog:

So do you say that this string is not externalised and thus cannot be translated?

**Comment by merks** [comment]
It is translated:
```
	/**
	 * The label for cancel buttons.
	 * Using this static label string provides optimum performance by looking
	 * up the label only once when JFace is initialized.  However, clients that
	 * wish to support multiple locales in one system should instead use the pattern
	 * <code>JFaceResources.getString(IDialogLabelKeys.CANCEL_LABEL_KEY)</code>
	 * so that a locale other than the default may be consulted.
	 */
	String CANCEL_LABEL = JFaceResources.getString(IDialogLabelKeys.CANCEL_LABEL_KEY);
```

Unfortunately the babel has been broken for years, so newer things might not have translations, but such old things will/do.

**Comment by selundqma** [comment]
> > Additional "fix".. Provide a way to translate "Cancel" in the ProgressMonitorFocusJobDialog:
> 
> So do you say that this string is not externalised and thus cannot be translated?

We use "-nl zh" to run our application in Chinese.. "Cancel" is then shown in English. So, I would say yes to that.

**Comment by BeckerWdf** [comment]
> We use "-nl zh" to run our application in Chinese.. "Cancel" is then shown in English. So, I would say yes to that.

So no, the original string is externalized:

<img width="1238" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/28338612/887a66c6-23cc-4a3f-a8c5-41402882f53e">

**Comment by selundqma** [comment]
> the original string is externalized:
> 
> <img alt="image" width="1238" src="https://private-user-images.githubusercontent.com/28338612/333153584-887a66c6-23cc-4a3f-a8c5-41402882f53e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NjIwMzksIm5iZiI6MTcxNjQ2MTczOSwicGF0aCI6Ii8yODMzODYxMi8zMzMxNTM1ODQtODg3YTY2YzYtMjNjYy00YTNmLWE4YzUtNDE0MDI4ODJmNTNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEwNTUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNjI2NTQ5OThkYTEzYjMzMzZiNTJiY2Q0MDJjOWNiNTk0MjA2N2E3MWQyMDgyOTE2YjA2OWI3YzllYTUyYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l5lj6U4tG2upylJ3gsoTjocJgcFCU9byA-a-Wg33V2g">

If I have a messages_zh.properties file for the org.eclipse.jface bundle and one for the org.eclipse.e4.ui.progress bundle, is there a way to use those two files without contributing the files into the Eclipse code? Or is the preferred way to always contribute with translations?

**Comment by merks** [comment]
You need to install the translation fragments.  This is the most recent:

- https://download.eclipse.org/technology/babel/babel_language_packs/R0.20.0/2022-03/2022-03.php
- https://eclipse.org/downloads/download.php?file=/technology/babel/update-site/R0.20.0/babel-R0.20.0-2022-03.zip
- https://download.eclipse.org/justj/?file=technology/babel/babel_language_packs/R0.20.0/2022-03

I'm having trouble with the mirrors.  In in the last link above, I think these are for the Platform:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/497d407b-f515-421b-9fd8-4edea855ae4a)

Those can be put in the drops folder.

The zipped site looks like you need to unzip it to be able to use it for Help -> Install New Software:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/6e533fab-f8e1-4dcd-af4b-dfecb9bc7faf)

Like this:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/09a1ee3c-0886-4a6a-92ff-0e758ca3e1ee)

**Comment by merks** [comment]
The platform will not ship translations.

**Comment by selundqma** [comment]
@merks I am convinced :). Thanks for explaining everything. I will try to include the Babel update site in our target platform and point out the correct unit. Then update our feature.xml and hopefully it is available in Chinese then.

Thank you for quick handling of this suggestion ticket!

**Comment by merks** [comment]
I hope Babel will soon provide newer updates!
