### ISSUE TITLE
Min-Max area too large in no editor is open

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#1903]
Eclipse SDK
Version: 2024-06 (4.32)
Build id: I20240528-1800
OS: Linux, v.6.5.0-35-generic, x86_64 / gtk 3.24.38, WebKit 2.44.2
Java vendor: Eclipse Adoptium
Java runtime version: 17.0.11+9
Java version: 17.0.11

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/139910/af861994-0eb6-4546-96cc-62e3dd89fffa)

**Comment by vogella** [comment]
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/139910/d9e5354d-649b-4dc6-82e1-787b0c0c38e3)

**Comment by BeckerWdf** [comment]
Does this only happen on Linux?

**Comment by merks** [comment]
It doesn't happen on Windows with the most-recent I-Build:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/a0bd5e79-cbb5-4152-ba55-c6346c1f6b33)

**Comment by HeikoKlare** [comment]
Is this produced with a new workspace? I am just wondering because, if I see correctly, the screenshot shows an empty onboarding area for the plug-in development perspective, which should have been fixed via #1775 and #1778.

**Comment by jukzi** [comment]
can NOT reproduce on win. Both light/dark them
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/05035ee5-518b-4708-92a2-625ce9dee96c)

**Comment by vogella** [comment]
> Does this only happen on Linux?



> Is this produced with a new workspace? I am just wondering because, if I see correctly, the screenshot shows an empty onboarding area for the plug-in development perspective, which should have been fixed via #1775 and #1778.

Yes, also in a new workspace. Under Linux, switch to dark theme, close Outline and you get:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/139910/d544c779-c469-4a52-85a5-2595937e1af3)

**Comment by HeikoKlare** [comment]
It also happens on light theme and it has at least already been present in the previous release. I still have a 4.31 version on WSL, where I see this:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/eab1790a-0b40-4647-b33e-4263421c95fb)

_Edit:_ has at least been present since 2023-06:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/1b602d6f-79e5-46c3-baba-28e984736938)

**Comment by vogella** [comment]
Looks fine with the update dark theme

![image](https://github.com/user-attachments/assets/87213ac9-2dd3-4c1b-93e1-88b55a98ef94)
