### ISSUE TITLE
Some way to pin a Debug Inspect window

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.ui#1905]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

I want to compare some inspected (select in code then right-lick > Inspect) value in 2 distinct executions I'm debugging.
Currently, whenever I click out of the 1st inspect window to try to open a second one (which involves switching target in the debug view, going to the other file, selecting the expression then right-click > Evaluate), the 1st inspect window gets closed and I cannot efficiently compare.

It would be extremely convenient to have an option on the Inspect window to "pin" it so that it doesn't close on focus out, and it just closes when users wants to close it.

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by laeubi** [comment]
@mickaelistria can you share a screenshot / cast? I can hardly follow the description mostly as I seldom use your described workflow.

**Comment by jukzi** [comment]
You can use the Expressions View instead of Inspect.

**Comment by mickaelistria** [comment]
> You can use the Expressions View instead of Inspect.

that doesn't work with "2 distinct executions" (which is the most important part of the workflow), as switching to another StackFrame updates the values. I basically want a way to be able to see some values from 2 distinct stack frames, without having to have 2 distinct workbench windows.
Another similar story (harder and maybe not as powerful) was https://github.com/eclipse-platform/eclipse.platform/issues/531

**Comment by jukzi** [comment]
If it is 2 different debugees you could use 2 distinct workspaces.
For comparing results of of different threads within same debugee i don't know a solution and help myself with screenshots. So i could use that feature too, but i have no idea how it could be intuitivly visualised which values belong to which stackframe.

**Comment by mickaelistria** [comment]
> If it is 2 different debugees you could use 2 distinct workspaces.

When in desperate need, I use 2 workbench windows (Window > New Window) which can allow to have different stackframes selected in each window and update all the context. It's really powerful, but it's not so easy to use and it often seems overkill to quickly compare 2 values.

A first idea would be to augment the Inspect popop with 2 new actions (Pin/Close) in its action menu:

![Screenshot from 2024-05-31 11-54-04](https://github.com/eclipse-platform/eclipse.platform.ui/assets/469058/3049a937-e29c-4490-a986-57e2c8fdae99)

So it would look like

- Move
- Resize
- [ ] Pin
- Close

**Comment by jukzi** [comment]
But how could the user know which Window belongs to which frame?

**Comment by mickaelistria** [comment]
> But how could the user know which Window belongs to which frame?

in a 1st iteration, I think it could be up to them to remember, as it's not (yet?) a very common workflow,.
But yes, later on we should consider adding some information to the dialog to show the context in which one it got evaluated. I wouldn't just make it a blocker right now.

**Comment by jukzi** [comment]
Things that need later to be done are a blocker for me, as otherwise they are usually not done.

**Comment by mickaelistria** [comment]
It seems like we could implement it in PopupDialog, so it could also help some other stories.

**Comment by iloveeclipse** [comment]
> It seems like we could implement it in PopupDialog, so it could also help some other stories.

I doubt having N pinned dialogs is "the" solution here.

I personally never use this functionality, but if I would use it in the way you do, I would probably just want to "move" current popup content to Expressions view and there provide a way to "pin" expressions to threads/frames, as long as they run/exist.

**Comment by mickaelistria** [comment]
> I personally never use this functionality, but if I would use it in the way you do, I would probably just want to "move" current popup content to Expressions view and there provide a way to "pin" expressions to threads/frames, as long as they run/exist.

I think it's more or less what I suggested in https://github.com/eclipse-platform/eclipse.platform/issues/531

**Comment by iloveeclipse** [comment]
> I think it's more or less what I suggested in [eclipse-platform/eclipse.platform#531](https://github.com/eclipse-platform/eclipse.platform/issues/531)

Probally I can't understand the use case, but you proposeda "diff" view and here you want persistent per frame inspection values?

**Comment by mickaelistria** [comment]
> you proposeda "diff" view 

No, in the other issue, I propose that we can show values from multiple sources in the Variable/Expressions view (I'm against yet-another-view), adding them as colums.

> here you want persistent per frame inspection values?

Yes, I just want to be able to look at 2 inspected expressions, from whichever source, simultaneously. And this is currently only possible without 2 distinct workbench window.

**Comment by mickaelistria** [comment]
I've managed to add the menu entries and so on, but pinning seems more deeply rooted than I thought. Here is the stack that shows the dialog closing when an external event happens. I was hoping for some listener to tweak in PopupDialog, but it seems deeper

```
Thread [main] (Suspended (entry into method close in PopupDialog))	
	QuickAccessDialog(PopupDialog).close() line: 1114	
	QuickAccessDialog.close() line: 306	
	QuickAccessDialog(Window).handleShellCloseEvent() line: 739	
	Window$1.shellClosed(ShellEvent) line: 685	
	TypedListener.handleEvent(Event) line: 115	
	EventTable.sendEvent(Event) line: 91	
	Display.sendEvent(EventTable, Event) line: 5855	
	Shell(Widget).sendEvent(Event) line: 1617	
	Shell(Widget).sendEvent(int, Event, boolean) line: 1643	
	Shell(Widget).sendEvent(int, Event) line: 1626	
	Shell.closeWidget() line: 711	
	Shell.close() line: 707	
	Shell.traverseEscape() line: 3144	
	Shell(Control).traverse(Event) line: 6667	
	Text(Control).translateTraversal(long) line: 6640	
	Text.translateTraversal(long) line: 2896	
	Text(Control).gtk_key_press_event(long, long) line: 3996	
	Text.gtk_key_press_event(long, long) line: 1886	
	Text(Widget).windowProc(long, long, long) line: 2595	
	Text(Control).windowProc(long, long, long) line: 6833	
	Text.windowProc(long, long, long) line: 2992	
	Display.windowProc(long, long, long) line: 6162	
	GTK3.gtk_main_do_event(long) line: not available [native method]	
	Display.eventProc(long, long) line: 1598	
	GTK3.gtk_main_iteration_do(boolean) line: not available [native method]	
	Display.readAndDispatch() line: 4514	
	PartRenderingEngine$5.run() line: 1151	
	Realm.runWithDefault(Realm, Runnable) line: 339	
	PartRenderingEngine.run(MApplicationElement, IEclipseContext) line: 1042	
	E4Workbench.createAndRunUI(MApplicationElement) line: 152	
	Workbench.lambda$3(Display, WorkbenchAdvisor, int[]) line: 639	
	0x00000000a629ed20.run() line: not available	
	Realm.runWithDefault(Realm, Runnable) line: 339	
	Workbench.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 546	
	PlatformUI.createAndRunWorkbench(Display, WorkbenchAdvisor) line: 173	
	IDEApplication.start(IApplicationContext) line: 152	
	EclipseAppHandle.run(Object) line: 208	
	EclipseAppLauncher.runApplication(Object) line: 143	
	EclipseAppLauncher.start(Object) line: 109	
	EclipseStarter.run(Object) line: 439	
	EclipseStarter.run(String[], Runnable) line: 271	
	DirectMethodHandle$Holder.invokeStatic(Object, Object, Object) line: not available	
	0x00000000a60c6800.invoke(Object, Object, Object, Object) line: not available	
	0x00000000a60c6c00.invokeExact_MT(Object, Object, Object, Object, Object) line: not available	
	DirectMethodHandleAccessor.invokeImpl(Object, Object[]) line: 155	
	DirectMethodHandleAccessor.invoke(Object, Object[]) line: 103	
	Method.invoke(Object, Object...) line: 580	
	Main.invokeFramework(String[], URL[]) line: 668	
	Main.basicRun(String[]) line: 605	
	Main.run(String[]) line: 1481	
	Main.main(String[]) line: 1454	
```

**Comment by mickaelistria** [comment]
My bad, please ignore last comment which was exactly about ESCAPE being pressed. Everything seems fine, I'm pushing a pull request.

**Comment by mickaelistria** [comment]
PR is https://github.com/eclipse-platform/eclipse.platform.ui/pull/1906

**Comment by mickaelistria** [comment]
And https://github.com/eclipse-platform/eclipse.platform/pull/1403 as consumer
