### ISSUE TITLE
[find/replace dialog] remove Ringtone

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#1908]
This Issue Documents a review-comment from the find/replace overlay PR
which could not be addressed into the current proposal:
[comment](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1192#issuecomment-2033690701) by @HeikoKlare and @vogella 

In the PR for the Overlay, we decided to remove the Ringtone notifying of errors while searching, because it was perceived as annoying.
We should also remove it from the Dialog.

**Comment by vogella** [comment]
+2 for this.
