### ISSUE TITLE
[find/replace overlay] incremental base position resets randomly when using "search in selection"

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#1914]
This Issue Documents a review-comment from the find/replace overlay PR
which could not be addressed into the current proposal
[comment](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1192#pullrequestreview-2085146414) by @HeikoKlare 

When activating and deactivating the "selected lines" option, the incremental base position seems to be reset (or not set properly).
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/9c4a1838-8393-45be-b830-8369d9071a49)

**Comment by HeikoKlare** [comment]
Not reproducible anymore after recent changes affecting the incremental base position: #2109 #2106
