### ISSUE TITLE
Impossible to change default text font

### ISSUE THREAD

**Issue by vkrevs** [eclipse-platform/eclipse.platform.ui#1930]
- [X ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)
Downloaded and installed eclipse-cpp-2024-03-R-linux-gtk-x86_64.tar.gz on openSUSE 15.5 under KDE.

## Steps to reproduce

From a fresh installation and clean workspace:

* Start eclipse. open new workspace
* Select Window->Preferences->General->Appearance->Colors and Fonts->Basic->Text Font
* "Preview" says "Cascadia Code 10" is selected. Cascadia Code is not a font referenced in KDE's font setttings nor in Gnome's font settings.
* Click Edit and select any other font, e.g. FiraCode NF Retina, click Select
* "Preview" says "Fira Code NF 10".
* Click "Apply and Close" and exit/restart Eclipse.
* Select Window->Preferences->General->Appearance->Colors and Fonts->Basic->Text Font. 
* "Preview" displays ""Fira Code NF 10".  Click on any item above "Text Font" and back on "Text Font" ->  "Preview" displays "Cascadia Code 10".

Clicking on "Restore Defaults" and selecting the font I want results in identical behavior. 

I tried to edit org.eclipse.ui.workbench.prefs and replace references to Cascadia Code with another font. Once Eclipse starts, it ignores these and forces Cascadia Code again.

I searched under $HOME for any files containing "Cascadia" - only org.eclipse.ui.workbench.prefs contains references to it. 

dconf dump / | grep -i cascadia results in nothing. So where does Eclipse pick up the preference for Cascadia Code from?

I expected: My selected font to remain selected.

Copies of ECLIPSE_HOME/configuration  and <workspace>/.metadata are attached.
[.metadata.tar.gz](https://github.com/user-attachments/files/15585644/default.metadata.tar.gz)
[configuration.tar.gz](https://github.com/user-attachments/files/15585688/configuration.tar.gz)

## Tested under this environment:
* OS & version: openSUSE 15.5, KDE
* Eclipse IDE/Platform version (as shown in *Help > About*):  Eclipse IDE for C/C++ Developers (includes Incubating components), Version: 2024-03 (4.31.0),  Build id: 20240307-1437

**Comment by vkrevs** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=569961 seems similar, except in my case everything happens with the default colour and font  theme, instead of reduced palette one.

**Comment by iloveeclipse** [comment]
Are you using OOmph? This could apply user/setup configured settings on startup.

**Comment by vkrevs** [comment]
Sadly, it was oomph applying the font.  "Using", though,  implies making a conscious choice/action - the Eclipse CDT/RCP downloads just started to bundle it by default from some time ago by the looks of it.

**Comment by merks** [comment]
So you recorded your preference but now want a different preference but don’t record it

**Comment by vkrevs** [comment]
I'm a very long time Eclipse CDT user, but do not recall ever "recording" my preferences in oomph at all (simply because I had no idea what oomph does or even exists until recently). Always set up my fonts/colour preferences via Preferences->Appearance->Colors and Fonts.

**Comment by merks** [comment]
I see. You were presented with a dialog for confirmation and presented with a help description. Most people do just press OK and don’t have time to read helpful information.  Then later versions, the recorder was not enabled by default though your recorded preferences are still applied with a log message to that effect.  It’s good if the preference is as you want and not so much when it isn’t.
