### ISSUE TITLE
Improve Quick Access filtering - Support ActionProvider

### ISSUE THREAD

**Issue by raghucssit** [eclipse-platform/eclipse.platform.ui#1936]
This is a follow up for https://github.com/eclipse-platform/eclipse.platform.ui/issues/1828.

`Add Java Exception Breakpoint` Action Contributions were still visible even after disabling the Java Development Activty.

Analysis:
The reason for this issue is Activity Support filtering was implemented at `ActionProvider`.

**Comment by mickaelistria** [comment]
Should this be closed now that #1937 is merged?

**Comment by iloveeclipse** [comment]
Yes
