### ISSUE TITLE
find/replace overlay: makes Eclipse unusable on switching editors

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1951]
Maybe Linux specific, not tried on Windows yet and I have no Mac to check on Mac.

Eclipse becomes irresponsible / flashes steadily after following steps (using latest master):
1) Start Eclipse, **maximize** the IDE window, open two Java editors
2) In one editor, Ctrl+F to open find/replace dialog
3) Switch to other editor by clicking on the editor tab
4) Ctrl+Shift+F6 to switch to the previous editor
5) Eclipse starts flashing and becomes (mostly) irresponsible (clicking anywhere inside Eclipse doesn't work)
6) Only changing window size & manually clicking the editor tab "fixes" flashing and one can continue using IDE

I guess the problem is caused *probably* by the focus restore on the editor vs shell opened for the find/replace dialog.
In any way the problem must be fixed as it makes Eclipse unusable for (not prepared) user.

https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/ea0cdd54-e462-42da-8913-f285c521dd53

**Comment by iloveeclipse** [comment]
@Wittmaxi : please check. Without a fix for this issue we can't enable find/replace overlay by default on Linux.

**Comment by Wittmaxi** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/pull/1946

Does this fix your issue or is this something separate?
I am trying to assess what my priorities are, is this the right priority list?:

1 Fix this bug (if still existant)
2 Add a search history
3 add a memento for search options and save the options accross tabs

What do you think?

**Comment by Wittmaxi** [comment]
Notably, the > icon in your overlay is broken! @HeikoKlare should we retuen to the icons?

**Comment by iloveeclipse** [comment]
> Notably, the > icon in your overlay is broken! @HeikoKlare should we retuen to the icons?

Dedicated ticket: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1960

**Comment by iloveeclipse** [comment]
> #1946
> 
> Does this fix your issue or is this something separate?

Kind of, because overlay is never shown with this PR, it can't flash anymore :-)

> I am trying to assess what my priorities are, is this the right priority list?

Yes. I prefer to make things bug free and after that add features, not otherwise, because later you never know which feature broke what...

**Comment by Wittmaxi** [comment]
@iloveeclipse I could not reproduce this on my windows PC.
I share your belief that something in the Shell-Listeners is likely broken on GTK (?).

![17](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/fbeb821e-8db5-4330-8e6c-6409524f93d8)
This is the behavior I get on my PC. Do you get any error messages? Any logs? If not, I can setup a Linux-VM and try to fix the issue there.

edit: I realize there is a way to run eclipse in WSL with gtk

**Comment by iloveeclipse** [comment]
> I could not reproduce this on my windows PC

Note: in my case Eclipse window **must be** maximized to see the problem. It is not the case in your screen recording.

**Comment by Wittmaxi** [comment]
@iloveeclipse the full-screen was for the sake of making a cleaner gif. It still works very well in full-screen.

**Comment by iloveeclipse** [comment]
OK, so it is Linux issue.

**Comment by Wittmaxi** [comment]
I can reproduce this on my Linux-Laptop - and it's really annyoing! Thanks for the report :)
