### ISSUE TITLE
find/replace overlay: The `Use find/replace overlay` preference is hard to locate because keyword definitions are absent

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.ui#1953]
The preference for the find/replace overlay is here:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/aba2db94-f55a-48b0-b7d0-30b8b3848f42)

But that preference is hard to find and cannot be found via a keyword search:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/3c21eeaf-489f-4fc8-b1a3-c75d724b4333)

The keywords are associated here:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/51edb279-3ba6-448d-a4ee-0eb36c9eaeb7)

And defined here:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/da035fea-7c14-4658-bdfd-b0f98dfffd22)

I'm not sure if we need a new keyword definition or if it should be added to the general one?

Here is how that is defined:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/7c9f97fb-ca70-4513-8be6-af41fcfff8b5)

Probably `find replace overlay` should be added.

See also https://github.com/eclipse-platform/eclipse.platform.ui/issues/1952

**Comment by mickaelistria** [comment]
IMO, it worth creating a new `org.eclipse.ui.editors.search` keyword as Search is a whole topic in an IDE and the keywords definition can be used in multiple place

**Comment by merks** [comment]
I don't have an opinion.  

As a data point thought, no `org.eclipse .ui.editors.*` keyword definition is currently/actually  referenced more than once:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/86801ed5-f29f-47e6-8a5a-f872e333d80e)

**Comment by jukzi** [comment]
> Probably `find replace overlay` should be added.

I second that, and add `search` to the wish list, which was the first word i searched for.
