### ISSUE TITLE
Sticky scrolling: prevents to jump to search result in EcorePlugin

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1954]
1. enable sticky scrolling, lines=10 
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/e4c245b8-b1e7-452c-bd01-0efc48500bbe)

2. search for callers of org.eclipse.core.internal.resources.File.getContents(boolean)
3. double click on org.eclipse.emf.ecore.plugin.EcorePlugin.computePlatformPluginToPlatformResourceMap()
4. => method is not shown in Editor and all those brackets in the sticky area are not helpful

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/f561f636-21a9-4619-9f08-f18e09bb5536)

probably the editor would have to scroll further up to show the result.

**Comment by jukzi** [comment]
On the other hand clicking on org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(IFile, String) scrolls to far down, so that a unrelated method is shown in the sticky area:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/a2287c01-a856-413c-a9ad-b19f49e9c602)

**Comment by jukzi** [comment]
another unwanted effect are empty lines in the sticky part, as happening when clicking on org.eclipse.jdt.ui.tests.refactoring.RenameTypeTests.helperQualifiedName(String, String, String, String)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/db304358-0012-4a55-beb6-8ba3876b61ad)

**Comment by jukzi** [comment]
Enabling a similar featur "Breadcumb" results in rendering errors:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/24e552dd-2e2b-463d-90e1-8702d5811820)

**Comment by Christopher-Hermann** [comment]
> On the other hand clicking on org.eclipse.jdt.internal.core.util.Util.getResourceContentsAsCharArray(IFile, String) scrolls to far down, so that a unrelated method is shown in the sticky area:

This works like expected/implemented. And that's how it's done in other IDEs (VS Code, Eclipse Theia) as well. When you click on a sticky line, the selected line will be made visible in the editor, with the maximum count of sticky lines used as an offset.

For the other issue I need to dig into it as soon as I have some time.
