### ISSUE TITLE
Inactive selected table/tree rows background color wrong, selected icon missing, foreground colors missing on Linux

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1956]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/1690.

1) Open two tree views next to each other, like Package and Project explorers. 
2) Select some element in one of them.
3) Select an element in other one.
4) Selection in previous one has background color that is almost indistinguishable from text color, so content of selection is impossible to read anymore.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/3dc2f04e-8c1d-40ed-ac82-011772408f97)

**This must be fixed, as it makes IDE usage impossible!**

**Comment by Christopher-Hermann** [comment]
@iloveeclipse can you provide me a screenshot of the coloring without my changes?

**Comment by iloveeclipse** [comment]
Once [I can start debugger](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2118#issuecomment-2162323939) I will do that :-)

**Comment by iloveeclipse** [comment]
Actually not only that is broken. Icons on selected rows aren't drawn anymore.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/0bb2f313-19b3-4195-8e96-5f5fa666da7d)

**Comment by Christopher-Hermann** [comment]
> Actually not only that is broken. Icons on selected rows aren't drawn anymore. 

Mh strange, is this really related to this change? At least on your other screenshots the icons are drawn. And on MacOS the icons in the plugin.xml are drawn as expected.
If it is related, I would revert the change if possible. I think it will take a while to check and fix the issues on other platforms.

**Comment by iloveeclipse** [comment]
> Once [I can start debugger](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2118#issuecomment-2162323939) I will do that :-)

So I've fixed my stupid error and can start debugger now.
This is how the IDE looks like **before** the change in question (note also NOT missing icon in Plugin editor):

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/621d8c88-39c2-4d27-9fe9-a567944bc4c2)

**Comment by iloveeclipse** [comment]
Same **without** CSS themes, OK before https://github.com/eclipse-platform/eclipse.platform.ui/pull/1690 :

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/9ca4bec4-0f13-4f84-bc03-5ce13065d237)

**Comment by iloveeclipse** [comment]
And that is with the latest master + https://github.com/eclipse-platform/eclipse.platform.ui/pull/1958

Note wrong color and missing icon...

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/5dcd982e-a03b-473f-8077-f5e57d6a7542)

**Comment by Christopher-Hermann** [comment]
That's interesting. It seems that on Linux, the active selection color (SWT.COLOR_TITLE_BACKGROUND) is used for inactive viewer as well, even though it is not active.
This causes a problem since the foreground color is always white in your case, but the inactive background color is not correct (SWT.COLOR_TITLE_INACTIVE_BACKGROUND).

On Mac and Windows, the inactive viewers are colored with a gray background color (SWT.COLOR_TITLE_INACTIVE_BACKGROUND):
<img width="1103" alt="Bildschirmfoto 2024-06-12 um 10 29 15" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/79514265/d8e6fcec-3a55-4d56-b2c4-5dcc7a5e3020">

**Comment by iloveeclipse** [comment]
Could be, what about missing icon?

**Comment by Christopher-Hermann** [comment]
Absolutely no clue about the icons. I did not touch anything in this area, at least I'm not aware of it. And since I do not have a Linux machine to test, it will be hard to find the issue for me. So most probably we need to revert the change to have more time.

**Comment by Christopher-Hermann** [comment]
The only change I can imagine having impact on the drawing of icons is this once: https://github.com/eclipse-platform/eclipse.platform.ui/blob/521543f02f2034adffe24d4806344661ac3f3884/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/StyledCellLabelProvider.java#L266

**Comment by iloveeclipse** [comment]
I've found yet another one regression: **custom** foreground colors are missing completely.
I have Plugins Explorer that can show errors in the platform like this:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/ed5413b6-77ea-459b-8b9c-8267a6a22035)

but on latest master all foreground colors are gone, one can see only black color.

**Comment by iloveeclipse** [comment]
All issues fixed via https://github.com/eclipse-platform/eclipse.platform.ui/pull/1957

**Comment by Christopher-Hermann** [comment]
I will take up the work on this again and try to provide a fix that is working on all platforms.

Special behavior for Linux:
Selection is always colored in focus color, where on windows and Mac, the selection has a focus and a non focus color.
