### ISSUE TITLE
find/replace overlay: "toggle" find/replace symbol not shown

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#1960]
Just seen that on Windows the toggle is supposed to be some filled arrow sign, which is obviously not the case for me on Linux:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/6e55645c-a2fc-47a1-a71c-a1f1f2f8ec6d)

I guess the symbol button uses/expects some font either not available or not configured as default one on my Linux machine.

That should be fixed. I wonder why don't we use a "simple" icon for that, or just draw that on screen instead of relying on fonts?

**Comment by iloveeclipse** [comment]
@Wittmaxi : FYI.

**Comment by HeikoKlare** [comment]
> I wonder why don't we use a "simple" icon for that, or just draw that on screen instead of relying on fonts?

One drawback of using icons is that they do not work well with themeing. While fonts simply adapt their color, icons need to be provided in a way that fits for all themes. It think it is quite okay to have a gray arrow here, but using a font would provide the arrow with more contrast, which I would consider a benefit. I think that is one of the reasons why icon fonts are rather common (in addition to their exchangeability).
