### ISSUE TITLE
External browser open URL: No such file or directory

### ISSUE THREAD

**Issue by Mailaender** [eclipse-platform/eclipse.platform.ui#1979]
Let's make sure issue is not already fixed in latest builds first.

- [ ] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

```java
PlatformUI.getWorkbench().getBrowserSupport().getExternalBrowser().openURL(new URL("https://www.eclipse.org"));
PlatformUI.getWorkbench().getBrowserSupport().createBrowser(null).openURL(new URL("https://www.eclipse.org"));
```

I expected: browser to open

But got:
```
/usr/bin/env: ‘https://www.eclipse.org’: No such file or directory
/usr/bin/env: ‘https://www.eclipse.org’: No such file or directory
```

## Tested under this environment:
* KUbuntu 24.04
* Eclipse IDE/Platform version (as shown in *Help > About*): 2024-03 (4.31.0)
* I have Google Chrome and Firefox installed.

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

Some hints on how to fix this myself would be nice though.

**Comment by akurtakov** [comment]
My guess would be that the browser used has in its desktop file more complicated Exec line, this used to be more or less `Exec=firefox %u` (or similar) and support for more complicated executions is not yet implemented. 
Most likely a duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/221 .

**Comment by Mailaender** [comment]
Firefox (via Snap) is the default browser so likely a duplicate.

**Comment by akurtakov** [comment]
@Mailaender If chrome is direct executable in its desktop file you can try making it default in Preferences/General/Web browser to try a workaround.

**Comment by Mailaender** [comment]
Switching to chrome which is installed as a `.deb` resolves it so it must be the snap sandboxing.
