### ISSUE TITLE
 Add Preference to Turn Off Warning-Check for Project Specific Encoding

### ISSUE THREAD

**Issue by ingomohr** [eclipse-platform/eclipse.platform.ui#198]
This is the UI contribution for backend issue [#166](https://github.com/eclipse-platform/eclipse.platform.resources/issues/166).

**Comment by ingomohr** [comment]
As discussed in the backend issue I created [a fork for this repo](https://github.com/ingomohr/eclipse.platform.ui) to add the new preference combo to the "Workspace" preference page.

💡 Pull Request is #220

**Comment by ingomohr** [comment]
@iloveeclipse Since the PR #220 had beem merged (thanks for merging btw): Is there anything left to do for this issue? Or shall I close it?

**Comment by ingomohr** [comment]
i.e. what about the New & Noteworthy entry? I remember I was asked to add that for my last UI contribution. However, I don't know the repo for that one any more...

**Comment by iloveeclipse** [comment]
> i.e. what about the New & Noteworthy entry? 

Yes, please.

> I remember I was asked to add that for my last UI contribution. However, I don't know the repo for that one any more...

This is now https://github.com/eclipse-platform/www.eclipse.org-eclipse-news

**Comment by ingomohr** [comment]
Added [PR to N&N repo](https://github.com/eclipse-platform/www.eclipse.org-eclipse-news/pull/48)

**Comment by ingomohr** [comment]
@iloveeclipse (just in case a mention is better than no mention; no pressure though). The PR is right there waiting. ;)

**Comment by vogella** [comment]
Thanks @ingomohr I think this issue is done. Please reopen if there is still something left

**Comment by ingomohr** [comment]
@vogella Hi Lars. Thank you for merging the N&N PR! I agree this can be closed now.
