### ISSUE TITLE
FindReplaceOverlayImages is Part of the API of org.eclipse.ui.workbench.texteditor

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-platform/eclipse.platform.ui#1982]
FindReplaceOverlayImages is located in the org.eclipse.ui.texteditor package which is API.
It's currently only used by FindReplaceOverlay. 
Is it really a good idea to make FindReplaceOverlayImages part of the API (that needs to be kept stable)?

**Comment by Wittmaxi** [comment]
In General, I find the entire structure of the Files for Find/Replace a bit suspicious. I will ask @HeikoKlare for a good Strategy on how to manage all of the files and assets for find/replace.

**Comment by HeikoKlare** [comment]
I agree that we should probably do some refactoring of the involved classes, but I actually do not understand the original issue:

> Is it really a good idea to make FindReplaceOverlayImages part of the API (that needs to be kept stable)?

@BeckerWdf can you further elaborate on this? Why should `FindReplaceOverlayImages` be part of the API? The class is package protected, so no one outside that package can access is (except for classes in the same package of a fragment of the bundle).

**Comment by BeckerWdf** [comment]
> Why should `FindReplaceOverlayImages` be part of the API? 

It should not.

>The class is package protected.

Where do you see that? In the MANIFEST.MF I see that org.eclipse.ui.texteditor is "public API".
There also is not "internal" in the package name.

**Comment by HeikoKlare** [comment]
> Where do you see that?

The class is package protected:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/fc44255456951ee0727f4fc02c9f61b7c97e9b2d/bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/texteditor/FindReplaceOverlayImages.java#L31-L35

**Comment by BeckerWdf** [comment]
> > Where do you see that?
> 
> The class is package protected:
> 
> https://github.com/eclipse-platform/eclipse.platform.ui/blob/fc44255456951ee0727f4fc02c9f61b7c97e9b2d/bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/texteditor/FindReplaceOverlayImages.java#L31-L35

A because it's missing the "public" keyword. 
Then everything is as expected.

**Comment by HeikoKlare** [comment]
Thank you for the feedback!
Then I consider the original question of this issue answered and thus close the issue. In case there is need for further discussion, feel free to reopen it.
