### ISSUE TITLE
Quick Access also lists class files

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#1987]
Quick Access also lists class files. Is this helpful? cc @mickaelistria as I think he implemented the file provider.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/139910/1cec36f4-f4c1-4ca7-8002-053bb732ce00)

**Comment by mickaelistria** [comment]
Are those class files "derived" ? If not, then there is no reason to not show them in general.
How does Ctrl+Shift+R behave?

**Comment by vogella** [comment]
Ctrl+Shift+R also shows them. They are located in the "target" folder. How do I mark these folders as derived?

**Comment by vogella** [comment]
Just found that I can set the derived property of the folder. Is this a necessary manual step?

**Comment by vogella** [comment]
Setting this flag manually seems "Prometheus work". A "mvn clean" on the command line removes the folder and the "mvn clean verify" re-creates the folder without the flag.

**Comment by mickaelistria** [comment]
Running "Update Maven Projects" should set the derived flag on the output folders.

**Comment by mickaelistria** [comment]
I believe your case should be redirected to m2e to make m2e set the Dervied flag on target/ folders when those are discovered as part of a refresh.

**Comment by vogella** [comment]
> Running "Update Maven Projects" should set the derived flag on the output folders.

In my case the projects are "only" plug-ins with a pom file (pomless build).

Thanks for your help. I will at some point check if I can reproduce with the regular Eclipse repos and if I can reproduce I will open a new bug for m2e.

**Comment by mickaelistria** [comment]
Maybe it's JDT that should mark the output folders as derived?

**Comment by vogella** [comment]
> Maybe it's JDT that should mark the output folders as derived?

I don't know. Not sure who is leading in this case JDT or M2E or PDE.
