### ISSUE TITLE
Find/Replace overlay:  "String xyz not found" message

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#1993]
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/661656a7-ec5a-4897-8d00-cbe6b906f464)

**Comment by HeikoKlare** [comment]
@jukzi can you briefly explain what exactly is wrong here, so in particular what you would expect in your scenario?

**Comment by jukzi** [comment]
minor: in the bottom left of the eclipse window the progress shortly says "String xyz not found"
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/d125a28c-04c3-4474-8141-d5648261ba6d)

1. The word "String" is something a user does not need to understand. Better: "'xyz' not found"
2. "xyz NOT FOUND" is a status not a progress, that should not disappear within a tens of a second


_Originally posted by @jukzi in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1990#issuecomment-2186273627_

**Comment by HeikoKlare** [comment]
Thanks for the additional information!

> * The word "String" is something a user does not need to understand. Better: "'xyz' not found"

I agree. This has just been taken over from the existing dialog, so if we change that, it should be changed at both places.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/ee85cf6e-2d29-4e09-addf-5e4d81cd78c0)

Maybe something like "No search results for: xyz"?

> * "xyz NOT FOUND" is a status not a progress, that should not disappear within a tens of a second

I see, that is definitely a bug.
