### ISSUE TITLE
Do not automatically expand Java files in Project Explorer

### ISSUE THREAD

**Issue by markozajc** [eclipse-platform/eclipse.platform.ui#2002]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* Create a new Java project
* Add a class named `TheClass` in a package named `thepackage`
* Add a main method to the class
* Collapse `thepackage`
```
└─ > thepackage
```

I tried

* Collapsing and expanding the package (clicking the arrow on the left)
Note: this only happens if there's exactly one .java file in the package.

I expected: the project tree is expanded up to the .java file
```
└─ v thepackage
   └─ > TheClass.java
```
But got: the expanded project tree that includes the class name and the main method
```
└─ v thepackage
   └─ v TheClass.java
      └─ v TheClass
         └─main(String[]) : void
```

## Tested under this environment:
* OS & version: Debian Trixie
* Eclipse IDE/Platform version (as shown in *Help > About*): 2024-06 (4.32.0), build id 20240606-1231
* This appears to be caused by changes in made by #1063

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by jukzi** [comment]
@Wittmaxi please check

**Comment by Wittmaxi** [comment]
A few thoughts on this issue after discussion with @HeikoKlare:
The problem is caused by the new Mechanism in SWT for auto expansion of single children, as merged here: https://github.com/eclipse-platform/eclipse.platform.ui/pull/1742
The best Solution is to add a predicate to the mechanism which then decides when to stop auto-expanding (i.e.: only auto-expand folders)

I am currently only looking into the issues find/replace overlay, I will keep this in the back of my mind for when I have less impotant things to do.

**Comment by HeikoKlare** [comment]
Just as a minor addition: depending on whether the reported issue is perceived as a severe problem, it would be possible to (temporarily) revert #1742 until we have a mechanism to define custom expansion-termination criteria (as proposed by @Wittmaxi).

**Comment by markozajc** [comment]
The issue is not severe (it simply clutters up my screen, which is rather annoying), but I would definitely prefer the old behaviour for the time being.

**Comment by HeikoKlare** [comment]
Just to understand the issue correctly: this kind of auto expansion only happens if you have a package with a single class, doesn't it? So do you have a setup with multiple packages only containing a single class?

**Comment by markozajc** [comment]
Normally I don't, but when starting new projects, which I did just recently, this happens quite often.

**Comment by HeikoKlare** [comment]
I see. Thank you for the clarification! That's of course a reasonable scenario.

**Comment by ddscharfe** [comment]
> The issue is not severe (it simply clutters up my screen, which is rather annoying), but I would definitely prefer the old behaviour for the time being.

There is a similar issue with this feature in Eclipse CDT. Eclipse CDT allows expanding binary files, and since #1063, they auto-expand if there is only one binary file. This clutters the screen and can also cause performance problems, as expanding binaries can be slow.

**Comment by iloveeclipse** [comment]
> Just as a minor addition: depending on whether the reported issue is perceived as a severe problem, it would be possible to (temporarily) revert #1742 until we have a mechanism to define custom expansion-termination criteria (as proposed by @Wittmaxi).

@HeikoKlare : would be nice to revert for M2 this week or latest fro M3.

**Comment by HeikoKlare** [comment]
Yes, totally makes sense to revert the feature enablement for now. We will try to improve the functionality to context-specifically consider the mentioned situation. I have created #2123 to revert the change.

**Comment by HeikoKlare** [comment]
The change has now been reverted. Thank you all for giving feedback and for providing use cases with degraded user experience due to the changes that we can take into account when improving the feature.
