### ISSUE TITLE
Find/Replace overlay: Buttons sometimes missing

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2006]
After resize the Buttons are sometimes missing even if the editor is super big after resizing it:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/346f3ec4-3a32-4ce2-82fd-9e4871a65737)
to reproduce:  shrink editor until buttons missing.
then double click the editor title to enlarge it -> buttons still missing

**Comment by HeikoKlare** [comment]
Related to #1992.
