### ISSUE TITLE
Startup preference page is unsorted

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-platform/eclipse.platform.ui#201]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/406876/178347169-dd523913-a20a-4948-a08f-d90e251bc0a2.png">

**Comment by mickaelistria** [comment]
Can't the natural order actually matter more than alphabetical order in most cases?  Ie if someone wants to debug startup, isn't it useful to know the order of extension startup?

**Comment by Bananeweizen** [comment]
Big fat "no". :)

A user interface should fit to the mental model of the user working with it, not to the mental model of the developer of the UI. Therefore just being able to read that list easily and to locate an item in the list easily is surely much more important than being able to deduce some additional debugging properties.

Besides that, I'm not even sure that the old list order really reflects the runtime startup order, since the code just asks the extension point for contributing members. My first guess would be they are sorted by bundle names alphabetically, but I really don't know.

**Comment by mickaelistria** [comment]
> A user interface should fit to the mental model of the user working with it, not to the mental model of the developer of the UI. 

It's not really about mental model; it's just that order can matter and can have a meaning; and that sorting in some other order just remove this piece of information. Not sure whether this is true here and whether the information is valuable; but in general being "nicer" at the risk of being less correct doesn't make a UI better.

**Comment by vogella** [comment]
+1 for sorting the entries. The current display does not seem valuable, only harder do find stuff for the user.
