### ISSUE TITLE
Find/Replace overlay: Immediate Replace after searching selected text not working

### ISSUE THREAD

**Issue by HannesWell** [eclipse-platform/eclipse.platform.ui#2011]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

When selecting a text in a file and opening the Find/Replace overlay the selected text is already entered into the search box.
If one subsequently opens the `Replace` part, types in a replacement and then hits Enter or presses the Replace button nothing happens.
I would expect that the previously selected text is replaced and if I continue pressing enter all other occurrences of that text.
If I press Search (or hit Enter in the Search text field) the next occurrence of the text is found and replace works as expected.
Therefore I assume replace is not working because the overlay is not yet in a 'Match-found' state.

In the Search/Find context it would probably be a bit odd to find the selected as first result, it would mean that one has to press Enter/Search twice to find the next occurrence. Therefore it is fine to start the search there after the selected text.
But in the context of replace I think it is reasonable to start the search before the selected text (or after if one replaces backwards, although that seems not to be possible).

Replace all is working as expected.

## Tested under this environment:
* OS & version: Windows 10
* Eclipse IDE/Platform version (as shown in *Help > About*): I20240629-1800

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

@Wittmaxi could you please have a look at this?

**Comment by Wittmaxi** [comment]
@HannesWell I remember having seen and addressed a similar bug a few weeks ago. I'll look into it :)
Thanks for the report!
