### ISSUE TITLE
Find/Replace overlay: Arrow button re-sizes on editor scrolling

### ISSUE THREAD

**Issue by thomasritter** [eclipse-platform/eclipse.platform.ui#2018]
Let's make sure the issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* Open an editor
* Open find via cmd+f
* Scroll the editor

I expected: The find UI control does not change on scrolling the editor

But got: The arrow buttons changes size. See GIF image

![trimmed](https://github.com/eclipse-platform/eclipse.platform.ui/assets/41768/afd1c54b-acce-4e0e-8011-edf273e83219)

## Tested under this environment:
* OS & version: Mac OS

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by Wittmaxi** [comment]
@HeikoKlare can you please have a look at this? I don't have a way to test on mac and I can't reproduce this behavior on my setup.
It is possible that https://github.com/eclipse-platform/eclipse.platform.ui/pull/2017 fixes this issue already

**Comment by HeikoKlare** [comment]
In my environment, the expand button does not change its size, but the find input field increases its size, so that the expand button is slightly moved to the left when scrolling. #2017 does not change anything with respect to that behavior.

**Comment by BeckerWdf** [comment]
I think this only happens if you have the "sticky scrolling" activated.

**Comment by Wittmaxi** [comment]
@Christopher-Hermann can you please check?

**Comment by Christopher-Hermann** [comment]
Yes, I will take a look. But it will probably take some time

**Comment by thomasritter** [comment]
I did another test round:

- Only used JDT Java Editor
- Switched off sticky scrolling
- Tried with and without the breadcrumb (bug always happened)
- Tried vertically and horizontal scrolling (bug always happened)

Same behavior. I do not think this is related to sticky scrolling.

I seems to me that any kind of redrawing the UI causes it to happen. For example, it also happens if I re-size the views or the Eclipse window.

**Comment by thomasritter** [comment]
Re-tested and looks good! Thanks for the fix Heiko :)
