### ISSUE TITLE
find/replace overlay - Notification API uses old X 

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#2035]
I haven't seen the notification API in a while, unfortunately the idea that we use it in the Eclipse IDE for non-blocking information seems not to have captured any interested and we removed it from theme switching as a restart is required.

So I'm happy to see it in the find/replace development.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/139910/775ad5d4-83f5-4676-bf1f-d7e1bca20111)

Unfortunately the pop-up uses the old Eclipse IDE close button which we discussed a very long time and decided that this X is very, very ugly.

@BeckerWdf IIRC we both discussed its replacement in the past. Could you create a PR for the replacement? I think it is a svg / png file.

**Comment by vogella** [comment]
Some background after a bit of research:

The X change was discussed and implemented via https://bugs.eclipse.org/bugs/show_bug.cgi?id=501491

My request https://bugs.eclipse.org/bugs/show_bug.cgi?id=575395 to update the notification API icon was never worked on, sorry this issue seems to have slipped my attention. 

https://git.eclipse.org/c/platform/eclipse.platform.swt.git/commit/?id=9a8d78ed435b81eb4a7fa3583d084e8b7593c543 replaced the drawing of the icon with a nicer drawing.

@HeikoKlare you already added a very nice looking icon. WDYT, can we also use this one for the notification API?

**Comment by HeikoKlare** [comment]
> you already added a very nice looking icon. WDYT, can we also use this one for the notification API?

Of course, we can use that. We just have to check whether it works fine with different themes on the different operating systems. But since I expect the themeing "constraints" to be same in the find/replace overlay and in the notification popup, it will probably just fit well.

**Comment by vogella** [comment]
I send a PR for the non-active state, "stealing" your icon.
