### ISSUE TITLE
org.eclipse.e4.ui.tests.css.core not running with Tycho

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.ui#204]
See https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/master/98/console
```
08:20:31.240 [INFO] --- tycho-surefire-plugin:3.0.0-SNAPSHOT:test (default-test) @ org.eclipse.e4.ui.tests.css.core ---
08:20:31.765 [INFO] Could not find a java toolchain of type jdk, using java from JAVA_HOME instead (/opt/tools/java/openjdk/jdk-17/latest/bin/java)
08:20:31.765 [INFO] Executing Test Runtime with timeout 0, logs (if any) will be placed at: /home/jenkins/agent/workspace/eclipse.platform.ui_master/tests/org.eclipse.e4.ui.tests.css.core/target/work/data/.metadata/.log
08:20:31.765 [INFO] Command line:
	[/opt/tools/java/openjdk/jdk-17/latest/bin/java, -Dosgi.noShutdown=false, -Dosgi.os=linux, -Dosgi.ws=gtk, -Dosgi.arch=x86_64, --add-modules=ALL-SYSTEM, -Dosgi.clean=true, -ea, -jar, /home/jenkins/agent/workspace/eclipse.platform.ui_master/.m2/repository/p2/osgi/bundle/org.eclipse.equinox.launcher/1.6.400.v20210924-0641/org.eclipse.equinox.launcher-1.6.400.v20210924-0641.jar, -data, /home/jenkins/agent/workspace/eclipse.platform.ui_master/tests/org.eclipse.e4.ui.tests.css.core/target/work/data, -install, /home/jenkins/agent/workspace/eclipse.platform.ui_master/tests/org.eclipse.e4.ui.tests.css.core/target/work, -configuration, /home/jenkins/agent/workspace/eclipse.platform.ui_master/tests/org.eclipse.e4.ui.tests.css.core/target/work/configuration, -application, org.eclipse.tycho.surefire.osgibooter.uitest, -testproperties, /home/jenkins/agent/workspace/eclipse.platform.ui_master/tests/org.eclipse.e4.ui.tests.css.core/target/surefire.properties]
WARNING: Using incubator modules: jdk.incubator.foreign, jdk.incubator.vector

Results:

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
```
then
```
08:22:17.008 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:3.0.0-SNAPSHOT:test (default-test) on project org.eclipse.e4.ui.tests.css.core: No tests found. -> [Help 1]
```

I suspect this is a consequence of addition of junit-* bundles.

**Comment by mickaelistria** [comment]
I believe this should be fixed with https://github.com/eclipse/tycho/pull/1137

**Comment by vogella** [comment]
Please also check the nightly build if this test suite is running as it uses Ant and a custom test runner.

**Comment by mickaelistria** [comment]
Some tests from nightly build are also not running, probably because JDT and PDE need to learn how to deal with junit-* bundles as well.

**Comment by mickaelistria** [comment]
If it can be used as an excuse, it looks like those tests have not been running for a long time on nightly builds:
* https://download.eclipse.org/eclipse/downloads/drops4/I20220606-1800/testresults/html/org.eclipse.e4.ui.tests.css.core_ep425I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html
* https://download.eclipse.org/eclipse/downloads/drops4/R-4.24-202206070700/testresults/html/org.eclipse.e4.ui.tests.css.core_ep424I-unit-win32-java11_win32.win32.x86_64_11.html (4.24 release)
* https://download.eclipse.org/eclipse/downloads/drops4/R-4.23-202203080310/testresults/html/org.eclipse.e4.ui.tests.css.core_ep423I-unit-win32-java11_win32.win32.x86_64_11.html (4.23)
* https://download.eclipse.org/eclipse/downloads/drops4/R-4.22-202111241800/testresults/html/org.eclipse.e4.ui.tests.css.core_ep422I-unit-win32-java11_win32.win32.x86_64_11.html (4.22)
* ...

So it's bad, but maybe not related here.

**Comment by mickaelistria** [comment]
This one is fixed on Tycho side, the issue with I-Build is tracked on https://github.com/eclipse-platform/eclipse.platform.ui/issues/206
