### ISSUE TITLE
Tasks view can no longer be sorted by priority

### ISSUE THREAD

**Issue by lukeu** [eclipse-platform/eclipse.platform.ui#2041]
- [✓] I verified I can reproduce this issue against Eclipse SDK 4.33-M1  (Updated from prior versions)
   - Includes a few extras like Buildship
   - Running on JDK-17

## Steps to reproduce

From a clean workspace:

1. Create a Java Project and class `Test` with the following content:
        
        /**
         * TODO: Test
         * FIXME: Really
         */
        public class Test {
               // TODO: Here too
        	public static void main(String[] args) {
        	}
        }
2. Open the Tasks view
3. (If necessary) compile the code to populate the view

**Observations:**

* Click the Description or Line table headers to confirm sorting - **works**
* Click the Priority table header - **nothing happens**
* Try the [ ... ] menu > Sort By > Priority - **nothing happens**

**Comments:** This issue was also present in Eclipse 4.32, but I suspect it must have regressed relatively recently. I haven't used this view for some months, so I can't give a solid timeframe. Just that when do, the priority-sort is something I would always use (due to years of TODO tags from a whole team).

There is nothing relevant-looking in the log.

## Tested under this environment:
Eclipse SDK
Version: 2024-09 (4.33)
Build id: I20240704-1800
Windows 11

## Community
- [✓] I'd be happy to help try and pinpoint the regression (via git-bisect) if someone can give me some pointers on which repo/package/(ideally) class to focus on. And maybe answer a few questions if I get stuck trying to get a dev env set up in a way to do such a bisect.

**Comment by lukeu** [comment]
Observed as working in Eclipse SDK 2023-12 (4.30) _(separate computer, but with a similar configuration)_

**Comment by iloveeclipse** [comment]
Could be regression from f13fb4997f5e7849da26285938a3a0aea1769747 / https://github.com/eclipse-platform/eclipse.platform.ui/pull/1733 (if I see it right, done in 4.32).
@jukzi : could you please check?

**Comment by iloveeclipse** [comment]
Fixed via https://github.com/eclipse-platform/eclipse.platform.ui/pull/2065
