### ISSUE TITLE
Notification-Overlay: old x-icon is shown when I hover over the new x

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#2043]
The new icon looks very good, but on hover, it becomes the old icon

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/97f6a297-313b-40ec-959a-4451845ef251)

**Comment by HeikoKlare** [comment]
Here the demonstration video from https://github.com/eclipse-platform/eclipse.platform.ui/pull/2037#issuecomment-2211736357:

![notification_close_active](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/45ba31c6-66b4-4167-a0ae-d53bea32143c)
