### ISSUE TITLE
project explorer tree view: make Left key jump to item parent

### ISSUE THREAD

**Issue by ronso0** [eclipse-platform/eclipse.platform.ui#205]
Goal: jump to and collapse a branch in the project explorer tree view with **Left** arrow key

If a project sub-directory has many files, navigating in the Eclipse tree view with the keyboard is cumbersome: with Up/Down it takes ages, PageUp/Down keys jump to far.
From Thunar file manager and Thunderbird I'm used to Left key
* child (leaf / collapsed branch): jump to item's parent
* branch (expanded): collpase

This greatly enhances navigation.

**Comment by vogella** [comment]
Good idea, a pull request would be very welcome.

**Comment by mickaelistria** [comment]
In some applications, left/right on a tree are also shortcuts for expanding/collapsing. We should first check whether some OS specific guidelines exist before implementing a strategy here.

**Comment by ronso0** [comment]
> In some applications, left/right on a tree are also shortcuts for expanding/collapsing

regardless of selected item & state (leaf/branch, collapsed/expanded)?

**Comment by mickaelistria** [comment]
Actually on my OS at least, it looks like Left/Right are bound to collapse/expand even in Eclipse IDE. I think it's more a OS thing to decide how to bind those keys in a tree; IMO Eclipse Platform shouldn't do anything particular here.

**Comment by ronso0** [comment]
Sure, that's the current behaviour **if** a collapsible branch item is selected.
The new thing would be **jump to parent branch**.

**Comment by lshanmug** [comment]
Using left arrow on collapsed item jumps to parent already in the Package Explorer on Mac and Windows. Couldn't test the  behavior on Linux.

**Comment by laeubi** [comment]
On Debian 9, nothing happens on "left-arrow"

**Comment by jukzi** [comment]
can not reproduce: left key already jump to parent (tested on win). since no PR contributed for years closing as not-planned. Feel free to reopen if you want to contribute something.

**Comment by ronso0** [comment]
So valid feature requests are closed as Not Planned if no one has opened a PR yet?

(I don't care much about this anymore, got used to the current state, also I don't plan to dive into Eclipse development either, so I'm fine with your decision)

**Comment by xerces8** [comment]
In my testing his works on Windows (and according the comment https://github.com/eclipse-platform/eclipse.platform.ui/issues/205#issuecomment-1183110015 also on Mac) but not on Linux.

There is also a similar issue with arrow-right. On Windows, it expands the selected item, and if already expanded, it moves to the first child.

There two make navigating trees much more pleasant in Windows than in Linux.

Please consider implementing it.

(I also suggest reopening this issue - I have no permission to do that myself)
