### ISSUE TITLE
Find/Replace overlay: weird placement when unmaximizing

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#2059]
Possibly regression after #1989

![31](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/9cf808cf-e7eb-4a8f-b9df-d9366e89830b)

**Comment by HeikoKlare** [comment]
Yes, it is a regression from #1989. Thank you for finding and reporting it! I have proposed a fix in #2062.
