### ISSUE TITLE
@AboutToHide method of dynamic menu contribution not called

### ISSUE THREAD

**Issue by glatuske** [eclipse-platform/eclipse.platform.ui#207]
Since Eclipse 2022-06 The @AboutToHide annotated method of a dynamic menu contribution is longer called.

I'm pretty sure this is due to recent changes in https://git.eclipse.org/r/c/platform/eclipse.platform.ui/+/192363/3/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/MenuManagerHideProcessor.java
@jukzi An Eclipse 4 contribution always has an contribution object attached to it. For such an item the @AboutToHide annotated method won't be called. This leads to items kept in context menu when opening it again.

Fix made for Eclipse 2022-06: https://bugs.eclipse.org/bugs/show_bug.cgi?id=578964

**Comment by iloveeclipse** [comment]
@glatuske : do you want to provide a patch? Or at least a simple example demonstrating the problem?

**Comment by glatuske** [comment]
For me reverting this commit https://github.com/eclipse-platform/eclipse.platform.ui/commit/d30e660750936aee1e87fb3a5cd5715d45a3ad9c would be sufficient. I'm not sure which kind of NPE it should fix. 
It looks like the condition is wrong:

`if (contribution != null) {
    continue; // avoid NPE (Bug 578964)
}`

In case contribution is null, the injector will be called and raises an NPE:

`ContextInjectionFactory.invoke(contribution, AboutToHide.class, parentContext,
         dynamicMenuContext, null); // contribution==null => NPE (Bug 578964)`

I case the contribution is not null the @AboutToHide method is not called.

**Comment by iloveeclipse** [comment]
@glatuske : I'm not e4 expert, I have no idea how to reproduce the problem.

I see in the code that the patch is most likely wrong, but ideally I would like to have a way to validate expected/observed behavior.

Could you please provide a simple e4 application example that demonstrates the problem? 

The e4 application I see in related https://bugs.eclipse.org/bugs/show_bug.cgi?id=442570 doesn't do *anything* in modern Eclipse.

**Comment by iloveeclipse** [comment]
@glatuske : would you please verify the fix with this SDk build: https://download.eclipse.org/eclipse/downloads/drops4/I20220717-1800 ?

**Comment by glatuske** [comment]
@iloveeclipse I have tested with our application. Work's as before. Thanks for the fix!

**Comment by jukzi** [comment]
thanks @glatuske  for testing and reporting. thanks @iloveeclipse  for fixing my typo.
