### ISSUE TITLE
Eclipse editors do not immediately release focus when pressing Alt+TAB (Linux, KDE)

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-platform/eclipse.platform.ui#2071]
I'm experiencing this problem after switching to 2024-06 in all my computers running Arch Linux KDE Plasma 6.1 (I still haven't gotten a chance to test it with other distributions or DE).

If I have an editor opened in Eclipse (Java, simple text editor, any kind of editor) and I press Alt+TAB to switch to another application, it looks like Eclipse releases the focus too late: the application switcher appears, but the TAB is inserted in the Eclipse editor (making it dirty).

Am I the only one experiencing this?
I don't think it's a problem with KDE Plasma, because it happens only with Eclipse.

**Comment by iloveeclipse** [comment]
I'm on KDE with plasma 5.27, I don't see the issue. Just a wild guess: are you using Wayland? If so, try X11 if that helps.

**Comment by LorenzoBettini** [comment]
I'm on Plasma 6.1, which is more recent.
I'm on Wayland, but I run Eclipse with `GDK_BACKEND=x11`

**Comment by LorenzoBettini** [comment]
However, you put me on the right track: running Eclipse without `GDK_BACKEND=x11` (i.e., Wayland) in KDE Wayland solved the problem.

**Comment by iloveeclipse** [comment]
On Linux we have two kinds of issues: either browser crashes (so webkit broken again), or anything else is wrong, but in most cases it's related to Wayland.

We can't fix that in platform UI, so closing.

**Comment by LorenzoBettini** [comment]
OK, let's hope this "closed" issue might help someone experiencing the same.

Out of curiosity, are you on X11?

**Comment by iloveeclipse** [comment]
Yes, and will stay for next few years, I don't want to be a beta tester, neither I will that for our customers.

I found this article describes very good what I feel about X11/Wayland state: https://www.dedoimedo.com/computers/wayland-2024.html

**Comment by LorenzoBettini** [comment]
To be honest, I found the opposite: Wayland is faster and less power consumption, anyway...

The problem seems to be only in Plasma: in Gnome Wayland (Fedora 40) I don't see this problem even when running Eclipse with `GDK_BACKEND=x11`,

**Comment by akurtakov** [comment]
Wayland or X11 has no clear winner - it depends on DE, apps, graphical card driver and even user preferences .
