### ISSUE TITLE
Sticky scrolling: Line Numbers look wrong (maybe sorted wrong way up?)

### ISSUE THREAD

**Issue by Wittmaxi** [eclipse-platform/eclipse.platform.ui#2098]
![grafik](https://github.com/user-attachments/assets/72b514a9-3f87-48ac-9f06-e4f119bae2ca)

**Comment by Christopher-Hermann** [comment]
Should be fixed by #2083

**Comment by Christopher-Hermann** [comment]
But great to see that the coloring is working for you on windows dark theme 👍

**Comment by BeckerWdf** [comment]
> Should be fixed by #2083

Then let's close it.
@Wittmaxi: Pls. reopen if the issue still persists.
