### ISSUE TITLE
Compare View for big files with Line Spacing freezes eclipse

### ISSUE THREAD

**Issue by DenisUngemach** [eclipse-platform/eclipse.platform.ui#2143]
First in your preferences (Window -> Preferences) for "Text Editors" set the line spacing to 50.

Then open a big java file, for example StyledText from the eclipse repo "eclipse.platform.swt" in the java editor, so that you can edit the code.

Make very much changes, for example format the complete code with another formatting style, so that all lines change and save.

Now open this file in the compare view and compare it with the previous version.
If you jump with the scrollbar to the middle of the file, eclipse freezes.

I think the reason for the freeze is the line spacing, this is the reason for opening the ticket here and not in the java repo.

**Comment by BeckerWdf** [comment]
So with "line spacing" set to 0 the performance issue does not happen?

**Comment by DenisUngemach** [comment]
No. 
With line spacing 0 it works fine. 

But if the compare editor is open and i change the line spacing to 50, then eclipse freezes.

**Comment by iloveeclipse** [comment]
Please run profiler and attach here some data which code "freezes" in SWT.

**Comment by DenisUngemach** [comment]
https://github.com/eclipse-platform/eclipse.platform/pull/1369/commits/9ef82d2a47affb7bbda9bf1b8c1e13ecf72366bb
This fix caused the performance problem. 

I work on the fix.

**Comment by iloveeclipse** [comment]
https://github.com/DenisUngemach/eclipse.platform/commit/9d4122ad39a548ac79957aedd17ff3d1aea80bc2 is not in master, so reopening.

@DenisUngemach : please create PR.

**Comment by DenisUngemach** [comment]
Sorry, this was a misclick i am on it.

**Comment by DenisUngemach** [comment]
Hello, now the PR is open.

**Comment by DenisUngemach** [comment]
For some reason the PR seems to close this issue. I didn't close this directly.

**Comment by iloveeclipse** [comment]
> For some reason the PR seems to close this issue. I didn't close this directly.

You should not merge anything to **your** repository **master** branch that says it will fix this issue. Work on a dedicated branch please.

![image](https://github.com/user-attachments/assets/43d28ce0-d3e8-4a9f-ba47-491af6a703a4)

**Comment by DenisUngemach** [comment]
Ok, thanks i see, it is the combination of "Fixes #issue#" in the commit message and the master branch of my forked repository.
