### ISSUE TITLE
Add feature to pin tabs

### ISSUE THREAD

**Issue by ask9** [eclipse-platform/eclipse.platform.ui#2156]
Please add feature to pin tabs.
If tab is pinned it becomes first.

Here is example from SSMS:

https://github.com/dbeaver/dbeaver/assets/33929221/f1d2e084-adde-4ba6-950c-ec6a4a2823e0

- add **menu item** "Pin tab" to a right click menu of each tab
OR/AND:
- show "Pin tab" **button** on each tab

Optionally:
- add option in Preferences: Hide button "Pin tab" on a tab (true/false). If it is true, then the button is not shown on each tab (in order to minimize a width of tabs for those users who don't need this feature, but they still can pin a tab using menu item of a tab).

**Comment by iloveeclipse** [comment]
This feature is already available, `Ctrl+3 -> Pin Editor` -> done, or use button on the toolbar to do same.
