### ISSUE TITLE
Find/replace overlay: improve switching between find and replace input fields

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.ui#2161]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) doesn't provide the feature.

## Suggestion

From a fresh installation and clean workspace:

* open a text editor
* open the find/replace overlay via CTRL+F / CMD+F
* open the replace bar (if not yet open) via CTRL+R / CMD+R
* try to navigate from find input field to replace input field via pressing TAB

You have to tab through all the search options before reaching the replace input field.

I would like to be able to directly navigate between find and replace input fields via a single keyboard interaction (a single TAB press), as this is (in my opinion) the most important navigation scenario.

I see options how to improve this:
1. Change the tab order by having replace input field right after search input field before navigating through the option buttons.
2. Use a different way of keyboard interaction to navigate through the options and the input fields (such as tab for the input fields and Alt+Tab for the option or the like).

## Acknowledgements

This proposal is based on a finding by Andreia Schoknecht and Lukas Kolender in a test session performed at SAP. Thank you for testing and reporting!

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by thomasritter** [comment]
I just received more internal customer feedback from regular users regarding this. So, this is really something we should improve. I would recommend option 1. This is how it behaves in Intellij/VS Code.

**Comment by Madjosz** [comment]
Option 1. is also how the old find/replace dialog behaved so it should definitely be implemented this way.

**Comment by ronso0** [comment]
While 1. would be the obvious fix, here's another idea (unconventional, I know):

3. reuse Ctrl+F/R, keep the tab order
   * Ctrl+R in Find field: show Replace row. If already visible -> focus Replace field
   * Ctrl+R in Replace field: hide Replace row
   * Ctrl+F in Find field: close dialog
   * Ctrl+F in Replace field: focus Find field

**Comment by DaveDibble** [comment]
Am grateful this thread was opened. How did you know to use Ctrl-R?  In the Edit Menu it lists Find/Replace as Ctrl+F

**Comment by HeikoKlare** [comment]
The shortcuts to use within the overlay are mentioned in the tooltips, e.g., for CTRL+R:
![Image](https://github.com/user-attachments/assets/b8dc7645-dbae-49c1-83d6-631c02012dbf)

This also applies to the search options.

**Comment by DaveDibble** [comment]
If one thinks to move the mouse over the > sign?   Okay I see that now. Thanks. The other icons with tool tips are a bit more obvious but I can be trained..
