### ISSUE TITLE
Recent changes to UI Themes have broken Table rendering on Mac

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.ui#2171]
Tested with `eclipse-SDK-I20240807-0710-macosx-cocoa-aarch64` on macOS Sonoma 14.6

On Mac, tables should have alternate row colors like this (screenshot from Eclipse 4.32):

<img width="999" alt="eclipse 4 32" src="https://github.com/user-attachments/assets/a2dd6dc3-0fd6-49a4-80a6-3d8df0a5720f">

The recent changes to the light theme now render a table like this:

<img width="1058" alt="eclispe 4 33" src="https://github.com/user-attachments/assets/0b707d1b-2bfe-4932-aa41-1048f9e2ff93">

Alternate row colors on Mac is a feature (and a useful one, at that) that has always been in Eclipse and is present in many native Mac apps.

**Comment by Phillipus** [comment]
In fact, the alternate row colors are present in the latest dark theme:

<img width="1055" alt="eclipse 4 33 dark" src="https://github.com/user-attachments/assets/6724c909-b2e1-48d8-86d7-67a7e23ce38e">

**Comment by BeckerWdf** [comment]
We did this change by intention and already tested this in-house our company. We did not get bad feedback about this.
I propose we keep it like it is for this release. Let's keep that issue open. If we get more comments that this was a bad decision we can revert that change for the next release.
What do yo think @Phillipus?

**Comment by Phillipus** [comment]
> What do yo think @Phillipus?

- I think that the loss of alternate row colours in a table is an ill-advised change for Mac users. This is something that exists in many Mac apps and has existed in Eclipse for a long time now and you may find a backlash from the broader Mac community after 4.33. I would definitely say this particular change is not a good idea.

- Generally, when you say "We did not get bad feedback about this" you might be making this judgement based on how these changes to the light theme impact the Eclipse IDE. Many RCP apps are built on the latest version of Eclipse and the UI of these apps will change if they adopt this light theme. I've already pointed out a side-effect of this [here](https://github.com/eclipse-platform/eclipse.platform.ui/issues/2173). As I said elsewhere, there's a big difference between "make this view grey" and "make all controls in every view grey".  Eclipse IDE users might be OK with the change but this has impact on RCP apps (and Eclipse plug-ins)

- Personally, I don't mind seeing a grey Package Explorer in Eclipse but I do mind seeing a homogenous mass of grey for _all_ views and controls in our RCP app (I applied the new theme for testing purposes).

**Comment by BeckerWdf** [comment]
This should be fixed with https://github.com/eclipse-platform/eclipse.platform.ui/pull/2181. If not pls. re-open.

**Comment by Phillipus** [comment]
> This should be fixed with #2181. If not pls. re-open.

Yes, it is. Thanks!

**Comment by Phillipus** [comment]
~I tested with I20240923-0040 and the tables on Mac have again lost alternate row colors and are a homogenous grey. Did something change?~

Edit - ignore. See below.

**Comment by mvm-sap** [comment]
@Phillipus we had reverted the changes that we had done for Table control. Table control no longer has a grey background. I think you are referring to  Views which have Tree control. we have set the background of Tree Control to grey. Could you please re-check and confirm

**Comment by Phillipus** [comment]
> @Phillipus we had reverted the changes that we had done for Table control. Table control no longer has a grey background. I think you are referring to Views which have Tree control. we have set the background of Tree Control to grey. Could you please re-check and confirm

You're right. I'd forgotten that it was applied to Trees only. Sorry for the noise!

**Comment by BeckerWdf** [comment]
> > @Phillipus we had reverted the changes that we had done for Table control. Table control no longer has a grey background. I think you are referring to Views which have Tree control. we have set the background of Tree Control to grey. Could you please re-check and confirm
> 
> You're right. I'd forgotten that it was applied to Trees only. Sorry for the noise!

Show we also apply it for tables?

**Comment by Phillipus** [comment]
> Show we also apply it for tables?

Not really. The original issue is that native Mac UI has alternate row coloring in tables and to keep it that way.

**Comment by Phillipus** [comment]
Actually, I was wrong about this, this issue applies to a `Table` **and** a `Tree` control. The "Problems" view contains a `Tree` (with lines visible), not a `Table`.

When a `Table` or `Tree` has lines visible (`Control#setLinesVisible(true)`) on Mac alternate row colors are displayed. So, the new light theme is hiding the alternate row colors on Mac on both controls.

Opened https://github.com/eclipse-platform/eclipse.platform.ui/issues/2395
