### ISSUE TITLE
The Find/Replace dialog finds case-insensitive matches, but doesn't replace them

### ISSUE THREAD

**Issue by estepper** [eclipse-platform/eclipse.platform.ui#2172]
For the following text:

```
   String msg;
   String getMsg() { return msg; }
   void setMsg(String msg) { this.msg = msg; }
```

When you use the (traditional) Find/Replace dialog as follows (note that "Case-sensitive" is not checked):

![image](https://github.com/user-attachments/assets/b7cccbbf-5fce-4a28-b66c-35f166e45980)

The first Alt+d (Replace/Find button) properly replaces the field declaration and selects the upper case Msg in "getMsg". 
But the second Alt+d does not replace the selected Msg in "getMsg". It replaces the lower case msg in "return msg" and selects the upper case Msg in "setMsg".  All the upper case Msg occurrences stay unreplaced.

**Comment by deepika-u** [comment]
@estepper 
I have the below observations on the issue you have reported.

- When the Find/Replace dialog is open, ctrl+d is not performing any action for me.
- When the cursor is on editor, ctrl+d is deleting that particular line as conveyed in Preferences -> General -> Keys.
- On the other side if i press Replace/Find button again and again in the snippet you have shared i am able to see all the instances getting replaced for me as shown below.
![image](https://github.com/user-attachments/assets/db287cf0-4731-4385-a78f-3f21e0991cff)
- I am on below environment.
Eclipse SDK
Version: 2024-12 (4.34)
Build id: I20241107-1800
OS: Windows 11, v.10.0, x86_64 / win32
Java vendor: Eclipse Adoptium
Java runtime version: 21.0.1+12-LTS
Java version: 21.0.1

Can you try on the latest and let us know if you are seeing the issue still?

**Comment by estepper** [comment]
Sorry, I really meant Alt+d, not Ctrl+d. I've changed the description accordingly.

I've now tested with Version: 2024-12 M2 (4.34.0 M2), Build id: 20241024-0621 and indeed it now works.

Thank you very much!

**Comment by deepika-u** [comment]
@estepper : Thanks for the update.

If its no more an issue, can this issue be closed?

**Comment by estepper** [comment]
Yes, thank you. I'll have an eye on this issue and report when I notice remaning problems.
