### ISSUE TITLE
Editor Tabs looks greyed out

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2182]
in the past month the File names in the editor  changed from black to grey or the used font got thinner then a pixel. Was that intentional? looks less readable
now (I20240811-1800):
![image](https://github.com/user-attachments/assets/dd4f90c3-69a2-49f1-919a-0d9dac95fe32)
before (I20240710-1800):
![image](https://github.com/user-attachments/assets/1d1845fc-f14f-439a-87b5-57622167e77a)

Sadly the screenshots are not so good to see the difference due to subpixel rendering. But it was basically the first thing that fleshed my eyes after having not used eclipse for a month.

**Comment by jukzi** [comment]
![image](https://github.com/user-attachments/assets/5f7f6659-9063-4a98-8aad-85d3ece15b43)

**Comment by jukzi** [comment]
old black was 0,0,0. new color is 59,59,59
![image](https://github.com/user-attachments/assets/7fe69239-9e2e-4972-b831-483138fd1e20)

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114

**Comment by Phillipus** [comment]
Agreed, the text color looks a bit pale now.

**Comment by BeckerWdf** [comment]
@mvm-sap: Was this change by intention? If yes: Why. If not: Can we get the old color with the better contrast back?

**Comment by mvm-sap** [comment]
> @mvm-sap: Was this change by intention? If yes: Why. If not: Can we get the old color with the better contrast back?

Yes, we followed VS Code tab font color codes. 
In editor
selected tab : #3b3b3b
unselected tab : #6a6a6a
In Views 
Both Selected and Unselected tabs : #3b3b3b

If this does not look good, may be I can try to change

**Comment by BeckerWdf** [comment]
> > @mvm-sap: Was this change by intention? If yes: Why. If not: Can we get the old color with the better contrast back?
> 
> Yes, we followed VS Code tab font color codes. In editor selected tab : #3b3b3b unselected tab : #6a6a6a In Views Both Selected and Unselected tabs : #3b3b3b
> 
> If this does not look good, may be I can try to change

I really can agree that the contrast of text and background was better in the past. And good contrast is a good think.
Was the color different for selected and unselect tabs before your change?

**Comment by mvm-sap** [comment]
> > > @mvm-sap: Was this change by intention? If yes: Why. If not: Can we get the old color with the better contrast back?
> > 
> > 
> > Yes, we followed VS Code tab font color codes. In editor selected tab : #3b3b3b unselected tab : #6a6a6a In Views Both Selected and Unselected tabs : #3b3b3b
> > If this does not look good, may be I can try to change
> 
> I really can agree that the contrast of text and background was better in the past. And good contrast is a good think. Was the color different for selected and unselect tabs before your change?

yes, it was #000000 for both selected and unselected tab

**Comment by BeckerWdf** [comment]
What about bringing #000000 back for the selected tabs and maybe have #3b3b3b for the unselected tabs?
What do you think?

**Comment by mvm-sap** [comment]
> What about bringing #000000 back for the selected tabs and maybe have #3b3b3b for the unselected tabs? What do you think?

Both in view and editor ?

**Comment by BeckerWdf** [comment]
> > What about bringing #000000 back for the selected tabs and maybe have #3b3b3b for the unselected tabs? What do you think?
> 
> Both in view and editor ?

I would say yes.

**Comment by jukzi** [comment]
> What about bringing #000000 back for the selected tabs and maybe have #3b3b3b for the unselected tabs?

Worth a try. But my guess that full contrast is still best for both. The active tab is already emphasized with that blue bar.
![image](https://github.com/user-attachments/assets/6d162c1b-f0a1-4ae1-8cee-f1151dde0d7a)

In general an UI should have high contrast on the active part and lower contrast on the dysfunctional surrounding to focus the reader on the important things. However the eclipse IDE does not follow that design principle. As long as the surrounding views still have high contrast lowering the contrast of the tabs only makes them harder to read without making the user focus on the editor content. 
Reducing contrast does only make sense if it is done consistently to serve the purpose of focus.

**Comment by BeckerWdf** [comment]
This is addressed it in: https://github.com/eclipse-platform/eclipse.platform.ui/pull/2294

**Comment by BeckerWdf** [comment]
I think this is fixed (see above). Pls. reopen if you disagree.
