### ISSUE TITLE
Adding new MarkerField via markerSupport extension point to problems view seems impossible

### ISSUE THREAD

**Issue by travkin79** [eclipse-platform/eclipse.platform.ui#2193]
I tried adding a new `MarkerField` to the problems view using the _markerSupport_ extension point. That seems not to be possible with the latest [org.eclipse.ui.ide](https://github.com/eclipse-platform/eclipse.platform.ui/tree/master/bundles/org.eclipse.ui.ide) bundle. I was not able to select the new `MarkerField` in the problems (or markers) view's "Configure Columns..." dialog.

Using the _markerSupport_ extension point I added a new _markerContentGenerator_ and a _markerContentGeneratorExtension_ for the problem view's marker content generator (`id=org.eclipse.ui.ide.problemsGenerator`). While debugging the code, I found out that my marker content generator was initialized and used the new `MarkerField`, but the [`ContentGeneratorDescriptor`](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/views/markers/internal/ContentGeneratorDescriptor.java) did not pick up the new `MarkerField`.

I guess, the method [`ContentGeneratorDescriptor#getAllFields()`](https://github.com/eclipse-platform/eclipse.platform.ui/blob/8ad21aa2384fb09ae4146c4905a2929d474bacff/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/views/markers/internal/ContentGeneratorDescriptor.java#L107) is not correct. I think, the `ContentGeneratorDescriptor` has to collect all `MarkerField`s provided by the corresponding marker content generator as well as `MarkerField`s provided by the marker content generator extensions. Instead, `ContentGeneratorDescriptor#getAllFields()` ignores the registered extensions. It seems, the only place, where marker content generator extensions are considered, is the method [`ContentGeneratorDescriptor#getFilterReferences()`](https://github.com/eclipse-platform/eclipse.platform.ui/blob/8ad21aa2384fb09ae4146c4905a2929d474bacff/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/views/markers/internal/ContentGeneratorDescriptor.java#L125).

Did I misunderstand something or do we have to handle marker content generator extensions in most of the `ContentGeneratorDescriptor`'s methods?

## Details

My marker support extension looked like that:

```java
   <extension
         point="org.eclipse.ui.ide.markerSupport">
      <markerField
            class="org.eclipse.lsp4e.ui.CustomMarkerField"
            id="org.eclipse.lsp4e.markerField.custom"
            name="Custom">
      </markerField>
      <markerContentGeneratorExtension
            generatorId="org.eclipse.ui.ide.problemsGenerator"
            id="org.eclipse.lsp4e.markerContentGenerator">
      </markerContentGeneratorExtension>
      <markerContentGenerator
            id="org.eclipse.lsp4e.markerContentGenerator"
            name="LSP4E MarkerContentGenerator">
         <markerFieldReference
               id="org.eclipse.lsp4e.markerField.custom">
         </markerFieldReference>
         <markerTypeReference
               id="diagnostic">
         </markerTypeReference>
      </markerContentGenerator>
   </extension>
```

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by jukzi** [comment]
Feel free to suggest a PR including a testcase showing the benefit.

**Comment by travkin79** [comment]
Hi @jukzi,
I'm working on it, but I have a few problems with compiling the unmodified bundles from _master_ branch.

It seems, one compile error is related to [one of your last commits](https://github.com/eclipse-platform/eclipse.platform.ui/commit/8d69dc277c67f1b185e2f6e521bd45d1bc476c7c). In my environment the method `IFile#readNBytes()` is not found. What do I have to change in my environment? Is there a target definition file, I can use? Does the dependency to org.eclipse.core.resources bundle use an obsolete version? My environment has version 3.20.200.v20240513-1323, while the MANIFEST.MF in org.eclipse.search.core demands version [3.1.4.0, 4.0.0).

I have a similar issue with the bundle org.eclipse.ui.workbench where `Display#isRescalingAtRuntime()` is not found (relates to another [commit](https://github.com/eclipse-platform/eclipse.platform.ui/commit/e30a52d4c4faa514671d294dcd1d35d9d0f6820b)).

**Comment by merks** [comment]
It's generally easiest to use the automated Oomph setup:

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

It clones a lot more repos than you need, but it's less error prone than try to set up a single repository. 

Minimally you should use the installer's advanced mode and choose the Platform's own SDK product:

![image](https://github.com/user-attachments/assets/b42b3f4c-dc90-4d80-b42c-8060d635ef7d)

And select the Platform UI project:

![image](https://github.com/user-attachments/assets/99523ca7-f5d5-4d22-aeab-06f0dad8079c)

---

My build had an error like this when I tested my own instructions above:

![image](https://github.com/user-attachments/assets/9b4a96ed-30b1-4d2a-b5c3-0728bab5ebaa)

But it seems to have recovered from that:

![image](https://github.com/user-attachments/assets/32281e72-ba78-469f-97d5-245e36b250e0)

**Comment by travkin79** [comment]
Thank you very much, @merks. That helps a lot.
I had the same NPE during Oomph installation, but now the projects compile and I can go on.

**Comment by jukzi** [comment]
please create an issue at https://github.com/eclipse-jdt/eclipse.jdt.core/issues with the stacktrace in text form

**Comment by travkin79** [comment]
> please create an issue at https://github.com/eclipse-jdt/eclipse.jdt.core/issues with the stacktrace in text form

Done: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2828

**Comment by travkin79** [comment]
I prepared a pull request for this issue: PR #2207.
