### ISSUE TITLE
modern light theme: inactive Console View Tab looks odd

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2197]
reproduce: 
1. disable "Show console" (automatically), switch to another view. 
![image](https://github.com/user-attachments/assets/b738a846-3875-4062-8454-3e464aba7719)

3. log something to Console
4. => "Console" becomes highlighted (bold, black) indicating pending output. With the new theme that feels/looks like Console is the active View but it is not. Screenshot:
![image](https://github.com/user-attachments/assets/83caa8b1-5774-4faf-be43-c0243e12a649)

With the old Scheme it was a also highlighted but it was obvious that it is not the title of the active view, because the active view tab was highlighted by the background color:
![image](https://github.com/user-attachments/assets/6e01b67b-c216-4ae6-9376-8a6d6046f409)
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114 @thomasritter

The UI needs to have a single consistent pattern what highlights the active View. I.e. either backgroundcolor or textcolor and must not mix that highlighting with other usecases

**Comment by Phillipus** [comment]
Possibly related https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114#issuecomment-2284571116 and https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114#issuecomment-2286023149

**Comment by BeckerWdf** [comment]
> The UI needs to have a single consistent pattern what highlights the active View. I.e. either backgroundcolor or textcolor and must not mix that highlighting with other usecases

It does with the blue underlining...

**Comment by jukzi** [comment]
>> single consistent pattern

> It does with the blue underlining...

that is only one of multiple. For the inactive Editors the text color is also changed (and is not a blue underline but a blue overline).

**Comment by BeckerWdf** [comment]
> and is not a blue underline but a blue overline

Really?

**Comment by jukzi** [comment]
> Really?

see:
![image](https://github.com/user-attachments/assets/926ba021-c769-4c30-8c74-52890ef3a3a4)

**Comment by HeikoKlare** [comment]
It started to appear like this for me today as well. Until yesterday, the highlight was always at the tab's bottom.

Even worse, the highlight at the top appears to be smaller in the dark theme, which makes it hardly visible for the active tab that has focus:
![image](https://github.com/user-attachments/assets/137de6f4-cc54-424f-94e5-0984bdc2c2ac)

_Edit:_ Just saw that it should have already been like this for quite some time, but for some reasons my SDK first changed today, even though I update it via Oomph on a daily basis and always properly get other changes in.

**Comment by jukzi** [comment]
With light theme (preview) it is very confusing which tab is hovered/active:
For the editors a mouse hover highlights the tab, while it dimms the tab on a hover in the breakpoints/variables view:
![image](https://github.com/user-attachments/assets/b4b2b129-9857-4016-8c98-27138f04dd62)
![image](https://github.com/user-attachments/assets/75a118b1-0065-4092-b3cf-a3b68251a34a)

**Comment by BeckerWdf** [comment]
> The UI needs to have a single consistent pattern what highlights the active View. I.e. either backgroundcolor or textcolor and must not mix that highlighting with other usecases

From my point of view this is address with https://github.com/eclipse-platform/eclipse.platform.ui/pull/2286.
Pls. reopen if you disagree.
