### ISSUE TITLE
modern light theme: editor right bar to bright

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2201]
Only the editor content should have white background, but now also the bar right to the scroll bar has white contrast.
![image](https://github.com/user-attachments/assets/47322a01-817d-4ed9-bbe2-b11a262bf32d)
old scheme had had it grey:
![image](https://github.com/user-attachments/assets/1b6774f0-2609-4f2c-a885-d2f7c3a1eb16)

**Comment by BeckerWdf** [comment]
see https://github.com/eclipse-platform/eclipse.platform.ui/pull/2144
for this.
Maybe you can help @mvm-sap with your knowledge to fix the remaining issues in that PR.

**Comment by jukzi** [comment]
> Maybe you can help @mvm-sap with your knowledge to fix the remaining issues in that PR.

Sorry i have no knowledge about how to use themes at all. All i remember is that i did consider the css enginge broken when i looked into it years ago as it did not consider subclasses to match super classes and would suggest to fix that before working with it. Also i would expect that the Layout Spy (shift-ctrl-alt-f9) shows which css classes an element does adhere to. But i can't see helpful information there. Maybe improve that tool first?
![image](https://github.com/user-attachments/assets/4d2c7964-917e-464c-9905-e086bdb5034c)

**Comment by jukzi** [comment]
with css spy fixed (https://github.com/eclipse-pde/eclipse.pde/issues/1381) one can see this in the css spy (old light theme):
![image](https://github.com/user-attachments/assets/9a6f3e21-bae4-4f46-b447-dedd68bf01f1)
and with preview light theme:
![image](https://github.com/user-attachments/assets/d233e841-4627-4609-819b-9e3fa3413f8f)

**Comment by jukzi** [comment]
i.e. this CSS entry did the coloring:

```
CTabFolder Canvas {
	background-color: #F8F8F8;
}
```
https://github.com/eclipse-platform/eclipse.platform.ui/blob/b06fb4736ef968ed4b7a143084dad7f86b1bfd86/bundles/org.eclipse.ui.themes/css/e4_default_win.css#L74

Adding that to `e4_preview_win.css` solves this problem - but i don't know what else it will color too.

**Comment by BeckerWdf** [comment]
> i.e. this CSS entry did the coloring:
> 
> ```
> CTabFolder Canvas {
> 	background-color: #F8F8F8;
> }
> ```
> 
> https://github.com/eclipse-platform/eclipse.platform.ui/blob/b06fb4736ef968ed4b7a143084dad7f86b1bfd86/bundles/org.eclipse.ui.themes/css/e4_default_win.css#L74
> 
> Adding that to `e4_preview_win.css` solves this problem - but i don't know what else it will color too.

@mvm-sap: Can you pls. have a look at this?

**Comment by mvm-sap** [comment]
This change will not cause problems in other places. I shall create a PR soon for this.

**Comment by mvm-sap** [comment]
This issue could be closed as the issue is resolved

**Comment by BeckerWdf** [comment]
@jukzi: Can you pls verify and close?

**Comment by jukzi** [comment]
seems to be fixed:
![image](https://github.com/user-attachments/assets/e3dd1ff2-5534-4f07-bc85-bbc49b5f2a52)
