### ISSUE TITLE
Marketplace Client does not open up

### ISSUE THREAD

**Issue by jochenw** [eclipse-platform/eclipse.platform.ui#2212]
Hi,

using a freshly extracted eclipse-platform-4.33M3-win32-x86_64.zip on Windows 11 in an empty workspace directory, I cannot open the Marketplace Client (Help / Eclipse Marketplace ...), because that fails with an error message

![image](https://github.com/user-attachments/assets/5e8eadd7-f944-4dbb-9293-45b5bf2c8332)

This is reproducable since 4.33M1, on Windows, and Linux.
The following plugins have been installed from the Eclipse plugin repository: 

![Installation](https://github.com/user-attachments/assets/c5eb8482-c14d-4bda-acd4-adf4a378bc2a)

I am also attaching my .log file

Jochen

[.log](https://github.com/user-attachments/files/16707758/default.log)

**Comment by jochenw** [comment]
As a workaround, I am doing the plugin installation in some steps:

1. Install *only* the Marketplace client.
2. Install some items from the Marketplace. (Always surprised, that this works, because most of them depend on the presence of plugins, that will be installed in step 3, thus are so far missing.)
3. Install the rest of the plugins from the above list.

**Comment by akurtakov** [comment]
This is not something eclipse platform can help with - Please report to https://github.com/eclipse-mpc/epp.mpc .

**Comment by merks** [comment]
Most likely this is a variation of this issue:

https://github.com/eclipse-orbit/orbit-simrel/issues/40

I know for sure that MPC was not working for exactly this reason because the underlying http client libraries were not working and hence anything using them is broken, include JGit and MPC.

I'm hopeful it will be fixed in SimRel M3 on Friday.

Note that I believe an IDE that is broken in this way cannot be updated so that it's no longer broken.

**Comment by merks** [comment]
@jochenw 

Note that the M3 SImRel repository is available  now:

https://download.eclipse.org/releases/2024-09/202408231000/

On Friday https://download.eclipse.org/releases/2024-09/ will compose it.

So you could follow your normal steps but get your updates from 202408231000.

**Comment by jochenw** [comment]
I will try that, @merks. Thank you!

**Comment by jochenw** [comment]
Happy to report, that the following procedure works, indeed.

1. Extract the file eclipse-platform-4.33M3-win32-x86_64.zip, creating a new "eclipse" folder.
2. Adding [https://download.eclipse.org/releases/2024-09/202408231000/](https://download.eclipse.org/releases/2024-09/202408231000/) as a new update site.
3. Install all my necessary extensions/plugins from that update site, rather than using "All available repositories".
4. Continue normally, using the Marketplace client.

**Comment by merks** [comment]
@jochenw 

That's super nice of you to test and confirm the results!  🏅 This problem really caused me a lot of grief and worry for folks updating to the release in September...
