### ISSUE TITLE
workspace path not writable on a smb home share

### ISSUE THREAD

**Issue by andy1805** [eclipse-platform/eclipse.platform.ui#2225]
Since the release 2024-03 we cant use the eclipse IDE for our exams because the students have to save the workspace on their home share and that's not more possible. The last release that worked was 2023-12. 

> Quote Ed Merks from eclipse forum: The logic was changed during the 2024-03 release cycle and now calls this method to test:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/e3628a3a67c44771465d7d317b3424920c425090/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/ide/ChooseWorkspaceDialog.java#L491-L504

In our system the exam software opens a folder on the students home share, where they have to save their workspace, and only files under this folder will be transferred into the teachers home share.
I have no idea about java, I only have to install eclipse in a way that's usable for exams. I don't know why the logic have be changed and why it recognize the path as not writable because it is. I can only imagine that it checks if the local user has write rights and they log in via Samba User.
![EclipseFehler](https://github.com/user-attachments/assets/afb903bf-2fa6-4024-ab95-325844ab9642)

**Comment by merks** [comment]
What probably works as a workaround is to specify the workspace on the command line:

eclipse.exe -data L:\eclipse_2024-06

Can you try if that works?

**Comment by andy1805** [comment]
Hi Ed,

thanks for your help. 

Yes, you're absolutely right. I already tested this workaround and it works. But how i wrote before, I don't know before the exam, where exactly the workspace have to be saved. So for example the students have to change the shortcut of eclipse.exe with "-data L:\Klassenarbeiten\M122-LB2-INP23C\eclipse_2024-06" (M122 is the modul, lb2 means "Leistungsbeurteilung 2" and the class name "INP23B") and this every time again, because it's always another path.

That's not practible at all. I can use this way for normal work but not for exams.

**Comment by jukzi** [comment]
`The path is not writable by the current user` was introduced with https://github.com/eclipse-platform/eclipse.platform.ui/pull/1522. @laeubi  can you please take a look?

**Comment by laeubi** [comment]
> `The path is not writable by the current user` was introduced with #1522. @laeubi can you please take a look?

No as I don't have any SMB setup like described by the user, and as verified with @merks the location obviously *is* writable so this is either a Windows Bug or JDK Bug but nothing that can be fixed by platform without further information or access to this special setup.

**Comment by merks** [comment]
This is why I asked the user in https://www.eclipse.org/forums/index.php?t=msg&th=1116027&goto=1869615&#msg_1869615 if they could test this code:
```
package test;

import java.nio.file.Files;
import java.nio.file.Path;

public class Test {

	public static void main(String[] args) {
		isWritable(Path.of("D:\\test"));
	}

	private static boolean isWritable(Path path) {
		if (Files.exists(path)) {
			return Files.isWritable(path);
		}
		Path parent = path.getParent();
		if (parent != null) {
			return isWritable(parent);
		}
		return true;
	}
}
```
Of course not everyone is programmer for whom such a thing is easy...

**Comment by jukzi** [comment]
according to the comments in 
sun.nio.fs.WindowsFileSystemProvider.checkAccess(Path, AccessMode...)
`for write access we need to check if the DOS readonly attribute and if the volume is read-only`
java.nio.file.Files.isWritable(Path) does check if the the drive is writable. i could imagine that this is not the case.

Also see https://github.com/adoptium/adoptium-support/issues/742 that it seems to be a known problem.
As a workaround java.io.File.canWrite() may work.

**Comment by iloveeclipse** [comment]
OK, it is Windows specific, I wasn't able to reproduce on Linux (using read only parent root directory etc)

**Comment by Phillipus** [comment]
I mapped a shared volume to `Y:` drive on my Windows network to test this and the snippet in the [comment ](https://github.com/eclipse-platform/eclipse.platform.ui/issues/2225#issuecomment-2312802649) returns false.

> As a workaround java.io.File.canWrite() may work.

Yep, it does.

**Comment by Phillipus** [comment]
The check in `ChooseWorkspaceDialog` is useless anyway because you can manually type in a non-existing path and it's happy. (The parent of a non-existing path is null so the code there returns true)

**Comment by laeubi** [comment]
> The check in `ChooseWorkspaceDialog` is useless anyway because you can manually type in a non-existing path and it's happy. (The parent of a non-existing path is null so the code there returns true)

If the path is not existing it will be created (we can't check if that possible at all). It then goes down and check the parent until it find one that exits or it finds the root of the file system (in that case we can't do anything at all)

> (The parent of a non-existing path is null so the code there returns true)

It is not see https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html#getParent--

> This method does not access the file system; **the path or its parent may not exist**.

**Comment by Phillipus** [comment]
> System.out.println(Path.of("imaginary_path").getParent());

null

As I said, the check in `ChooseWorkspaceDialog` returns true when a path does not exist.

**Comment by laeubi** [comment]
> System.out.println(Path.of("imaginary_path").getParent());

This is not an absolute path and therefore return `null` as described as we have no more path elements

> As I said, the check in ChooseWorkspaceDialog returns true when a path does not exist.

Please try with an absolute path ...

**Comment by merks** [comment]
We’re probably best to err on the side of being too permissive than to err with a jdk bug.

**Comment by Phillipus** [comment]
> Please try with an absolute path ...

`System.out.println(Path.of("Y:\\").getParent());`

(I don't have a `Y:` drive.)

To be clear, the test in `ChooseWorkspaceDialog` returns true if a given path does not exist because once it gets to the non-existing root parent is null.

Test the snippet in https://github.com/eclipse-platform/eclipse.platform.ui/issues/2225#issuecomment-2312802649 with a non-existing drive like this:

`Y:\\Hello`

**Comment by laeubi** [comment]
> To be clear, the test in ChooseWorkspaceDialog returns true if a given path does not exist because once it gets to the non-existing root parent is null.

And that is what is desired, so if you want to test is please test

1. With an absolute path
2. With a root that exits
3. Where at laest one segment exits

**Comment by jukzi** [comment]
I understand the "parent"-complaint as following:
A path on a non existing root like
![image](https://github.com/user-attachments/assets/2e33f69b-e5c6-4afd-b5a3-7f7612fd1570)
results in no warning but later it can not be created:
![image](https://github.com/user-attachments/assets/af000b00-4c3c-45fc-bd40-960cbac07131)
i.e. it should have had a "The path is not writable by the current user" warning.

**Comment by jukzi** [comment]
> I mapped a shared volume to `Y:` drive on my Windows network to test this and the snippet in the [comment ](https://github.com/eclipse-platform/eclipse.platform.ui/issues/2225#issuecomment-2312802649) returns false.

@Phillipus 
Please file a ticket about that to https://bugreport.java.com/bugreport/start_form so they can fix JDK. They just don't know how to reproduce.

> > As a workaround java.io.File.canWrite() may work.
> 
> Yep, it does.

So we should use that as workaround in the meantime.

**Comment by jukzi** [comment]
`Files.isWritable()` does also not work on my computer for very simple path like c:\aaa
![image](https://github.com/user-attachments/assets/0e72a9ce-29ba-429e-bfa2-721cd2db01cc)
i could create a workspace there.
On the other way around `File.iswritable() `does return wrong value for `C:\Program Files\myWorkspace` - programs can not write on `C:\Program Files` without admin privileges on my computer. This leads to
```
java.io.IOException: The folder "C:\Program Files\myWorkspace\.metadata" is read-only.
	at org.eclipse.osgi.internal.location.BasicLocation.lock(BasicLocation.java:226)
	at org.eclipse.osgi.internal.location.BasicLocation.lock(BasicLocation.java:199)
	at org.eclipse.ui.internal.ide.application.IDEApplication.checkInstanceLocation(IDEApplication.java:226)
```
So i don't know any reliant workaround. Maybe it is best to give user a warning that java thinks the folder would not be writable, but do not block the "launch" button in such situation.

**Comment by jukzi** [comment]
@Phillipus could you please test this change ASAP?

**Comment by Phillipus** [comment]
> @Phillipus could you please test this change ASAP?

Yep, I tried it with a network drive path like `\\Network_Drive\Stuff\eclipse` and also a mapped drive `Y:\eclipse` and got the warning text in the dialog and clicked "Launch" and it was fine.

**Comment by merks** [comment]
@Phillipus 

I **assume** that without this fix, both those would have prevented the workspace dialog from completing?

**Comment by Phillipus** [comment]
> @Phillipus
> 
> I **assume** that without this fix, both those would have prevented the workspace dialog from completing?

That's correct. The "Launch" button in the dialog is greyed out.

**Comment by merks** [comment]
So to me this argues very strongly in favor of merging the change.  It's well tested, the current state is clearly broken on Windows, and in the worst case the dialog allows one to try to use a workspace that really is read-only which will fail miserably though with no harm done. 

Here's another "fun" implementation for the test:

org.eclipse.osgi.storage.StorageUtil.canWrite(File, String)

**Comment by merks** [comment]
@jukzi 

Please feel free to merge when the PR is in good shape.  And THANKS for taking action!!

**Comment by andy1805** [comment]
many thanks to all for their fast and effective work. Really top :-)
