### ISSUE TITLE
IWorkbenchWindow.getShell.dispose will cause failure

### ISSUE THREAD

**Issue by natarol** [eclipse-platform/eclipse.platform.ui#224]
I found that after calling "IWorkbenchWindow.getShell.dispose", exiting "workbench" will not trigger the "IDEWorkbenchAdvisor.postShutdown()" and "WorkbenchListener"

**Comment by merks** [comment]
Why do you dispose the workbench window shell?

**Comment by natarol** [comment]
yes

**Comment by merks** [comment]
Yes is not an answer to the question.  **Why** do you this and expect it not to cause problem?  Have you tried to use IWorkbenchWindow.close()?

**Comment by natarol** [comment]
Sometimes I need to forcibly close the workbench window, but I lack such an API

"IWorkbenchWindow.getShell" is public, and the document does not say that it is not allowed to be used in this way. So I don't think calling this API is an error

> 2022年7月22日 上午1:33，Ed Merks ***@***.***> 写道：
> 
> Yes is not an answer to the question.  Why do you this and expect it not to cause problem? Have you tried to use IWorkbenchWindow.close()?

**Comment by merks** [comment]
There are methods such as these for that purpose:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/50c198705372a3ce4bffb34e8cda443ebf300853/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/IWorkbenchWindow.java#L60-L70

https://github.com/eclipse-platform/eclipse.platform.ui/blob/50c198705372a3ce4bffb34e8cda443ebf300853/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/IWorkbenchPage.java#L272-L282

**Comment by natarol** [comment]
What I need is to forcibly close the workbench window. In any case, it must be closed.

Your suggestion cannot do this

**Comment by natarol** [comment]
When I use PDE, I occasionally encounter such a problem: the editor is dirty, but it cannot be saved or closed.
So I'm afraid of similar problems in my RCP. I need a forced close as the final solution

The API you provided cannot solve my problem

**Comment by merks** [comment]
Then you should report a problem to PDE for how to reproduce that problem because disposing the shell is not going to ever be a clean way to exit the workbench.   I believe you can call org.eclipse.ui.IWorkbenchPage.closeEditor(IEditorPart, boolean) with false to close an editor even if it is dirty.

**Comment by natarol** [comment]
ok ,thank you

**Comment by natarol** [comment]
When I use PDE, I occasionally encounter such a problem: the editor is dirty, but it cannot be saved or closed.
So I'm afraid of similar problems in my RCP. I need a forced shutdown as the final solution
