### ISSUE TITLE
Invisible/Missing text in Problems view's Show menu

### ISSUE THREAD

**Issue by nlisker** [eclipse-platform/eclipse.platform.ui#2241]
Windows 10
Eclipse Version: 2024-06 (4.32) Build id: I20240601-0610

Theme: Dark/Light
Color and Font theme: Default

1. Open the Problems view
2. Click on the vertical `...`
3. Hover over Show

The menu will have invisible selectable and highlight-able options:
![image](https://github.com/user-attachments/assets/24d1dd56-0a3f-4197-93de-c0aa3be11af2)

![image](https://github.com/user-attachments/assets/a85d684c-5528-4a89-bc34-6f68c50c6e23)

**Comment by tomaswolf** [comment]
> Build id: I20240601-0610

That's a development build. My "Eclipse for Committers" shows for final 4.32 release "Build id: 20240606-1231". In that release I cannot reproduce this.

**Comment by nlisker** [comment]
https://download.eclipse.org/eclipse/downloads/drops4/R-4.32-202406010610/ shows the final release as 202406010610. Trying to update it from the release stream https://download.eclipse.org/eclipse/updates/4.32/ shows the same version.

**Comment by jukzi** [comment]
Can not reproduce:
![image](https://github.com/user-attachments/assets/1a964512-2d99-43fc-9177-664605a5c5c8)
Please add how to reproduce.

**Comment by nlisker** [comment]
Could it have been added by a plugin? Is there a way for me to debug this locally and see where the extra items are coming from?

**Comment by nlisker** [comment]
I narrowed it down to a settings file in the workspace: workspace\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.eclipse.ui.ide.prefs

The default one for a new workspace looks like this:
```
eclipse.preferences.version=1
platformState=585142530998296
quickStart=false
tipsAndTricks=true
```
The one in my workspace looks like this
```
IMPORT_FILES_AND_FOLDERS_MODE=prompt
IMPORT_FILES_AND_FOLDERS_RELATIVE=true
IMPORT_FILES_AND_FOLDERS_TYPE=23,1\:7,1
IMPORT_FILES_AND_FOLDERS_VIRTUAL_FOLDER_MODE=prompt
PROBLEMS_FILTERS_MIGRATE=true
SAVE_ALL_BEFORE_BUILD=true
TASKS_FILTERS_MIGRATE=true
eclipse.preferences.version=1
org.eclipse.ui.internal.views.markers.CachedMarkerBuilderorg.eclipse.ui.views.ProblemView=<?xml version\="1.0" encoding\="UTF-8"?>\r\n<filterGroups andFilters\="false" markerLimit\="100" markerLimitEnabled\="true">\r\n<filterGroup IMemento.internal.id\="Errors/Warnings on Project" enabled\="true" filterLimit\="-1" scope\="2" workingSet\="Aggregate for window 1480666682402">\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="6"/>\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\r\n</filterGroup>\r\n<filterGroup IMemento.internal.id\="Errors/Warnings on Selection" enabled\="false" filterLimit\="-1" scope\="2" workingSet\="Aggregate for window 1480666682402">\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="6"/>\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\r\n</filterGroup>\r\n<filterGroup IMemento.internal.id\="Warnings on Selection" enabled\="false" filterLimit\="-1" scope\="2" workingSet\="Aggregate for window 1480666682402">\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="2"/>\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\r\n</filterGroup>\r\n<filterGroup IMemento.internal.id\="All Errors on Workspace" enabled\="false" filterLimit\="-1" scope\="0" workingSet\="Aggregate for window 1480666682402">\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="4"/>\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\r\n</filterGroup>\r\n<filterGroup IMemento.internal.id\="All Errors" enabled\="false" filterLimit\="-1" name\="" scope\="0" workingSet\="Aggregate for window 1480666682402">\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="4"/>\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\r\n</filterGroup>\r\n</filterGroups>
org.eclipse.ui.internal.views.markers.CachedMarkerBuilderorg.eclipse.ui.views.TaskList=<?xml version\="1.0" encoding\="UTF-8"?>\r\n<filterGroups andFilters\="false" markerLimit\="100" markerLimitEnabled\="true">\r\n<filterGroup IMemento.internal.id\="TODOs" enabled\="true" filterLimit\="-1" scope\="2" workingSet\="Aggregate for window 1480666682402">\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.completionField" completion\="3"/>\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.priorityField" selectedPriorities\="7"/>\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.descriptionField" containsModifier\="CONTAINS" containsText\=""/>\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\r\n</filterGroup>\r\n</filterGroups>
platformState=585142530998296
quickStart=false
tipsAndTricks=true
```
The line with `ProblemView` is obviously the suspect, but I don't know what this does or why it's there.

**Comment by jukzi** [comment]
Did you try with a new workspace? Maybe you used some old workspace with a new eclipse version?
How about deleting that file so the standard settings are applied again.

**Comment by nlisker** [comment]
I wrote what the file looks like in a new workspace. That one does not have the extra invisible items. The one in my workspace has additions that comes from somewhere and it has the invisible items. The question is what causes that and what exactly in that files adds these faulty items. Is it a plugin? Is it a setting?

I tried with a clean Eclipse 4.33 and I see the same behavior with the above 2 files.

**Comment by jukzi** [comment]
i have no clue what made that file wrong. I suggest to lose the issue until you know how to reproduce that the file gets wrong.

**Comment by Phillipus** [comment]
I have similar entries in my `org.eclipse.ui.ide.prefs` file but there are no invisible items in the menu.

```
org.eclipse.ui.internal.views.markers.CachedMarkerBuilderorg.eclipse.ui.views.ProblemView=<?xml version\="1.0" encoding\="UTF-8"?>\n<filterGroups andFilters\="false" markerLimit\="120" markerLimitEnabled\="true">\n<filterGroup IMemento.internal.id\="org.eclipse.ui.ide.projectErrorsWarningsGrouping" enabled\="false" filterLimit\="-1" scope\="3" workingSet\="Aggregate for window 1696273340275">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="6"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n<filterGroup IMemento.internal.id\="org.eclipse.ui.ide.selectedErrorsWarningsGrouping" enabled\="false" filterLimit\="-1" scope\="2" workingSet\="Aggregate for window 1696273340275">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="6"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n<filterGroup IMemento.internal.id\="org.eclipse.ui.ide.selectedWarningsGrouping" enabled\="false" filterLimit\="-1" scope\="2" workingSet\="Aggregate for window 1696273340275">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="2"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n<filterGroup IMemento.internal.id\="org.eclipse.ui.ide.errorsFilter" enabled\="false" filterLimit\="-1" scope\="0" workingSet\="Aggregate for window 1696273340275">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="4"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n</filterGroups>
org.eclipse.ui.internal.views.markers.CachedMarkerBuilderorg.eclipse.ui.views.TaskList=<?xml version\="1.0" encoding\="UTF-8"?>\n<filterGroups andFilters\="false">\n<filterGroup IMemento.internal.id\="TODOs" enabled\="false" scope\="2" workingSet\="Aggregate for window 1254656427504">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.completionField" completion\="3"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.priorityField" selectedPriorities\="7"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.descriptionField" containsModifier\="CONTAINS" containsText\="TODO"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n</filterGroups>
```

**Comment by nlisker** [comment]
> I have similar entries in my `org.eclipse.ui.ide.prefs` file but there are no invisible items in the menu.
> 
> ```
> org.eclipse.ui.internal.views.markers.CachedMarkerBuilderorg.eclipse.ui.views.ProblemView=<?xml version\="1.0" encoding\="UTF-8"?>\n<filterGroups andFilters\="false" markerLimit\="120" markerLimitEnabled\="true">\n<filterGroup IMemento.internal.id\="org.eclipse.ui.ide.projectErrorsWarningsGrouping" enabled\="false" filterLimit\="-1" scope\="3" workingSet\="Aggregate for window 1696273340275">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="6"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n<filterGroup IMemento.internal.id\="org.eclipse.ui.ide.selectedErrorsWarningsGrouping" enabled\="false" filterLimit\="-1" scope\="2" workingSet\="Aggregate for window 1696273340275">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="6"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n<filterGroup IMemento.internal.id\="org.eclipse.ui.ide.selectedWarningsGrouping" enabled\="false" filterLimit\="-1" scope\="2" workingSet\="Aggregate for window 1696273340275">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="2"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n<filterGroup IMemento.internal.id\="org.eclipse.ui.ide.errorsFilter" enabled\="false" filterLimit\="-1" scope\="0" workingSet\="Aggregate for window 1696273340275">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="4"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n</filterGroups>
> org.eclipse.ui.internal.views.markers.CachedMarkerBuilderorg.eclipse.ui.views.TaskList=<?xml version\="1.0" encoding\="UTF-8"?>\n<filterGroups andFilters\="false">\n<filterGroup IMemento.internal.id\="TODOs" enabled\="false" scope\="2" workingSet\="Aggregate for window 1254656427504">\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.completionField" completion\="3"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.priorityField" selectedPriorities\="7"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.descriptionField" containsModifier\="CONTAINS" containsText\="TODO"/>\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\n</filterGroup>\n</filterGroups>
> ```

Interesting. I have checked a couple of times: if I replace the default file with the one I have, the invisible items appear, then if I restore the original file, they disappear. It surely has to do with it. Perhaps there is another interacting component, but I used a clean 4.33 version. I can even create a video showing this if it will help.

**Comment by Phillipus** [comment]
@nlisker Did you try deleting that problem line in the prefs file, re-starting Eclipse and seeing if the invisible items are gone? Maybe the line has some legacy stuff in it?

**Comment by Phillipus** [comment]
I copied and pasted your problem line into my prefs file and I can see the blank menu items, so I would say to delete that line.

**Comment by Phillipus** [comment]
Actually, open up the "Filters.." dialog from the Problems view and you'll see you have some custom filters that have no names. Simply delete them in the dialog.

**Comment by nlisker** [comment]
Thanks @Phillipus, I delete the filters. I compared the modified file and this chunk was removed:
```
IMemento.internal.id\="org.eclipse.ui.ide.markerType"/>\r\n</filterGroup>\r\n<filterGroup IMemento.internal.id\="All Errors" enabled\="false" filterLimit\="-1" name\="" scope\="0" workingSet\="Aggregate for window 1480666682402">\r\n<fieldFilter IMemento.internal.id\="org.eclipse.ui.ide.severityAndDescriptionField" containsModifier\="CONTAINS" containsText\="" selectedSeverities\="4"/>\r\n<fieldFilter
```
Don't know what added them, but I think this issue can be closed as it's not a UI issue.
