### ISSUE TITLE
Find/replace overlay: logs NPE

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-platform/eclipse.platform.ui#2244]
I repeatedly get NPEs in the log when using the find/replace overlay on Linux (X11), (XFCE / Xubuntu 22.04)

```
!ENTRY org.eclipse.ui 4 0 2024-09-05 10:39:45.524
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Shell.getDisplay()" because the return value of "org.eclipse.ui.internal.findandreplace.overlay.FindReplaceOverlay.getShell()" is null
	at org.eclipse.ui.internal.findandreplace.overlay.FindReplaceOverlay.updatePlacementAndVisibility(FindReplaceOverlay.java:848)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
```

They are all the same, getShell() retuning null at this line:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/31a902749e53ae095fb98c40459ba8cfc70d6d0d/bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/internal/findandreplace/overlay/FindReplaceOverlay.java#L848

I don't have a way to reliably reproduce, but it seems to happen when focus is coming in to the IDE.

Note that the test on the line above is `true` if `getShell() == null`:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/31a902749e53ae095fb98c40459ba8cfc70d6d0d/bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/internal/findandreplace/overlay/FindReplaceOverlay.java#L847-L848

https://github.com/eclipse-platform/eclipse.platform.ui/blob/31a902749e53ae095fb98c40459ba8cfc70d6d0d/bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/internal/findandreplace/overlay/FindReplaceOverlay.java#L882-L887

**Comment by jonahgraham** [comment]
PS This was tested with the Eclipse IDE for C/C++ Developers 2024-09 RC2, its not published yet, but will be soon as I found this issue while doing my smoke tests of the EPP builds.

**Comment by HeikoKlare** [comment]
I cannot reproduce the bug on Windows, but that's somehow expected as most of the asynchronous execution are only necessary for specific GTK behavior anyway. Can you confirm that this "only" results in log entries but not in unexpected, user-perceivable behavior, @jonahgraham?

The posted code is definitely incorrect, as it inconsistently handles `getShell()` being null. An additional issue is a broken contract of `Window.getShell()`. It says:
```
/**
 * Returns this window's shell.
 *
 * @return this window's shell, or <code>null</code> if this window's
 *         shell has not been created yet
 */
```

From my current understanding, the NPEs do not occur in the situation in which the shell has not been created yet, but in a situation in which the Window has been closed. And in that case `getShell()` also returns null, even though the contract does not state this.

**Comment by jonahgraham** [comment]
> Can you confirm that this "only" results in log entries but not in unexpected, user-perceivable behavior

Yes, I can confirm it is "only" in the logs.
