### ISSUE TITLE
Previous Perspective lost when restarting IDE 2024-09 version 4.33

### ISSUE THREAD

**Issue by minduch** [eclipse-platform/eclipse.platform.ui#2263]
Using any Eclipse IDE installation type (Java/Committer/RCP/etc), the last used Perspective is not restored upon IDE startup. This happens in Eclipse 2024-09 GA (did not happen in M1/M"/M3, RC1 = I'm not sure).

This is quite annoying and confuses the user.

To reproduce, just open e.g. a Java project, set the Java Perspective. Stop and restart IDE. The Perspective is now set to some "generic" perspective and the Package Explorer is not present. Toggling manually to the Java Perspective fixes the issue.

**Comment by jukzi** [comment]
could not reproduce with
https://www.eclipse.org/downloads/download.php?file=/oomph/epp/2024-09/R/eclipse-inst-jre-win64.exe&mirror_id=1190

be sure that your workspace path does not contain any non ascii character like space

**Comment by minduch** [comment]
Hi, I found the problem: it's the AI code assistant plugin "Tabnine" that causes this problem. They have been informed about this issue. Please close this case, and I'm sorry for have taken up your time.
