### ISSUE TITLE
Regression: 4.33 Install New Software ignores content of a "work with" ZIP

### ISSUE THREAD

**Issue by ewillink** [eclipse-platform/eclipse.platform.ui#2265]
Version: 2024-09 (4.33)
Build id: I20240903-0240

Unzip eclipse-SDK-4.33-win32-x86_64.zip
Start Eclipse
Help->Install New Software...
   works with EMF-Updates-2.39.0.zip
Select
   EMF - Eclipse Modeling Framework SDK	2.39.0.v20240731-0952
   XSD - XML Schema Definition SDK	2.37.0.v20240604-0832
(Contact all update sites checked by default)
Finish
... really slow
Click on Progress View animation
- shows that numerous JARs that are available in the local EMF-Updates-2.39.0.zip are instead/also fetched from a 2024-09 releases mirror.

The regression is that only missing Jars such as org.apache... should be fetched from a releases mirror. The content of the "works with" ZIP should be used whenever possible.

**Comment by jukzi** [comment]
![image](https://github.com/user-attachments/assets/c28b627b-a77f-42a0-9977-5c076e7bb676)
https://www.eclipse.org/downloads/download.php?file=/modeling/emf/emf/builds/release/2.39.0/EMF-Updates-2.39.0.zip
![image](https://github.com/user-attachments/assets/2a9d3922-52e4-4dc1-beda-23bb9c9665e9)
![image](https://github.com/user-attachments/assets/3900afbe-5dc5-46dd-890f-b46d64cd5eb0)
![image](https://github.com/user-attachments/assets/2a1646f4-2f66-4b24-8223-dbefa70bfb16)

> ... really slow

took << 1min for me

**Comment by ewillink** [comment]
Your images are different since presumably you are upgrading with EMF already installed. I started from eclipse-SDK-4.33-win32-x86_64.zip.

**Comment by jukzi** [comment]
i suggest you add more information like screenshots and which file exactly is wrongly downloaded.

**Comment by ewillink** [comment]
Every zip I install is really slow because 100s if not 1000s of jars are redundantly loaded from the net which for me is not fast.

**Comment by merks** [comment]
I'm a bit doubtful about regression, especially given nothing changing substantially during the most recent release cycle.  Anyway, in the debugger I see it processing the artifact repositories in this order:

![image](https://github.com/user-attachments/assets/392ad697-779f-482d-b5c4-1572bd551b3e)

The order is determined by this:

![image](https://github.com/user-attachments/assets/7c5e4267-0e5d-481b-992b-e6cef7c69be3)

And if you look at the comparator you'll notice it doesn't consider `jar:file:` as a local:

![image](https://github.com/user-attachments/assets/f367b8e2-d714-4bc8-a604-a4e89c58b908)

But then it never has though it probably should.

**Comment by merks** [comment]
Processing the repositories in this order would definitely be better:

![image](https://github.com/user-attachments/assets/6198faa4-da5f-45ab-a098-dde05f5382ca)

**Comment by ewillink** [comment]
I just tried to verify the regression by comparing 4.33 with 4.26; both normal speed (30 seconds) 4.33 slightly slower because of the extra PGP trust dialog. Perhaps I was having a really bad Internet day when I reported. Perhaps the repository order is unstable and so I had a bad order then and Ed's better order now.

**Comment by merks** [comment]
Yes, I don't think it's a regression.  I think it's possible the repo order might be arbitrarily different before in difference places such that sometimes the jar was first and sometime not. 

In any case, you could dramatically improve performance in general, even for jar:file: by unzipping the jar and using a file: URI for the folder location.
