### ISSUE TITLE
Find/Replace Overlay: intuitive key to enter replace field

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#2293]
currently TAB cycles through all the search options
and  SHIFT-TAB cycles through all the replace options

I just want to TAB to go to `replace` as it was in old replace dialog
I found i could use - CTRL+R but that is unintuitive for a very common usecase

**Comment by HeikoKlare** [comment]
Totally agree on this. I think it reflects the same issue as #2161. Can we close this as duplicate?
