### ISSUE TITLE
Eclipse GitHub integration in SDK setup?

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#23]
There is a

>     Eclipse GitHub integration with task focused interface	6.1.0.202203080745-r

now we have migrated many (all?) projects to github it might be a good idea to have this installed by default, @merks ?

Its description says: Integration with GitHub this seems to be the description page: https://wiki.eclipse.org/EGit/GitHub/User_Guide

**Comment by akurtakov** [comment]
This is Mylyn based plugin and Mylyn (except Wikitext) is dead project https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/commit/?id=fadb9deb14c86da37d2b0b29026f7faf9201ba09 . So most probably this would be gone from EGit or will have to be rewritten.

**Comment by merks** [comment]
Yes, Mylyn is not keeping up with the times so this not a good dependency to add I think.

**Comment by laeubi** [comment]
Alright I just was curious as there is an explicit "Gihub" component at EGit but this seems something historical then...

**Comment by vogella** [comment]
Latest EGit supports PR integration (Ctrl+3 - Fetch Github PullRequest). The name of the branch is unfortunately not the same as the source branch for the PR, which is due to limitations in the GH API.
