### ISSUE TITLE
Eclipse file search results show only when search process has completed

### ISSUE THREAD

**Issue by alongolom** [eclipse-platform/eclipse.platform.ui#231]
In the past the file search results have been displayed in the midst of the search process. 
We have moved to a new workspace using oomph and currently the results do not show up during the search process, but only at the end of it.
This issue results long waiting times for results when searching the entire project files.

**Comment by iloveeclipse** [comment]
@alongolom : which Eclipse version are you using?

@jukzi : could you please check if that is related to any of the recent search changes?

**Comment by jukzi** [comment]
i did solve that problem with [my recent changes.](https://github.com/eclipse-platform/eclipse.platform.text/pull/30)
