### ISSUE TITLE
Add dropdown history to the "in" field of the Quick Search dialog window

### ISSUE THREAD

**Issue by mplukas** [eclipse-platform/eclipse.platform.ui#2329]
It would be very helpful if the Quick Search dialog window (Ctrl+Alt+Shift+L) kept a [short] history of the values used in the **"in"** field and allowed to select from it (similar like "File name patterns" field in the regular Search window (Ctrl+H)).

**Comment by jukzi** [comment]
Will you contribute such PR?

**Comment by Wittmaxi** [comment]
Hey, you might want to look into the HistoryTextWrapper class. By re-using it, implementing this should be ~very easy~ doable.
The plan: replace the input box in the quick search with that HistoryTextWrapper class or something similar.

**Comment by PValdovinos** [comment]
I'm working on this :)

**Comment by HannesWell** [comment]
> I'm working on this :)

Great. You are one of the students from CodeDays, aren't you?

Much success on this task and don't hesitate to ask for help if you need any.

**Comment by jannisCode** [comment]
Because I did not hear anything anymore and did not know if this is still worked on, I implemented the feature here:
https://github.com/eclipse-platform/eclipse.platform.ui/pull/2541
@HannesWell @Wittmaxi @jukzi Would you like to take a look at the new PR? 😅

**Comment by jukzi** [comment]
> I'm working on this :)

@PValdovinos are you still working on this?
