### ISSUE TITLE
Plugin demo export error

### ISSUE THREAD

**Issue by TigerGod** [eclipse-platform/eclipse.platform.ui#2336]
I created a new plugin demo and then chose to export it directly, but this problem occurs. Here is the error log.
The export screen didn't disappear when I clicked the finish button on the export screen, it just flickered, hence the error log. This is the latest version of eclipse:
Version: 2024-09 (4.33.0)
Build id: 20240905-0614
![image](https://github.com/user-attachments/assets/a932e9f6-2baf-45bb-b4c6-ea162389d3ef)

**Comment by TigerGod** [comment]
and the launching part is empty
![image](https://github.com/user-attachments/assets/cd9cd3de-8d7f-4524-b90a-05f0d25c9a8d)

**Comment by akurtakov** [comment]
This is PDE problem. Platform can't do anything for that. Github doesn't allow moving issues between organization thus create a new one at https://github.com/eclipse-pde/eclipse.pde . 
Also please describe the exact steps you did so it's clear how to reproduce.
As a last thing, this functionality relies on pde.build which is in deep maintenance mode (https://github.com/eclipse-pde/eclipse.pde/blob/master/build/README.md) so it's recommended you use another tool to build (e.g. Tycho) .

**Comment by TigerGod** [comment]
thank you!
