### ISSUE TITLE
Find/replace overlay:  wrong position and inwindow-mobement

### ISSUE THREAD

**Issue by stbischof** [eclipse-platform/eclipse.platform.ui#2392]
## Steps to reproduce

From a fresh installation and clean workspace:

* Create Project
* create File

I tried

* Ctrl +F

I expected: overlay over right upper corner

But got: on other place more middle and funny movements

## Here is some relevant log output

no logfile `<workspace>/.metadata/.log`

## Tested under this environment:
* OS & version: Fedora Silverblue
* Eclipse IDE/Platform version (as shown in *Help > About*):
Eclipse Platform
Version: 2024-12 (4.34)
Build id: I20241010-1800
* ...Anything else that can be useful...

[Jdt](https://github.com/user-attachments/assets/c79044cf-96ee-4ab0-9cdf-d81742ad7716)

[latest integration](https://github.com/user-attachments/assets/535b533a-db57-4f7a-9164-5ab4d86d3f2d)

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HeikoKlare** [comment]
Thank you for reporting. This is a known bug when using Linux with Wayland. It is documented here: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1447

A fix has been merged just today (#2254), so the issue should be resolved in integration builds starting from tomorrow. I will thus close this issue as already fixed. If you still face the issue after the fix or you find any other/new issues after it, please reopen this issue or create a new one.
