### ISSUE TITLE
Find/replace overlay: active overlay breaks Ctrl+PageDown/PageUp navigation

### ISSUE THREAD

**Issue by ronso0** [eclipse-platform/eclipse.platform.ui#2397]
* have a few editor tabs open
* open Find/replace in one of them
* (Ctrl+PageUp/Down not usable as long as Find/replace has keyboard focus)
* a) make sure editor has focus and switch with Ctrl+PageUp/Down, or
* b) switch to another tab by clicking its header
* ...
* cycle tabs with Ctrl+PageUp/Down
* = as soon as tab with Find/replace is activated Find/replace catches focus again and prevents further switching

Not sure if this related to #1951 or already tracked by some other issue (no hits for PageUp or PageDown)

Eclipse 2024-09 (4.33.0)
Build id: 20240905-0614

**Comment by HeikoKlare** [comment]
Thank you for reporting this. I am not aware of any other issue that may cover this, but this is actually somehow "expected" (from a technical perspective, not from a user-experience perspective) with the existing implementation: the find/replace overlay is realized as a dialog window, so shortcuts will only affect that dialog but not the parent workbench window. I agree that from a user perspective, the described behavior is expexted.

This behavior has changed/improved with #2254, which has been merged last week. Now the overlay is integrated into the workbench window and many shortcuts for the workbench will still be processed when the overlay has focus. This also applies to Ctrl+PageUp/PageDown. This recording shows the new behavior:
![findreplace_switch_tab](https://github.com/user-attachments/assets/380e09e8-7565-49bd-a76c-07a147814fd8)

So with recent I-Builds, the reported issue should be fixed. I will therefore close this issue as already fixed. In case you still face the issue or find other or similiar issues, please reopen this ticket or create a new one.

**Comment by ronso0** [comment]
Thank you very much!

So, for testing CDT, where would I get an I-build?
Found this https://download.eclipse.org/eclipse/downloads/drops4/I20241013-1800/ but looks worng, doesn't mention CDT anywhere.

**Comment by HeikoKlare** [comment]
I have to admit that I am not sure how to properly set up a C++/CDT IDE based on the current build artifacts from latest I-Build.
I would try to use an Oomph setup for CDT development, as explained on the contributing page: https://github.com/eclipse-cdt/cdt/blob/main/CONTRIBUTING.md

Maybe @jonahgraham can give a hint here?

**Comment by jonahgraham** [comment]
> So, for testing CDT, where would I get an I-build?
> Found this https://download.eclipse.org/eclipse/downloads/drops4/I20241013-1800/ but looks worng, doesn't mention CDT anywhere.

@ronso0 to test with CDT, install the I-build of the Eclipse Platform (the link you shared is correct). That is the I-build, from there you can install other components (like CDT) using the standard install new software flow.

If you additionally want to checkout CDT's sources, you can follow the contributing link that @HeikoKlare shared. That will give you CDT's sources running on the latest I-build of Eclipse Platform.

Let me know if you need anything else.
