### ISSUE TITLE
Why is WizardDialog so hard coded to SWT.APPLICATION_MODAL ?

### ISSUE THREAD

**Issue by jcompagner** [eclipse-platform/eclipse.platform.ui#242]
if i look at the code i see this:

```
	private static int getShellModality(boolean modal) {
		return modal ? SWT.APPLICATION_MODAL : SWT.NONE;
	}
```

which is called in the constructor, also i see this:

```
	public WizardDialog setModal(boolean modal) {
		setShellStyle(getShellStyle() & ~SWT.APPLICATION_MODAL | getShellModality(modal));
		return this;
	}
```

and

```
	public boolean isModal() {
		return (getShellStyle() & SWT.APPLICATION_MODAL) == SWT.APPLICATION_MODAL;
	}
```

but i don't want our wizard dialogs to be application modal but SWT.PRIMARY_MODAL 
because they only should block the window that triggers them, there parent, not other windows. those can be completely different things.

But it is now so hard coded even if we just override it like overwriting setShellStyle then it kind of breaks isModal()

it would be very nice if there was a static? global var:

public static int DEFAULT_MODAL_STYLE = SWT.APPLICATION_MODAL;

and getShellModality would return that.
that by the start of the application we could do WizardDialog.DEFAULT_MODAL_STYLE  = SWT.PRIMARY_MODAL

and all of them would then work this way

i think isModal should be something like

```
	public boolean isModal() {
		return (getShellStyle() & SWT.APPLICATION_MODAL) == SWT.APPLICATION_MODAL ||
                            (getShellStyle() & SWT.PRIMARY_MODAL) == SWT.PRIMARY_MODAL;
	}
```

**Comment by vogella** [comment]
Pull request to improve this is welcome

**Comment by vogella** [comment]
I think using SWT.PRIMARY_MODAL would be fine. Please provide PR

**Comment by jcompagner** [comment]
so you mean just as the default? 

Then it would be a behavior change for some if people do have multiply windows in eclipse right? Then opening a wizard in one will not block the other anymore

But that would be an easy patch (just search replace SWT.APPLICATION_MODAL with SWT.PRIMARY_MODAL)

**Comment by vogella** [comment]
Yes as default. Current behaviour sounds not desirable. Please provide PR

**Comment by laeubi** [comment]
> just search replace SWT.APPLICATION_MODAL with SWT.PRIMARY_MODAL

I think the "isModal" should better then be used to check any of the modal flags?

**Comment by jcompagner** [comment]
> > just search replace SWT.APPLICATION_MODAL with SWT.PRIMARY_MODAL
> 
> I think the "isModal" should better then be used to check any of the modal flags?

yes that is better i think, then isModal makes more sense,

**Comment by merks** [comment]
Note too that the word is "modal" and that "model" is a different thing...  😃

**Comment by laeubi** [comment]
This think this now causes regressions as dialogs are no more getting default focus anymore:

Eclipse SDK
Version: 2023-03 (4.27)
Build id: I20221214-0610
OS: Linux, v.4.19.0-17-amd64, x86_64 / gtk 3.24.5
Java vendor: Oracle Corporation
Java runtime version: 17.0.2+8-86
Java version: 17.0.2

I start the Eclipse-IDE then STRG+SHIFT+T to search for a type and start to type but nothing happens because the focus is "somewhere" and one has to click on the dialog first.

I noticed this for other dialogs as well so probably a more general problem.

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/502 & https://github.com/eclipse-platform/eclipse.platform.swt/pull/503 and just use latest nightly build.

**Comment by iloveeclipse** [comment]
For the record: this caused regression on Windows/Mac, see https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/557
