### ISSUE TITLE
API errors on org.eclipse.ui.editors and org.eclipse.ui.workbench.texteditor

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#2430]
Regression from commit 9bd3284d67ef8703bb29453a12dca20520a96c61 / https://github.com/eclipse-platform/eclipse.platform.ui/pull/2400

- New constant was added in `AbstractDecoratedTextEditorPreferenceConstants` API (`org.eclipse.ui.editors`)
- New method was added to `SourceViewerDecorationSupport` (`org.eclipse.ui.workbench.texteditor`)

In both cases minor segment version should have been updated. Interestingly, no checks failed...

I will push updated manifests.

**Comment by akurtakov** [comment]
Maybe api tools are not "enabled" in/for some bundle?

**Comment by iloveeclipse** [comment]
> Maybe api tools are not "enabled" in/for some bundle?

But for *both* bundles? 
I don't see pom in the related bundles, where are the API settings are taken from? Parent pom? I don't see any mention of API tooling there too, so I assume it should enabled by default?

**Comment by merks** [comment]
The my Eclipse SDK IDE today after a pull shows these errors today:

![image](https://github.com/user-attachments/assets/87648e60-b016-4ef4-88b6-96ace689d4f7)

**Comment by iloveeclipse** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/2431.

Once merged, I will trigger I build, also for https://github.com/eclipse-jdt/eclipse.jdt.core/issues/3125.

**Comment by akurtakov** [comment]
I was more thinking about .settings/.project configs. But now that I looked more into it - these are split packages so my gut feeling is that API tools fails thanks to that.
