### ISSUE TITLE
"Colors and Fonts" Preview useless

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#247]
Of all those ~30 configurations only 3 are actually used in the Preview (WIN 10):
![image](https://user-images.githubusercontent.com/51790620/182827834-6be7ced8-9668-4fc8-a8f8-c24001a8f9cf.png)

**Comment by mickaelistria** [comment]
I believe those are shown here because they're declared in https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.themes/css/dark/e4-dark_ide_colorextensions.css .

**Comment by vogella** [comment]
Yes, they are defined via CSS (and not considered in the preview). We can remove unused colors from https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.themes/css/dark/e4-dark_ide_colorextensions.css, I assume over the years, multiple colors must have been obsolete by now.

**Comment by vogella** [comment]
Closing as the display of the colors is correct as they are defines via CSS, only preview does not consider them. Follow-ups could be to clean up the colors which are not used anymore
