### ISSUE TITLE
NLS for "Enable theming" preference missing

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform.ui#2480]
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

* open the preferences
* go to General -> Appearance
* see the first entry:
![{F854E0E3-03E5-44C2-8668-C57CFF0ADD56}](https://github.com/user-attachments/assets/f3573584-216e-4c91-bf30-e607dda755e5)

## Here is some relevant log output

```
Warning: NLS missing message: ThemingEnabled in: org.eclipse.ui.internal.messages
```

## Tested under this environment:
* OS & version: Windows 11
* Eclipse IDE/Platform version (as shown in *Help > About*): Eclipse SDK I20241031-1800

## Reason
This is a regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/2224
The messages file was changed, removing a necessary whitespace at the end of the line preceding the one with the missing NLS
![{8EB93999-04D5-43CF-9159-AB7E730959BA}](https://github.com/user-attachments/assets/464c5ed1-71fc-49a5-94da-615357577d25)

## Community

- [x ] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by BeckerWdf** [comment]
@HeikoKlare: Thanks for fixing.
