### ISSUE TITLE
Paste into find overlay control does not work in multipage editor (manifest.mf, plugin.xml)

### ISSUE THREAD

**Issue by tobiasmelcher** [eclipse-platform/eclipse.platform.ui#2509]
- [X] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/) - I downloaded eclipse-SDK-I20241107-1800-win32-x86_64

## Steps to reproduce

From a fresh installation and clean workspace:

* import an eclipse plugin project
* open a MANIFEST.MF file
* select the word "qualifier" in the text editor and press CTRL-C to copy the text into the clipboard
* select another word in the text editor, e.g. "plugin"
* press CTRL-F to open the new find overlay control shown inplace of the text editor. The word "plugin" is taken over in the find overlay which is correct. I expect that the find overlay control now has the focus.
* now press CTRL-V to paste "qualifier" into the find overly search control -> this is currently not the case, the word "qualifier" from the clipboard is pasted into the text editor and not into the find overlay

The same steps work fine in the Java source editor, but not in a multipage editor containing a text editor as page.
Screencast:

https://github.com/user-attachments/assets/3613e358-09ee-4002-b89e-1074be1a9ff0

## Tested under this environment:
* OS & version: Windows
* Eclipse IDE/Platform version (as shown in *Help > About*): ...
* eclipse-SDK-I20241107-1800-win32-x86_64

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by HeikoKlare** [comment]
Additional information: this also happens in other editors (like Java source code editor) when pasting into the replace input field.

**Comment by HeikoKlare** [comment]
Fixed via:
- #2516

I used a wrong tag, so that this issue was not auto-closed by merging that PR.

**Comment by tobiasmelcher** [comment]
Thanks a lot. Fix is also working fine in the Abap Development Tools source editors.
