### ISSUE TITLE
Multiple tests failures in I-Build I20241113-0600

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#2517]
~There are 409 failed tests in yesterday's I-BUILD: https://download.eclipse.org/eclipse/downloads/drops4/I20241113-1800/testresults/html/org.eclipse.ui.tests_ep434I-unit-win32-x86_64-java17_win32.win32.x86_64_17.html~

EDIT: it happened even sooner: https://download.eclipse.org/eclipse/downloads/drops4/I20241113-0600/testresults/html/org.eclipse.ui.tests_ep434I-unit-win32-x86_64-java17_win32.win32.x86_64_17.html

Many of them fail with `No more handles`.

~I'm reporting it here because the tests belong to `ui.test` but this seems to be an SWT problem so the issue might be moved later.~
EDIT 2: it seems to be the exact same problem that we had a few weeks ago [helpdesk#5214](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5214)

**Comment by fedejeanne** [comment]
cc @HeikoKlare , @akoch-yatta , @amartya4256 , @ShahzaibIbrahim

**Comment by fedejeanne** [comment]
Any chance this has something to do with https://github.com/eclipse-platform/eclipse.platform.swt/pull/1590 @akoch-yatta ?

**Comment by HeikoKlare** [comment]
> Any chance this has something to do with [eclipse-platform/eclipse.platform.swt#1590](https://github.com/eclipse-platform/eclipse.platform.swt/pull/1590) @akoch-yatta ?

I do not see any chance for a relation to this.

Isn't this an infrastructural issue? It looks like the same as some weeks ago: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1486
See the M2 results for comparison: https://download.eclipse.org/eclipse/downloads/drops4/S-4.34M2-202410172140/testResults.php

Can you create a helpdesk issue for this?

**Comment by fedejeanne** [comment]
Thank you for the hint, I left a comment in the existing issue since it seems to be the exact same problem: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/5214#note_2855852.

I also changed the title of this issue since the tests failed even sooner (in I20241113-**0600**), which rules out https://github.com/eclipse-platform/eclipse.platform.swt/pull/1590 as the possible cause.

**Comment by fedejeanne** [comment]
Re-spinning the last I-BUILD --> https://ci.eclipse.org/releng/job/AutomatedTests/job/ep434I-unit-win32-x86_64-java17/40/

**Comment by fedejeanne** [comment]
The fix worked (see Help Desk issue)
