### ISSUE TITLE
DataFormatException with badColor3

### ISSUE THREAD

**Issue by opcoach** [eclipse-platform/eclipse.platform.ui#2521]
Let's make sure issue is not already fixed in latest builds first.

- [X] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation and clean workspace:

Install the setup of 'platform ui' by dragging the setup link in the banner of the installer : see   [Setting your environment](https://github.com/eclipse-ide/.github/blob/main/CONTRIBUTING.md)   and [projects guide](https://github.com/eclipse-ide/.github/blob/main/projects.md)

Set a breakpoint in StringConverter line 568 (on the throw DataFormatException of asRGB(String) ) : 

![image](https://github.com/user-attachments/assets/54bb79b4-5c77-462e-af05-9bbd152f9c7f)

Launch with all the plugins and hit the breakpoint. 

The value received is 0,0, 1x which is not compliant with the format expected by StringConverter. Should be 0,0,1 or something with 3 Integers. 

If you go up in the stack trace, you will see that it concerns the color definition 'badColor3'. 

## Tested under this environment:
* OS & version: macOS X 15.1 (sequoia). 
* Eclipse IDE/Platform version (as shown in *Help > About*): Version: 2024-12 (4.34) Build id: I20241117-1800 (got from the platform.ui current setup).

## Community

- [X] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by opcoach** [comment]
Here is the stack trace : 

!ENTRY org.eclipse.ui 2 2 2024-11-18 15:04:13.529
!MESSAGE Could not parse value for theme color badColor3
!STACK 0
org.eclipse.jface.resource.DataFormatException: For input string: "1x"
	at org.eclipse.jface.resource.StringConverter.asRGB(StringConverter.java:568)
	at org.eclipse.ui.themes.ColorUtil.getColorValue(ColorUtil.java:159)
	at org.eclipse.ui.internal.themes.ColorDefinition.getValue(ColorDefinition.java:111)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.installColor(ThemeElementHelper.java:272)
	at org.eclipse.ui.internal.themes.ThemeElementHelper.populateRegistry(ThemeElementHelper.java:181)
	at org.eclipse.ui.internal.Workbench$22.runWithException(Workbench.java:1844)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:35

**Comment by vogella** [comment]
IIRC this is input for  a test case which tests that this exception is thrown. The variable "badColor3" also seems to describe that this is by intention.

**Comment by merks** [comment]
Yes, if you include test bundles in your launch and those intentionally include errors, you should expect this such a problem:

![image](https://github.com/user-attachments/assets/26ceb163-4f0b-42ff-8853-3ca18ac941b1)

This why the setup creates a launcher with meaningful features that do not include tests:

![image](https://github.com/user-attachments/assets/b555c6dc-c11f-4e2f-ae7e-84500bc97ffe)

So I think the "launch with all the plugins" is not generally a good idea and will generally create strange things, e.g., contributions in the UI that are intended only be to be used in UI tests.

**Comment by HannesWell** [comment]
> So I think the "launch with all the plugins" is not generally a good idea and will generally create strange things, e.g., contributions in the UI that are intended only be to be used in UI tests.

Yes. That's why I usually start an Eclipse app based on features that contains e.g. only `org.eclipse.sdk` and automatically includes all dependencies. Unfortunately it's a bit more difficult for tests.

**Comment by opcoach** [comment]
Ok, I see. The variable should be named badColor3OnlyUsedForTest... 

This lead to use only well configured launch configuration so as to avoid to do such mistakes. 

I will close this issue in this case.
