### ISSUE TITLE
Enable code mining for method references by default

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#2524]
Code minings in Eclipse are hard to discover for users, other IDEs enable (some) of them by default, hence making it obvious that they have it. In a recent workshop my clients were really surprised that the Eclipse IDE also has these.

I setting which I find useful and non-disruptive is the display of a method usage on top of methods.

![image](https://github.com/user-attachments/assets/da78afea-e0c3-49b9-ab96-7786ec158aee)

Maybe we should enable this by default? This would signal to the user that we also support this.

cc @HannesWell @HeikoKlare @mickaelistria

**Comment by BeckerWdf** [comment]
Isn't this a JDT setting? If yes this issue should be opened on the JDT project not platform.

**Comment by vogella** [comment]
True, moved to https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1802
