### ISSUE TITLE
Eclipse Hover loses control in certain cases

### ISSUE THREAD

**Issue by mehmet-karaman** [eclipse-platform/eclipse.platform.ui#2534]
## Steps to reproduce

From a fresh installation and clean workspace:
* Create a new Java Project and open a java class in the java editor
* Move the mouse to a place where the hover shows up. (eg. Class head and hover on the class name) 
* Double click on the Hover
* Minimize the Eclipse window and show it back.
* Move any other applications window to the foreground
* The hover is still visible above the foreign windows 

## I expected: 
The Sticky hover shouldn't be visible (closed when focus is lost)

## But got: 
Sticky hover is still there

## Tested with Eclipse Version:
Version: 2024-12 (4.34)
Build id: I20241022-1800

## Here is a video recorded in windows:
https://github.com/user-attachments/assets/2eb51c05-caee-4256-8b9b-72c78492a991

**Comment by iloveeclipse** [comment]
Reproducible with latest 4.34 RC2 on RHEL 9.2 too, so this is not Windows specific.

**Comment by mehmet-karaman** [comment]
The PR Was merged, so we can close this bug ticket now.

PR: https://github.com/eclipse-platform/eclipse.platform.ui/pull/2540
