### ISSUE TITLE
Toolbar icons in inactive tab have incorrect background

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#2552]
This is a long outstanding issue and unfortunately it is still present in the new Dark theme from https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114

The toolbar icons in inactive tab have incorrect background

![image](https://github.com/user-attachments/assets/03b35c82-4f08-40a7-a3ff-d9847e4e95da)

@mvm-sap can you have a look at this?

**Comment by mvm-sap** [comment]
@vogella is this MAC ?

**Comment by vogella** [comment]
> @vogella is this MAC ?

This is an Ubuntu system

**Comment by mvm-sap** [comment]
> > @vogella is this MAC ?
> 
> This is an Ubuntu system

Sure. Will have a look at it.

**Comment by mvm-sap** [comment]
@vogella this issue should be solved with the dark theme changes https://github.com/eclipse-platform/eclipse.platform.ui/pull/2548

**Comment by vogella** [comment]
Yes @mvm-sap looks really good with https://github.com/eclipse-platform/eclipse.platform.ui/pull/2548 

Thanks a bunch that issue was really annoying.
