### ISSUE TITLE
Dark theme - Reduce colors in form based editor

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#2555]
IMHO we should use less colors in the new dark theme https://github.com/eclipse-platform/eclipse.platform.ui/issues/2114 in form based editors. For example in the MANIFEST.MF editor.

![image](https://github.com/user-attachments/assets/e6bf6146-9e83-4cda-94cc-58493b23ec77)

@BeckerWdf @mvm-sap @thomasritter WDYT?

**Comment by vogella** [comment]
Areas for improvement:

Dark spacing between elements (marked in the screenshot):

![image](https://github.com/user-attachments/assets/39f08750-d4d7-4f3d-8e66-84ac01d2cd18)

Form header background

![image](https://github.com/user-attachments/assets/965f0724-6f15-4ce6-ac9a-266cba408a04)

**Comment by mvm-sap** [comment]
This is a Linux-only issue, but it looks fine in Windows.  Will check and fix it.

**Comment by vogella** [comment]
Thanks @mvm-sap
