### ISSUE TITLE
Align Text related icons according to UI guidelines

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#2582]
After @BeckerWdf and @Michael5601 fixed the misaligned icons at the beginning of the main toolbar, the text icons starts to stand out as misaligned.

![image](https://github.com/user-attachments/assets/a8c198f9-9e09-4f21-82fe-8b73fd00ec5d)

![image](https://github.com/user-attachments/assets/e2f195d5-d83b-4b1c-93db-93f0d55c160d)
![image](https://github.com/user-attachments/assets/1d95da59-d452-492a-8c12-d065905a915c)
![image](https://github.com/user-attachments/assets/e791fd74-b098-4cca-b7d1-2e4f975a414a)

Would be great if these could also be aligned according to the current UI standard.

**Comment by vogella** [comment]
@BeckerWdf can you help here?

**Comment by BeckerWdf** [comment]
> @BeckerWdf can you help here?

Yes I can. I just need to find some time for it.

**Comment by BeckerWdf** [comment]
@vogella: Is this issue now fixed?

**Comment by vogella** [comment]
Thanks @BeckerWdf, it looks much better for me:

![image](https://github.com/user-attachments/assets/f0a8f046-7281-4f2d-bdd7-8b195194ddbc)

If my sense of order is not mistaken, the last icon looks still looks not centered to me (it is a bit to low AFAICS).

![image](https://github.com/user-attachments/assets/28c85d82-2379-425e-868d-4bff70f9782f)

**Comment by Michael5601** [comment]
> Thanks @BeckerWdf, it looks much better for me:
> 
This is really a great improvement. I agree the last icon is still not right but the rest is fine.

**Comment by BeckerWdf** [comment]
if you give me the name / location of the icon I can have a look at it.

**Comment by Michael5601** [comment]
The icon is `pin_editor` in `org.eclipse.platform.doc.user\images` and `org.eclipse.ui\icons\full\etool16`. 

It also has duplicates in:

`org.eclipse.search\icons\full\elcl16\pin_view.svg`
`org.eclipse.jdt.ui\icons\full\elcl16\pin_view.svg`
`eclipse.platform.common\bundles\org.eclipse.jdt.doc.user\images\org.eclipse.jdt.ui\elcl16\pin_view.svg`

and maybe also `org.eclipse.ui\icons\full\elcl16\pin_view.svg` because it looks like a half version of the original icon. I don't know if this is wanted.

**Comment by BeckerWdf** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/2637

Before on top / After below:
<img width="207" alt="image" src="https://github.com/user-attachments/assets/2bf636f1-cad5-4351-9305-16b7628b6ccb" />


I also made some changes to the icon:
- "Pin" moves up one pixel
- "Editor" moves up one pixel and get's bigger by one pixel in width and height
- Made all strokes exactly one pixel and aligned them on pixel borders (see the grid lines)

Before:
<img width="50%" alt="Screenshot 2024-12-17 at 16 34 41" src="https://github.com/user-attachments/assets/86ff74df-ed3a-4fb9-8125-5dad07af33f6" />

After:
<img width="50%" alt="image" src="https://github.com/user-attachments/assets/ae60bf55-49f2-41cf-9bcc-79fde95fa88a" />

What do you think?

**Comment by BeckerWdf** [comment]
> and maybe also `org.eclipse.ui\icons\full\elcl16\pin_view.svg` because it looks like a half version of the original icon. I don't know if this is wanted.

I could not find a usage of this. Has anybody seen this icon ![pin_view@2x](https://github.com/user-attachments/assets/19b2f097-bbfb-42b2-90a3-03373e3fea81) somewhere in the UI?

It's defined at https://github.com/eclipse-platform/eclipse.platform.ui/blob/0344b2b062792a7336fe40edaefe768595e1d3f0/bundles/org.eclipse.ui.workbench/eclipseui/org/eclipse/ui/internal/IWorkbenchGraphicConstants.java#L50

This is in an internal package that is visible to these bundles:
org.eclipse.ui.internal;ui.workbench=split;mandatory:="ui.workbench";
  x-friends:="org.eclipse.ui,
   org.eclipse.ui.intro,
   org.eclipse.ui.ide,
   org.eclipse.ui.ide.application,
   org.eclipse.ui.views,
   org.eclipse.ui.navigator.resources,
   org.eclipse.ui.tests.browser,
   org.eclipse.debug.ui"
   
None of these uses the icon. Should we delete it?

**Comment by vogella** [comment]
> Should we delete it?

Yes.

**Comment by BeckerWdf** [comment]
> > Should we delete it?
> 
> Yes.

Done in https://github.com/eclipse-platform/eclipse.platform.ui/pull/2637/commits/ef7fbea7afb7a322cc8e5ca0980888d641015c60

**Comment by tomaswolf** [comment]
> > > Should we delete it?
> > 
> > 
> > Yes.
> 
> Done in [ef7fbea](https://github.com/eclipse-platform/eclipse.platform.ui/commit/ef7fbea7afb7a322cc8e5ca0980888d641015c60)

The Search and History views do have a pin icon in their view toolbars. Don't know if it's that one, though.

**Comment by Michael5601** [comment]
> > > > Should we delete it?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > Done in [ef7fbea](https://github.com/eclipse-platform/eclipse.platform.ui/commit/ef7fbea7afb7a322cc8e5ca0980888d641015c60)
> 
> The Search and History views do have a pin icon in their view toolbars. Don't know if it's that one, though.

It's not the one for the search for sure. I don't know about the history.

**Comment by BeckerWdf** [comment]
The history view has it's on version. That is slightly different:

If I change this to the new improved version this looks like this:
New is on top / old is below:

<img width="146" alt="Screenshot 2024-12-18 at 12 56 27" src="https://github.com/user-attachments/assets/ab0203d5-9471-41fb-8138-2842d71c942b" />

What do you think?

**Comment by vogella** [comment]
New looks better

**Comment by BeckerWdf** [comment]
Pls. close when you think this is fixed.

**Comment by vogella** [comment]
> Pls. close when you think this is fixed.

I suggest to wait for the your last PRs to be merged, if that is fine for you.

**Comment by BeckerWdf** [comment]
> I suggest to wait for the your last PRs to be merged, if that is fine for you. 

I only see one open PR: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/1862
