### ISSUE TITLE
Context menus do not appear where mouse click occurred, often context menu appears on a different display

### ISSUE THREAD

**Issue by losmurfs** [eclipse-platform/eclipse.platform.ui#2595]
I have 4 4k displays, I have Eclipse on the second display from the left. I have tried rebooting my computer. Every context menu appears 1,000 pixels or so to the right of where it should appear, often on a seperate display from Eclipse itself.  This issue started when I upgraded to 2024-12

![image](https://github.com/user-attachments/assets/3f5870f8-25cb-4cdc-a2c2-41ce2ba9d9dc)
![image](https://github.com/user-attachments/assets/25a12e98-eb6b-429d-b7fb-2f7693e42851)

**Comment by losmurfs** [comment]
Here is what it looks like when I right click on the beginning of a line in some source code:
![image](https://github.com/user-attachments/assets/2d0c98da-4f5c-423c-ab45-ad7965b8c913)

**Comment by losmurfs** [comment]
Found sub-optimal work-around: I'm running Eclipse in Windows 11 with latest patches from Microsoft. If I go into System > Display and set Scale on display where Eclipse is running to 100%, problem goes away. I have always used 150% (Recommended) in the past. So there is a new problem in 2024-12 that makes Eclipse incompatible with Windows 11 Display Scaling.

**Comment by HeikoKlare** [comment]
Can you please give some more information about your setup?
- Number of monitors, their arrangement and their individual scale values and which of them is the primary.
- Do you run the application with "default" settings or do you have the new rescaling at runtime activated? See https://eclipse.dev/eclipse/news/4.34/platform.php#rescale-on-runtime-preference

I tried to reproduce the issue with two monitors set to 150% on Windows 11 without having any issues with the context menus.

**Comment by losmurfs** [comment]
Found a fix: I tried scaling at 125% and 175% and that did not fix it. Then I set it to 100% as stated in comment above. Once I returned it to 150% (Recommended) it started working correctly.  So the bug is that what ever code deals with the scaling only works when changing from 100% to something else and does not work when you start at a scale different from 100%.

**Comment by losmurfs** [comment]
This may be related to doing an in-place upgrade to 2024-12 while scale was set to 150%

**Comment by losmurfs** [comment]
Display arrangement: 3 in a row with a fourth below the right most display. Laptop is below the right most display (4k display integrated into laptop, plus 3 42" 4k displays.

**Comment by losmurfs** [comment]
Eclipse is all defaults except dark mode theme.

**Comment by losmurfs** [comment]
![image](https://github.com/user-attachments/assets/dc0bcbf7-4721-400c-94e2-43712223f627)

**Comment by HeikoKlare** [comment]
Can you please share the individual scale/zoom values of those three/four monitors and the information which of them is the primary monitor? Otherwise it is hard to reproduce the problem.
And please also describe a concrete workflow, i.e., whether it sufficient to start the application on the given setup and move it to a specific monitor, whether some scaling needs to be changed while the application is running or the like.

**Comment by losmurfs** [comment]
The 3 42" 4Ks are set to 150%, the display integrated into the laptop is set to 250% (Recommended)

**Comment by losmurfs** [comment]
The laptop display is set as the Primary Display (I wish Windows did not have a concept of a Primary Display, I'd like to have taskbars and fully functional systrays on all four displays.)

**Comment by losmurfs** [comment]
![Screenshot 2024-12-06 082404](https://github.com/user-attachments/assets/925ebf36-3df3-4098-a455-ae4074edc52a)

**Comment by HeikoKlare** [comment]
Thank you! I can now reproduce the issue with the following simplified two-monitor setup:
- Secondary monitor to the left, 150% (probably also other, lower scale values)
- Primary monitor to the right, 175% (probably also other, higher scale value)

Move the application from the primary, right monitor, to the secondary, left monitor. The context menu seems to indeterministically pop up at wrong positions. It did not find a pattern when it appears at the correct and when it appears at a wrong position yet.

Right-clicking at the last character of the marked editor line indeterministically pops up the context menus at the following positions:
![image](https://github.com/user-attachments/assets/fdfa5eb7-6c15-4630-a5a4-1a774ca4bb7a)
![image](https://github.com/user-attachments/assets/7ff16e65-f167-454e-a405-90f2c008004b)

@akoch-yatta can you have a look please? Might be related to the coordinate system adaptations in SWT.

**Comment by losmurfs** [comment]
BTW - EXPERIMENTAL HiDPI settings Monitor-specific UI scaling works great, no context menu positioning errors when using it

**Comment by losmurfs** [comment]
EXPERIMENTAL HiDPI settings Monitor-specific UI scaling: Is there a way to adjust scaling? I would like to "zoom out" a bit.
-Dswt.autoScale=100 effects the Eclipse Splash Screen but has no effect on Eclipse IDE when Monitor-specific UI scaling is enabled. Monitor-specific UI scaling would be awesome if I could adjust the scaling.

**Comment by losmurfs** [comment]
Turns out Monitor-specific UI scaling is still un-usable: All dialogs chop off the checkboxes, OK buttons, Cancel buttons, etc and do not provide a way to resize the dialogs to see the options. So you have to navigate them by keyboard and by memory using arrow keys, tab, space bar, enter, etc.

**Comment by HeikoKlare** [comment]
> Turns out Monitor-specific UI scaling is still un-usable: All dialogs chop off the checkboxes, OK buttons, Cancel buttons, etc and do not provide a way to resize the dialogs to see the options. So you have to navigate them by keyboard and by memory using arrow keys, tab, space bar, enter, etc.

Would you mind creating a separate issue for this? I am not sure what exactly you mean by saying that it is "still" un-usable. The feature has just been provided with the 2024-12 release for initial testing. That's why the news and the preferences dialog state that the feature is experimental. We appreciate every testing of it and every feedback on it, so creating tickets for issues that you face would be great.

Regarding the original context menu placement issue: we are currently investigating this.
