### ISSUE TITLE
Tab text in classic theme not readable 

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#26]
Do we have users of the classic theme under Windows? I tried it today and the text in the tabs in hardly readable for me.

Not sure if that is a regression or the "classic theming".

![image](https://user-images.githubusercontent.com/139910/164443914-cc70925c-ba68-4975-998a-f94f578fc1be.png)

**Comment by iloveeclipse** [comment]
Lars, hardly possible that this is **not** a regression, why would anyone ever design such unreadable theme **on purpose**.

**Comment by akurtakov** [comment]
I know that theming is personal thing but this theme particularly is way too heavy and probably requires most maintenance due to all "curly" elements. CTabFolder is probably the nastiest piece of SWT which is even badly hacked by the theme engine (by replacing the rendered and calling to the SWT one via reflection) to make things even worse. 
This is just FYI if someone is interested in trying to fix it.

**Comment by vogella** [comment]
> Lars, hardly possible that this is **not** a regression, why would anyone ever design such unreadable theme **on purpose**.

AFAICS the classic themes have not been touched in years. I guess a change in SWT broken them and nobody noticed or nobody cared to report.

**Comment by merks** [comment]
This is from a debug launched IDE with the TP from last night's IBuild:

![image](https://user-images.githubusercontent.com/208716/164445308-1245f8a9-f1fb-4933-9262-6b02d7b60d8f.png)

Even if I change the color/font theme part to classic as still, it looks the same.

**Comment by vogella** [comment]
@merks please try the theme for a regular IDE, my screenshot is not from a runtime IDE but a regular one.

**Comment by merks** [comment]
Eclipse SDK
Version: 2022-06 (4.24)
Build id: I20220420-1800

![image](https://user-images.githubusercontent.com/208716/164447122-3018f745-35f7-4fad-9bcd-e354c9442386.png)

![image](https://user-images.githubusercontent.com/208716/164447345-3e36a6d2-22cb-4f78-9a2a-000041b80500.png)

![image](https://user-images.githubusercontent.com/208716/164447742-e359c5de-b473-42b3-9514-033e34bfe726.png)

**Comment by akurtakov** [comment]
Could this be Win10/11 difference?

**Comment by merks** [comment]
I've been scared to update to 11 because I really don't need disruptive changes!

**Comment by vogella** [comment]
I'm also using windows 10

Edition	Windows 10 Pro
Version	21H2
Installiert am	‎23.‎08.‎2021
Betriebssystembuild	19044.1586
Seriennummer	PF31JAAZ
Leistung	Windows Feature Experience Pack 120.2212.4170.0

**Comment by merks** [comment]
Edition	Windows 10 Pro for Workstations
Version	21H2
Installed on	‎20.‎09.‎2021
OS build	19044.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

**Comment by vogella** [comment]
Not reproducable by others.
