### ISSUE TITLE
Color selection widgets shows wrong scaled Image on Linux at 200% scaling

### ISSUE THREAD

**Issue by Phillipus** [eclipse-platform/eclipse.platform.ui#261]
- Eclipse 4.25
- Linux Mint Cinnamon X11
- DPI Scaling set to 200%

Running Eclipse at 200% DPI on Linux the color images created in the JFace ColorSelector widget are not scaled correctly.

To simulate a hi-DPI monitor you can launch a child Eclipse with Environment setting `GDK_SCALE=2` in the launch configuration.

![capture1](https://user-images.githubusercontent.com/600504/184537011-7207f1bf-c1b0-496f-89a8-8e579e8ef9b2.png)

![capture2](https://user-images.githubusercontent.com/600504/184537030-ca3576e2-7f49-41ac-9e58-115fd85965fe.png)

**Comment by Phillipus** [comment]
Looking at the code for [ColorSelector](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.jface/src/org/eclipse/jface/preference/ColorSelector.java) it seems that no auto scaling is done when creating the color image. The Image instance probably needs to implement `ImageDataProvider` to return a correctly scaled image.

**Comment by Phillipus** [comment]
Actually, the `ColorSelector` widget is only used for the widget in the 2nd screenshot.  `ColorsAndFontsPreferencePage` creates the color boxes for the 1st screenshot with an Image, again with no auto scaling.

**Comment by Phillipus** [comment]
This can probably be fixed by using `DPIUtil.AutoScaleImageDataProvider` like this:

```java
Image image = new Image(display, w, h);

GC gc = new GC(image);
// Draw on GC here
gc.dispose();

ImageData imageData = image.getImageData(DPIUtil.getDeviceZoom());
image.dispose();
image = new Image(display,
                 new DPIUtil.AutoScaleImageDataProvider(display, imageData, DPIUtil.getDeviceZoom()));
```

CTabFolder uses the same approach:

https://github.com/eclipse-platform/eclipse.platform.swt/blob/0a4effe8961a288c998bcdc7e16e20cbbea48f0a/bundles/org.eclipse.swt/Eclipse%20SWT%20Custom%20Widgets/common/org/eclipse/swt/custom/CTabFolder.java#L727-L746

**Comment by jukzi** [comment]
please provide a Pull request.

**Comment by Phillipus** [comment]
> please provide a Pull request.

I tried and failed because `org.eclipse.swt.internal.DPIUtil` cannot be accessed from `org.eclipse.jface` due to access restrictions.

**Comment by Phillipus** [comment]
The color widgets size in ` ColorsAndFontsPreferencePage` (first screenshot in OP) has been fixed by https://github.com/eclipse-platform/eclipse.platform.swt/issues/315

https://github.com/eclipse-platform/eclipse.platform.swt/commit/f7a6d0761437e4f22a8d046268fc43370031d599

The problem in `ColorSelector` is the same as before.

**Comment by mbooth101** [comment]
Hi chaps, I was looking at this today, please consider reviewing my patch at https://github.com/eclipse-platform/eclipse.platform.ui/pull/420 to fix the `ColorSelector` widget.

**Comment by mbooth101** [comment]
Verified in I20221019-1800 on Fedora 36 w/GTK 3.24.34
