### ISSUE TITLE
Eclipse offers to remove unreachable Software Sites: Please provide the ability to restore them after accidentally clicking Yes

### ISSUE THREAD

**Issue by losmurfs** [eclipse-platform/eclipse.platform.ui#2614]
My internet connection quit working for about 5 minutes, I did not know it was not working. In Eclipse, while internet was not working I clicked Help -> Check for Updates

Not of the sites worked, so Eclipse offered to remove them. I did not realize the situation so now I have no Available Software Sites.

Enhancement: When a software site is removed, store that site along with any other that have been "removed" and provided a "Past Software Sites" button that launches a dialog that lets you select sites you want to restore.

**Comment by laeubi** [comment]
This is actually something for P2

https://github.com/eclipse-equinox/p2

in any case I think blindly hitting remove and then want to restore this is not really a usual use-case so if you really need such a feature it is likely you need to provide a PR for that.

**Comment by merks** [comment]
Yes, we can't move issues to another organization so open for p2.  Keep in mind that yes, unfortunately no one else is likely to consider this a priority enhancement that is worth their limited time to implement, so if it's important to you, it will likely needs self service.
