### ISSUE TITLE
Openjdk/23.0.0, maven/3.9.5 in local machine 

### ISSUE THREAD

**Issue by NithiyananthamArunagiri** [eclipse-platform/eclipse.platform.ui#2640]
I have tried to build 4.33.0-SDK (OpenJDK 23 and maven 3.9.5) in local machine, we are getting below error message

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.4:validate-classpath (default-validate-classpath) on project com.ericsson.eecs.shared.branding: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:3.0.4:validate-classpath failed: org.osgi.framework.BundleException: Bundle com.ericsson.eecs.shared.branding cannot be resolved:com.ericsson.eecs.shared.branding [73]
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.ui.intro
[ERROR] -> Bundle-SymbolicName: org.eclipse.ui.intro; bundle-version="3.7.400.v20240414-0828"; singleton:="true"
[ERROR] org.eclipse.ui.intro [2]
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.help.base; bundle-version="[4.0.0,5.0.0)"; resolution:="optional"
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.workbench
[ERROR] -> Bundle-SymbolicName: org.eclipse.e4.ui.workbench; bundle-version="1.15.500.v20240730-1919"; singleton:="true"
[ERROR] org.eclipse.e4.ui.workbench [54]
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.services; bundle-version="0.9.0"
[ERROR] -> Bundle-SymbolicName: org.eclipse.e4.ui.services; bundle-version="1.6.300.v20231201-1637"; singleton:="true"
[ERROR] org.eclipse.e4.ui.services [45]
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR] -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.400.v20240413-1529"; singleton:="true"
[ERROR] org.eclipse.e4.core.services [35]
[ERROR] Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.component)(version>=1.2)(!(version>=2.0)))"
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.model.workbench; bundle-version="1.2.0"
[ERROR] -> Bundle-SymbolicName: org.eclipse.e4.ui.model.workbench; bundle-version="2.4.300.v20240321-1245"; singleton:="true"
[ERROR] org.eclipse.e4.ui.model.workbench [52]
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR] -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.400.v20240413-1529"; singleton:="true"
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR] -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.400.v20240413-1529"; singleton:="true"
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.6.0,4.0.0)"
[ERROR] -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.206.100.v20240720-1232"; singleton:="true"
[ERROR] org.eclipse.ui [67]
[ERROR] Unresolved requirement: Require-Bundle: org.eclipse.ui.workbench; bundle-version="[3.130.0,4.0.0)"; visibility:="reexport"
[ERROR] -> Bundle-SymbolicName: org.eclipse.ui.workbench; bundle-version="3.133.0.v20240818-1923"; singleton:="true"
[ERROR] org.eclipse.ui.workbench [68]
[ERROR] Unresolved requirement: Import-Package: org.eclipse.e4.ui.internal.workbench
[ERROR] -> Export-Package: org.eclipse.e4.ui.internal.workbench; bundle-symbolic-name="org.eclipse.e4.ui.workbench"; bundle-version="1.15.500.v20240730-1919"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.workbench.fragment, org.eclipse.e4.ui.workbench.addons.swt, org.eclipse.e4.ui.workbench.renderers.swt, org.eclipse.e4.ui.workbench.swt, org.eclipse.ui.workbench, org.eclipse.ui.ide.application, org.eclipse.ui.ide, org.eclipse.e4.emf.xpath.test"
[ERROR] Unresolved requirement: Import-Package: org.eclipse.e4.ui.internal.workbench.addons
[ERROR] -> Export-Package: org.eclipse.e4.ui.internal.workbench.addons; bundle-symbolic-name="org.eclipse.e4.ui.workbench"; bundle-version="1.15.500.v20240730-1919"; version="0.0.0"; x-friends:="org.eclipse.ui.workbench"
[ERROR] Unresolved requirement: Import-Package: org.eclipse.e4.core.commands
[ERROR] -> Export-Package: org.eclipse.e4.core.commands; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="1.1.400.v20240424-0444"; version="0.0.0"
[ERROR] org.eclipse.e4.core.commands [30]
[ERROR] Unresolved requirement: Import-Package: org.eclipse.e4.core.services.log
[ERROR] -> Export-Package: org.eclipse.e4.core.services.log; bundle-symbolic-name="org.eclipse.e4.core.services"; bundle-version="2.4.400.v20240413-1529"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings, org.eclipse.e4.ui.services, org.eclipse.e4.ui.workbench, org.eclipse.e4.ui.workbench.renderers.swt, org.eclipse.e4.ui.workbench.swt, org.eclipse.ui.workbench, org.eclipse.e4.core.commands"
[ERROR] Unresolved requirement: Import-Package: org.eclipse.e4.core.commands.internal
[ERROR] -> Export-Package: org.eclipse.e4.core.commands.internal; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="1.1.400.v20240424-0444"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,org.eclipse.ui.workbench,org.eclipse.e4.ui.workbench,org.eclipse.e4.ui.workbench.renderers.swt

**Comment by akurtakov** [comment]
You are not building Eclipse SDK as it doesn't contain com.ericsson.eecs.shared.branding  as can be seen in the log you attached "Bundle com.ericsson.eecs.shared.branding cannot be resolved:com.ericsson.eecs.shared.branding [73]" . Whatever you try to build is not smth Eclipse Platform project can help you with. https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/README.md explains how to build Eclipse SDK.
