### ISSUE TITLE
Unclear where/how to install org.eclipse.e4.ui.progress

### ISSUE THREAD

**Issue by lppedd** [eclipse-platform/eclipse.platform.ui#265]
Seems like the sources are being tracked here now.  
The page https://wiki.eclipse.org/Eclipse4/ProgressView is obsolete and every link is down.  
Any pointer, or do I have to build from scratch?

**Comment by akurtakov** [comment]
This bundle has been part of eclipse regular releases for a while now so you can just use latest release p2 site https://download.eclipse.org/eclipse/updates/4.24/ . Please confirm everything is fine for you that way so I will edit that page and say "Just fetch from latest Eclipse release"

**Comment by lppedd** [comment]
@akurtakov thanks a lot! Yes, I can confirm it can be found under that address. Added correctly to my Target Platform.  
Is it normal that the bundle is not available under https://download.eclipse.org/releases/2022-06/ tho?

**Comment by akurtakov** [comment]
Most likely nothing in Eclipse SDK uses it and thus it's not contributed to simrel https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/tree/ep.aggrcon . I don't know more details on this one but @vogella probably knows more about its current state and @sravanlakkimsetti about why it's not contributed to simrel

**Comment by akurtakov** [comment]
I have adjusted the paths and general info in the wiki. Please feel free to improve the page about the bundle usage yourself if smth is missing or incorrect as I've never looked into the details of this one yet.
