### ISSUE TITLE
Workspace selection dialog allows relative paths and that leads to unexpected workspace path

### ISSUE THREAD

**Issue by kohlschuetter** [eclipse-platform/eclipse.platform.ui#279]
At least on macOS and Eclipse 2022-06, the dialog where the path to the Eclipse workspace is specified does not resolve the tilde character (`~`), referring to the user's home directory (It does work when you click on browse and then start typing, since this is probably a system UI)

Instead of resolving `~` to the user's home directory, the path is treated as being relative to the Eclipse application folder, in my case `/Applications/Eclipse.app/Contents/MacOS/~/test`.

You can imagine what happened next: After I found the actual path using the "browse" button (because the drop down menus also only show `~/test`), I used Terminal to cd into /Applications/Eclipse.app/Contents/MacOS and tried to `rm -rf ~`...

I guess I should have finished my morning coffee first. Thankfully, I have recent backups of my actual home directory.

<img width="716" alt="tilde-of-death" src="https://user-images.githubusercontent.com/822690/183629794-ad878ac1-96a6-45ed-b7ad-fdcbfc904ff9.png">

**Comment by laeubi** [comment]
> does not resolve the tilde character (`~`), referring to the user's home directory

Please note that this is shell **(!)** feature not an OS feature see: https://stackoverflow.com/questions/998626/meaning-of-tilde-in-linux-bash-not-home-directory so saying  `~` = `user home` is not really valid in all cases, even though its a common agreement in *nix based system shells.

> and tried to `rm -rf ~`...

With big power... ;-)

**Comment by kohlschuetter** [comment]
I'm on macOS, which supports tilde `~` as a shortcut to the home directory (as well as `~username` etc.) in Finder. It's also working when you click the "Browse" button in the Eclipse UI and start typing:

<img width="525" alt="tilde-working" src="https://user-images.githubusercontent.com/822690/183631420-e10c917e-ded3-4884-9ecd-d90e7ad52eff.png">

If I put myself into a new Eclipse user's shoes: they shouldn't be thrown under the bus with the very first UI they see.

**Comment by laeubi** [comment]
I fear this is just a "dump" text-field and not a system-control :-/
But I think nothing should prevent from adding support for `~` there,

**Comment by kohlschuetter** [comment]
One other thing to consider: Disallow relative paths (or at least warn the user about them).
It's almost always wrong to create a workspace within Eclipse.app.

**Comment by iloveeclipse** [comment]
> Disallow relative paths (or at least warn the user about them).

Yes, this is the point, not only on mac this would lead to strange results. 
Patches are welcome. The code in question is `org.eclipse.ui.internal.ide.ChooseWorkspaceDialog` and the "entry point" for all code that wants to do something with the entered text is `org.eclipse.ui.internal.ide.ChooseWorkspaceDialog.getWorkspaceLocation()`.

One could probably add modify listener to the `text` field to prepend entered data with "user.home" if the path is not absolute.

**Comment by jonahgraham** [comment]
Please don't stop relative paths, warning is fine but I and others rely on relative paths for a number of use cases.

**Comment by iloveeclipse** [comment]
> I and others rely on relative paths for a number of use cases.

Could you please provide more info?

**Comment by jonahgraham** [comment]
> > I and others rely on relative paths for a number of use cases.
> 
> Could you please provide more info?

Two specific workflows:

1. on the command line where workspace is specified as relative. This is very common and I use it all over the place, from quick testing the IDE, to using the IDE in builds. Here is an [example in CDT](https://github.com/eclipse-cdt/cdt/blob/637eb04dfb107f082f3a685d7949e258e87470a4/releng/scripts/do_format_code.sh#L29-L32)
2. I have customers with workflows where they use lots of workspaces for embedded work where the workspace is "close" to the code. As the workflows work with command line launches of the IDE, the practice is to just type plain `workspace` in the prompt so that it makes the workspace in the current directory. Of course that dialog remembers `workspace` so if the user runs eclipse in any directory the default is the `workspace` in that directory, therefore after the first time they never actually type `workspace` again and just continue with the last-used.
![image](https://user-images.githubusercontent.com/679236/183671024-8d4ea92c-7d41-4906-91b7-cd6d35eb2f53.png)

**Comment by iloveeclipse** [comment]
OK, so it is not a bug but a feature :-)

With that, I don't see what we can do here.

**Comment by kohlschuetter** [comment]
> OK, so it is not a bug but a feature :-)
> 
> With that, I don't see what we can do here.

I think using relative paths from the command line is different from using them in the GUI, especially if the path base is within a macOS application package (Eclipse.app).

A trivial fix for my issue would be to disallow paths that contain a tilde (`~`) as the first character. If you specify a path containing it via shell, it should already be converted to the correct absolute path when it reaches Eclipse code. The error message could suggest specifying an absolute path in this particular case.

**Comment by jonahgraham** [comment]
> A trivial fix for my issue would be to disallow paths that contain a tilde (~) as the first character. 

That is a good idea for a small fix - but a warning rather than an error.

What was mentioned in your [earlier comment](https://github.com/eclipse-platform/eclipse.platform.ui/issues/279) would be even better - that is use native directory selection dialog elements here. Much more work for sure, but frankly having auto-complete in that dialog would be nice.

Either way - this same problem does exist all over the place in Eclipse wherever paths can be set (e.g. launch configurations, build settings, etc)

**Comment by jukzi** [comment]
> With that, I don't see what we can do here.

It would be possible to add a text label below the input field that shows the resolved path if the path is relative (as already shown in your screenshot :-) ). That would make it obvious to the user what will happen.

**Comment by iloveeclipse** [comment]
The fix https://github.com/eclipse-platform/eclipse.platform.ui/pull/1477 caused regression on Linux, the dialog looks like this now:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/5a193fca-27a1-4142-91c3-d4b6f2d507b1)

This has to be fixed, it is not acceptable.

**Comment by iloveeclipse** [comment]
Here how it is **supposed** to look like on Linux:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/94af16cb-a642-468b-bb53-f15fd33e7670)

**Comment by iloveeclipse** [comment]
Even worse, the new label provides **absolutely wrong** information

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/47fac143-05ba-43be-b3f1-f664b67fb860)

If that wouldn't be fixed ASAP, I'm going to revert https://github.com/eclipse-platform/eclipse.platform.ui/pull/1477.

**Comment by iloveeclipse** [comment]
So to fix are:

1) "Browse" button layout
2) Remove border around new label
3) Fix broken label content computation

@mickaelistria, @elsazac : please consider to fix ASAP.

**Comment by elsazac** [comment]
> So to fix are:
> 
> 1. "Browse" button layout
> 2. Remove border around new label
> 3. Fix broken label content computation
> 
> @mickaelistria, @elsazac : please consider to fix ASAP.

Thanks for reporting this. I am investigating.

**Comment by elsazac** [comment]
> Even worse, the new label provides **absolutely wrong** information
> 
@iloveeclipse Please let me know what is wrong with this information.

The resolved path showed in the feature 
![Screenshot 2024-01-10 at 1 14 37 PM](https://github.com/eclipse-platform/eclipse.platform.ui/assets/122080218/e319bd20-b8fd-4b2a-b36d-e7d1f63b8314)

The actual path used when launched 
![Screenshot 2024-01-10 at 1 15 12 PM](https://github.com/eclipse-platform/eclipse.platform.ui/assets/122080218/1238838b-7e15-460d-9158-a838225857c9)

as you can see both are same and the label is showing the correct information.I may be missing something, please let me know.

**Comment by mickaelistria** [comment]
@elsazac when there is a `~`, isn't it expected the specific warning would show up?
I agree with @iloveeclipse regarding the layout: the border should be removed and the browse button should be aligned with the text entry only.

**Comment by elsazac** [comment]
> @elsazac when there is a `~`, isn't it expected the specific warning would show up?

I agree that the warning symbol should show up but it is not. I am investigating that now.

on the other hand I am still trying to understand "label provides absolutely wrong information" that @iloveeclipse mentioned.

**Comment by iloveeclipse** [comment]
> Please let me know what is wrong with this information.

It looks like Mac and Linux understand `~` differently.

I have no Mac access, so can't say anything if the path label shows wrong or not info there, but on Linux `~` **always** means home directory.

So saying that `~` corresponds to `<eclipse working directory> + ~` sounds like a complete nonsense, **even if Eclipse actually will do that**.

I would expect either that Eclipse properly resolves `~` to a home directory and uses that, or at least warns that `~` is not meant to use home directory at all.

**Additional issue found**
One started with `~/hello` path, on next startup the path is shown but the "explanation" label is empty:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/6e7e3c82-4382-4736-8157-278de7c90c04)

**Comment by laeubi** [comment]
> on the other hand I am still trying to understand "label provides absolutely wrong information" that @iloveeclipse mentioned.

I guess that the the expectation is that `~` resolves to `<user home>`

**Comment by laeubi** [comment]
> but on Linux ~ always means home directory

This is not true ... this is a bash feature:

https://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html

even though often programs adapt to this convention.

**Comment by mickaelistria** [comment]
I don't think we should implement `~` expansion. `~` expansion is a feature of bash, not a filesystem feature. If you write `~` in any bit of code, or start the application with something else than bash (ie doing a spawn from node or using a System.exec() in Java), it wouldn't be understood. We don't aim at supporting bash expansion, it's beyond achievable. On the other end, nomalization is Java and URI standard operation, so it's OK and safe to support it.

**Comment by elsazac** [comment]
> So saying that `~` corresponds to `<eclipse working directory> + ~` sounds like a complete nonsense, **even if Eclipse actually will do that**.

@iloveeclipse Can you explain what this means? at least in Mac  `~` corresponds to <eclipse working directory> + `~` .please refer to my previous images. Are you saying that `~` resolves to users home directory in linux in this context (launch window) ? If you can confirm that I will confine this change to Mac and Windows.

**Comment by kohlschuetter** [comment]
@iloveeclipse I think the misunderstanding about the UI is that the recent fix only shows the (unexpected) path, it does not add support for mapping `~` to the home directory.

"Tilde Expansion" is a POSIX feature of the Shell Command Language. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01

Whether this applies here or not determines whether the resolved path is "wrong", but I would say the solution of showing the unexpected path is acceptable (as long as the UI is fixed for the button height).

**Comment by iloveeclipse** [comment]
> This is not true ... this is a bash feature:

This is not true, this is a POSIX standard:

https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01

**Comment by mickaelistria** [comment]
OK, my bad, it's a standard *Shell* feature then; but the proposal here is to show the resolved path for standard filesystem normalization and to warn that `~` expansion is not implemented so people are not seeing unexpected behavior without working; it's not to implement the shell POSIX spec in the workspace dialog.
If someone is willing to implement `~` expansion here, that can be welcome in a further PR; but it's not the scope of this change.

**Comment by elsazac** [comment]
> @iloveeclipse I think the misunderstanding about the UI is that the recent fix only shows the (unexpected) path, it does not add support for mapping `~` to the home directory.

@kohlschuetter 
True, the PR doesn't implement ~ expansion, it implements the consensus gathered in this issue-  
https://github.com/eclipse-platform/eclipse.platform.ui/issues/279#issuecomment-1224793014

**Comment by laeubi** [comment]
> > This is not true ... this is a bash feature:
> 
> This is not true, this is a POSIX standard:
> 
> https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_01

If you know that why you are surprised then? Eclipse is not a POSIX shell... and still the point it that it is not true that `~` **always** means home directory on Linux....

**Comment by kohlschuetter** [comment]
I'm glad this bug got traction after almost 1.5 years, but yes, let's not bikeshed too much here.
My initial problem was that I _expected_ the tilde to be resolved. Showing the resolved path is a totally fine way of addressing this expectation/reality mismatch.

So thank you for putting this together, @elsazac!

@laeubi is absolutely correct. `~` is not always the home directory, otherwise the path would resolve correctly.
Notably,
`Path.of("~").toAbsolutePath()` will absolutely, and rightfully, not resolve to the user's home directory.

The resolution is only expected in shell contexts, and whether this UI is considered a shell is not clear.

If you wanted to fix this for good, then all places in Eclipse where user can type in a path from the UI would need to have an abstraction that take care of this resolution.

**Comment by jukzi** [comment]
the empty border also looks strange on windows:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/114f850b-48a8-4a7a-92d7-55dcb7968da5)

**Comment by jukzi** [comment]
[win]: when i type `C:\Users\jkubitz\platform-2024-01-10\ws\\\\a`, then select the heading `C:\Users\jkubitz\platform-2024-01-10\ws\\` and press DEL key, the dialog somehow crashes such that the input field is not updated anymore, but the resolved path is updated when i press other keys:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/8184086b-2f28-406e-b977-3cfec6db3878)

**Comment by jukzi** [comment]
Why are relative paths resolved against the eclipse installation? i would never encourage someone to create data within the installation
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/2bb81f48-2a9c-4f6f-b306-eb1e332a5720)

**Comment by jukzi** [comment]
I also suggest to resolve against the canonical name - the exiting capitalisation of the path is not taken into account:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/54d12590-306c-4008-a6d0-3809e382c834)

**Comment by jukzi** [comment]
The dialog also crashes now when i enter `\\\\a` on win
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/d1076bc9-65d3-4a3e-9ace-a53a97b639c8)

**Comment by merks** [comment]
> Why are relative paths resolved against the eclipse installation?

I would expect a relative path to be evaluated against the `user.dir` system property and if you launch from a shortcut and have not changed the "Start in":

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/208716/6801f8b9-c647-48f2-aa89-e716439e5955)

that will be the installation folder.  Of course the dialog has always been doing this, it's just now showing that it is doing this...

**Comment by laeubi** [comment]
> > Why are relative paths resolved against the eclipse installation?
> 
> I would expect a relative path to be evaluated against the `user.dir` system property and if you launch from a shortcut and have not changed the "Start in":
> 
> that will be the installation folder. Of course the dialog has always been doing this, it's just now showing that it is doing this...

"relative" pathes are always evaluated against the Working directory of the process (in Linux/Mac/Windows) because if you run something like `dir testme` you want tit to list the directory 'testme' relative to the current directory and not relative to any whatever directory (e.g. user directory).

See https://docs.oracle.com/javase/8/docs/api/java/nio/file/Path.html

> ## Accessing Files
> Paths may be used with the [Files](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html) class to operate on files, directories, and other types of files. For example, suppose we want a [BufferedReader](https://docs.oracle.com/javase/8/docs/api/java/io/BufferedReader.html) to read text from a file "access.log". The file is located in a directory "logs" relative to the current working directory and is UTF-8 encoded.
> 
>      Path path = FileSystems.getDefault().getPath("logs", "access.log");
>      BufferedReader reader = Files.newBufferedReader(path, StandardCharsets.UTF_8);

**Comment by jukzi** [comment]
> "relative" pathes are always evaluated against the Working directory of the process (in Linux/Mac/Windows) because if you run something like `dir testme` you want tit to list the directory 'testme' relative to the current directory and not relative to any whatever directory (e.g. user directory).

Just because the OS does so it does not mean it makes sense in an application.

**Comment by laeubi** [comment]
The same like for `~` expansion applies here, anyone is free to enhance this ... but this has nothing to do with this feature nor what one should "expect" as this just works as defined in the JVM API so unless someone adds special code it works like the defaults of java...

**Comment by merks** [comment]
Note that there is conflicting advice on using get getCanonicalPath():

https://github.com/eclipse-platform/eclipse.platform.ui/pull/1477#discussion_r1445744287

(With feedback both both here and in the PR it feels disjointed, my mail folder feels like a bomb blew up.)

**Comment by jukzi** [comment]
its not conflicting. java offers normalization without following symlinks
https://docs.oracle.com/javase/8/docs/api/java/nio/file/LinkOption.html#NOFOLLOW_LINKS

**Comment by kohlschuetter** [comment]
Using canonical paths here is most likely wrong:
1. it would usually result in a longer, less readable path
2. canonicalization can be slow and can fail (think of network directories, etc.)
3. canonicalization is a representation of the moment. The same path may resolve to a different location when symbolic links are changed, etc.

Let's not overthink this please. Just fix the remaining UI glitches and call it a day.

**Comment by merks** [comment]
> its not conflicting. java offers normalization without following symlinks https://docs.oracle.com/javase/8/docs/api/java/nio/file/LinkOption.html#NOFOLLOW_LINKS

I would advise making suggestions against the PR's actual code with actual code snippets you'd like to see being used.  I.e., the code uses java.io.File which is no doubt no longer the best API to use...

All this reminds me of the exact same problems in the installer, where eventually we did additional things like validating that the location is actually writable...

**Comment by szarnekow** [comment]
As interesting as it seems to discern whether `~` is a shell, posix, bash or whatever feature, we should focus on the user expectation. As far as I can tell, other editors agree that `~/someFolder` is relative to the users home folder. So it *seems* that this would be the user's expectation, or nobody would have made the effort to mimic that expansion.

**Comment by laeubi** [comment]
> So it _seems_ that this would be the user's expectation, or nobody would have made the effort to mimic that expansion.

That is correct, but this is like Eclipse "worked forever" so not to blame on this change ...

**Comment by jukzi** [comment]
I suggest to make sure that the resolved name shown matches the name shown in the already existing options:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/df7aea28-ba81-4ebc-9139-64c051839b4e)

i guess org.eclipse.core.internal.utils.FileUtil.realPath(IPath) is used

**Comment by laeubi** [comment]
Layout issue is described / tracked here:
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/1492
