### ISSUE TITLE
Publish the IEventBroker also as OSG services

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#285]
The IEventBroker is a convinient wrapper around the EventAdmin service from OSGi. It would be nice to get it easily injected also into OSGi services. I suggest we also publish it as OSGI service instead of "only" making it available via the application context.

Opinions? @opcoach or @laeubi

**Comment by laeubi** [comment]
As far as I know `IEventBroker` is per Context and not a singleton and tied to E4 so why not inject it at the first place?

**Comment by vogella** [comment]
> As far as I know IEventBroker is per Context and not a singleton and tied to E4 so why not inject it at the first place?
Currently it is available via the application context so it is defacto singleton. And OSGi services cannot directly access it via @Inject.

**Comment by laeubi** [comment]
I mean: Why do I need this in an OSGi service? And in an E4 Component I can let it inject anyways :-)

**Comment by laeubi** [comment]
Looking at the code, it seems an `EventBroker` needs the `UISyncronize` that it gets injected from its E4Context so it seems one can't easily register `IEventBroker` as a service.

**Comment by vogella** [comment]
> Why do I need this in an OSGi service? 

To send out event as easy as in e4 code.

> it seems one can't easily register IEventBroker as a service. 

FrameworkUtil.getBundle(getClass()).getBundleContext().registerService(IEventBroker.class, broker, null) would publish the E4 service also as OSGI service

**Comment by laeubi** [comment]
Sure I can register **any** object, I just doubt that's what some one really expects, because this will only register the service in OSGi if it was used once in E4 (what is probably always but who knows?)

> To send out event as easy as in e4 code.

Looking at the code, it might be possible to extract the relevant code into a static `sendEvent(EventAdmin , String, Object)` method?

**Comment by vogella** [comment]
I will keep this line in my clients code base, not worth the time to discuss this that long.
