### ISSUE TITLE
Disable or fix System theme on Windows

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#3]
System theme looks not native on Windows. I suggest we remove it, users which want native styling can disable theming via unchekcing "Enable theming".

System theme

![image](https://user-images.githubusercontent.com/139910/162949479-65f31df5-27b7-47db-bed1-d5809777ff78.png)

No theming:

![image](https://user-images.githubusercontent.com/139910/162949680-76287725-ae66-4307-942f-edeea449a466.png)

**Comment by mickaelistria** [comment]
System theme looks better on Linux. I use it all the time and the feedback is positive, it also better adapts to system theme than no theme at all. So no, let's not retire. Instead, one can fix how it looks on WIndows.

**Comment by vogella** [comment]
@mickaelistria what about if me made is special for Linux? I don't think you plan to fix it under windows neither do I and it looks broken.

**Comment by vogella** [comment]
Tbh. you should have done this for the default light theme in Linux instead of starting a new theme.

**Comment by mickaelistria** [comment]
It's not special to any OS, it's following the color constants retrieved by SWT for the current system. The default light theme use color constants and does not adapt to native theme changes; and the system theme may actually be dark, or green, or light and Eclipse would react.
Ideally, the best would be no theme at all, but things like multiple CTabFolders to identify which folder has focus require a theme at the moment.
That said, if you don't want that theme to be visible under Windows, feel free to add the necessary flags for it. I wouldn't mind. But retiring this theme, I certainly mind, a lot.

**Comment by vogella** [comment]
@matthiasbecker how does it look on Mac?

**Comment by mickaelistria** [comment]
I've thought a bit more about it, as I agree 1 goal is to remove the System theme all together and replace it with native. The blocking issue is the default CTabRendering of e4 that makes it hard to find out which current CTabFolder has focus. I'll try to keep it in mind and hopefully will be able one day to improve that in SWT directly.
I've reported https://github.com/eclipse-platform/eclipse.platform.swt/issues/55 to SWT to fix this problem at its root. When it's fixed, I think we can just remove the System theme and use no theme instead.

**Comment by vogella** [comment]
I was trying to reduce the styling to only style the tab folder but only styling the tab results in an endless loop, see #4

**Comment by mickaelistria** [comment]
I plan to remove the System theme as soon as https://github.com/eclipse-platform/eclipse.platform.swt/pull/183 is merged.

**Comment by vogella** [comment]
Windows looks really good with the forms fix and theming disabled. @mickaelistria do you still plan to delete the system theme, or do you still need it for Linux?

**Comment by mickaelistria** [comment]
In any case, I think it's better to remove it and focus attention on SWT itself. I don't plan to maintain the System theme further. So I will try to remove it soon-ish.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/142
