### ISSUE TITLE
3 UI tests fail since I20220420-1800

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#30]
See https://download.eclipse.org/eclipse/downloads/drops4/I20220420-1800/testresults/html/org.eclipse.ui.tests_ep424I-unit-cen64-gtk3-java11_linux.gtk.x86_64_11.html

On all platforms they are failing now:

- UIComparePreferencesAuto.testCompareViewersPref
- DeprecatedUIPreferencesAuto.testFieldEditorEnablePref
- DeprecatedUIPreferencesAuto.testFontEditorsPref

This is a regression from https://github.com/eclipse-platform/eclipse.platform.team/pull/14 commit https://github.com/eclipse-platform/eclipse.platform.team/commit/3b042694088b273c9c37bdcfbf36b249bf46b5e5

**Comment by jonahgraham** [comment]
I can see how UIComparePreferencesAuto.testCompareViewersPref was caused by the mentioned commit, and @T-Svensson and I have provided a PR for that (#31). But the other two failures do not fail when I run locally, and I can't understand why they would fail because of that change. I'll look at the 20220421 results tomorrow.

**Comment by vogella** [comment]
Merged https://github.com/eclipse-platform/eclipse.platform.ui/pull/31, thanks @jonahgraham

**Comment by jonahgraham** [comment]
The 20220421 still has same failures and the PR #31 build results are gone already :-( 

Since I can't reproduce locally, I will create some dummy PRs to see if I can debug the problem that way.

**Comment by jonahgraham** [comment]
These tests:
- DeprecatedUIPreferencesAuto.testFieldEditorEnablePref
- DeprecatedUIPreferencesAuto.testFontEditorsPref

only failed if run after:
- UIComparePreferencesAuto.testCompareViewersPref

So the fix in #31 does fix all of the above three cases.

In PR #36 I have provided the test fix to make sure tests clean up after themselves a bit better. See details in the PR.

**Comment by iloveeclipse** [comment]
Seem to fixed all the fails, thanks Johan.
