### ISSUE TITLE
Ctrl+E: Prepend parent directories when resources have the same name

### ISSUE THREAD

**Issue by fapdash** [eclipse-platform/eclipse.platform.ui#301]
When doing web development I often have html files that share the same name but are in different folders.
In Eclipses Ctrl+E menu I can't differentiate between and I'm left guessing and switching to files until I find the one I'm looking for.

The workaround that I found works by going through "Open Resources" and searching for "${foldername}/${filename}" but I think the Ctrl+E menu should also support this use case.

### Current state
![Selection_191](https://user-images.githubusercontent.com/459631/187322012-b4b50215-377d-4639-bc08-e892cb396053.png)

### Proposed solution
![Selection_214](https://user-images.githubusercontent.com/459631/187322040-73cbc3bd-6246-4dd1-89b5-2e09de9ab47b.png)

---

Transferred from https://bugs.eclipse.org/bugs/show_bug.cgi?id=576994

**Comment by mickaelistria** [comment]
This ia not something that can be fixed on Wild Web Developer but more on Platform. Closing it here.

**Comment by laeubi** [comment]
> This ia not something that can be fixed on Wild Web Developer but more on Platform. Closing it here.

So why you are closing it on **Platform** then? :-)

**Comment by mickaelistria** [comment]
Oops, sorry! Let's reopen.
