### ISSUE TITLE
org.eclipse.swt.SWTException: Device is disposed during  "Animation start".

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#303]
IIRC @jukzi asked a while ago for an example how to reproduce the Device is disposed example during  "Animation start". I didn't do that that this point in time, as the functionality seemed useless and I removed it, later we found that is provides progress in the Windows taskbar and we restored it.

So here is the reproduced:

Import org.eclipse.e4.core.tests from eclipse.platform repo
Open MessageRegistryTest
Run it as plug-in test

You see the following stacktrace in the console:

!MESSAGE An internal error occurred during: "Animation start".
!STACK 0
org.eclipse.swt.SWTException: Device is disposed
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1254)
	at org.eclipse.swt.widgets.Display.asyncExec(Display.java:793)
	at org.eclipse.ui.progress.UIJob.run(UIJob.java:84)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by laeubi** [comment]
Is this probably:
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/283
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/276

**Comment by jukzi** [comment]
> Is this probably:

exactly. duplicate.

Thanks for sharing @vogella

**Comment by laeubi** [comment]
Duplicate of #276
