### ISSUE TITLE
Progress View sometimes shows short living jobs twice

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#307]
It's the identically job that was scheduled again. The old jobInfo is still shown when the new Jobinfo is added.

![image](https://user-images.githubusercontent.com/51790620/187929112-5f57f281-1aa3-40f0-941b-8d7d1b397366.png)

Mostly annoying because it that it makes the heights of the progress view flickering.

**Comment by merks** [comment]
For me the progress bar is pretty much always jittery never progressing toward completion but rather always restarting after a little flash of green.  Something is badly wrong here.

![image](https://user-images.githubusercontent.com/208716/188895119-ff59050d-9270-4559-b53b-28537da3ff61.png)

![image](https://user-images.githubusercontent.com/208716/188895179-ca6d4e9c-7665-4af0-ad54-809504bb694b.png)

One would expect the bar to represent the % value we see...

**Comment by iloveeclipse** [comment]
@merks : I believe it is a different issue, could you create a dedicated ticket for it?

**Comment by jukzi** [comment]
> For me the progress bar

the progress *bar* is unrelated to the progress *view* ?!

**Comment by merks** [comment]
I opened this:

https://github.com/eclipse-platform/eclipse.platform.ui/issues/327
