### ISSUE TITLE
If the Preferences window could save the last used size

### ISSUE THREAD

**Issue by iraidaa** [eclipse-platform/eclipse.platform.ui#347]
Hello,

I'm writing to you on behalf of DBeaver, Eclipse RCP application. Some of our users would like the Preferences window to be the fixed size or save the last size they use. They say that it would be more pleasant for them to work with the app. We agree that the default Preferences window size can be considered relatively small.

It would be great to add such a feature.

Thanks in advance.

**Comment by Baytars** [comment]
I'm not sure if, like p2.ui having its own SDK (p2.ui.sdk) to allow customization of RCP update, preferences window has, too, to allow functional extension of the UI.

Reference: [Equinox/p2/Adding Self-Update to an RCP Application](https://wiki.eclipse.org/Equinox/p2/Adding_Self-Update_to_an_RCP_Application)

**Comment by elsazac** [comment]
@iraidaa I tested this and looks like it has been fixed in Eclipse version 4.30. Can you check and let me know?

**Comment by BeckerWdf** [comment]
Was implemented with https://github.com/eclipse-platform/eclipse.platform.ui/pull/964

**Comment by merks** [comment]
Let’s assume it’s fixed.
