### ISSUE TITLE
Dark theme dark text issue

### ISSUE THREAD

**Issue by qasimshahid** [eclipse-platform/eclipse.platform.ui#349]
Firstly, forgive me as I'm not a very technical user of Eclipse, I just use it for my school work.

I'm having an odd issue where the dark theme has black text on the preferences menu in the dark theme. I'll provide photos of what I mean. Additionally, all my taskbars are white in color when they should be black because I'm using the dark theme for Windows.
Is this a bug or an issue only I'm facing? How do I fix this? 

I have tried uninstalling and reinstalling Eclipse to no avail. I'm on the latest build of Windows 11, if that information is needed. 

![image](https://user-images.githubusercontent.com/106047063/191403854-57fceb10-558e-4038-ab42-0c1523f05104.png)

![image](https://user-images.githubusercontent.com/106047063/191404017-acd24e6c-f10b-4a0c-a717-a1f0a8c18fa9.png)

**Comment by vogella** [comment]
IIRC this only happens if you Windows installation is older. You you update your Windows installation?

**Comment by qasimshahid** [comment]
> 

I’m on the latest release version of Windows 11

**Comment by qasimshahid** [comment]
I tried fixed it on my own. Alas, I think I'll just move to IntelliJ because I'm not too fond of Eclipse anymore.
