### ISSUE TITLE
[Tests] Few org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest tests fail on windows in the I-Build

### ISSUE THREAD

**Issue by ktatavarthi** [eclipse-platform/eclipse.platform.ui#371]
The below tests in org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest fail on [windows  ](https://download.eclipse.org/eclipse/downloads/drops4/I20220928-1800/testresults/html/org.eclipse.ui.tests_ep426I-unit-win32-java11_win32.win32.x86_64_11.html)

 - testMultipleFilesWithSharedParentFoldersButNotAllShareTheSameParentFolders
```
Text should have parent folder prepended expected:<[bar/]example.txt> but was:<[C:bar\]example.txt>

junit.framework.ComparisonFailure: Text should have parent folder prepended expected:<[bar/]example.txt> but was:<[C:bar\]example.txt>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.TestCase.assertEquals(TestCase.java:253)
at org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest.testMultipleFilesWithSharedParentFoldersButNotAllShareTheSameParentFolders(WorkbookEditorsHandlerTest.java:212)
```
 - testMultipleFilesWithSharedParentFolders
 ```
Text should have first differing folder and the mark for collapsed matching folders prepended expected:<test2[/.../]example.txt> but was:<test2[\...\]example.txt>

junit.framework.ComparisonFailure: Text should have first differing folder and the mark for collapsed matching folders prepended expected:<test2[/.../]example.txt> but was:<test2[\...\]example.txt>
at junit.framework.Assert.assertEquals(Assert.java:100)
at junit.framework.TestCase.assertEquals(TestCase.java:253)
at org.eclipse.ui.tests.internal.WorkbookEditorsHandlerTest.testMultipleFilesWithSharedParentFolders(WorkbookEditorsHandlerTest.java:182) 
 ```

**Comment by mickaelistria** [comment]
@fapdash Can you please have a look?

**Comment by fapdash** [comment]
At first glance`testMultipleFilesWithSharedParentFolders` test failure looks like an error in the test (not using `File.separator` for the expected value), but the `testMultipleFilesWithSharedParentFolders` looks like some Windows specific behavior that I didn't anticipate.

I'll have access to a Windows machine over the weekend and will investigate.

**Comment by iloveeclipse** [comment]
Regression from https://github.com/eclipse-platform/eclipse.platform.ui/pull/302.
Yes, this is path separator problem, so test only issue, but nevertheless would be good to fix it soon.
