### ISSUE TITLE
jface Updated the snippets wiki

### ISSUE THREAD

**Issue by wimjongman** [eclipse-platform/eclipse.platform.ui#384]
I have updated the jface snippets wiki because it was still using git.eclipse.org references. 

https://wiki.eclipse.org/JFaceSnippets

Since the wiki is deprecated, please let me know where this content should go and I will take care of it.

**Comment by laeubi** [comment]
@wimjongman what about Javadoc snippets?

https://docs.oracle.com/en/java/javase/18/code-snippet/index.html

Beside that, we have a wiki at https://github.com/eclipse-platform/eclipse.platform/wiki or can use github pages or ...

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/Snippets.md is what we did for swt.

**Comment by wimjongman** [comment]
Thanks, guys. I will do the same for JFace.

**Comment by mbooth101** [comment]
Hi @wimjongman FWIW I just added a new JFace snippet -- should I add it to the wiki still? Or will you pick it up in the conversion to markdown?

**Comment by wimjongman** [comment]
Hi Mat. Please add it to the old wiki then I will convert all to the new.

**Comment by vogella** [comment]
The JFace Snippets page is now here: https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/docs/JFaceSnippets.md I close this issue assuming that if actions are required, a PR is sufficient
