### ISSUE TITLE
Bad first impression (HiDPI, dark mode, …)

### ISSUE THREAD

**Issue by ctron** [eclipse-platform/eclipse.platform.ui#388]
Downloading a fresh Eclipse IDE and starting it, switching to the "light" theme gives you this:

![image](https://user-images.githubusercontent.com/202474/194242924-f8861a36-0f54-497c-be8e-fa96810d82a5.png)

And this is not new, this is there for years now.

What needs to be fixed (IMHO):

* When "Light" is set as theme, all widgets should be rendered in "Light" colors
* There should be no "light text" on "light widget"
* Icons should be scaled on HiDPI images
* Widgets should be sized correctly, so that texts fits into them and doesn't get truncated (in may cases the font size seems correct, but the widget too small). I guess the same is true for some buttons/icons, as one can see artifacts around them.
* Workaround settings to tweak this should come out of the box.

System: Fedora 36, KDE … and just to be clear. I only have such problems with the Eclipse IDE. All other applications I use work just fine!

**Comment by ctron** [comment]
Applying the following fixes makes the IDE at least usable:

```shell
#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

export GDK_DPI_SCALE=1.25
export GTK_THEME=:light

exec "$DIR/eclipse" "$@"
```

Which gives the following, which I would expect out-of-the box:

![image](https://user-images.githubusercontent.com/202474/194245345-86fc5baf-53e8-4942-a764-5328675b113c.png)

However, it is difficult to figure out and apply.

**Comment by akurtakov** [comment]
So I assume this is Linux with default dark theme, right? Which DE (probably doesn't matter but just in case)?

**Comment by ctron** [comment]
Yes, dark theme on the DE.

> System: Fedora 36, KDE … and just to be clear. I only have such problems with the Eclipse IDE. All other applications I use work just fine!

**Comment by akurtakov** [comment]
In order to rule out SWT bug here and blame Platform theming only have you tried to disable theming entirely and how do things look in this case?

**Comment by mickaelistria** [comment]
I opened https://github.com/eclipse-platform/eclipse.platform.ui/issues/390 about the theming issue.
I think other bugs are about hidpi support, and may already be reported so I didn't open them. I'll let someone more knowledgeable with this topic open new issues if necessary.

**Comment by mickaelistria** [comment]
Let's close thise issue which is not on the right grain. Each particular issue is worth a dedicated ticket.
