### ISSUE TITLE
"Project->Build Automatically" setting not persisted after restart

### ISSUE THREAD

**Issue by nimo23** [eclipse-platform/eclipse.platform.ui#395]
Each time Eclipse is restarted, the "Project->Build Automatically" setting is turned off even though it was on. This is annoying because every time you restart Eclipse you have to remember that you have to reactivate the check mark "Project->Build Automatically"(because this setting is lost with every restart).

Version: 2022-12 M1 (4.26.0 M1)

**Comment by iloveeclipse** [comment]
It's Oomph, please remove rhis setting from user settings and be happy.
