### ISSUE TITLE
[jface] Certain ImageDescriptor classes should be adaptable for some internal properties

### ISSUE THREAD

**Issue by Dani-Hub** [eclipse-platform/eclipse.platform.ui#396]
This issue is a follow-up of the suggestion by @laeubi in [issue comment-1270353935](https://github.com/eclipse-platform/eclipse.platform.ui/pull/385#issuecomment-1270353935) to open a new issue that suggests increasing the testability of certain ImageDescriptor subclass properties. I'm starting with two motivating use-cases, which are completely orthogonal but could be solved by the same approach:

1. In method [MenuHelper#getIconURI](https://github.com/eclipse-platform/eclipse.platform.ui/blob/849e023520392865995477474ef731f5302edbda/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/menus/MenuHelper.java#L463) it is attempted to retrieve an URL (or URI) from a given `ImageDescriptor` subclass. The first three parts of that attempt consist of reflection-based techniques, followed by a the "adaptable pattern" to realize this. It turns out that the very general very first step (which assumes that classes whose name ends with "URLImageDescriptor" do have a special meaning) caused problems in my companies code base, because we also provide a `ImageDescriptor` that falls into this naming pattern but where this approach fails (I cannot go into the details here). In fact, it would be easily possible for us to make our class adaptable to fit that purpose of this method, but since the name pattern happens first and no other case is tested, we would be required to rename our class, which is hard to justify.
2. In PULL request #385 I had provided an improvement of the internal `ImageFileNameProvider` implementations of `URLImageDescriptor` and `FileImageDescriptor`, but it turned out that the current implementation state made it extremely hard to actually test the correctness of those `ImageFileNameProvider` improvements, since there is no direct or indirect way to call them under controlled zoom values.

This issue suggests to let certain package-private `ImageDescriptor` classes (such as `FileImageDescriptor` and `URLImageDescriptor`) implement the `org.eclipse.core.runtime.IAdaptable` interface to allow to retrieve certain otherwise inaccessible properties for _internal_ reasons such as testability (See bullet 2 above) or to convert to an URL/URI in (See bullet 1 above) as alternative to reflection-based approaches. Note that this issue intentionally does *not* suggest to let the public, abstract class `ImageDescriptor` implement that interface because this issue doesn't intent to make this generic query API part of the public API. Of-course this issue doesn't prevent a future decision to support this case, but that would be a different request.

Both examples can be solved independently and since the submitter assumes that possibly not the same enthusiasm may exist to support both cases, independent PULL requests will be provided to demonstrate the usefulness. I'm starting with the originally motivating case (bullet 2). If that PULL request becomes accepted, I will (depending on further feedback from reviewers) possibly suggest a second PULL request for bullet 1.

**Comment by laeubi** [comment]
`IAdaptable` seamms a very good idea I think as it both decouples us from adding new API as well from implementation details and is very flexible! For example getting the URL or File from File/URLImageDescriptor seems a valid use-case for different purpose.

**Comment by Dani-Hub** [comment]
@laeubi I think that we can close this issue now (as resolved). The main idea - introduction of `IAdaptable` to some internal `ImageDescriptor` classes and testability of the internal `ImageFileNameProvider`s has been realized. My planned follow-up work is now issue #401 where I would implement adaption to `java.net.URL` for certain internal `ImageDescriptor` classes and use this adaption to solve the issues with [MenuHelper#getIconURI](https://github.com/eclipse-platform/eclipse.platform.ui/blob/63b65f971ccc8b165774365d1dfc10e8888059f5/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/internal/menus/MenuHelper.java#L456) described in that issue in detail.

**Comment by mickaelistria** [comment]
Closed as per request.
