### ISSUE TITLE
[jface] Improve URLImageDescriptor and its ImageDataProvider

### ISSUE THREAD

**Issue by Dani-Hub** [eclipse-platform/eclipse.platform.ui#399]
During my work on #397 I observed the following opportunities of improvement in `URLImageDescriptor` in relation to its underlying `ImageDataProvider`:

1. It is currently not possible to test the correct zoom behaviour because no access to the `ImageDataProvider` currently exists. For the underlying `ImageFileNameProvider` it was found by making it testable (See [issuecomment 1272352893](https://github.com/eclipse-platform/eclipse.platform.ui/pull/397#issuecomment-1272352893)) that the previous implementation was defect. We should take advantage of the new `IAdaptable` implementation of `URLImageDescriptor` by #397 to also support a query for its underlying `ImageDataProvider`.
2. In Issue #398 it has been observed that we should optimize the underlying `ImageFileNameProvider` to be represented by a single instance. The same approach could be done for the `ImageDataProvider` as well.
3. During my work fixing the `ImageFileNameProvider` I noticed that also the `ImageDataProvider` could be optimized for the 100% zoom case as well. We should do that here as well to prevent unnecessary tests for xPath and xName in that situation.

**Comment by Dani-Hub** [comment]
I would like to withdraw the suggestion in bullet (1) above (but not the others), for the reason that the underlying `ImageDataProvider` of `URLImageDescriptor` is _indirectly_ testable through the public `getImageData(int zoom)` and this method *is* currently used to test the correctness depending on specific zoom values. Nonetheless both bullet (2) and (3) still apply and I'm planning my upcoming PULL requests on those two aspects.

**Comment by Dani-Hub** [comment]
I think we can close this issue now, resolved by #400.

**Comment by akurtakov** [comment]
As per previous comment.
