### ISSUE TITLE
Wrong source

### ISSUE THREAD

**Issue by andreasdc** [eclipse-platform/eclipse.platform.ui#436]
When I open reference using F3 it shows source code from libraries not from the project list.

**Comment by akurtakov** [comment]
Please provide exact steps to reproduce the issue preferably with test project, what's expected and what is actually shown. The issue is non actionable with current information.

**Comment by andreasdc** [comment]
1. Have a project.
2. Press F3 on some reference from another project.
3. The source code is not picked up from the project in your workspace, but the one from the library.

**Comment by mickaelistria** [comment]
This case works as expected for me; your issue can typically highlight some incorrect project configuration
This is more likely an issue with JDT. Please report issue to https://github.com/eclipse-jdt/eclipse.jdt.ui/ , with some example workspace to reproduce.

**Comment by trancexpress** [comment]
> 1. Have a project.
> 2. Press F3 on some reference from another project.
> 3. The source code is not picked up from the project in your workspace, but the one from the library.

Can you attach a small reproducer? What type of projects do you use? E.g. Java project, plug-in project, etc.?

**Comment by andreasdc** [comment]
Java project
