### ISSUE TITLE
Disappearing code

### ISSUE THREAD

**Issue by andreasdc** [eclipse-platform/eclipse.platform.ui#442]
When I do ctrl + z to maximum, then I return using ctrl + y, most of the code got deleted.

**Comment by trancexpress** [comment]
Please provide steps to reproduce, if you can also a screen recording. What type of editor do you use (`.java`, `.txt`, etc.), what OS are you on (Linux, Windows, etc.)?

Without extra info this can only get closed.

**Comment by andreasdc** [comment]
Java, windows 10. Steps to reproduce are what I described. Maybe small missclick ruins that, but I think I remember I didn't do missclick and it happened.

**Comment by iloveeclipse** [comment]
Can't reproduce. If you see the problem again, please provide **exact** steps to reproduce.

**Comment by andreasdc** [comment]
> Can't reproduce. If you see the problem again, please provide **exact** steps to reproduce.

Maybe during undoing you have to missclick some letter or something, then all is lost. I had this situation happen couple times, I don't remember missclicks.

**Comment by andreasdc** [comment]
It happens because of missed key, while redoing you can press any key instead of Y and your code goes to trash.
