### ISSUE TITLE
[Only for Windows] ToolBar gets resized when mixing ToolItems with text(no icon) and with items with icons

### ISSUE THREAD

**Issue by GuilhermeSaraiva96** [eclipse-platform/eclipse.platform.ui#443]
When mixing ToolItems with only text and with icons, the ToolBar resizes not only the height but also the width of the ToolItems weirdly on Windows, on Mac everything is working fine. This happens on ManagedForm's Toolbars:

![image](https://user-images.githubusercontent.com/100677558/200785532-0b5636bc-e0f8-4a9a-91e9-b4cc5d1a32bf.png)

Found the bug in bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=383307

Source Project:
[bug_project_example.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/9969164/bug_project_example.zip)

**Comment by marcushoepfner** [comment]
The bugzilla link is not working :(

**Comment by laeubi** [comment]
> The bugzilla link is not working :(

I fixed the link...

**Comment by marcushoepfner** [comment]
[Bugzilla 383307](https://bugs.eclipse.org/bugs/show_bug.cgi?id=383307) links [Eclipse Snippet 36](https://bugzillaattachments.eclipsecontent.org/bugs/attachment.cgi?id=217739) which shows the problem.

**Comment by Christopher-Hermann** [comment]
Found a way to fix this issue in the SWT Toolbar for Windows. I'm not an expert in this area, hence I'm not sure if there are any unintentionally side effects. At least while testing I didn't find any issue with this solution.

Toolbar on Windows with the fixed coding:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/79514265/207303905-b496395c-019e-467f-a83b-5dd2bda559e1.png">

**Comment by marcushoepfner** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/pull/499 has been closed.
So I close this one.
Thanks @Christopher-Hermann  for fixing.
