### ISSUE TITLE
SDK application should start on the Resources perspective (instead of Java)

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.ui#448]
The Resource perspective is by far enough in most cases to use the SDK. Most of the necessary parts of JDT (views, actions) are either easily accessible in the Resource view, or will pop-up at relevant times.

**Comment by merks** [comment]
What are the cases to use the SDK?  How do we know what most of them are?   Something indicates that most will want the Project explore not the Package explorer and that most will not need the Problems view?  I thought the SDK was primarily used for Java development, and even plug-in development, given JDT and PDE are present, but I could be wrong...

**Comment by mickaelistria** [comment]
>  I thought the SDK was primarily used for Java development, and even plug-in development, given JDT and PDE are present, but I could be wrong...

OK, so let's use the Plug-in perspective by default then.

**Comment by iloveeclipse** [comment]
Why can't we leave things "AS IS", is there any reason to change the current state?
Any product based on SDK might customize any aspect of it, including default perspective, so if some product needs now "Resources" perspective, I would expect that to be done in the product.

SDK used a lot in automated tests (also in 3rd party tests), so if there is no good reason for change, I would just leave it in the current state.

**Comment by trancexpress** [comment]
> Why can't we leave things "AS IS", is there any reason to change the current state?

+1 from me, this issue looks like we want to change things for the sake of changing things.

**Comment by laeubi** [comment]
Whats SDK we are talking about? The Platform (devlopment) SDK?

Because if I look at:

https://github.com/eclipse-platform

the screenshot of "The SDK" (it says Eclipse SDK in the window title) seem to use the resource perspective already?

**Comment by trancexpress** [comment]
> Whats SDK we are talking about? The Platform (devlopment) SDK?

I assumed the issue was about builds downloaded from here: https://download.eclipse.org/eclipse/downloads/

For those, the Java perspective is the default one.

**Comment by elsazac** [comment]
looks like we don’t have a consensus on this? In the absence of more discussions / convergence, should we close this? @mickaelistria - WDYT?
