### ISSUE TITLE
Import projects wizard asks whether to overwrite .settings

### ISSUE THREAD

**Issue by PetrSlaby** [eclipse-platform/eclipse.platform.ui#452]
Reproduced with Eclipse IDE for Java Developers Version: 2022-06 (4.24.0). The same problem exists in any RCP application based on the same platform.

Select File ->Import->General->Existing Projects Into Workspace

Select a folder containing an Eclipse project. To reproduce, the folder must be outside of the active workspace and the imported project must contain a .settings directory.

Check "Copy projects into workspace"

Click Finish.

A dialog appears asking "Overwrite '.settings' in the folder 'XY'? This is quite surprising for the user as they are importing a project which did not exist in the workspace yet and there should be nothing to overwrite.

The problem seems to be triggered by the feature to explicitly set an encoding on new projects https://www.eclipse.org/eclipse/news/4.24/platform.php#explicit-encoding-projects The wizard creates a new project first (org.eclipse.ui.internal.wizards.datatransfer.WizardProjectsImportPage line 1422), which already produces the resource .settings/org.eclipse.core.resources.prefs. The confirmation dialog comes if the imported project contains .settings as well (even if it does not contain org.eclipse.core.resources.prefs)

**Comment by elsazac** [comment]
possibly same issue as reported in https://github.com/eclipse-platform/eclipse.platform.ui/issues/617 . Either way, a fix is proposed in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1519. @PetrSlaby - are you in a position to test the change?  thanks.

**Comment by PetrSlaby** [comment]
@elsazac I have patched our Eclipse based application with the fix proposed in #1519 and it really solves the issue which I was reporting. The overwrite .settings confirmation dialog does not appear any more.

**Comment by elsazac** [comment]
Thanks for your confirmation.

**Comment by elsazac** [comment]
@merks Just to let you know, the linked PR hasn't been reviewed or merged yet.

**Comment by merks** [comment]
Sorry.

**Comment by elsazac** [comment]
This is most likely the same issue that was reported in #617, and the suggested patch #1519 has been merged. So this could be closed?
