### ISSUE TITLE
When CTabRendering renderer is extended the shortenedText in the tab is sometimes written

### ISSUE THREAD

**Issue by opcoach** [eclipse-platform/eclipse.platform.ui#462]
It is possible to change the tab folder renderer (CTabFolderRenderer) and it has been done with CTabRendering : 

![image](https://user-images.githubusercontent.com/1716878/203970422-5dd6f6f7-c094-4663-b484-431aa8970383.png)

Unfortunately, if we extend again the CTabRendering for some advanced customization, the text in the tab folder is sometimes shortened. This is due to this ugly patch in CTabFolderRenderer which test if the current renderer is a possible CTabRendering !!?? 

![image](https://user-images.githubusercontent.com/1716878/203971288-e401d029-ac51-4f65-8056-b906eac68786.png)

So updateCurves should be defined protected and overriden empty in CTabRendering.

**Comment by opcoach** [comment]
Additional remark.. 

The CTabFolderRenderer is defined in each swt fragment for each os (org.eclipse.swt.cocoa.macosx.x86_64_xxxxx.jar
, org.eclipse.swt.win32.win32.x86_64_xxxx.jar) and the code is the same ! 

So modification must be done in all these fragments.. 

I guess this is the same problem for linux...

**Comment by akurtakov** [comment]
CTabFolder (and supporting classes) is already a total nightmare to support so whoever wants to open more of it to the world to make it even harder should be ready to provide the support next time it breaks and even more downstreams will break with a fix. 
I have a strong -1 for such proposal.

**Comment by opcoach** [comment]
What I propose is to allow to make CTabRendering extendable.. just changing the test on the subclass and to redefine the method as empty in CTabRendering.. 

But I agree this class, implementation and content is really a nightmare !!  I guess the linux gtk version is a copy of it also... ? 

We have the problem on a project to customize the min, max buttons.. which are drawn using gc draw instead of using images.. and we would like to be able to override the drawMinimize or drawMaximize (see issue #463) ... 

May be these bugs could be moved to the swt project ... as the code is there... ?

**Comment by akurtakov** [comment]
This is not a copy/paste but same source compiled in the different fragments as most of the other classes are WS-specific.

**Comment by opcoach** [comment]
I opened another but on the swt project :

https://github.com/eclipse-platform/eclipse.platform.swt/issues/474

Fixing the current bug needs to have the swt one fixed

**Comment by opcoach** [comment]
I will propose a PR  in CTabRendering that will simply override the computeSize to avoid to call the 'updateCurves' that cause the trouble...

**Comment by opcoach** [comment]
This issue is out of date and may be reconsidered later.
