### ISSUE TITLE
Quick Search show search term in title bar to support multiple search windows

### ISSUE THREAD

**Issue by MisterScott** [eclipse-platform/eclipse.platform.ui#478]
Please display the search term in the title bar of the search window.
Request:  when multiple Quick Search windows are open, currently they are all titled "Quick Search".  When minimized to the title bar, they are anonymous, making it difficult to find the one desired and to avoid duplicate windows (when duplicates are not desired; sometimes I want to keep old search results AND have new search results).  
Please display the search term in the title bar.
Currently using:
Eclipse IDE for Embedded C/C++ Developers (includes Incubating components)

Version: 2022-06 (4.24.0)
Build id: 20220609-1112
With QuickSearch plugin:
	Eclipse.org	Quick Search	1.1.300.v20211203-1705	org.eclipse.text.quicksearch

**Comment by mickaelistria** [comment]
would you be willing to submit a pull request that changes that?

**Comment by elsazac** [comment]
https://github.com/eclipse-platform/eclipse.platform.ui/blob/c1d22a3cb5983dc5ec091af3239cd5aaad8fc85f/bundles/org.eclipse.text.quicksearch/src/org/eclipse/text/quicksearch/internal/ui/QuickSearchDialog.java#L1269

I tried `this.settitle()` in this location with the filter text but for some reason the title is not refreshing. searching in the code base I didn't see any examples of dialog titles being changed after creation, so not sure if I am missing something.

**Comment by merks** [comment]
Yes, the title is used only as a convenience to configure the title of the shell (so it can be set before the shell is even create):

https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/dialogs/SelectionDialog.java#L75C1-L80C3

**Comment by elsazac** [comment]
@merks you mean to say that the setTitle has no effect after the dialog has been created? I see some APIs (e.g. setShellStyle) that says it has no effect once it is displayed. Is setTitle one of those type? it is not mentioned in its javadoc explicitly though.

@MisterScott - given that the dialog title cannot be changed at runtime, is any other workaround acceptable to you? for example a header label / a status bar that reflects the search text ?

**Comment by merks** [comment]
Looking at the implementation answers that question.  The implementation could be smarter.

**Comment by elsazac** [comment]
@merks Thanks for the pointers.
