### ISSUE TITLE
Windows11: Missing Font-Properties-File in Bundle org.eclipse.jface

### ISSUE THREAD

**Issue by Rainer7000** [eclipse-platform/eclipse.platform.ui#488]
There is no Default-Font-Properties-File in Bunlde org.eclipse.jface for Windows 11

org.eclipse.jface_3.28.0.v20221024-1426\org\eclipse\jface\resource\jfacefonts_**windows11**.properties

As a result the default-fonts look outdated under Windows11 due to the fallbacks in FontRegistry#readResourceBundle.

**Comment by iloveeclipse** [comment]
@ConradGroth : you provided via 4c9741c62a49505a3ee4c09bea927a2db511cdf0 last change in this area.
Could you check what is needed for Windows 11?
Is this same as for 10?

**Comment by ConradGroth** [comment]
@iloveeclipse sorry, I don't have Windows 11 running. I cannot prove, what's needed here.

**Comment by iloveeclipse** [comment]
Thanks Conrad.
@SyntevoAlex : something for you?

**Comment by SyntevoAlex** [comment]
Sorry, I'm only focused on SWT.

**Comment by SyntevoAlex** [comment]
@ConradGroth with VirtualBox 7.0, Win11 can easily be installed in a VM.

**Comment by Rainer7000** [comment]
I tried patching the bundle locally by just copying jfacefonts_windows10.properties to jfacefonts_windows11.properties. As far as I can tell the fonts look good. The main issue was that the default text-font was set to **Courier** instead of the more modern **Consolas** in Windows 10 and 11.

**Comment by vogella** [comment]
I have no windows at the moment to test, can you add "before" and "after" screenshots to this issue?

**Comment by iloveeclipse** [comment]
Is this fixed via https://github.com/eclipse-platform/eclipse.platform.ui/pull/744 or is something left open?

**Comment by Rainer7000** [comment]
Yes this is fixed.
