### ISSUE TITLE
SashLayout should provide public fields 

### ISSUE THREAD

**Issue by opcoach** [eclipse-platform/eclipse.platform.ui#489]
The layout usage is to have public fields to be able to modify directly the values like in the [GridLayout](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/common/org/eclipse/swt/layout/GridLayout.java) or in [BorderLayout](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/common/org/eclipse/swt/layout/BorderLayout.java). 

The [org.eclipse.e4.ui.workbench.renderers.swt.SashLayout](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/SashLayout.java) provides 6 parameters that can't be set using public fields or setter. 

That would be really handy to give access to modify them easily rather than to copy the class ... when a [SashRenderer](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/SashRenderer.java) should be redefined

![image](https://user-images.githubusercontent.com/1716878/207896296-d67853d3-a5a6-459d-8033-41ad9fb5f32c.png)

**Comment by trancexpress** [comment]
At least for `sashWidth` there was https://bugs.eclipse.org/bugs/show_bug.cgi?id=562536. Whatever is done here, the bug should not get re-introduced.

**Comment by opcoach** [comment]
This is not really the same bug .. SashLayout in its current version does not follow the policy used in other layouts (having public fields) ...  The bug you mention is still relevant and will not be disturbed by this fix .. 

So what do you suggest ? To close this one or can I provide a PR ?

**Comment by trancexpress** [comment]
See this commit: https://git.eclipse.org/c/platform/eclipse.platform.ui.git/commit/?id=6dcb5e8d493e11f0bcb045cfd7e8df67105a375d

```
diff --git a/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/SashLayout.java b/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/SashLayout.java
index d974d9c2430..78811fd1380 100644
--- a/[bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/SashLayout.java](https://git.eclipse.org/c/platform/eclipse.platform.ui.git/tree/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/SashLayout.java?id=b6aeb4039efbd963dfcb81f688986045941c129a)
+++ b/[bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/SashLayout.java](https://git.eclipse.org/c/platform/eclipse.platform.ui.git/tree/bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/SashLayout.java?id=6dcb5e8d493e11f0bcb045cfd7e8df67105a375d)
@@ -18,6 +18,7 @@ package org.eclipse.e4.ui.workbench.renderers.swt;
 import java.util.ArrayList;
 import java.util.List;
 import org.eclipse.core.runtime.Platform;
+import org.eclipse.e4.ui.internal.css.swt.ISashLayout;
 import org.eclipse.e4.ui.model.application.ui.MGenericTile;
 import org.eclipse.e4.ui.model.application.ui.MUIElement;
 import org.eclipse.e4.ui.workbench.IPresentationEngine;
@@ -31,7 +32,8 @@ import org.eclipse.swt.widgets.Layout;
 import org.eclipse.swt.widgets.Listener;
 import org.eclipse.swt.widgets.Shell;
 
-public class SashLayout extends Layout {
+@SuppressWarnings("restriction")
+public class SashLayout extends Layout implements ISashLayout {
 	// The minimum value (as a percentage) that a sash can be dragged to
 	int minSashPercent = 10;
 
@@ -230,6 +232,16 @@ public class SashLayout extends Layout {
 	}
 
 	@Override
+	public int getSashWidth() {
+		return sashWidth;
+	}
+
+	@Override
+	public void setSashWidth(int sashWidth) {
+		this.sashWidth = sashWidth;
+	}
+
+	@Override
 	protected void layout(Composite composite, boolean flushCache) {
 		if (root == null)
 			return;
```

Aside from the other code that was necessary just for `sashWidth` changing (one of the members you want to make public), the code was reverted due to introducing a regression (see comments in the bug).

So whatever is done here, the regression should not be re-introduced.

**Comment by opcoach** [comment]
Ok. I close it and wait for the final patch of original bug.

**Comment by trancexpress** [comment]
> Ok. I close it and wait for the final patch of original bug.

I don't think any more work will be done for https://bugs.eclipse.org/bugs/show_bug.cgi?id=562536, considering that the last changes were done in 2020. IMO its fine to have a github issue, the Eclipse bugzilla is supposed to be archived soon.

For this issue, its possible that other values you wish to make public are likewise not trivial to change. Though I didn't check the git history if there were attempts for this already.

**Comment by opcoach** [comment]
Ok, feel free to reopen it if necessary...  

I made a new SashRenderer for a project and I changed all the margin and sashWidth using public fields and the result is as expected. We can resize all the areas and margins and sashWidth are ok. Example on the java browsing perspective.

![image](https://user-images.githubusercontent.com/1716878/207912292-a6987cbe-7abb-440f-9c1c-493393fb5425.png)
