### ISSUE TITLE
Project wizzards should be shown below "New Project ..."

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#502]
Currently if one implements the extension point
https://help.eclipse.org/latest/topic/org.eclipse.platform.doc.isv/reference/extension-points/org_eclipse_ui_navigator_navigatorContent.html?cp=2_1_1_193#e.commonWizard

The wizard is displayed a bit random:

1. if **no group** is declared, it is showed together with the `New File` / `New Folder` group
2. if a **group is defined** it is shown below

But a wizard that has the property / tag "project" is a project wizard and therefore should better be displayed below `New Project ...`

![grafik](https://user-images.githubusercontent.com/1331477/210262610-68e20ec0-6727-4903-b438-15011357fb30.png)

**Comment by laeubi** [comment]
I could take a look at this issue but wondering where the menu is created? If someone can give a hint where to start, that would be useful.

**Comment by mickaelistria** [comment]
I think it's org.eclipse.ui.internal.navigator.resources.actions.NewActionProvider.
