### ISSUE TITLE
Wizard pages should be able to specify their minimum size

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform.ui#516]
For the m2e target dependency editor, I'd like to specify the minimum size the wizard page can have. Normally, I would do this via `WizardDialog.setMinimumPageSize()`. However, this dialog is created within PDE and therefore not accessible.

I can work around this limitation by calling `getContainer().getShell().setMinimumSize()`, but I'd prefer a cleaner solution for this.

It would be good if a IWizardPage would have a `getMinimumPageSize()` (and `getMaximumPageSize()`) (the default can just use getControl().computeSize(-1,-1)).

See also :
-  https://github.com/eclipse-m2e/m2e-core/pull/1157#issuecomment-1382603940

**Comment by HannesWell** [comment]
Are you interested in providing a PR for this?
I think there is not general objection against this change and with a specific change we can discuss it more explicitly.

**Comment by ptziegler** [comment]
It doesn't seem too complex to implement. I'll try to come up with something in the next few days.

**Comment by mickaelistria** [comment]
I believe you can simply configure the layoutData of the parent composite (or maybe  its parent) you receive when building a wizard page and that should affect the dialog. I don't remember the specific trick, but I believe I made it work once.

**Comment by ptziegler** [comment]
> I believe you can simply configure the layoutData of the parent composite (or maybe its parent) you receive when building a wizard page and that should affect the dialog. I don't remember the specific trick, but I believe I made it work once.

I've thought of that as well. But as far as I can tell, the minimum size in the layout is only a "soft" limit. If I set the minimum size to e.g. 800x600, then the created dialog will be of equal or larger size.

However, there is nothing stopping the user from manually adjusting the shell to a lower size, which is what I'd like to prevent.
