### ISSUE TITLE
slow marker sort (many markers)

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#53]
Sometimes when there is a severe error (like missing target platform)  in the workspace i end up with many problem Markers which are sorted quiet slow:
![image](https://user-images.githubusercontent.com/51790620/166679423-02172c56-b2f0-401f-bcc1-c31ed06d778b.png)

Looks like the slow thing is the language aware comparison.  I don't see much value of sorting problem message (usual english) by Locale aware Comparator. Even on german which has special sorting rules i would not need that feature. When i click on sort by description i just want to have same descriptions grouped.
Also i wonder if all those "performance optimizations " in MarkerSortUtil realy work as desired. It feels like the collatorcache is cleared too often. Also i wonder what that optimizations try to archive - getting the top(k) of n entries always has a minimal O(n+log(k)) which is not significant better than the trivial O(n*log(n)) when just sorting all entries.

**Comment by jukzi** [comment]
BTW org.eclipse.ui.tests.markers.MarkerSortUtilTest does use a trivial comparator instead of collator which is kinda insignificant for the actual usecase.

**Comment by laeubi** [comment]
Just curious, but maybe sorting with multiple threads can outweigh any 'special' optimization for the linear case? Sorting is most often good to be parallelized if significant magnitude of items are required or comparison of items if a non trivial operation.

**Comment by jukzi** [comment]
> Sorting is most often good to be parallelized

the sorting itself of hundret thousend items is no problem. the problem here is only calculating of collationKeys which has to be done for every every key once.

**Comment by jukzi** [comment]
wow, when i sort many problems by description the result is even not consistent and sometimes in the wrong order:
![image](https://user-images.githubusercontent.com/51790620/166870617-0cb791b8-2fd4-455b-bc60-ab9b401a3625.png)
when i order several times for the same column it seems to stabalize.
