### ISSUE TITLE
Dark mode: Toolbar background color vanished - toolbar rendering ugly

### ISSUE THREAD

**Issue by de-jcup** [eclipse-platform/eclipse.platform.ui#536]
## Situation
The background color changes in eclipse 2022-12 in multiple views

When I start eclipse on my Linux Mint machine (GTK) I see
![image](https://user-images.githubusercontent.com/11644753/215429224-ecc7c860-cf09-48da-8d8c-7d931cf13ded.png)

When I select something inside the tree (e.g. a Java project) The background color changes (and looks and keeps ugly after this):
![image](https://user-images.githubusercontent.com/11644753/215429818-07c328ad-2fac-4597-9ffc-e4d075dae921.png)

I think this is related to #467 

The console view does always show the wrong (ugly) background behavior.

**Comment by akurtakov** [comment]
Committers that used to work on dark theme are no longer that active so help is required in this area.

**Comment by de-jcup** [comment]
Hmm... tried out oomp-installer + platform IDE - starting Eclipse 2023-03 (master) I had following:

![image](https://user-images.githubusercontent.com/11644753/215443418-2cd6b7a3-73e2-4676-9ade-564d21f6401d.png)

The toolbar icons are now correct rendered with Theme "dark". Navigator and console view are looking good now/again.

So I think this has been already fixed for 2023-03 ? Shall I close the issue?

**Comment by akurtakov** [comment]
At least I'm not aware of any fix in that area in this cycle. Have you started with new workspace aka smth bad being cached up? Could it be some additional plugin installed causing issues with theming? I'm only guessing here.

**Comment by de-jcup** [comment]
Oh. It is still a problem. It was only correct rendered, because the toolbar was "on top". When reducing the size of the window, the toolbar is no longer rendered with the light grey background, but uses the dark one - this is also the problem with the not visible toggle situation from #467 : The Border has the same color like the dark background - so border for selection becomes invisible.
![image](https://user-images.githubusercontent.com/11644753/215466696-667c8a9a-fdd6-431c-ab56-e4ced1d15580.png)

**Comment by de-jcup** [comment]
@akurtakov

I temporarily changed the css syling  in e4-dark_globalstyle.css

```java
ToolBar {
/*	background-color:inherit;	*/
/*    background-color: #ff0000;*/
    background-color: '#org-eclipse-ui-workbench-DARK_BACKGROUND'
}
```
And I think this looks good:

![image](https://user-images.githubusercontent.com/11644753/215471673-9d266576-3728-4051-bd67-c9e5da591036.png)

![image](https://user-images.githubusercontent.com/11644753/215471824-1adefe5c-13a5-4e1b-81c8-1592616f5f15.png)

I could create a PR for this.

I think this will fix #467 as well (maybe there should be a dedicated border color but at least the toggle state is visible again)

**Comment by akurtakov** [comment]
please submit  a PR so more people test it.

**Comment by de-jcup** [comment]
@akurtakov - I created PR #536

**Comment by akurtakov** [comment]
I seem to be able to get the old rendering by clicking on e.g. buttons in Outline view: 
![image](https://user-images.githubusercontent.com/574788/215510111-fbcf77dd-299d-40f2-8328-845c5d632333.png)

**Comment by de-jcup** [comment]
Yes. I can reproduce it. (remark: when you resize the outline window it is correct rendered again)
I will investigate more and try to fix this as well.

**Comment by akurtakov** [comment]
OK, I'll resist merging this one as it's not clearly fixing the issue.

**Comment by vogella** [comment]
I think this is fixed with the recent changes of the dark theme by @mvm-sap. Please check again with the latest I-Build from https://download.eclipse.org/eclipse/downloads/
