### ISSUE TITLE
Regression caused by Ctrl+E: Prepend parent directories for file name collisions (#301 / #302)

### ISSUE THREAD

**Issue by sratz** [eclipse-platform/eclipse.platform.ui#547]
#301 / #302 introduced a feature to use segments of the path in case the names returned by `IEditorInput.getName()` are non-unique.

However, this broke scenarios in which the file name / path is intentionally **not** used in the editor input name, because, for example, the file system is virtual.

As an example this breaks SAP's ABAP Development Tools:

Before:
![image](https://user-images.githubusercontent.com/14908423/216344883-004066cc-f5cc-4b4e-9e67-529802365134.png)
After:
![image](https://user-images.githubusercontent.com/14908423/216344947-7007e6a4-8bbb-4df6-b1d2-f64bb2c0d8dc.png)

We use a custom file system implementation and the files do not really exist on disk, when calling `IPathEditorInput.getPath()` they are copied via `IFileStore.toLocalFile(EFS.CACHE, ...)` to a temporary cache file on disk.

Therefore, the assumption of change #301 / #302 that every editor that uses `IPathEditorInput` uses regular files on disk is not correct.

I am not sure how to solve this in a generic way.

One approach could be to limit the new handling to cases where `editorReference.getName()` is really equal to the actual file name that `iPathEditorInput.getPath().toFile().toPath().getFileName().toString()` produces.

**Comment by fapdash** [comment]
I think we could move the current collision handling into a default method on `IPathEditorInput`: `IPathEditorInput#distinguishableName(Entry<EditorReference, IPath> nameCollisions)`, something like that.
Clients overwriting `IEditorInput.getName()` then could also overwrite the `IPathEditorInput#distinguishableName()` method.

@sratz Are you interested in that? Of course that would introduce new public API that has to be maintained..

**Comment by sratz** [comment]
> I think we could move the current collision handling into a default method on `IPathEditorInput`: `IPathEditorInput#distinguishableName(Entry<EditorReference, IPath> nameCollisions)`, something like that. Clients overwriting `IEditorInput.getName()` then could also overwrite the `IPathEditorInput#distinguishableName()` method.
> 
> @sratz Are you interested in that? Of course that would introduce new public API that has to be maintained..

It's an interesting idea but it would need some fine-tuning. E.g.,
- for symmetry reason, this method should probably be purely based on either `EditorReference` or `IEditorInput`, not a mixture of both. It should probably also be not specific to `IPathEditorInput` but would reside next to the `getName()` method: `org.eclipse.ui.IEditorInput#distinguishableName(Set<IEditorInput> nameCollsions)`
- By delegating this to the individual editor inputs...
  - Is this method called for each of the collision? This would result in `O(... * N)` worse performance, as the comutation would be done N times, not just once, centrally.
  - How to make sure these collision are resolved in the same manner, if each editor input is asked?

An alternative could be the follows: Instead of resolving this collision by changing the name displayed in Ctrl-E, something distinguishable could be *appended* to the name, e.g.
![image](https://user-images.githubusercontent.com/14908423/216954137-171a3f99-0ef1-4a23-97e4-e3a8bedffa29.png)
similar to how it looks like in the outline:
![image](https://user-images.githubusercontent.com/14908423/216954358-50b80bf2-0b6d-4758-b836-bc5976f300ad.png)
or the project explorer

Then of course this additional String should probably also be provided by the `IEditorInput` implementation. Concretely, `FileEditorInput` would need to be adjusted to take such caching scenarios into account and return something better than the temporary cache path.


I guess all such new functionality would require some discussion.

If there are no objections, I would go ahead with my proposed workaround in #548 for now, and we can consider improvements in the next release(s) if needed.
