### ISSUE TITLE
quick-switch-editor now does nothing in 2022-12 workspace (works in 2022-06)

### ISSUE THREAD

**Issue by davidmichaelkarr** [eclipse-platform/eclipse.platform.ui#552]
I originally filed this here: https://bugs.eclipse.org/bugs/show_bug.cgi?id=581464 , but I was told to file it here instead.

I've been using 2022-12 for several weeks now, off and on with 2022-06 because of performance and deadlock issues with 2022-12.  I just noticed that the "quick-switch-editor" action in 2022-12 does nothing (bound to Ctrl+e).  There's no error dialog or entry in the log, it just does nothing.  I verified my key binding.  I use Emacs+ so I can easily verify the binding, and I can even directly execute the action.  When I do that (directly execute it using Emacs+), it reports just "Failed" (from Emacs+).  I did the exact same thing in 2022-06, and it works fine.  I have most of the same projects in both distributions (imported from the same git repositories, that is).

I also verified that I don't see this problem in my 2022-09 workspace.

I don't see any other problems with actions that present dialogs (or anything else, for that matter).

Note that when I say it does "nothing", It isn't actually doing "nothing", it's just not presenting the dialog.  If I press the key binding when the cursor is on a line I just moved to, a vertical blue "focus" bar moves to the method or block the cursor is in, and if the cursor is in a variable or type name, it also highlights that variable name in grey and highlights other nearby references in an orangish color.

I also wondered whether this is caused by the installation or the workspace, so I exited Eclipse, created another 2022-12 workspace, imported my saved preferences from 12/9/22, imported one of my many git repos and opened a file.  At that point, the action is working fine.  I then realized that I had made some preferences changes since that save back in December, so I reopened the workspace with the problem, saved my preferences (unfortunately, without thinking of making a copy of that saved file from December), exited, reopened the new workspace, imported the newer preferences, restarted, and now the action is not doing anything.

So, it seems like something in my preferences that were recently changed is related to this.  I know I recently made changes to the Console and LSP sections, but that's all I remember.

**Comment by merks** [comment]
Have you checked the key bindings for Ctrl+E to make sure it's really bound to the Quick Switch Editor command?

![image](https://user-images.githubusercontent.com/208716/216923392-12c8dd40-3a69-4bcf-a1ec-2072f0425b01.png)

**Comment by davidmichaelkarr** [comment]
Yes, and I did, and note that I pointed out that the key binding itself doesn't matter, as I'm able to execute the action directly using Emacs+, and it just says "Failed".

**Comment by merks** [comment]
Note that someone else will need to be able to reproduce the problem if you want someone else to fix it.  I cannot reproduce it nor can I comment on Emacs+ because I don't have that installed.  Maybe the problem only happens when you have Emacs+  installed, in which case it's not a problem the Platform can fix.  Please try to reproduce the problem in a from-scratch installation that someone else can follow those steps...

**Comment by davidmichaelkarr** [comment]
I've noticed that when I create a new workspace, it seems to work for a while. I just noticed now that it wasn't working, although I know it was working yesterday. I didn't even restart Eclipse.  I've even found a very odd pattern that allows me to toggle it working or not working.

I am also using the Mylyn plugin, and I often switch back and forth between tasks.  At this moment, Ctrl+e works. If I switch to one other task, which has the same file in its context (along with many differences), Ctrl+e doesn't work.  If I switch back to the original task, Ctrl+e works again. I can go back and forth between these tasks, with Ctrl+e alternately working or not working, depending on which task I am on.

I then tried switching to some other tasks, and it wasn't working in those tasks. I then switched back to the task where it was working, and it's working again.

And now, curiously, I'm seeing stacktraces in the log that appear to be specific to this. I didn't see these before.  I'll put the entire excerpt into a file and attach it here. I see that some of these are lsp4e exceptions, which would likely be unrelated, but I'm not going to assume that.

[excerpt.log](https://github.com/eclipse-platform/eclipse.platform.ui/files/10714537/excerpt.log)

**Comment by merks** [comment]
That looks like the same stack trace as here:

https://github.com/eclipse-platform/eclipse.platform.ui/issues/487

It doesn't look possible to reproduce this stack trace in the latest version of the code.

Please try to reproduce the problem with a newer version of Eclipse containing the fix for the above issue:

https://www.eclipse.org/downloads/packages/release/2023-03/m2

**Comment by davidmichaelkarr** [comment]
Reading that other report, I managed to find another factor that when I removed it, Ctrl+e worked again.  As I said, I use Mylyn.  I said earlier that when I switch to one particular task, Ctrl+e wasn't working. However, when I looked at the open file tabs, there were a few that "did not exist", because they corresponded to files in closed projects, or perhaps files that were open in that context in another workspace (when I create a new workspace, I always export my current Mylyn tasks and reimport it in the new workspace).  I found those questionable files by going through all of the open tabs. When I found a tab corresponding to a file that doesn't exist, I closed that tab.  After closing each one, I tested Ctrl+e.  It still wasn't working, until I closed the last tab corresponding to a file that doesn't exist.  If that fix you added deals with the same situation, then I guess it would resolve it.

**Comment by merks** [comment]
Yes, I tried hard to reproduce the problem, even with this missing underlying file scenario, but it looks to me like the changes in that commit ensure that `getPathSegment` is never called with an index that is out of bounds:
```
if (maxMatchingSegment < npath.getNameCount()) {
	prependedSegment = prependedSegment.append(getPathSegment(maxMatchingSegment, npath).toString());
```
