### ISSUE TITLE
Improvement for the WizardProjectsImportPage

### ISSUE THREAD

**Issue by richardgroote** [eclipse-platform/eclipse.platform.ui#617]
Hello,

The org.eclipse.core.internal.resources.Project class has recently been changed. The '.settings' folder is automatically created containing a preference file with the encoding in it.

When i use the 'import existing projects within workspace' wizard the following happens:
- i select multiple projects (with already an '.settings' folder) 
- Select the option 'copy projects into workspace'
- For every project an popup is shown that there is already existing '.settings' folder.

From a customer perspective this popup is strange because this is triggered because of the working within the WizardProjectsImportPage. First a project is created and opened within the workspace and then the resources are copied.

It would be nice if this popup would not be shown.

Kind regards,

Richard

**Comment by jukzi** [comment]
@richardgroote contributions welcome. Please provide a fix.
