### ISSUE TITLE
Use empty editor area for guiding texts

### ISSUE THREAD

**Issue by marcushoepfner** [eclipse-platform/eclipse.platform.ui#633]
Bringing over bug from bugzilla...

How VScode does it
<img width="1243" alt="Screenshot 2019-04-04 at 16 07 11" src="https://user-images.githubusercontent.com/29301444/224765927-210952c4-af8d-4279-bc0e-5c3af1d81afa.png">

When no editors are open the user currently sees a big empty space on his screen.
We could use this area to provide some guiding / onboarding text.
See how Visual Studio code does it.

We could also show the product's icon there. The question is what exactly would we show there? This list must somehow be extendable by the installed plugins.

And from a technical point of view: 
- How can we draw into that area? Do we need an SWT enhancement here?

I think this would nicely complement the work done in (https://bugs.eclipse.org/bugs/show_bug.cgi?id=543746.

**Comment by marcushoepfner** [comment]
#78 was merged and added functionality to show some text in the empty editor area.

Let's discuss how we can progress.

The grey image of the perspective and the shortcuts should be provided by a perspective and maybe a text.
Shall we use 

1. the existing extension point `org.eclipse.ui.perspective` and enhance it (by the fields for image, shortcuts and text) or
2. a new extension point?

**Comment by trancexpress** [comment]
Isn't the idea of the welcome screen to do this?

**Comment by marcushoepfner** [comment]
This is related to the perspective while the welcome screen is more a general introduction. 
Furthermore you may not know what to do when you see the empty editor area the first time.
Feature has kind of been accepted already, refer to the original bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=546115

**Comment by LiamHD** [comment]
> Isn't the idea of the welcome screen to do this?

No. The welcome page is to actively inform user about news etc. The user can interact with the welcome page by e.g. clicking links etc.

This here is a more passive / not so intrusive way to provide some hints to the user. It's rendered like a watermark and the user cannot interact (e.g. by clicking links) with this.

Compare with VScode - they also have this watermark in the empty editor area and they also have welcome pages (e.g. after you install / update extensions).

**Comment by LiamHD** [comment]
> 1. the existing extension point `org.eclipse.ui.perspective` and enhance it (by the fields for image, shortcuts and text)

AFAIK this extension point today is only read when you switch to a perspective. If you just e.g. restart your IDE then this is not read. On restart platform simply restores the layout.

**Comment by BeckerWdf** [comment]
> Isn't the idea of the welcome screen to do this?

No. The welcome page is to actively inform user about news etc. The user can interact with the welcome page by e.g. clicking links etc.

This here is a more passive / not so intrusive way to provide some hints to the user. It's rendered like a watermark and the user cannot interact (e.g. by clicking links) with this.

Compare with VScode - they also have this watermark in the empty editor area and they also have welcome pages (e.g. after you install / update extensions).

**Comment by BeckerWdf** [comment]
> 1. the existing extension point `org.eclipse.ui.perspective` and enhance it (by the fields for image, shortcuts and text)

AFAIK this extension point today is only read when you switch to a perspective. If you just e.g. restart your IDE then this is not read. On restart platform simply restores the layout.

**Comment by marcushoepfner** [comment]
> > 1. the existing extension point `org.eclipse.ui.perspective` and enhance it (by the fields for image, shortcuts and text)
> 
> AFAIK this extension point today is only read when you switch to a perspective. If you just e.g. restart your IDE then this is not read. On restart platform simply restores the layout.

Are you saying that option 2 (see above) is the better one then? A "small" extension point just for the new properties (image, shortcuts and text).
I'm asking because extension point reading has to be implemented anyway then for the new feature. I wonder if it matters which extension point this is. The existing (enhanced) one or a new one.

**Comment by BeckerWdf** [comment]
> > > 1. the existing extension point `org.eclipse.ui.perspective` and enhance it (by the fields for image, shortcuts and text)
> > 
> > 
> > AFAIK this extension point today is only read when you switch to a perspective. If you just e.g. restart your IDE then this is not read. On restart platform simply restores the layout.
> 
> Are you saying that option 2 (see above) is the better one then? 

No. I think the mentioned limitation is not a showstopper for option 1. Just wanted to give the information I already found out. I think still both options are valid an option 1 would be easier for consumers of this feature. As they already have the extensions point for the perspective - a new extension point might easily been overlooked.

**Comment by mickaelistria** [comment]
Please don't use `org.eclipse.ui.perspective`, this one is not really meant to change much, as most perspectives as "set in stone" and very unlikely to change. It would also mean that adding support for a new feature would require a rebuild of the bundle that provides the perspective, it's not very convenient.
The is the `org.eclipse.ui.perspectiveExtension` extension point that you can use for it. So it allows to customize a perspective from an external plugins, without having to rebuild the perspective. As long as the added elements are backward compatible, it's fine to grow the scope of this point to newer features.

**Comment by marcushoepfner** [comment]
> Please don't use `org.eclipse.ui.perspective`, this one is not really meant to change much, as most perspectives as "set in stone" and very unlikely to change. It would also mean that adding support for a new feature would require a rebuild of the bundle that provides the perspective, it's not very convenient. The is the `org.eclipse.ui.perspectiveExtension` extension point that you can use for it. So it allows to customize a perspective from an external plugins, without having to rebuild the perspective. As long as the added elements are backward compatible, it's fine to grow the scope of this point to newer features.

Thanks @mickaelistria. The extension point `org.eclipse.ui.perspectiveExtension` is somehow bound to `org.eclipse.ui.IPageLayout`. I have the impression, that both can do the same, e.g. 
- add an action set via IPageLayout in the implementation of IPerspectiveFactory or 
- declarative via the extenstion point org.eclipse.ui.perspectiveExtension

Do I need to extend this interface as well and provide methods for image, shortcuts and text?

**Comment by marcushoepfner** [comment]
I extended `org.eclipse.ui.perspectiveExtension` and added a property for just the text.
I put this into the tags of the MPerspective and read it from there in StackRenderer. It is shown in empty editor area. 
Refer to my PR #637 

But I won't be that easy with the welcome image and the list of short cuts. Single strings like the welcome text can be put into tags. But complex things like list to not really fit.
Is it appropriate to extend the model in this case? @vogella, maybe you can answer this.

Alternative: `org.eclipse.ui.perspectiveExtension` is basically referring other extensions with an id, like actionsets, which are defined by extension point `org.eclipse.ui.actionsets`. I could create e.g. `org.eclipse.ui.emptyEditorWelcome`(bad name I know) with all the properties and use it in `org.eclipse.ui.perspectiveExtension`. But I guess the basic problem would stay, how to retrieve  this information in StackRenderer.

Attention: Stackrender is in `org.eclipse.e4.ui.workbench.renderers.swt` while things like action set extension point are in `org.eclipse.ui`.
`org.eclipse.e4.ui.workbench.renderers.swt` is not able to use `org.eclipse.ui` because of a cycle.

**Comment by marcushoepfner** [comment]
I dont understand this build error: https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/4500799323/jobs/7920392840

` Error: ] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.eclipse.platform:eclipse.platform.ui:4.28.0-SNAPSHOT: Could not find artifact org.eclipse:eclipse-platform-parent:pom:4.28.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 17, column 11`

Did not change anything in the pom.xml.

Does someone know what happened here?

**Comment by marcushoepfner** [comment]
Now there are some other errors that I don't understand:
https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/4503243004/jobs/7926183379?pr=656

**Comment by iloveeclipse** [comment]
I think once https://github.com/eclipse-platform/eclipse.platform.ui/pull/656 is merged, existing perspectives that are provided by platform should be updated to contain some most useful commands.

There are two commands that I wish would always be shown first in every SDK provided perspective:
- "Ctrl+3" as the most important shortcut to almost everything
- "Ctrl+Shift+L" to show available commands

actually "Ctrl+3" is **the** command that should be always shown.

I can imagine that additionally
- "Java" perspective should show "Ctrl+Shift+T" / Open Type
- "Resource" perspective should show "Ctrl+Shift+R" / Open Resource
- etc

**Comment by vogella** [comment]
See also https://github.com/eclipse-platform/eclipse.platform.ui/issues/674
