### ISSUE TITLE
Remove long deprecated Navigator view

### ISSUE THREAD

**Issue by akurtakov** [eclipse-platform/eclipse.platform.ui#644]
It has been deprecated years ago (see https://bugs.eclipse.org/bugs/show_bug.cgi?id=549953 ) and deprecation period ended even for 2022-06. For 2023-03 I've cleaned whatever I found and will start removing it gradually for June release.

**Comment by trancexpress** [comment]
Who exactly is benefiting from this removal? There are committers who are burdened by maintaining the code?

**Comment by akurtakov** [comment]
We got to a state where any meaningful improvement to anything is hindered by the amount of legacy shipped . Here is just one example https://github.com/eclipse-platform/eclipse.platform.ui/discussions/500#discussioncomment-4573759 . Having the code is not just maintaining it, it's navigating the codebase, making the mindmap of what/where/how/etc. and when for almost everything there is half a dozen different way to do it  - good luck on improving anything (not just bug fixes) and no one even dares to think of any slightly bigger improvement.

**Comment by trancexpress** [comment]
-1 from me for this change, as usual do whatever.

**Comment by akurtakov** [comment]
Let's see what the majority vote would be. 
For the record - such concerns should be raised when something is deprecated for removal not when it's actually being removed.

**Comment by mickaelistria** [comment]
> -1 from me for this change

Can you please elaborate why? We need to collect data to ensure we take the best decision for the project continued success. So arguments in favor of keeping this view are still welcome (although they'd better have been expressed when deprecation was agreed upon).

**Comment by trancexpress** [comment]
> Let's see what the majority vote would be. For the record - such concerns should be raised when something is deprecated for removal not when it's actually being removed.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=549953#c15

> Can you please elaborate why? We need to collect data to ensure we take the best decision for the project continued success. So arguments in favor of keeping this view are still welcome (although they'd better have been expressed when deprecation was agreed upon).

Because I use the view.

**Comment by mickaelistria** [comment]
Thanks for linking to your comment on previous discussion; everything is done proper then if the comment was captured and discussed earlier.

> Because I use the view.

Then you can copy the code to some plugin and offer it on Marketplace ;)

**Comment by iloveeclipse** [comment]
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=549953#c15

The contents of bin folders are shown for me in Project Explorer, if I uncheck "java output folders"

![image](https://user-images.githubusercontent.com/964108/225960891-faa96d1f-7588-486d-a89c-6de9a77ba2a3.png)

Beside this, I'm +-0 here.

**Comment by laeubi** [comment]
Another solution would be to to add missing features to the new view.

e.g. a rename file shortcut

I also very much like the EGit Shortcut "Open in System Explorer"

**Comment by vogella** [comment]
+1 for removal, I have never used it.

**Comment by vogella** [comment]
Thanks @akurtakov, now we allow have two slightly different implementations providing almost the same functionality, Project explorer and Package Explorer.

**Comment by jonahgraham** [comment]
I have sent an email to the PMC on this topic - the link should be https://www.eclipse.org/lists/eclipse-pmc/msg04130.html once it is archived.

**Comment by Bananeweizen** [comment]
> I also very much like the EGit Shortcut "Open in System Explorer"

Even though I contributed that one, it's still just a workaround. Much better is to install the [EasyShell plugin](https://github.com/anb0s/EasyShell), which will provide you with your personalized shell (e.g. cmd, powershell, Terminal, bash, ...). Highly recommended.

**Comment by mpalat** [comment]
-1 still for me - I still use this frequently while doing compiler development -  refer https://bugs.eclipse.org/bugs/show_bug.cgi?id=549953#c26 for conditions acceptable for me for the removal - essentially captured in https://bugs.eclipse.org/bugs/show_bug.cgi?id=550385

**Comment by merks** [comment]
It seems the archiving of mailing lists is broken again with nothing for April:

https://www.eclipse.org/lists/eclipse-pmc/2023/

I opened this issue:

https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2903

**Comment by tschwei** [comment]
Add me to the list of longtime Eclipse users that is upset about the removal of the very reliable and useful "Navigator" view.  
The "Project Explorer" view in recent Eclipse versions is flaky, does not render closed projects correctly, and does not reliably link with the open files in the editor.

**Comment by ptziegler** [comment]
But wouldn't it then make sense to try and get those issues in the "Project Explorer" fixed?

And if people feel so strongly about the old "Navigator" view... The component was pretty isolated. So forking https://github.com/eclipse-platform/eclipse.platform.ui/commit/d3a7abfd3b3a0c9a863675604d4bf8e81735ef82 and publishing it via the Eclipse Marketplace as an external component doesn't sound overly difficult.

**Comment by laeubi** [comment]
I personally never missed that thing and haven't used it for years. I agree that reporting issues and fixing them is much more valuable than being upset about its removal ;-)

**Comment by tschwei** [comment]
> But wouldn't it then make sense to try and get those issues in the "Project Explorer" fixed?
> 
> And if people feel so strongly about the old "Navigator" view... The component was pretty isolated. So forking [d3a7abf](https://github.com/eclipse-platform/eclipse.platform.ui/commit/d3a7abfd3b3a0c9a863675604d4bf8e81735ef82) and publishing it via the Eclipse Marketplace as an external component doesn't sound overly difficult.

Thanks for this interesting suggestion.
Does that commit contain everything needed to bring back the Naviator as an optional component?
Unfortunately I'm not familiar with the eclipse codebase so I would make a mess of it if I tried to do this.
But if somebody could do this I think many eclipse users who want a folder-based file view would be very greateful!

OTOH, I could cope with the Project Explorer view if the "Link with Editor" option worked reliably and if it reliably indicated which projects are open/closed.

Thanks,
Tim

**Comment by mickaelistria** [comment]
> OTOH, I could cope with the Project Explorer view if the "Link with Editor" option worked reliably and if it reliably indicated which projects are open/closed.

Please make sure the particular issues you face are reported with steps to reproduce; so they get a good chance of being fixed some day.
