### ISSUE TITLE
Code mining shouldn't format the line until the cursor is moved away

### ISSUE THREAD

**Issue by danibs** [eclipse-platform/eclipse.platform.ui#667]
When you start modify a line of code with mining active, che line is continually formatted just after a millisecond you stop to digit:

![immagine](https://user-images.githubusercontent.com/30932554/228507596-2461a84a-0795-4594-a0c6-e83ccae7c267.png)

Is very stressful and useless in that way.

**Comment by mickaelistria** [comment]
I don't think this is the correct issue. The symptom you see is not really against the code-mining strategy, but more that you would expect that in such case, the `valueA:` remains while you're trying. This can be achieved by a smarter codeMiningProvider on JDT, that would still be able to provide the mining for incomplete statements.
So I'm closing it here and I suggest you open this issue against JDT to get the codeMiningProvider smarter, smart enough to keep the annotations while typing.
