### ISSUE TITLE
Reused editors lost their icon in 4.26

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#679]
Found originally in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/506 with class file editors, but can be easily reproduced with plain text editors.

**This is a regression in 4.26.**

- Make sure "Reuse editors to show search matches" is enabled 
![image](https://user-images.githubusercontent.com/964108/229118965-74709ddb-6646-448c-83a4-136090b3993e.png)
- Open java.util.Random type
- Click on the name and "Search for References"
- In the Search view, just open few types that refer to "Random"
- First match opened in the editor tab **with an icon**
- **Second** and each other match is shown in the same editor **without** the icon n the tab:
![image](https://user-images.githubusercontent.com/964108/229120334-3bdaba07-9602-49be-96fe-43057cab7dc2.png)

Same for plain text editors:
- Make sure "Reuse editors to show search matches" is enabled 
- Create few text files with "aaaaa" text
- Search for "aaaaa" text in the project
- Open files one after each other, starting with the second one they all lose icon.

It only **still** works in Java editors after 4.26 because CompilationUnitEditor has extra codee that **always** recomputes and resets the editor icon in `org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor.doSetInput(IEditorInput)` with the help of `org.eclipse.jdt.internal.ui.javaeditor.JavaEditorErrorTickUpdater.updateEditorImage(IJavaElement)`.

**Comment by iloveeclipse** [comment]
OK, this is a regression between I20221009-1800 (OK) and I20221010-1840 (BAD).

I assume one of the commits this PR caused the regression: https://github.com/eclipse-platform/eclipse.platform.ui/pull/400

This was middle part of the patch series that refactored URLImageDescriptor & Co:
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/397
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/400
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/402

@Dani-Hub : could you please check what exactly caused regression & provide a patch?

The icon is supposed to be changed in `org.eclipse.ui.texteditor.AbstractTextEditor.initializeTitle(IEditorInput)` that calls `org.eclipse.ui.part.WorkbenchPart.setTitleImage(Image)`.

I assume the code that creates/disposes images from descriptors is somehow broken now, but this is just a wild guess.

**Comment by mickaelistria** [comment]
> this is a regression between I20221009-1800 (OK) and I20221010-1840 (BAD).

Thanks a lot for narrowing it down that much!

**Comment by iloveeclipse** [comment]
For bug hunting, simply pull https://github.com/eclipse-platform/eclipse.platform.ui/pull/680 with "working" versions and compare that with current head.

**Comment by Dani-Hub** [comment]
Thanks for the report. I will surely take a look at it, but that needs a bit of time.

**Comment by iloveeclipse** [comment]
> Thanks for the report. I will surely take a look at it, but that needs a bit of time.

This "bit" will be in the time frame of 4.28?

**Comment by Dani-Hub** [comment]
I'm speaking of a time range of multiple days and surely not more than 2 weeks (This includes my calculated absence during Easter).

**Comment by Dani-Hub** [comment]
My current working hypotheses is, that a patch is very simply and requires only the creation of a fresh ImageFileNameProvider/ImageDataProvider when provided to an Image (This is a preliminary assertion!). The reason being is that Image#equals uses those optional members as part of the test has the effect that it compares the equality of the hold image URLs (which are equal). The effect is that UIEventPublisher#notifyChanged returns quickly without doing anything (as consequence of part.getTransientData().put(IPresentationEngine.OVERRIDE_ICON_IMAGE_KEY, newImage)). The previous code relied on the effect that those Image*Providers where different (regardless whether the image URL was equal or not). I'm not quite sure that this is actually a defect in the changed two ImageDescriptor implementations, but it is easy to revert the effect. I'll return and report once I have more precise information available.

**Comment by Dani-Hub** [comment]
> My current working hypotheses is, that a patch is very simply and requires only the creation of a fresh ImageFileNameProvider/ImageDataProvider when provided to an Image (This is a preliminary assertion!). [...]

I confirmed my working hypotheses by implementing it and validating that it would solve the here described problem. 

@laeubi Providing this as PULL request would essentially mean that we revert #398, it seems that our optimization has caused this regression. I do repeat (see my previous comment above) that I think that most likely the actual cause of the erroneous behavior is located elsewhere (it seems that someone first removes the icon and later decides that the two icons are the same without creating a new one. The positive equality test should not have the effect that the image is not shown anymore) and I will try to search for some possible alternative fix candidates, but at least we do have an escape hatch just in case that we either cannot track it down in time or that general agreement exists that the alternative would be to risky to apply. That solution would not worsen the state that existed before my series of improvement issues, albeit it hurts a bit to realize that this optimization shouldn't be valid.

**Comment by laeubi** [comment]
If it is really a problem of two images considered equal if they are not, this should be fixed instead of hiding the problem by making them always evaluate to false.

A quick look at the `Image#equals` method let me think that at least the aspect of disposal is not correctly accounted for images. So probably you can put a breakpoint in the equals method and see if probably one of the compared images are actually disposed.

**Comment by Dani-Hub** [comment]
> So probably you can put a breakpoint in the equals method and see if probably one of the compared images are actually disposed.

I did that of-course - and it is a nightmare to debug, because Tree#WM_KILLFOCUS triggers that each time ;-)

**Comment by laeubi** [comment]
maybe you can use a conditional breakpoint then that triggers if either the current or the compared is disposed ...

I think that for an image, one probably should never simply put this in a map if one is not in control of that image and otherhwise instead of:

`part.getTransientData().put(IPresentationEngine.OVERRIDE_ICON_IMAGE_KEY, newImage))`

do something like

 ```
part.getTransientData().compute(IPresentationEngine.OVERRIDE_ICON_IMAGE_KEY, newImage (oldImage, newImage) -> {
if (oldImage.isDisposed() {
   if (newImage.isDisposed() {
     return null;
  }
  retrun newImage;
}
return oldImage;
}))
```

or similar ....

It might also be interesting to check who dispose the image!

**Comment by Dani-Hub** [comment]
> maybe you can use a conditional breakpoint then that triggers if either the current or the compared is disposed ...

Yes, I found that out and can debug now quite well.
 
> I think that for an image, one probably should never simply put this in a map if one is not in control of that image and otherhwise instead of:
> 
> `part.getTransientData().put(IPresentationEngine.OVERRIDE_ICON_IMAGE_KEY, newImage))`
> 
> do something like
> 
> ```
> part.getTransientData().compute(IPresentationEngine.OVERRIDE_ICON_IMAGE_KEY, newImage (oldImage, newImage) -> {
> if (oldImage.isDisposed() {
>   if (newImage.isDisposed() {
>     return null;
>  }
>  retrun newImage;
> }
> return oldImage;
> }))
> ```
> 
> or similar ....

This is a possible change that I can test, but according to my analysis the image is *not* disposed, but is still there. The
part.getTransientData().put(IPresentationEngine.OVERRIDE_ICON_IMAGE_KEY, newImage) lands (if a difference is noticed, see above) in StackRenderer#subscribeTopicTransientDataChanged to set the CTabItem image. The problem is: I cannot locate yet why the image is not visible anymore. It does not seem to be disposed and no-one else is calling CTabItem#setImage. I'm stuck now. The only thing that is clear is that part.getTransientData().put(IPresentationEngine.OVERRIDE_ICON_IMAGE_KEY, newImage) is ignored because there is no actual value change. I'm now following your suggestion to use part.getTransientData().compute and set a debug point into the lambda.

**Comment by laeubi** [comment]
I have now debugged this a bit and found that I can "fix" the bug when uncomment the line in

`org.eclipse.ui.texteditor.AbstractTextEditor.initializeTitle(IEditorInput)`

that disposes the `oldImage` here:

```
private void initializeTitle(IEditorInput input) {

	Image oldImage= fTitleImage;
	fTitleImage= null;
	String title= ""; //$NON-NLS-1$

	if (input != null) {
		IEditorRegistry editorRegistry= PlatformUI.getWorkbench().getEditorRegistry();
		IEditorDescriptor editorDesc= editorRegistry.findEditor(getSite().getId());
		ImageDescriptor imageDesc= editorDesc != null ? editorDesc.getImageDescriptor() : null;

		fTitleImage= imageDesc != null ? imageDesc.createImage() : null;
		title= input.getName();
	}

	setTitleImage(fTitleImage);
	setPartName(title);

	firePropertyChange(PROP_DIRTY);

        // This disposes the image and then the icon disappears on the reused editor
	// if (oldImage != null && !oldImage.isDisposed())
		//oldImage.dispose();
}
```

**Comment by laeubi** [comment]
What happens is that the `org.eclipse.ui.internal.e4.compatibility.CompatibilityPart` is notified about the `IWorkbenchPartConstants.PROP_TITLE` change event and updates the `OVERRIDE_ICON_IMAGE_KEY` what equals the previous value (what of course is considered equal -> no update) and then **after** this even the image is disposed -> icon is gone.

**Comment by laeubi** [comment]
I'll provide a fix for this in the `CompatibilityPart`, but in general the `AbstractTextEditor` could be improved as well, because currently it always create a new image (and dispose the old one) even that the image descriptor is always the same.
