### ISSUE TITLE
Onboarding icon and background use same gray color

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-platform/eclipse.platform.ui#687]
I've just launched a new created launch config from my platform.ui IDE, and the onboarding icon in the runtime looks like this:
![image](https://user-images.githubusercontent.com/406876/229493243-b27812ba-fa6c-4233-af0a-07934f80e102.png)
The gray border of the "text icon" is the same as the background color, therefore the border of that "icon" vanishes. This is on Windows.
Compare with https://github.com/eclipse-platform/eclipse.platform.ui/commit/dd671fd5be6d1af2d857be26f634456f8684e26d to see the real image.

**Comment by BeckerWdf** [comment]
Good catch.
I will have a look at this.
