### ISSUE TITLE
Unexpected gray borders in empty editor area

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#694]
## What I did:

- [Install the Eclipse SDK IDE](https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#create-an-eclipse-development-environment)
- Start a new Dev Eclipse
- Create some random plugin project
- Switch to the PDE perspective and make sure all editors are closed

## Result:
![grafik](https://user-images.githubusercontent.com/1331477/229751298-b7c33d1c-9935-4437-b195-2883b8cba57d.png)

## Expectation:

User should not see any borders, the background should be colored equally.

**Comment by vogella** [comment]
cc @marcushoepfner

**Comment by marcushoepfner** [comment]
@laeubi I cannot reproduce on Mac, no matter which theme I use.
Could you please try the PR #698 and let me know, whether it is fixed.
And could you post a screenshot with opened resource perpective (without any editor open). Resource perspective has onboarding information already and I would like to check all background colors.

**Comment by laeubi** [comment]
This is how it looks at the moment:

![grafik](https://user-images.githubusercontent.com/1331477/229772726-e5e09bd9-53ac-4ad0-9954-9f3f86734ef2.png)

**Comment by marcushoepfner** [comment]
> This is how it looks at the moment:
> 
> ![grafik](https://user-images.githubusercontent.com/1331477/229772726-e5e09bd9-53ac-4ad0-9954-9f3f86734ef2.png)

This is with or without my PR?

**Comment by laeubi** [comment]
It looks like this if I fetch your PR

![grafik](https://user-images.githubusercontent.com/1331477/229773162-9b4f80ba-f73e-4a4d-b8a4-ed393f5b3c07.png)

by the way the image looks odd now @vogella I think the folder should at laest remove the intersection border like this:
![grafik](https://user-images.githubusercontent.com/1331477/229773520-40e7f19b-ef71-42a0-a83a-c6252cd84e2a.png)

**Comment by marcushoepfner** [comment]
> It looks like this if I fetch your PR
> 
> ![grafik](https://user-images.githubusercontent.com/1331477/229773162-9b4f80ba-f73e-4a4d-b8a4-ed393f5b3c07.png)
> 
> by the way the image looks odd now @vogella I think the folder should at laest remove the intersection border like this: ![grafik](https://user-images.githubusercontent.com/1331477/229773520-40e7f19b-ef71-42a0-a83a-c6252cd84e2a.png)

so it is fixed isnt it?

**Comment by iloveeclipse** [comment]
Yes, it is.

**Comment by laeubi** [comment]
At least it looks "normal" now except the icon but this is probably because of:
- https://github.com/eclipse-platform/eclipse.platform.ui/pull/696
