### ISSUE TITLE
Consider removing the inner background from image to make them less "strong" in the dark theme

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#695]

**Comment by vogella** [comment]
Light theme

![image](https://user-images.githubusercontent.com/139910/229758118-e4427a1f-9f4e-4dd2-ad8f-dfc53e5c9e59.png)

Dark theme

![image](https://user-images.githubusercontent.com/139910/229758230-89fad831-9cf0-4950-a14f-e615cf53df6d.png)


@BeckerWdf did you try to use transparency for the inner part? I could image that the light theme looks almost the same but the dark theme would look much better.

**Comment by trancexpress** [comment]
Sorry I've not followed the discussions too closely so I'm not sure what the expectations are. When I start Eclipse, default is not maximized. The text for hotkeys is then not shown completely. Resizing  the window showcases this best:

https://user-images.githubusercontent.com/24752155/229905135-19a6846f-49c8-4f30-929f-5e84c4ce9a40.mp4

Should I open a bug for this or its expected?

**Comment by iloveeclipse** [comment]
> Should I open a bug for this or its expected?

I haven't reviewed this code too, but believe one could try to resize **both** image and text. So yes, please create ome issue to check that.

**Comment by trancexpress** [comment]
OK, opened: #702
