### ISSUE TITLE
Onboarding shows incomplete text on start-up in new workspace

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform.ui#702]
See screen recording:

https://user-images.githubusercontent.com/24752155/229907264-e3964d97-ff45-4ea7-a1b4-66a9cd4652f4.mp4

This is when starting an SDK build in a new workspace:

```
Eclipse SDK
Version: 2023-06 (4.28)
Build id: I20230404-0600
```

I'm on Linux with KDE, using Breeze Dark and theming enabled (with dark theme).

I'm not sure how the text is expected to appear, but there seems to be enough space to show the text with the default window size.

**Comment by iloveeclipse** [comment]
See original enhancement request here: https://github.com/eclipse-platform/eclipse.platform.ui/issues/633

@marcushoepfner, could you please check this?
I wonder if the image & text can **both** be scaled to available area.

Alternative would be to reduce default image sizes to fit the default window size - some space for text.

**Comment by marcushoepfner** [comment]
Not sure how to achieve this. 
A reasonable minimum screen resolution was expected actually. 
I mean the image is 350 by 350. Plus text plus commands. I guess this is ~500 px height. Plus problems view height plus top toolbar height. Thats not much pixels  isn't?

What screen resolution are you on @trancexpress ?

**Comment by BeckerWdf** [comment]
I just checked what vscode does. If the windows hight is not sufficient they remove the shortcuts. The icon is visible all the time. And if he hight get's even lesser then the icon is scaled down.

**Comment by marcushoepfner** [comment]
> @marcushoepfner, could you please check this? I wonder if the image & text can **both** be scaled to available area.

This would re-introduce #678. There is a space of 50px on each side.

**Comment by vogella** [comment]
Maybe hide the image if the size of the container is below a certain value? Something like:

```
if (container is less than 640 px in height) {

GridData gridData = new GridData(SWT.FILL, SWT.FILL, true, true);
gridData.exclude = true;
label.setLayoutData(gridData)
}
```

Scaling the image seems not a bit to design effort for this startup case.

**Comment by trancexpress** [comment]
> I just checked what vscode does. If the windows hight is not sufficient they remove the shortcuts. The icon is visible all the time. And if he hight get's even lesser then the icon is scaled down.

Good for VS Code but isn't that their logo? I assume they'll want to show it.

For Eclipse users, the hot keys are more important?

**Comment by BeckerWdf** [comment]
> Good for VS Code but isn't that their logo? I assume they'll want to show it.
> 
> For Eclipse users, the hot keys are more important?

Sure. It was not my intention to say that we need to do it in the same way. We can also agree on hiding the image if there is not sufficient hight.

**Comment by marcushoepfner** [comment]
I ve seen this on a 13" screen now. Image was kind of huge. It is 350 x 350. Should we reduce the size a bit?
The hiding logic when there is not enough space can be implemented anyway.

**Comment by iloveeclipse** [comment]
Yes and yes

**Comment by BeckerWdf** [comment]
> I ve seen this on a 13" screen now. Image was kind of huge. It is 350 x 350. Should we reduce the size a bit? The hiding logic when there is not enough space can be implemented anyway.

So what size would you propose?

**Comment by BeckerWdf** [comment]
> > @marcushoepfner, could you please check this? I wonder if the image & text can **both** be scaled to available area.
> 
> This would re-introduce #678. There is a space of 50px on each side.

See #705: At least on macOS 2px spacing are sufficient instead of 50 px. Does this also work for windows and linux?

**Comment by BeckerWdf** [comment]
> I've seen this on a 13" screen now. Image was kind of huge. It is 350 x 350. Should we reduce the size a bit?
The hiding logic when there is not enough space can be implemented anyway.

I decreased it from 350x350px to 250x250px. (See https://github.com/eclipse-platform/eclipse.platform.ui/pull/705/commits/896b2b3b9f5069313c8cc1ee37202f73589bfc1b also part of #705 )

Look like this:
<img width="1136" alt="Screenshot 2023-04-06 at 13 45 05" src="https://user-images.githubusercontent.com/28338612/230367889-b81c2255-0d98-4ddd-812f-9ce328500697.png">

**Comment by BeckerWdf** [comment]
> Look like this: <img alt="Screenshot 2023-04-06 at 13 45 05" width="1136" src="https://user-images.githubusercontent.com/28338612/230367889-b81c2255-0d98-4ddd-812f-9ce328500697.png">

Do you think the strokes width in the image is now to big in this smaller version?

**Comment by iloveeclipse** [comment]
Are we done here, or something else pending?
@trancexpress : please check latest build if you are OK with the result.

**Comment by trancexpress** [comment]
> Are we done here, or something else pending? @trancexpress : please check latest build if you are OK with the result.

Using `I20230413-0320`, the Eclipse window looks fine at start-up. So fine from my POV.

**Comment by BeckerWdf** [comment]
> The hiding logic when there is not enough space can be implemented anyway.

What about this? Should we handle this in this issue or create a new one for it?

**Comment by iloveeclipse** [comment]
> > The hiding logic when there is not enough space can be implemented anyway.
> 
> What about this? Should we handle this in this issue or create a new one for it?

If you plan work on this, please create new one. If not, we can close this issue as we are OK with current state.
