### ISSUE TITLE
Dragging Files Into Empty Editor Area Fails on Onboarding Image

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-platform/eclipse.platform.ui#706]
When the empty editor area shows onboarding information dragging files works in the complete area except of the area covered by the onboarding image. See:

https://user-images.githubusercontent.com/28338612/230372276-339f4171-3498-47b0-afee-dfdcd158c2bd.mov

**Comment by iloveeclipse** [comment]
I haven't checked how drag and drop implemented, I assume the image object is somehow different to the rest of the widgets. Here I wonder if one can set image **as a background** to a simple composite, or just paint image to canvas (assuming composite and canvas support DnD).
@marcushoepfner : WDYT?

**Comment by BeckerWdf** [comment]
> assume the image object is somehow different to the rest of the widgets

They all are labels.

**Comment by iloveeclipse** [comment]
Just checked on Linux, works fine with I20230410-1800. Not sure if that was caused by a [small refactoring](https://github.com/eclipse-platform/eclipse.platform.ui/pull/709) I did in the code over the weekend?

**Comment by BeckerWdf** [comment]
> Just checked on Linux, works fine with I20230410-1800. Not sure if that was caused by a [small refactoring](https://github.com/eclipse-platform/eclipse.platform.ui/pull/709) I did in the code over the weekend?

It issue exists on macOS with and without your refactoring.

**Comment by BeckerWdf** [comment]
Can a windows user also check this?

**Comment by merks** [comment]
@BeckerWdf 

It works for me pulling the latest and testing in a debug self-host launch(and looks cool.  🏆

**Comment by BeckerWdf** [comment]
> @BeckerWdf
> 
> It works for me pulling the latest and testing in a debug self-host launch(and looks cool. 🏆

On Windows?

**Comment by iloveeclipse** [comment]
So it is Mac only issue? In this case we should create SWT bug with a simple snippet demonstrating the issue.
I don't have Mac: @BeckerWdf : can you please check if any of the "Drag and Drop" examples from https://www.eclipse.org/swt/snippets/ aren't working for you?

**Comment by BeckerWdf** [comment]
> So it is Mac only issue? In this case we should create SWT bug with a simple snippet demonstrating the issue. I don't have Mac: @BeckerWdf : can you please check if any of the "Drag and Drop" examples from https://www.eclipse.org/swt/snippets/ aren't working for you?

How do I get them into my workspace the easiest way?

**Comment by iloveeclipse** [comment]
Checkout [SWT repo](https://github.com/eclipse-platform/eclipse.platform.swt) & import `eclipse.platform.swt/examples/org.eclipse.swt.snippets` project?

**Comment by merks** [comment]
> > @BeckerWdf
> > It works for me pulling the latest and testing in a debug self-host launch(and looks cool. 🏆
> 
> On Windows?

That way implicit in spending to you, but yes it works on Windows 10; I've not upgraded to 11 yet...

**Comment by BeckerWdf** [comment]
> can you please check if any of the "Drag and Drop" examples from https://www.eclipse.org/swt/snippets/ aren't working for you?

It looks like they are working

**Comment by iloveeclipse** [comment]
> > can you please check if any of the "Drag and Drop" examples from https://www.eclipse.org/swt/snippets/ aren't working for you?
> 
> It looks like they are working

So the next step would be to extract minimal amount of required code that creates the label with giant image in the StackRenderer to the standalone SWT snippet where DnD would **not work** for you. 

Once we have plain SWT reproducer, we can create SWT issue and discuss there the best way to fix that.

**Comment by BeckerWdf** [comment]
> So the next step would be to extract minimal amount of required code that creates the label with giant image in the StackRenderer to the standalone SWT snippet where DnD would **not work** for you.

@marcushoepfner: I need your help for this.

**Comment by BeckerWdf** [comment]
I opened https://github.com/eclipse-platform/eclipse.platform.swt/issues/649 for this. So closing this one.
