### ISSUE TITLE
Remove Perspective button is done by Close menu

### ISSUE THREAD

**Issue by xerces8** [eclipse-platform/eclipse.platform.ui#728]
To remove a button for a certain perspective from the toolbar (on the top right), the context menu item labeled "Close" is used.
"Remove" would be more on point, as nothing is closed.

**Comment by vogella** [comment]
It also closes the active perspective if that is what you use in this moment.

**Comment by iloveeclipse** [comment]
The button **closes** perspective, does **not** remove it => nothing to fix here.

**Comment by merks** [comment]
Keep in mind that it does the opposite "Open Perspective":

![image](https://user-images.githubusercontent.com/208716/234265427-6feb4bfb-c6e2-451d-aa76-1137a1a68fc5.png)

So renaming it to Remove would see to call for changing that to Add Perspective.  But it doesn't really add a perspective, it opens an existing defined perspective, and you'll note you can only open a given perspective once...

**Comment by xerces8** [comment]
The "Open Perspective" does two things:
 - add the new perspective button to the toolbar
 -  opens it (the perspective)

The Close menu does:
 - removes the perspective button from the toolbar
 - (if the perspective is open, then it closes it, I guess, I did not try)

Also, what exactly is "closing a perspective" ? Showing an empty Eclipse window?

**Comment by merks** [comment]
I really don't see this as significantly different from tabs in a browser where you can open and close tabs, although one could also argue that one actually adds and removes tabs.  Is there some deep semantic important difference that must be highlighted by changing terminology from open/close that has been in use for two decades to use add/remove instead?
