### ISSUE TITLE
New setting: show icons in editor area

### ISSUE THREAD

**Issue by albertmink** [eclipse-platform/eclipse.platform.ui#735]
During development the number of opened views might increase significantly, see the views at the bottom. Here the titles cannot be shown properly and in can get worse easily.
<img width="1344" alt="Screenshot 2023-04-27 at 11 58 53" src="https://user-images.githubusercontent.com/38354196/234829046-5c2f7368-f028-4f9e-aef9-df370c511da9.png">

This issue propose to add a functionality that allows to hide icons. This provides more space for the titles see mock-up
<img width="1474" alt="lots_of_views_no_icon" src="https://user-images.githubusercontent.com/38354196/234828797-892feb49-3b83-4209-9aa1-43992625588e.png">

UX perspective:
Without icons (in the bottom section) the editor gains focus, which could be favourable over the additional icon (that help of simple identify views).

**Comment by jukzi** [comment]
Feel free to provide a PR that optionally removes icons. But by default i want to see icons and the typical way to prevent that many views is to switch between perspectives.

**Comment by albertmink** [comment]
We propose to add two (one shown above already) options to allow further visual customising in the page 'Preferences' -> 'Appearance'.
To start with, adding a new section with the checkboxes (default: not checked/ticked ➡️  won't change the recent behaviour)

Tab icons and texts:
- [ ] Show icons only in editor area
- [ ] Show full text for all tabs except in editor area

~~Screenshot for checked boxes will be added below~~ Get the preference page up and running as the first step.

**Comment by jukzi** [comment]
Sounds reasonable. Do you really have problems with many tabs in the java-IDE or rather problems on a product based on it?

**Comment by albertmink** [comment]
From my daily work 
<img width="1159" alt="Screenshot 2023-06-15 at 12 40 04" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/38354196/ebf3d567-5075-4435-a50f-7ce0bb549559">

**Comment by jukzi** [comment]
"ABAP" -> @sratz can you look at it, please?

**Comment by sratz** [comment]
> "ABAP" -> @sratz can you look at it, please?

Our team is currently working on this and we will provide a pull-request soon.

**Comment by vogella** [comment]
To many options should be avoided, why the distinction of icons in the editor area? Is this really necessary?

**Comment by Phillipus** [comment]
Removing the icon won't make much difference if the view title is quite long.

> Too many options should be avoided,

Agreed

**Comment by albertmink** [comment]
@Phillipus depends what you mean by much difference. Referring to screenshots in #1071, the difference in number is 9 (with icons) or 10 (w/o icons) 🧐
Let me draw your attention to this one (as explained in #1071) and not the raw number of views:
> Lots of view icons draw attention away from the editor area. However, when playing the role as a classic IDE for a programming language the editor area should be most prominent.

**Comment by BeckerWdf** [comment]
> > Too many options should be avoided,
> 
> Agreed

So what is your concrete proposal?

**Comment by BeckerWdf** [comment]
> To many options should be avoided, why the distinction of icons in the editor area? Is this really necessary?

See https://github.com/eclipse-platform/eclipse.platform.ui/issues/735#issuecomment-1697525075 for an answer. It's about focus in the UI. This has been discussed with the UX experts for the SAP ADT team. It's a recommendation from them and in addition competitors of the Eclipse IDE also only have icons in the view area.

**Comment by sratz** [comment]
Resolved by #1071.
