### ISSUE TITLE
New Workbench Window is not opened on the device on which it was called

### ISSUE THREAD

**Issue by MarcelBoerner** [eclipse-platform/eclipse.platform.ui#739]
When opening a new Workbench window over window -> new window or over the api  PlatformUI.getWorkbench().openWorkbenchWindow(defaultPerspective, adapter); the window is not opened on the same screen (device as the workbenchwindow on which the command was started) It seems as it is opened on the primary screen or where the application was initially started. The new workbench window should be opened on the same screen as the current active workbench window is, or it should give a possibility to tell on which screen the new workbench window should be opened. The only way to do so is using discouraged api:
org.eclipse.ui.internal.Workbench.openWorkbenchWindow(IAdaptable, IPerspectiveDescriptor, MWindow, boolean)
or using the emodelservice clone Methode which has other bugs.
@HeikoKlare : can you look for this please.

**Comment by fedejeanne** [comment]
Hello @MarcelBoerner , do you have a snippet to demonstrate the problem?
I'm particularly interested in how you solved it and which parameters did you pass to the internal method `org.eclipse.ui.internal.Workbench.openWorkbenchWindow(IAdaptable, IPerspectiveDescriptor, MWindow, boolean)`

**Comment by MarcelBoerner** [comment]
Hi yes:

```java
  private static IWorkbenchWindow openTemporaryWorkbenchWindow() {
    String defaultPerspective = PlatformUI.getWorkbench().getPerspectiveRegistry().getDefaultPerspective();
    try {
      return PlatformUI.getWorkbench().openWorkbenchWindow(defaultPerspective, null);
    } catch (WorkbenchException e) {
      Log.logException(e.getLocalizedMessage(), e);
    }
    return null;
  }
```

**Comment by MarcelBoerner** [comment]
The workaround is:    

```java
    Rectangle bounds = PlatformUI.getWorkbench().getActiveWorkbenchWindow().getShell().getBounds();
    MApplication application = PlatformUI.getWorkbench().getService(MApplication.class);
    EModelService eModelService = application.getContext().get(EModelService.class);
    MTrimmedWindow window = eModelService.createModelElement(MTrimmedWindow.class);
    window.setX(bounds.x);
    window.setY(bounds.y);
    application.getChildren().add(window);
    IPerspectiveDescriptor perspectiveDescriptor = PlatformUI.getWorkbench().getPerspectiveRegistry().findPerspectiveWithId(PlatformUI.getWorkbench().getPerspectiveRegistry().getDefaultPerspective());
    return ((Workbench) PlatformUI.getWorkbench()).openWorkbenchWindow(null, perspectiveDescriptor, window, true);
```

**Comment by MarcelBoerner** [comment]
@fedejeanne : i use windows 11
