### ISSUE TITLE
Close Window button not in corner when maximized

### ISSUE THREAD

**Issue by sambo22** [eclipse-platform/eclipse.platform.ui#749]
Working with S32 Design Studio but was not able to find an NXP bug report page. Assuming this is an Eclipse bug as it is a window UI element. The 'Close Window' 'X' button at the top right of the window is a few pixels from the right side of the window. With Eclipse maximized, and another window maximized behind it, attempting to move cursor to the upper right-most corner of the screen and clicking closes the window behind Eclipse.

This is S32 Design Studio (Eclipse?)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/108307405/025ae028-0d79-4541-829c-924a30ea56ce)

This is Microsoft Edge
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/108307405/65c6964a-5ba4-44a4-949f-d83f600254fa)

Other similar issues found on the internet:
https://superuser.com/questions/783098/windows-8-close-button-not-exactly-at-top-right-corner-of-the-screen
https://forums.autodesk.com/t5/fusion-360-support/close-button-not-on-edge-of-top-right-corner-on-windows-10/td-p/9564334
I also have the same issue with an inhouse program built using .NET Core 6.

**Comment by iloveeclipse** [comment]
> This is S32 Design Studio (Eclipse?)

We cannot afford to provide support for all products based on Eclipse.
Please report bugs for products that are not coming from eclipse.org to product vendors.
They are supposed to analyze issues and provide support.

> but was not able to find an NXP bug report page

Just click on "Support" menu shown next to "Design" in the screenshot below and follow with steps...
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/507ba112-112e-4cec-abcb-2dab224d1b86)
