### ISSUE TITLE
Security Best Practices

### ISSUE THREAD

**Issue by ghost** [eclipse-platform/eclipse.platform.ui#761]
Hi,

As a member of the Security Team from the Eclipse Foundation, we used a tools [Scorecard](https://github.com/ossf/scorecard) and [StepSecurity](https://www.stepsecurity.io/) to analyze this repo  in order to push a pull request that cover some or all the following best practices below:
* Apply least privilege principle to [GITHUB_TOKEN](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/)
* Add or fine tune the use of [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)
* Pin actions to a [full length commit SHA](https://michaelheap.com/ensure-github-actions-pinned-sha/)

As a result, You will see a PR coming from [StepSecurity](https://www.stepsecurity.io/) to help to implement those fixes above which will cover a list of points below identified detected:
* Apply least privilege principle to [GITHUB_TOKEN](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/) for files [.github/workflows/updateRelease.yml](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/.github/workflows/updateRelease.yml) 
* Add or fine tune the use of [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)

Please don’t hesitate and reach out if there is something unclear above.

Kind Regards,
Francisco Perez

**Comment by netomi** [comment]
The resulting dependabot config is not a valid yml file:

```yaml
version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily


  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
```

the indentation levels for the different package ecosystems is wrong. In yaml you can start an array on the same level or indented, but it must be consistent. Originally the file started without indentation, the stepsecurity PR blindly added additional ecosystems with an indented level. With the next run of dependabot you should see an error, but I would make this file correctly indented already before.

The same applies for some of the other PR wrt dependabot config.

You can also use https://www.yamllint.com/ to verify if the file is in a correct yaml format.

**Comment by mickaelistria** [comment]
Thanks for noticing @netomi . Would you mind submitting a PR that fixes it?

**Comment by netomi** [comment]
Please find a proposed fix in PR #764 .

**Comment by ghost** [comment]
Thanks @netomi

**Comment by ghost** [comment]
Hi

Please find below a list of points which summarize a root cause of this issue:
-  Unfortunately, the first dependabot.yml didn't have a proper indention and Github accepted as a valid yaml
-  StepSecurity added new policies following a proper yaml indention and unfortunately that caused an issue.

I apologize for inconvenience caused for this issue. I am working on pushing a fix to all PRs where we have detected this issue. Sorry.

Thanks, 

Kind Regards,
