### ISSUE TITLE
Problems view is not translated when changing IDE language

### ISSUE THREAD

**Issue by ptziegler** [eclipse-platform/eclipse.platform.ui#763]
When changing the Eclipse to e.g. German, the title of the Problems view is not correctly translated. Weirdly enough, the correct name is shown in the drop-down menu and other views such as the Progress are correctly translated.
 
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/82097481-6799-450f-ae16-6258f2eebba6)

**Comment by ptziegler** [comment]
It seems like the name of the view is fetched twice:

Once from the extension point, where it uses the correct name.
Once from the Memento which - as far as I understand - are persisted metadata.

Workaround: Use `-DclearPersistedState=true`

**Comment by iloveeclipse** [comment]
Is this a real world use case? I wonder why a nee property needed to be saved to fix that.

**Comment by ptziegler** [comment]
> Is this a real world use case?

It is. We allow the user to change the application language between German/English. But even after a restart, the UI is only partially updated. 

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/70652978/6ed38575-ac21-4845-8925-2f73714acfa9)

> I wonder why a nee property needed to be saved to fix that.

You need some way to detect the locale of the part name. I just mentioned in the linked pull request that this is probably not the correct approach. Instead, the "part name" property should only be persisted when it's a custom name.
