### ISSUE TITLE
Content Assist dialog reacts too fast / prevents user from selecting text / behave erractically

### ISSUE THREAD

**Issue by tommai78101** [eclipse-platform/eclipse.platform.ui#766]
The blue highlight indicates the debugger paused at this specific line. It is not a text selection highlight.

[Screencast from 05-18-2023 04:19:34 PM.webm](https://github.com/eclipse-platform/eclipse.platform.ui/assets/6444116/b1379a32-d4d9-4ead-a64e-b234dba9da5b)

When the mouse is hovering over a variable while a debugger is paused on a breakpoint, the content assist dialog shows up. As the mouse moves towards the dialog to inspect the variable's contents, the content assist dialog would get in the way of things, such as getting dismissed too early, or the dialog gets dismissed when the user clicks on the dialog (at Mouse Button Up mouse event), or that it flashes briefly and not display anything to the user.

[Screencast from 05-18-2023 04:26:16 PM.webm](https://github.com/eclipse-platform/eclipse.platform.ui/assets/6444116/d8c59bd1-47f3-4700-a489-5ba87df8c3b8)

The same behavior can be said to the annoyance of the user, when the user wants to navigate and open the implementation of a particular class object, or wanting to open the declared class type. Here, I am showing you that I wanted to drag my mouse over the **Open Implementation** and the **Open Declared Type** options to select and navigate to that class. However, as I move my mouse over the content assist dialog, that dialog automatically dismisses away, preventing me from being able to click on it.

It feels like the mouse events are getting triggered too often that the focus is lost somewhere in the middle of it.

I find these behaviors to be annoying because I cannot inspect the variable that I wanted to or jump away to read their implementations without having to mess around with the mouse controls over this UI issue. 

**Platform:** Ubuntu 22.04 LTS
**Version:** 2023-03 (4.27.0)
**Build id:** 20230309-1520

**Comment by mickaelistria** [comment]
This duplicates https://github.com/eclipse-platform/eclipse.platform.swt/issues/177 , let's close.
