### ISSUE TITLE
Align suggested Keybindings

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.ui#788]
Currently all text is center-aligned, what makes it hard to read
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/756be798-687d-43df-b83f-8ac1e16dc543)

I'd like to suggest to align the text and keybindings and separate them, at best the will look like keys:

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/1efcb456-96d4-4697-919e-b10dee18696b)

**Comment by merks** [comment]
I kind of like the text right aligned and the keys left aligned but the space between them ought to be significantly bigger so that one easily sees the separation.  But that's just my opinion...

**Comment by laeubi** [comment]
Currently its just hard to see what is text and what is key and it could easily be mixed, also if you draw a line it seems like the image is left aligned to the text and the key actions centered to the text, this all looks quite "unsteady" ...

If one likes them to "meet at the middle", I think it should at least be aligned with with image so the form one line
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/b0d2bbe2-b0ac-4c4b-b573-24e82abcc644)

maybe even a thin line (here in green) would help to give a better separation.

**Comment by BeckerWdf** [comment]
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/772

**Comment by marcushoepfner** [comment]
Interesting. Does not look that bad on Mac w.r.t space between command text and shortcut.
<img width="403" alt="2023-06-06_10-47-46" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/29301444/03bc89e2-763c-4eee-992f-fd6bc6754007">

Anyway, I'll provide a fix.
Center alignment of image and "onboarding text" was missing yet. I did it in #772, but will do it rather separately now.

**Comment by marcushoepfner** [comment]
Refer to https://github.com/eclipse-platform/eclipse.platform.ui/pull/796#issuecomment-1578267938 how it looks now.

**Comment by iloveeclipse** [comment]
Now the master is opened. Please don't forget to bump bundle version.
