### ISSUE TITLE
Prevent JobManager UI freeze when waiting for a rule in the UI Thread

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-platform/eclipse.platform.ui#8]
This is a followup of discussions in https://github.com/eclipse-platform/eclipse.platform.ui/pull/6 and former Gerrit patch.

The general problem is that when one wants to run a job or some other operation protected by scheduling rules in UI Thread, and this scheduling rule is currently "blocked" by some other work, then the result is a UI Freeze.
We could do better by allowing the workbench/IDE parts to customize a bit the JobManager, more specifically the `beginRule` so it would show the interesting ProgressDialog when called from the UI Thread, so it doesn't seem too much like a freeze, and users have the opportunity to workaround it. It would also ease debugging.
Such a solution would allow to serve multiple operations that have implemented workarounds for this freeze, such as https://github.com/eclipse-platform/eclipse.platform.ui/pull/6 , and those workarounds could then be removed.

**Comment by laeubi** [comment]
I don't think we need more JobManager Customizations here, the underlying problem is more that in some circumstances the UI-Events are not driven, see 

- https://github.com/eclipse-platform/eclipse.platform.runtime/issues/40 

for an analysis and fix.What is left is to just need to override these new methods .

**Comment by mickaelistria** [comment]
#40 is promising, I suggest we follow that track first and then we'll evaluate if we needs further smartness here and there.
