### ISSUE TITLE
can not launch plain Java

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.ui#828]
for example trying to launch
`org.eclipse.ui.internal.views.markers.ViewerColumnsDialog.TestData.main(String[])` as plain-java
fails with classnotfound:
```
Fehler: Hauptklasse org.eclipse.ui.internal.views.markers.ViewerColumnsDialog$TestData konnte nicht gefunden oder geladen werden
Ursache: java.lang.ClassNotFoundException: org.eclipse.ui.internal.views.markers.ViewerColumnsDialog$TestData

```
Because the launch configuration does not add right the classpathcontainer:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/a92a6f17-4c06-4b0e-9c17-9d9868431635)

There should be "Plug-in Dependencies" instead of m2e container like in swt:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/2d3bad6d-a746-4292-8df2-9895a9c667c5)

workaround: with "disable Maven Nature" and deleting the launch config it works again.
Is that a problem of m2e or of platform.ui?

**Comment by iloveeclipse** [comment]
With I20230615-0550 and without m2e I can right click on TestData, say "Run As Java Application" and that works out of the box. I assume this is m2e issue.

**Comment by jukzi** [comment]
not platform.

**Comment by apeteri** [comment]
I also encountered this issue while trying to check out platform.ui using Eclipse Installer (the "IDE for Eclipse Committers" product, releases 2023-12 RC1 and 2023-09).

The very first launch of a Java application (a JFace snippet) works and I see the "Plug-in Dependencies" container on the Dependencies tab of the run configuration dialog, but once I make any modifications, it turns into "org.eclipse.m2e.MAVEN2_CLASSPATH_CONTAINER" and main classes can no longer be found.

Edit: removing the Maven project nature from `org.eclipse.jface.snippets` indeed makes things work again!

**Comment by jukzi** [comment]
@apeteri please comment on https://github.com/eclipse-m2e/m2e-core/issues/1430
