### ISSUE TITLE
The default button in FiltersConfigurationDialog is in the wrong section

### ISSUE THREAD

**Issue by eobrienPilz** [eclipse-platform/eclipse.platform.ui#85]
The FiltersConfigurationDialog that is used by MarkerSupportView has a usefull button to restore default settings. However the button is positioned at the same level as the ok and cancel buttons. Instead it should be in the section used to configure the filter settings.
See the the position of the default button in the preferences dialog for the correct place.

**Comment by eobrienPilz** [comment]
Screenshots showing what I mean.

![filterDefaults](https://user-images.githubusercontent.com/58333578/170678435-560d6169-7dd6-41e7-95f1-33ddea90cc1a.png)
![preferencesRestoreDefaults](https://user-images.githubusercontent.com/58333578/170678442-c77328ac-12bc-4838-8a60-25f87f02f6de.png)

**Comment by Wittmaxi** [comment]
@eobrienPilz can we close this issue?

**Comment by eobrienPilz** [comment]
yes thanks, I just checked in 4.28 and it looks good now .
