### ISSUE TITLE
2023-06 (4.28.0) freezes with almost every mouseclick

### ISSUE THREAD

**Issue by ranxero** [eclipse-platform/eclipse.platform.ui#852]
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)
Version: 2023-06 (4.28.0)
Build id: 20230608-1333

I know this may sound crazy but I'm rather understating. 
Waiting for about 15 seconds to open a java source file with maybe 30 lines of code. Even worse when trying to open a xml file. Same when files are already open but not in the current focus of the editor.
Switching between the tabs at the bottom almost makes eclipse crash. Same for top menu selections. 
Impossible to work. With the prior versions I had absolutely no issues like that. 
I already disabled all validators and set -Xmx4096m in eclipse.ini  ... didn't help much. I deleted the history in the .metadata\.plugins\org.eclipse.core.resources and .metadata\.plugins\org.eclipse.jdt.core with no effect.
My OS is Win 10 Pro and default JRE is JDK13. 

Following is my full ini:

```
-startup
plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.win32.win32.x86_64_1.2.700.v20221108-1024
-product
org.eclipse.epp.package.jee.product
-showsplash
org.eclipse.epp.package.common
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.win32.x86_64_17.0.7.v20230425-1502/jre/bin
-vmargs
-Dosgi.requiredJavaVersion=13
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Dsun.java.command=Eclipse
-server
-Xverify:none
-Xms256m
-Xmx4096m
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM

```

**Comment by iloveeclipse** [comment]
@ranxero : if you encounter freezes, you should see errors or warnings reported with freeze stack traces in the Error Log view.
Please attach the workspace log here. Without it it is impossible to diagnose the problem.

**Comment by merks** [comment]
Would they need a -D option to enable such freeze traces?

All the works well for me on Windows 10.

**Comment by iloveeclipse** [comment]
> Would they need a -D option to enable such freeze traces?

No.
Products can enable preferences to report freeze, and *I believe* that should be enabled by default by our packages (it is at least enabled by SDK itself).
Please check this preferences that has to be set:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/964108/b9f84823-a6d5-431a-b139-d34189ace38e)

**Comment by ranxero** [comment]
I checked the differences between the prior version I was using and the current one. 
The issue is not related to eclipse itself but to some plugins I installed in the new version. They were all from the JBoss-tools group. I guess that was too much. I didn't uncheck the tools I didn't need and let all JBoss tools being installed that were pre-selected. 
After making a fresh eclipse install and only installing JBoss-Tools and - reporting(2 options checked) everything runs smoothly again. 
I cannot say which one of the JBoss-tools caused this, Would have to test the different combinations. 
Anyway, issue solved, as far as I am concerned.

**Comment by merks** [comment]
Thanks for reporting back!

**Comment by iloveeclipse** [comment]
@merks : if you reopened, do you plan to work on this issue? If not, please close.

**Comment by merks** [comment]
Sorry. Fail to operate via iPhone.
