### ISSUE TITLE
Refresh status... Cannot invoke java.util.List.isEmpty() because resources is null

### ISSUE THREAD

**Issue by losmurfs** [eclipse-platform/eclipse.platform.ui#856]
This bug occurs when refreshing a project, seems to make build take forever.
Popup:
Problem Occurred
"Refresh status..." has encountered a problem.
An internal error occurred during: "Refresh status...".
Cannot invoke "java.util.List.isEmpty()" because "resources" is null
![Screenshot 2023-06-26 083155](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10159345/9aa6544d-b3b1-466d-a8f2-e6e88825f073)
Steps to reproduce:
Open eclipse, refresh project
![Screenshot 2023-06-26 084007](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10159345/762c5c7d-3499-4449-b8a5-456dbb9de068)
![Screenshot 2023-06-26 083840](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10159345/21483582-f494-4377-b740-35be893087bf)
![Screenshot 2023-06-26 083932](https://github.com/eclipse-platform/eclipse.platform.ui/assets/10159345/a3bf6135-0ba8-42be-9424-3a2094ca86cf)

**Comment by iloveeclipse** [comment]
Please attach Eclipse workspace log (Error Log view -> export)

**Comment by jukzi** [comment]
Closing as not enough information provided. Please reopen with reproducer if any or at least logfile

**Comment by vogella** [comment]
@jukzi thanks for cleaning up old issues.

FYI - the usage of the Github ping bot for closing issue older than x (I think we discussed 12 months) was rejected in the past, as several people claimed that leaving old issues open is valuable.
