### ISSUE TITLE
MarkerSupportView Should allow a help link on the FilterConfigurationDialog

### ISSUE THREAD

**Issue by eobrienPilz** [eclipse-platform/eclipse.platform.ui#86]
We would like to have the option of having a help link on the FilterConfigurationDialog. As the dialog is internal we can't extend and there is no method provided to add a help link in the dialog. There is an attachment that shows what we would like to be able to do
![helpLink](https://user-images.githubusercontent.com/58333578/170675082-e1e7de6a-c3b1-4846-97b2-f1f7f59f0c80.png)
.

**Comment by mickaelistria** [comment]
Would the help be a generic help about this dialog, that could go into common Eclipse Platform, or do you want something that's specific to your application?

**Comment by eobrienPilz** [comment]
> Would the help be a generic help about this dialog, that could go into common Eclipse Platform, or do you want something that's specific to your application?

We need something specific to our application. Such as an API to allow the help link to appear on the dialog and a handler to launch the help page when the button is pressed.
I was thinking maybe it could be an addition to markerSupport extension point, because FiltersConfigurationDialog is internal and I'm not sure if its ok to extended for use as an API.

**Comment by eobrienPilz** [comment]
I just added a pull request with a potential fix for this: https://github.com/eclipse-platform/eclipse.platform.ui/pull/348

**Comment by eobrienPilz** [comment]
:)
