### ISSUE TITLE
org.eclipse.ui.tests.datatransfer.ImportExistingProjectsWizardTest failing on Linux

### ISSUE THREAD

**Issue by Shee43** [eclipse-platform/eclipse.platform.ui#863]
In the Build [I20230525-0350](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/), the below tests in org.eclipse.ui.tests.datatransfer.ImportExistingProjectsWizardTest failed
on [cen64](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.ui.tests_ep428I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html)

>```
>Expected no auto-build triggers expected:<0> but was:<1>
>java.lang.AssertionError: Expected no auto-build triggers expected:<0> but was:<1>
>at org.junit.Assert.fail(Assert.java:89)
>at org.junit.Assert.failNotEquals(Assert.java:835)
>at org.junit.Assert.assertEquals(Assert.java:647)
>at org.eclipse.ui.tests.datatransfer.ImportTestUtils$TestBuilder.assertFullBuildWasDone(ImportTestUtils.java:97)
>at org.eclipse.ui.tests.datatransfer.ImportExistingProjectsWizardTest.test21FullBuildAfterImportedProjects(ImportExistingProjectsWizardTest.java:1059)
>at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
>at java.base/java.lang.reflect.Method.invoke(Method.java:578)
>```

**Comment by jukzi** [comment]
also
https://download.eclipse.org/eclipse/downloads/drops4/I20230528-1800/testresults/html/org.eclipse.ui.tests_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20230529-0600/testresults/html/org.eclipse.ui.tests_ep428I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html

not reproducible locally on win

**Comment by Shee43** [comment]
In the Build [I20230815-18000](https://download.eclipse.org/eclipse/downloads/drops4/I20230815-1800/), the below tests in org.eclipse.ui.tests.datatransfer.ImportExistingProjectsWizardTest failed on [cen64](https://download.eclipse.org/eclipse/downloads/drops4/I20230815-1800/testresults/html/org.eclipse.ui.tests_ep429I-unit-cen64-gtk3-java20_linux.gtk.x86_64_20.html)

 ```
Expected no auto-build triggers expected:<0> but was:<1>
java.lang.AssertionError: Expected no auto-build triggers expected:<0> but was:<1>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.eclipse.ui.tests.datatransfer.ImportTestUtils$TestBuilder.assertFullBuildWasDone(ImportTestUtils.java:97)
at org.eclipse.ui.tests.datatransfer.ImportExistingProjectsWizardTest.test21FullBuildAfterImportedProjects(ImportExistingProjectsWizardTest.java:1058)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
```

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-platform/eclipse.platform.ui/issues/811
