### ISSUE TITLE
org.eclipse.ui.tests.progress.ProgressViewTests.testItemOrder failing on Windows

### ISSUE THREAD

**Issue by Shee43** [eclipse-platform/eclipse.platform.ui#864]
In the Build [I20230525-0350](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/), the below tests in  org.eclipse.ui.tests.progress.ProgressViewTests.testItemOrder failed
on [win32](https://download.eclipse.org/eclipse/downloads/drops4/I20230525-0350/testresults/html/org.eclipse.ui.tests_ep428I-unit-win32-java17_win32.win32.x86_64_17.html)

>```
>Wrong job order: arrays first differed at element [0]; expected:<1. User Job(1299)> but was:<6. Low Priority Job(1304)>
>at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)
>at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
>at org.junit.Assert.internalArrayEquals(Assert.java:534)
>at org.junit.Assert.assertArrayEquals(Assert.java:285)
>at org.eclipse.ui.tests.progress.ProgressViewTests.testItemOrder(ProgressViewTests.java:193)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>```

**Comment by jukzi** [comment]
Can not reproduce locally. Must be a random fail.

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-platform/eclipse.platform.ui/issues/195
