### ISSUE TITLE
Standard text editor ignores preferences for foreground color

### ISSUE THREAD

**Issue by peterdell** [eclipse-platform/eclipse.platform.ui#869]
The following issue is present in Version: 2022-12 (4.26).
I have the dark theme active. When I create a plain text .txt file and put some there is is displayed in the light grey color configured in the preferences "General / Editors / Text Editors / Appearance and color options / Foreground color". But changing the color there has no effect. All the other color settings there (selection foreground and background, line numbers, .... ) work correctly. In this example I've set the foreground to purple:

![image](https://user-images.githubusercontent.com/10855380/229361583-4bd6ef40-cc6d-4bb7-b676-76032a985fc2.png)

**Comment by laeubi** [comment]
> The following issue is present in Version: 2022-12 (4.26).

Have you tried 2023-03 already?

**Comment by peterdell** [comment]
Oh, sure, I should have verified there first. But I did now and yes, the issue is the same in https://download.eclipse.org/eclipse/downloads/drops4/R-4.27-202303020300/download.php?dropFile=eclipse-platform-4.27-win32-x86_64.zip.

**Comment by mickaelistria** [comment]
I suspect the Theme engine incorrectly overrides the color here. Can you please try disable theming to verify the preference setting work?

**Comment by peterdell** [comment]
You are right, if theming is disabled, the preferences setting is used.

**Comment by DenisUngemach** [comment]
The color which overrides the preference is in the plugin org.eclipse.ui.themes in file e4-dark_partstyle.css the color: #AAAAAA line 59. 
The override happens if the TextEditor gets focus.
With a breakpoint in StyledText in the method setForeground(Color color)  it is possible to get the stack trace of the stylesheet override.

**Comment by DenisUngemach** [comment]
Bug already existed: [Dark Theme: Custom editor background color not properly applied](https://bugs.eclipse.org/bugs/show_bug.cgi?id=559321) 
Related to this might be:  [Move Color options from Text Editors to the Colors and Fonts preference page](https://bugs.eclipse.org/bugs/show_bug.cgi?id=531033)  

Further discussion about setForeground/setBackground: https://github.com/eclipse-platform/eclipse.platform.ui/issues/306

**Comment by BeckerWdf** [comment]
this was fixed by https://github.com/eclipse-platform/eclipse.platform.ui/pull/1036
