### ISSUE TITLE
Press Save or Enter Empty multiple times to appear in a code prompt box

### ISSUE THREAD

**Issue by baily-s** [eclipse-platform/eclipse.platform.ui#891]
Pressing the Save shortcut multiple times or entering other invalid characters will pop up a code prompt box.

**Comment by mickaelistria** [comment]
Can you please provide detailed steps to reproduce from a fresh and recent installation of Eclipse IDE?

**Comment by baily-s** [comment]
1. Mac M1 chip version
2. Eclipse 2022-3 version
3. Set auto activation triggers for java:.abcdefghijklmnopqrstuvwxyz
4. At this time, press the shortcut key (ctrl+s) multiple times and a prompt box will pop up
5. I guess auto activation triggers should be triggered, but my intention is to save
thakns

**Comment by mickaelistria** [comment]
I cannot reproduce it on Fedora 36.

**Comment by elsazac** [comment]
The linked PR has been merged, so this can be closed.
