### ISSUE TITLE
"Confirm Enablement" Dialog (for Capabilities) causes Eclipse to hang in MacOSX

### ISSUE THREAD

**Issue by juanpabloramirezibm** [eclipse-platform/eclipse.platform.ui#895]
We disable several perspectives in our RCP application to simplify the gui. In MacOS Ventura, when opening any perspective that requires a Capability to be enabled, the Confirm Enablement dialog fails to show and hangs Eclipse. 

This is the dialog:
<img width="358" alt="Screen Shot 2023-03-31 at 10 06 38 AM(2)" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/138041612/887821d3-b581-45b1-a84d-f942ad81a292">

The dialog is the one referenced by the Preferences > General > Capabilities > "Prompt when enabling capabilities" checkbox preference option.

We've confirmed this is present in both Eclipse 4.23 and 4.8.

On Windows and Linux (irrespective of OS versions) the dialog shows correctly.

The hang prevents the UI Responsiveness Monitoring system from logging the error, and the application must be force quit, so I do not have a stack trace / error log to provide.

**Comment by iloveeclipse** [comment]
Please create jstack from hanging Eclipse and attach it here.

**Comment by jukzi** [comment]
Closing due to missing information
