### ISSUE TITLE
Allow to configure UI defaults for new workspaces

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.ui#91]
@mickaelistria suggested to change some UI defaults, which I personally like.
As some people will not like this, we could offer a configuration similar to what @merks implemented for Oomph / EPL (which AFAIK no EPP currently actively uses.

![image](https://user-images.githubusercontent.com/139910/171613764-9dd308da-9913-48ac-99cd-53e9d32adfe4.png)

I made a "professional" ;-) mockup-up for such a flag which could trigger a wizard to configure a configuration wizard.

![image](https://user-images.githubusercontent.com/139910/171613963-64062cf3-2eb4-4c5b-9e4a-a6994abc87b1.png)

This wizard could set selected preferences in a certain folder, e.g.  .eclipse in the user home and these prefeence could be applied for each new workspace. Preferences which come to mind:

* Dark Theme / Light Theme
* Toolbar visible / Toolbar not visible.

This would allow us to modify the default with the option for users to change the new default back to their preferences.

**Comment by laeubi** [comment]
> I made a "professional" ;-) mockup-up for such a flag which could trigger a wizard to configure a configuration wizard.

This does not look like Standard SWT/Windows/GKT/Anything/...  :-P

> This would allow us to modify the default with the option for users to change the new default back to their preferences.

Isn't there already the Welcome page offering something similar for "new" features? Maybe it would make more sense to have a comparison Image:

"this is how it looks before" --> "this is the new Default"
[please click here to change the defaults]

this would then also allow people to get aware if the do not always show a workspace chooser.

**Comment by vogella** [comment]
Welcome screen would also work. As long as we give an easy way to change the new defaults back to the user prference, it should be easier for us to adjust the defaults.

**Comment by vogella** [comment]
@merks could your configuration wizard be extraced from Oomph and contributed to platform without a lot of work or it is strongly dependent on Oomph code?

**Comment by merks** [comment]
I don't think that would be so easy.  It's pretty pimped up, making it harder to update to new preference and then is of course it's geared toward recording the preferences the way that Oomph records preferences...
