### ISSUE TITLE
ControlObservableValueTest.testObserveFocus fails on Windows

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.ui#910]
After merge of https://github.com/eclipse-platform/eclipse.platform.swt/pull/553 `ControlObservableValueTest.testObserveFocus` is **consistently** failing on Windows.

https://download.eclipse.org/eclipse/downloads/drops4/I20230704-1800/testresults/html/org.eclipse.jface.tests.databinding_ep429I-unit-win32-java17_win32.win32.x86_64_17.html

```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at org.eclipse.jface.tests.internal.databinding.swt.ControlObservableValueTest.testObserveFocus(ControlObservableValueTest.java:223)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

[According](https://github.com/eclipse-platform/eclipse.platform.swt/pull/553#issuecomment-1620813588) to @SyntevoAlex :  

> The problem is in test only.
It can be seen how it struggles to activate Shell:

> https://github.com/eclipse-platform/eclipse.platform.ui/blob/f0ce6e75ebab0142f7ff9f13afda67554e0f3818/tests/org.eclipse.jface.tests.databinding/src/org/eclipse/jface/tests/internal/databinding/swt/ControlObservableValueTest.java#L217-L221

> And here (old logs before patch) it can be seen that this never worked on Windows:
https://download.eclipse.org/eclipse/downloads/drops4/I20230612-1800/testresults/ep429I-unit-win32-java17_win32.win32.x86_64_17/org.eclipse.jface.tests.databinding.BindingTestSuite.txt

> ControlObservableValueTest.testObserveFocus() start active shell: null
active shell (2): null
active shell (3): null
So the test was always kind of broken.

> I think that test needs to wait for SWT.Activate properly, like we did here:
https://github.com/syntevo/eclipse.platform.swt/blob/9e43c2659d35e66a350260999e25b432c1344f50/tests/org.eclipse.swt.tests/JUnit%20Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Shell.java#L942

**Comment by SyntevoAlex** [comment]
I will investigate this tomorrow. Hopefully I can reproduce it on my machine.

**Comment by SyntevoAlex** [comment]
Not reproducible locally. I added SWT's helper method and some debugging code.

**Comment by HeikoKlare** [comment]
Became obsolete because of reverting changed behavior of https://github.com/eclipse-platform/eclipse.platform.swt/pull/553 in https://github.com/eclipse-platform/eclipse.platform.swt/pull/743.
