### ISSUE TITLE
Eclipse 2023-06 IE Embedded Webpage Error Displays Whenever I View Tooltip

### ISSUE THREAD

**Issue by plaincube** [eclipse-platform/eclipse.platform.ui#915]
Whenever I hover over an object to view its tooltip, the Embedded IE Browser's Webpage Error popup (the one with the debugger) displays.
Why is the tooltips being loaded through IE? How can I change this?

**Comment by merks** [comment]
Maybe share a picture of what you see so we know exactly what you are taking about; you can paste images directly into the issue description.

Also, please open the Error Log view and check if there are logged errors there.  If so, sharing the stack trace would be good.

it is possible to use Edge, but you have to install WebView:

https://www.eclipse.org/forums/index.php/t/1108905/

**Comment by plaincube** [comment]
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/93862196/5cbd596a-e2b0-4830-bdff-b14d5cb3cfe0)
Hover over 
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/93862196/ee837343-e1b5-45e9-b5e1-2e7714a1b617)

**Comment by merks** [comment]
I see. This looks to be a problem perhaps specific to m2e's POM editor.  Do hovers in *.java files work properly?

**Comment by plaincube** [comment]
Yes they do.

**Comment by akurtakov** [comment]
This points to issue with highlight.js which is used in lsp4e project.  Please try using [Edge browser](https://www.eclipse.org/swt/faq.php#howuseedge) as IE is kind of dead browser.

**Comment by plaincube** [comment]
Thanks for your help! =)

**Comment by akurtakov** [comment]
So I assume hover works for you now ?

**Comment by plaincube** [comment]
Yes, it works with the Chromium/Edge setting (no difference).
