### ISSUE TITLE
My build envinronment: openjdk/17.0.5, maven/3.8.2

### ISSUE THREAD

**Issue by VietHungPhan** [eclipse-platform/eclipse.platform.ui#922]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:01 min
[INFO] Finished at: 2023-07-07T11:24:47-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.4:validate-classpath (default-validate-classpath) on project com.ericsson.eecs.shared.branding: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:3.0.4:validate-classpath failed: org.osgi.framework.BundleException: Bundle com.ericsson.eecs.shared.branding cannot be resolved:com.ericsson.eecs.shared.branding [75]
[ERROR]   Unresolved requirement: Require-Bundle: org.eclipse.ui.intro
[ERROR]     -> Bundle-SymbolicName: org.eclipse.ui.intro; bundle-version="3.7.0.v20230503-0628"; singleton:="true"
[ERROR]        org.eclipse.ui.intro [2]
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.help.base; bundle-version="[4.0.0,5.0.0)"; resolution:="optional"
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.workbench
[ERROR]            -> Bundle-SymbolicName: org.eclipse.e4.ui.workbench; bundle-version="1.15.0.v20230501-1823"; singleton:="true"
[ERROR]               org.eclipse.e4.ui.workbench [57]
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.model.workbench; bundle-version="1.2.0"
[ERROR]                   -> Bundle-SymbolicName: org.eclipse.e4.ui.model.workbench; bundle-version="2.4.0.v20230404-0801"; singleton:="true"
[ERROR]                      org.eclipse.e4.ui.model.workbench [55]
[ERROR]                        Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR]                          -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.0.v20230429-1914"; singleton:="true"
[ERROR]                             org.eclipse.e4.core.services [38]
[ERROR]                               Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.component)(version>=1.2)(!(version>=2.0)))"
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.services; bundle-version="0.9.0"
[ERROR]                   -> Bundle-SymbolicName: org.eclipse.e4.ui.services; bundle-version="1.6.0.v20230501-1823"; singleton:="true"
[ERROR]                      org.eclipse.e4.ui.services [48]
[ERROR]                        Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR]                          -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.0.v20230429-1914"; singleton:="true"
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR]                   -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.0.v20230429-1914"; singleton:="true"
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.6.0,4.0.0)"
[ERROR]            -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.203.100.v20230417-1307"; singleton:="true"
[ERROR]               org.eclipse.ui [69]
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.ui.workbench; bundle-version="[3.128.0,4.0.0)"; visibility:="reexport"
[ERROR]                   -> Bundle-SymbolicName: org.eclipse.ui.workbench; bundle-version="3.129.0.v20230525-0648"; singleton:="true"
[ERROR]                      org.eclipse.ui.workbench [70]
[ERROR]                        Unresolved requirement: Import-Package: org.eclipse.e4.core.commands.internal
[ERROR]                          -> Export-Package: org.eclipse.e4.core.commands.internal; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="1.1.0.v20230501-1823"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,org.eclipse.ui.workbench"
[ERROR]                             org.eclipse.e4.core.commands [33]
[ERROR]                               Unresolved requirement: Import-Package: org.eclipse.e4.core.services.log
[ERROR]                                 -> Export-Package: org.eclipse.e4.core.services.log; bundle-symbolic-name="org.eclipse.e4.core.services"; bundle-version="2.4.0.v20230429-1914"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,  org.eclipse.e4.ui.services,  org.eclipse.e4.ui.workbench,  org.eclipse.e4.ui.workbench.renderers.swt,  org.eclipse.e4.ui.workbench.swt,  org.eclipse.ui.workbench,  org.eclipse.e4.core.commands"
[ERROR]                        Unresolved requirement: Import-Package: org.eclipse.e4.ui.internal.workbench
[ERROR]                          -> Export-Package: org.eclipse.e4.ui.internal.workbench; bundle-symbolic-name="org.eclipse.e4.ui.workbench"; bundle-version="1.15.0.v20230501-1823"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.workbench.fragment,  org.eclipse.e4.ui.workbench.renderers.swt,  org.eclipse.e4.ui.workbench.swt,  org.eclipse.ui.workbench,  org.eclipse.ui.ide.application,  org.eclipse.ui.ide,  org.eclipse.e4.emf.xpath.test"
[ERROR]                        Unresolved requirement: Import-Package: org.eclipse.e4.ui.internal.workbench.addons
[ERROR]                          -> Export-Package: org.eclipse.e4.ui.internal.workbench.addons; bundle-symbolic-name="org.eclipse.e4.ui.workbench"; bundle-version="1.15.0.v20230501-1823"; version="0.0.0"; x-internal:="true"
[ERROR]                        Unresolved requirement: Import-Package: org.eclipse.e4.core.commands
[ERROR]                          -> Export-Package: org.eclipse.e4.core.commands; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="1.1.0.v20230501-1823"; version="0.0.0"
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by VietHungPhan** [comment]
My platform repository is https://download.eclipse.org/eclipse/updates/4.28/R-4.28-202306050440/plugins/. I have tried to build 4.28.0-SDK, unfortunately I always get the unresolved error from the platform org.eclipse.ui. Please help me to fix the issue.

**Comment by elsazac** [comment]
@VietHungPhan - is this still an issue for you? let me know, and if yes I can spend some time debugging. If so, pls provide steps to reproduce.

**Comment by VietHungPhan** [comment]
Thanks Elsa. The problem has been fixed, please close the ticket.

**Comment by akurtakov** [comment]
As per previous reply.

**Comment by VietHungPhan** [comment]
Thanks Elsa. The problem has been fixed. Please close the ticket.
BR,Viet-Hung Phan Eng.

    On Wednesday, January 17, 2024 at 06:35:22 a.m. EST, Elsa Zacharia ***@***.***> wrote:  
 
 


@VietHungPhan - is this still an issue for you? let me know, and if yes I can spend some time debugging. If so, pls provide steps to reproduce.

**Comment by NithiyananthamArunagiri** [comment]
I have tried to build 4.33.0-SDK (OpenJDK 23 and maven 3.9.5) in local machine, we are getting below error message 

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:3.0.4:validate-classpath (default-validate-classpath) on project com.ericsson.eecs.shared.branding: Execution default-validate-classpath of goal org.eclipse.tycho:tycho-compiler-plugin:3.0.4:validate-classpath failed: org.osgi.framework.BundleException: Bundle com.ericsson.eecs.shared.branding cannot be resolved:com.ericsson.eecs.shared.branding [73]
[ERROR]   Unresolved requirement: Require-Bundle: org.eclipse.ui.intro
[ERROR]     -> Bundle-SymbolicName: org.eclipse.ui.intro; bundle-version="3.7.400.v20240414-0828"; singleton:="true"
[ERROR]        org.eclipse.ui.intro [2]
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.help.base; bundle-version="[4.0.0,5.0.0)"; resolution:="optional"
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.workbench
[ERROR]            -> Bundle-SymbolicName: org.eclipse.e4.ui.workbench; bundle-version="1.15.500.v20240730-1919"; singleton:="true"
[ERROR]               org.eclipse.e4.ui.workbench [54]
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.services; bundle-version="0.9.0"
[ERROR]                   -> Bundle-SymbolicName: org.eclipse.e4.ui.services; bundle-version="1.6.300.v20231201-1637"; singleton:="true"
[ERROR]                      org.eclipse.e4.ui.services [45]
[ERROR]                        Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR]                          -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.400.v20240413-1529"; singleton:="true"
[ERROR]                             org.eclipse.e4.core.services [35]
[ERROR]                               Unresolved requirement: Require-Capability: osgi.extender; filter:="(&(osgi.extender=osgi.component)(version>=1.2)(!(version>=2.0)))"
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.e4.ui.model.workbench; bundle-version="1.2.0"
[ERROR]                   -> Bundle-SymbolicName: org.eclipse.e4.ui.model.workbench; bundle-version="2.4.300.v20240321-1245"; singleton:="true"
[ERROR]                      org.eclipse.e4.ui.model.workbench [52]
[ERROR]                        Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR]                          -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.400.v20240413-1529"; singleton:="true"
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.e4.core.services; bundle-version="0.9.0"
[ERROR]                   -> Bundle-SymbolicName: org.eclipse.e4.core.services; bundle-version="2.4.400.v20240413-1529"; singleton:="true"
[ERROR]          Unresolved requirement: Require-Bundle: org.eclipse.ui; bundle-version="[3.6.0,4.0.0)"
[ERROR]            -> Bundle-SymbolicName: org.eclipse.ui; bundle-version="3.206.100.v20240720-1232"; singleton:="true"
[ERROR]               org.eclipse.ui [67]
[ERROR]                 Unresolved requirement: Require-Bundle: org.eclipse.ui.workbench; bundle-version="[3.130.0,4.0.0)"; visibility:="reexport"
[ERROR]                   -> Bundle-SymbolicName: org.eclipse.ui.workbench; bundle-version="3.133.0.v20240818-1923"; singleton:="true"
[ERROR]                      org.eclipse.ui.workbench [68]
[ERROR]                        Unresolved requirement: Import-Package: org.eclipse.e4.ui.internal.workbench
[ERROR]                          -> Export-Package: org.eclipse.e4.ui.internal.workbench; bundle-symbolic-name="org.eclipse.e4.ui.workbench"; bundle-version="1.15.500.v20240730-1919"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.workbench.fragment,  org.eclipse.e4.ui.workbench.addons.swt,  org.eclipse.e4.ui.workbench.renderers.swt,  org.eclipse.e4.ui.workbench.swt,  org.eclipse.ui.workbench,  org.eclipse.ui.ide.application,  org.eclipse.ui.ide,  org.eclipse.e4.emf.xpath.test"
[ERROR]                        Unresolved requirement: Import-Package: org.eclipse.e4.ui.internal.workbench.addons
[ERROR]                          -> Export-Package: org.eclipse.e4.ui.internal.workbench.addons; bundle-symbolic-name="org.eclipse.e4.ui.workbench"; bundle-version="1.15.500.v20240730-1919"; version="0.0.0"; x-friends:="org.eclipse.ui.workbench"
[ERROR]                        Unresolved requirement: Import-Package: org.eclipse.e4.core.commands
[ERROR]                          -> Export-Package: org.eclipse.e4.core.commands; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="1.1.400.v20240424-0444"; version="0.0.0"
[ERROR]                             org.eclipse.e4.core.commands [30]
[ERROR]                               Unresolved requirement: Import-Package: org.eclipse.e4.core.services.log
[ERROR]                                 -> Export-Package: org.eclipse.e4.core.services.log; bundle-symbolic-name="org.eclipse.e4.core.services"; bundle-version="2.4.400.v20240413-1529"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,  org.eclipse.e4.ui.services,  org.eclipse.e4.ui.workbench,  org.eclipse.e4.ui.workbench.renderers.swt,  org.eclipse.e4.ui.workbench.swt,  org.eclipse.ui.workbench,  org.eclipse.e4.core.commands"
[ERROR]                        Unresolved requirement: Import-Package: org.eclipse.e4.core.commands.internal
[ERROR]                          -> Export-Package: org.eclipse.e4.core.commands.internal; bundle-symbolic-name="org.eclipse.e4.core.commands"; bundle-version="1.1.400.v20240424-0444"; version="0.0.0"; x-friends:="org.eclipse.e4.ui.bindings,org.eclipse.ui.workbench,org.eclipse.e4.ui.workbench,org.eclipse.e4.ui.workbench.renderers.swt
