### ISSUE TITLE
Command handler state is not observed

### ISSUE THREAD

**Issue by basilevs** [eclipse-platform/eclipse.platform.ui#925]
This is discussed in [Bug 549802](https://bugs.eclipse.org/bugs/show_bug.cgi?id=549802)

Corresponding tests are disabled:
https://github.com/eclipse-platform/eclipse.platform.ui/blob/50553ea8426afdc390e14676abf8906c44d184a4/tests/org.eclipse.ui.tests/Eclipse%20UI%20Tests/org/eclipse/ui/tests/commands/StateTest.java#L43
https://github.com/eclipse-platform/eclipse.platform.ui/blob/50553ea8426afdc390e14676abf8906c44d184a4/tests/org.eclipse.ui.tests/Eclipse%20UI%20Tests/org/eclipse/ui/tests/commands/ToggleStateTest.java#L45

Commands try to subscribe to handler state in `org.eclipse.core.commands.Command.addState(String, State)` and `org.eclipse.core.commands.Command.setHandler(IHandler)`, but handler proxies fail to propagate `org.eclipse.core.commands.IObjectWithState` protocol.

Offending proxies:

- org.eclipse.ui.internal.WorkbenchHandlerServiceHandler
- org.eclipse.ui.internal.handlers.E4HandlerProxy

While `org.eclipse.ui.internal.handlers.HandlerProxy.handleStateChange(State, Object)` does propagate the states to the actual handler, it is never called as upstream proxies do not invoke `HandlerProxy.addState()`

[Attached is a simple plugin with a stateful command handler](https://github.com/eclipse-platform/eclipse.platform.ui/files/11995015/handler_state_fail.zip), events from which fail to propagate to command framework.
The menu item is "File/I should blink". It does not change state even if menu is reopened.

### Workaround
if command id is known, update command state through service locator:
```
	@Override
	public void setEnabled(Object evaluationContext) {
		super.setEnabled(evaluationContext);
		boolean isRegisteredIdle;
		try {
			Stream<JavaThread> threads = getThreads(evaluationContext);
			isRegisteredIdle = threads.parallel()
					.anyMatch(Activator.getDefault()::isIdle);
		} catch (ExecutionException e) {
			LOG.error("Failed to process selected threads", e);
			isRegisteredIdle = false;
		}
		
		IWorkbenchSite site;
		try {
			site = HandlerUtil.getActiveSiteChecked(adapt(evaluationContext));
		} catch (ExecutionException e) {
			throw new IllegalStateException(e);
		}
		State state = site.getService(ICommandService.class).getCommand("org.basilevs.jstackfilter.eclipse.ui.markidle").getState(RegistryToggleState.STATE_ID);
		state.setValue(isRegisteredIdle);
	}
```

**Comment by iloveeclipse** [comment]
PR caused regression, reopening issue.
