### ISSUE TITLE
[Coding conventions] Using brackets for blocks of code with only 1 line of code

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#928]
The issue was raised by @HeikoKlare in https://github.com/eclipse-platform/eclipse.platform.ui/pull/755#discussion_r1256321294

The easiest way to make sure this always happens is by setting it in the preferences: 

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/2205684/14693c67-f2da-4bc6-b11a-850847d99cd7)

What do you guys think:
1. Are you in favor of adding this as a coding convention? (I'm in favor so 👍  from my side)
2. If yes, do you see any other way of doing it besides setting this property in each and every project?

Any hints on the second question would be highly appreciated since setting the property in each project is a load of work and it can easily be forgotten when setting new projects (also, setting only that property on 1 project added like 30+ changed lines in the properties file).

Thank you in advance for your participation!

**Comment by mickaelistria** [comment]
we could discuss the proposal of making it the default setting in JDT directly.

**Comment by fedejeanne** [comment]
> we could discuss the proposal of making it the default setting in JDT directly.

Pardon my ignorance but how would that look like (_i.e._ which files would need to be changed?) and how far would those settings reach? I'm assuming several repos would be affected?

**Comment by mickaelistria** [comment]
I imagine it's a preference to change in JDT UI preference initializer. If JDT accepts that change, then it will mean all projects that do not set a specific value for the setting will then get brackets added by formatter.

**Comment by fedejeanne** [comment]
I see. 

If possible, would you kindly transfer this issue to the proper repo? If not, I can create a new one in ... `eclipse-jdt/eclipse.jdt.ui` ?

**Comment by mickaelistria** [comment]
We cannot transfer issue from eclipse-platform to eclipse-jdt. Opening a new on in `eclipse-jdt/eclipse.jdt.ui` as you guessed is the best appraoch.

**Comment by fedejeanne** [comment]
> We cannot transfer issue from eclipse-platform to eclipse-jdt. Opening a new on in `eclipse-jdt/eclipse.jdt.ui` as you guessed is the best appraoch.

Understood 👍 

I copied this issue to: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/667

I'm closing this issue so we can resume the discussion there. 
Thank you for participating!

**Comment by fedejeanne** [comment]
> We cannot transfer issue from eclipse-platform to eclipse-jdt. Opening a new on in `eclipse-jdt/eclipse.jdt.ui` as you guessed is the best appraoch.

Understood 👍 

I copied this issue to: https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/667

I'm closing this issue so we can resume the discussion there. 
Thank you for participating!
