### ISSUE TITLE
PreferencePage renders error/warn message as Text on Macos that looks confusing

### ISSUE THREAD

**Issue by fyudanov** [eclipse-platform/eclipse.platform.ui#930]
The Text element is readonly, but still this may initially confuse user, because of looking like editable field, not just like a label.

![Screen Shot 2023-07-10 at 23 57 17](https://github.com/eclipse-platform/eclipse.platform.ui/assets/743434/9729a885-4280-4efd-885a-7db6edf08c72)

Looks even more confusing on Linux (e.g. RHEL) where Text element can be focused with caret shown.
Looks fine on Windows.

It seems like the issue is only applicable to PreferencePage, the other dialogs/wizards don't use Text element for message displaying.

**Comment by elsazac** [comment]
looks like the logic is implemented here (in JDT UI, not in this repo):
https://github.com/eclipse-jdt/eclipse.jdt.ui/blob/8c6926b3c935764ecf40e7572beb6dc858d12aaa/org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/preferences/JavaBuildConfigurationBlock.java#L301-L317

request to transfer this issue to jdt.ui repo

**Comment by merks** [comment]
Issues can't be transferred between organizations.

 Please open an issue here:

https://github.com/eclipse-jdt/eclipse.jdt.ui/issues
