### ISSUE TITLE
Suspend all validators does not suspend validators

### ISSUE THREAD

**Issue by hohwille** [eclipse-platform/eclipse.platform.ui#943]
In 2011 a bug [The 'Suspend all validators' checkbox under Window > Preferences > Validation does not suspend validators](https://bugs.eclipse.org/bugs/show_bug.cgi?id=338759) was filed. More than a decade and many eclipse releases later my observation is as following:

In my current project I am waiting more than 30 minutes for "Validation (xx%)" to complete. All these validators do things that I do not want to have. I do not want Eclipse to validate every JSON, XML, HTML, JavaScript, etc. file at all. I just want to do Java coding and scanning and validating all these files takes forever and causes red error icons that only cause confusion to me.
The functionality "Suspend all validators" has been removed from the UI.
Instead I find many specific `Validation` subsections in the `Preferences` what might make sense due to the plugin architecture.
I went through all of them and tried to disable what I can (side note: Labelling a checkbox `Enables or disables all validations` is a usability fraud). 
Still I get the same result. Eclipse is busy forever doing things that typical users never requested it to do and there seems no way to stop it. Even more crazy, the JSON validator still reports red errors for an empty JSON file present in our git repo but I have unchecked all validations in Preferences > JSON > JSON Files > Validation. 
There have been endless flame-wars on the web about eclipse hanging, being grayed out, stalled, whatever.
I still like eclipse and would love to use it, if I only was able to tame it.

Is there a chance to get this solved in the next couple of decades?
I do not want it to validate all the web content stuff if I downloaded a Java IDE (java edition of eclipse).
Should and can I simply uninstall all the web related plugins after all the complex inter-dependencies? Or how it is possible to get around all this undesired effects in some other way?
As one can see with the old bugzilla issue, various stackoverflow posts (e.g. https://stackoverflow.com/questions/15899976/turning-off-eclipse-validation or https://www.eclipse.org/forums/index.php/t/220342/), etc. there seems to be a clear demand for such improvement but Eclipse seems to ignore this.
Also I would love that Eclipse can simply ignore `node_modules` folders instead of scanning them recursively into its virtual filesystem until the OutOfMemoryException death.

Sorry, if I might be in the wrong place but I am clueless where to really report this issue. If the eclipse platform and JDT team could have a chat on this topic that would be great. I am happy to file more specific issues in the according plugins and projects and close this one once there is some first alignment how to proceed with this problem. Thanks in advance.

**Comment by hohwille** [comment]
It does not seem to be possible to uninstall web developer tools.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1923119/70c77085-672a-4c52-bcef-1b5121891115)
It would also still be nice to have the editor support. But the validation is so annoying that I would rather loose all the features.

**Comment by hohwille** [comment]
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1923119/53fe7bb7-acbc-48e8-be2f-ecc5d77abeb6)
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1923119/4d9dd7f1-8eea-4de5-8d16-32fe089c90bc)
No effect!

**Comment by mickaelistria** [comment]
This page and feature is not provided by Eclipse Platform. Please try to identify which plugin contributes it (Plugin Spy can help for that), and report it to the relevant project (most likely webtools).

**Comment by vogella** [comment]
Jörg, you could use another download like the Eclipse for Java developer
and could add Wild Web Developer (and not WTP). This should avoid using the
piece of code

Mickael Istria ***@***.***> schrieb am Di., 18. Juli 2023,
16:41:

**Comment by hohwille** [comment]
> Jörg, you could use another download like the Eclipse for Java developer
and could add Wild Web Developer (and not WTP). This should avoid using the
piece of code

Thanks for your suggestion.
However, I am using the java edition and not JEE and as you can see in my plugins screenshot I do have `Wild Web Developer` that is causing the problems.

**Comment by hohwille** [comment]
> This page and feature is not provided by Eclipse Platform. Please try to identify which plugin contributes it (Plugin Spy can help for that), and report it to the relevant project (most likely webtools).

I was posting the issue here because `IValidator` and the validation infrastructure is coming from this git repository.
I was hoping that it would be possible to still have a feature to `suspend all validators` that would just make eclipse skip the validation step that is triggered centrally and not from within an individual plugin.
However, I can file an issue to `Wild Web Developer` in each according plugin and also create one for the "usability fraud".

**Comment by dashorst** [comment]
We were able to disable all validations successfully in our projects, but since 2025.6 we now have an oodle of HTML warnings/errors that we want to ignore. Similarly to the OP we have lots of XML, HTML, JS, etc files that we specifically don't want to be validated by Eclipse, we use different tooling for that, and the validations take lots of memory, CPU time and are typically a waste.

WWD is probably the culprit in our case as well, as only HTML Problem's are coming through, even though we have disabled all validations.

**Comment by merks** [comment]
Did you check if web tools might be creating the markers? I thought wwd only creates markers when the editor is open.

**Comment by iloveeclipse** [comment]
AFAIK it's webtools feature.

**Comment by dashorst** [comment]
By changing the individual warnings in the settings -> Web -> HTML Files -> Validation pane from warning/error to Ignore I was able to remove the 600 extra warnings in my workspace, but this was previously not needed.

**Comment by merks** [comment]
Web tools.
