### ISSUE TITLE
Save the bounds (size, location) of dialogs

### ISSUE THREAD

**Issue by luapfr** [eclipse-platform/eclipse.platform.ui#949]
As it has the possibility of resizing the screens, it would be very good to save the size of each of the screens, including the settings Form

**Comment by BeckerWdf** [comment]
Can you please elaborate a bit more in details that the issue is?

**Comment by luapfr** [comment]
for you to understand better see this post

https://github.com/dbeaver/dbeaver/issues/20498

**Comment by BeckerWdf** [comment]
So it's basically this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=563362 ?

**Comment by luapfr** [comment]
that same

What do you say about this problem any solution ?

**Comment by marcushoepfner** [comment]
Just to understand (and in order to avoid that other have to follow several links), this is about Preference Dialog correct?
You request that is shall have
- the same size
- and same position (?)
as last time you have closed it.

Is my understanding correct?

**Comment by luapfr** [comment]
>the same size
>and same position (?)
>as last time you have closed it.


Yes












Just to understand (and in order to avoid that other have to follow several links), this is about Preference Dialog correct?
You request that is shall have

the same size
and same position (?)
as last time you have closed it.

Is my understanding correct?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Enviado do Vivaldi Mail. Baixe o Vivaldi de graça em vivaldi.com

**Comment by luapfr** [comment]
Not only preferences all screens should be saved the size and position 


Thankful.




Em Terça-feira, 25 de julho de 2023 05:04:19 (-03:00), marcushoepfner escreveu:



Just to understand (and in order to avoid that other have to follow several links), this is about Preference Dialog correct?
You request that is shall have

the same size
and same position (?)
as last time you have closed it.

Is my understanding correct?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Enviado do Vivaldi Mail. Baixe o Vivaldi de graça em vivaldi.com

**Comment by marcushoepfner** [comment]
What do you mean by all screens?
Sorry, but if you do not provide concrete examples and always only throw a few words in, we will not really making progress here.

I agree on the preference dialog, but what else is missing?
Please provide screen shots and explanation what is missing and what you expect.

This is an open source project. Some maintainers are even maintaining this in their free time and I find it not fair, to just throw a few word. Please give detailed descriptions.

**Comment by marcushoepfner** [comment]
I have create  #964 as a starting point. 
Some questions:

1. Should we move the code up in the type hierarchy to have other preference pages profit:
![2023-07-25_14-52-41](https://github.com/eclipse-platform/eclipse.platform.ui/assets/29301444/ea448b41-7cd6-4cae-81ca-2e8bfc2f8d7e)
E.g. PropertyDialog also extends FilteredPreferenceDialog. PropertyDialog appears if you right click an object in project explorer and select "Properties".

1. Is the dialog settings identifier correct? WorkbenchPreferenceDialog.class.getSimpleName(). 
2. Is there any unit test where I can put additional tests?

**Comment by luapfr** [comment]
The problem is with the Dbeaver that you said you cannot change because it depends on you


I see that all screens should have their sizes and positions saved


Saying which screen in particular is complicated because there are many screens.


https://github.com/dbeaver/dbeaver/issues/20498










Em Terça-feira, 25 de julho de 2023 09:12:39 (-03:00), marcushoepfner escreveu:



What do you mean by all screens?
Sorry, but if you do not provide concrete examples and always only throw a few words in, we will not really making progress here.

I agree on the preference dialog, but what else is missing?
Please provide screen shots and explanation what is missing and what you expect.

This is an open source project. Some maintainers are even maintaining this in their free time and I find it not fair, to just throw a few word. Please give detailed descriptions.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Enviado do Vivaldi Mail. Baixe o Vivaldi de graça em vivaldi.com

**Comment by marcushoepfner** [comment]
And with "screens" you mean dialogs?
And there are not that many dialogs in the Eclipse Platform itself (Workbench Preference Dialog, Some Property Dialogs, the New Wizard and the Save Dialog, and a few more).

If you don't not let us know which ones, we cannot fix it.

**Comment by luapfr** [comment]
I took a picture of all the screens that should be able to save the size








Em Terça-feira, 25 de julho de 2023 10:24:38 (-03:00), marcushoepfner escreveu:



And with "screens" you mean dialogs?
And there are not that many dialogs in the Eclipse Platform itself (Workbench Preference Dialog, Some Property Dialogs, the New Wizard and the Save Dialog, and a few more).

If you don't not let us know which ones, we cannot fix it.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Enviado do Vivaldi Mail. Baixe o Vivaldi de graça em vivaldi.com

**Comment by marcushoepfner** [comment]
There is no picture.

**Comment by luapfr** [comment]
I took a picture of all the screens that should be able to save the size


https://mega.nz/file/EqhG1Z7I#KzM4Fb87r1telThYIuA2yojNx4bmW08IYK6_I9kvAbs


https://mega.nz/file/JrohmKyb#p0kuswqv3T-ckYvM03sUbD4VHhS1Ef69DuoF2u_fK0I


https://mega.nz/file/xzoxgabA#M_I2g5op4VI_TjCrHrc2c9-Zc7wLyXBkQRSwLr5khWo


https://mega.nz/file/0rp1gaIa#5u3sDy4L5yAOMS2cZsgzzzwGO-j4ePjNhG5KO6ovB10


https://mega.nz/file/cjhTgJwL#nB9vZ28jWcNmY3ZJHdjmCYClT-EilORThb0Lmd_ATs0


https://mega.nz/file/tu50mKbb#zFUuinpXH29hulJoS0oSAaQUEeVpViY5AviGrnT3_2g


https://mega.nz/file/sv4y1SjI#E3LTDmXvxTdMMzNR8Iw4cwajf5NfyWzZ7xtxeD5aTBM


https://mega.nz/file/pqRX0BLL#AsfIV3aSyIyiHfsgQhyneHKAXorZNhrjN6y3w_JuErs


https://mega.nz/file/AnpQ0QwR#9dWJpzS3iooyeawjjExO0qdjvJ9WqX77jM_Ik3poCiU


https://mega.nz/file/o6oxnLyL#0rNLl0Sh6Cz9Nwuij62tZLYS4qmNCF-ahv9Wn0XI6cs


https://mega.nz/file/t6RTmRRT#kYX-NU8dM7rspJOiEoYkZWBLwDw52PbRvGS7XF5yxiY


https://mega.nz/file/p2oSGTbZ#ItgawFU6i9R0rcdva04IfNr51dG8YmG49A2yz3Ua6H4




Em Terça-feira, 25 de julho de 2023 14:23:09 (-03:00), marcushoepfner escreveu:



There is no picture.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.


-- 
Enviado do Vivaldi Mail. Baixe o Vivaldi de graça em vivaldi.com

**Comment by laeubi** [comment]
@luapfr you can simply drag & drop the picture in the Github comment area to upload them to github directly.

**Comment by luapfr** [comment]
![Index](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/63b71a30-5d8c-4022-910e-aecbf62cd497)
![Ordem](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/7030d33f-293b-453b-9e38-0417c7fe3b6e)
![PK](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/7f5174fd-638a-4164-9d7e-c8cf2788498d)
![preference](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/c651fc50-4210-45fc-928c-f2b9de84ded0)
![Task](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/4e8fe5e5-57aa-41da-acbd-7250864d540c)
![Column](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/bf00e519-0147-4fd2-8efb-d19cb0e92eec)
![Compare](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/bf7910e3-16e6-4fc9-8e2e-ec14c29505b3)
![DataTransfer](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/a7d3d570-bd04-4991-9e9e-f3529a5c4c7c)
![DataWizad](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/defa5a46-1e8a-4b3f-8f67-8ab4a95887b7)
![ExportTable](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/3c93a727-3111-4649-946f-b7c8cf6de921)
![FK](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/010c8f58-0e40-4025-956f-f569db304292)
![import](https://github.com/eclipse-platform/eclipse.platform.ui/assets/50739062/90922da1-b9be-4149-a9af-029e7c514de7)

**Comment by marcushoepfner** [comment]
Ok, now I got it.
Except from the new wizard and the preference dialog, nothing belongs to native Eclipse.
Maybe to the Dbeaver, I don't know the tool. So you should create issues/bugs somewhere else.

For the preference dialog I have provided PR #964

**Comment by luapfr** [comment]
So the Colleague could program the screens that belong to Eclipse, I also already sent this link to the Dbeaver people, they already said that they will implement it there.




Em Quarta-feira, 26 de julho de 2023 03:12:14 (-03:00), marcushoepfner escreveu:



Ok, now I got it.
Except from the new wizard and the preference dialog, nothing belongs to native Eclipse.
Maybe to the Dbeaver, I don't know the tool. So you should create issues/bugs somewhere else.

For the preference dialog I have provided PR #964

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.


-- 
Enviado do Vivaldi Mail. Baixe o Vivaldi de graça em vivaldi.com

**Comment by BeckerWdf** [comment]
Fixed
