### ISSUE TITLE
SyncExecWhileUIThreadWaitsForLock and FoldersAsProjectsContributionTest are failing from time to time

### ISSUE THREAD

**Issue by marcushoepfner** [eclipse-platform/eclipse.platform.ui#962]
Like in #911 

Refer to:

- https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5653230011/job/15315312687
- https://github.com/eclipse-platform/eclipse.platform.ui/actions/runs/5587249759/job/15133265583

**Comment by HeikoKlare** [comment]
Individual issues already exist for the test failures:
* #789 
* #946
* #907

**Comment by marcushoepfner** [comment]
Thank you. Should have checked it.

**Comment by HeikoKlare** [comment]
No problem. When seeing the issue I just thought that I already came across those test cases before 😉
