### ISSUE TITLE
Error occurs while opening a java/txt file using generic text editor

### ISSUE THREAD

**Issue by Dinesh0723** [eclipse-platform/eclipse.platform.ui#974]
**Pre-conditions:**
Eclipse Version: 2023-06 (4.28.0)
Build id: 20230608-1333
OS - Windows10
**Streps to reproduce:**
1) Open "Open resource" window
2) Type **"*.java"** or **"*.txt"**  and select the file.
3) Right click on the selected file and select open with-> Generic text editor->Unable to open the file (error appears)

**Comment by iloveeclipse** [comment]
I can't reproduce using I20230726-1800. Please attach stack trace.

**Comment by mickaelistria** [comment]
Same, cannot reproduce with recent I-Build.

**Comment by Dinesh0723** [comment]
I have tested in the eclipse SDK version: 2023-09 (4.29) [build id: I20230809-1800] the issue is not reproducible. But the issue is reproducible in IDE version: 2023-09 M2 (4.29.0 M2) [build id: 20230803-1509] downloaded via Oomph installer, refer the attached video.

https://github.com/eclipse-platform/eclipse.platform.ui/assets/130960675/27cae723-cc72-456d-b564-28c743d419ba

**Comment by merks** [comment]
The stack trace suggests it's best to report the problem here:

https://github.com/eclipse/tm4e

We cannot move the issue to another organization, so you need to open a new one there.

**Comment by Dinesh0723** [comment]
A new issue has been created in tm4e [https://github.com/eclipse/tm4e/issues/585].
Hence closing this issue.
