### ISSUE TITLE
 Saving Java file is very slow when the class has many markers

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.ui#983]
Saving the contents of a Java class can take a long time when the class has many markers (errors/warnings/search matches/etc). The reason for this is that updating the markers may trigger up to 3 workspace-operations and each operation triggers a lock release and a graph reduction.

Here's a snapshot of a save action that took over 30 seconds to complete.

![Image](https://user-images.githubusercontent.com/2205684/257476951-e4f23c5d-9a04-4bd3-b4fe-71243f89aaa0.png)

Each of the `set` methods in `MarkerUtilities` ends up calling `DeadLockDetector::reduceGraph` which ends up taking most of the time. Here's an example with `MarkerUtilities::setCharEnd`.

![Image](https://user-images.githubusercontent.com/2205684/257477885-49c23c6e-bc1b-4065-819f-a0665bf8ebfb.png)

**Comment by jukzi** [comment]
> Here's a snapshot of a save action that took over 30 seconds to complete.

for how many markers approx?

**Comment by fedejeanne** [comment]
> > Here's a snapshot of a save action that took over 30 seconds to complete.
> 
> for how many markers approx?

Difficult to say because I only got a sampling, so all I have is the _Hits_ count from VisualVM (it says **55** hits). The class isn't that big though and based on this incomplete screenshot I got, I'd say it couldn't have been more than 300 markers.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/2205684/5f26be2a-79f5-4228-bf4e-becc7dd4cf58)

**Comment by jukzi** [comment]
> couldn't have been more than 300 markers.

Could you please test with an synthetic File that has so many markers (or even many more) if it's really reproducible to get a 30s lag. And if any change finally fixed  it.
I really can't imaging 300 markers would take 30s.

**Comment by fedejeanne** [comment]
I couldn't reproduce the error so far and I agree: under normal circumstances 300 markers don't take that long to be processed (even before #984 and https://github.com/eclipse-platform/eclipse.platform/pull/615). I can imagine something must have made these methods run very slow because they are the main reason for the poor performance:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/2205684/c561a4b6-83dd-465e-8d25-7202e32254db)

I couldn't see any obvious reasons by looking at the code I mean `reduceGraph` and `resizeGraph` do copy arrays and check for locks (hence https://github.com/eclipse-platform/eclipse.platform/pull/615) but that's usually pretty fast.

Any hints about what should I look at?
Here's the sample: [saveChangeSlow.zip](https://github.com/eclipse-platform/eclipse.platform.ui/files/12368942/saveChangeSlow.zip)

**Comment by jukzi** [comment]
I suggest to get a reproducer before trying around in the code.
May be it was a very special file with any special format or encoding or special marker, or overall many markers in the workspace... who knows.
