### ISSUE TITLE
Copy as path for resources

### ISSUE THREAD

**Issue by weberjn** [eclipse-platform/eclipse.platform.ui#998]
Resources in the Project Explorer should have a context menu entry Copy as path (as in Windows 10 Explorer"
and the Resource properties should have a copy icon beside the "Show In System Explorer" icon in the Location line.

Both should copy the file system path of the resource to the system clipboard.

This would be useful for pasting a path into the shell or the open dialog of an editor or ...

Currently you have to select and copy the path from the Resource properties, but this is harder without a mouse on a laptop.

**Comment by jukzi** [comment]
"Copy OS path" feature would be welcome: Please provide a PR. Beware that not everything might have a path. Links should copy the target's path.

**Comment by mickaelistria** [comment]
It's a trade-off: more UI elements means more parsing for users, more time being spent on *any* operations to sort out the one they want. So unless an operation is used frequently enough, it's not worth adding it to a top-level menu as it reduce the accessibility of this menu. The hard part is that there is no objective metric to determine what "frequently enough" mean.
For this case, what about adding a command "Copy filesystem location" to put the location in the clipboard; and make it only visible via Ctrl+3 (all commands are) and in the top-level "Edit" menu?

**Comment by iloveeclipse** [comment]
Not sure what the current default "Copy" does, but instead of providing a second action, why not provide a second clipboard content type that would contain resource path as plain text?

**Comment by jukzi** [comment]
or a copy button in the properties dialog, would help too
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/2971ba2c-915e-4e57-8e25-21be075ab2ca)

**Comment by laeubi** [comment]
> Not sure what the current default "Copy" does, but instead of providing a second action, why not provide a second clipboard content type that would contain resource path as plain text?

It is copied as a file, under linux I can the paste this in a terminal what gives **the filename only** but my shell also offers a "Paste as filename" what gives the full path, but text editors or OpenOffice don't offer that (only file name is copied). So probably it would be enough to have the text flavor of the copied file be the full path?

**Comment by jukzi** [comment]
> Not sure what the current default "Copy" does

currently that pastes the unqualified name. Would be OK for me if that would copy the full system path instead.

**Comment by iloveeclipse** [comment]
So let us copy full path as plain text not just file name.

**Comment by jukzi** [comment]
> So probably it would be enough to have the text flavor of the copied file be the full path?

we would need to check what happens then if you paste it to word/powerpoint, which can paste both types.

**Comment by weberjn** [comment]
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/13678748/29b16828-5c78-4c8a-bb83-2c7fcb243e13)

A little copy icon should not distract the users.

**Comment by Dinesh0723** [comment]
> ![grafik](https://user-images.githubusercontent.com/13678748/261962408-29b16828-5c78-4c8a-bb83-2c7fcb243e13.png)
> 
> A little copy icon should not distract the users.

I agree with this approach. Shall I provide PR for this?

**Comment by Dinesh0723** [comment]
> Resources in the Project Explorer should have a context menu entry Copy as path (as in Windows 10 Explorer" and the Resource properties should have a copy icon beside the "Show In System Explorer" icon in the Location line.
> 
> Both should copy the file system path of the resource to the system clipboard.
> 
> This would be useful for pasting a path into the shell or the open dialog of an editor or ...
> 
> Currently you have to select and copy the path from the Resource properties, but this is harder without a mouse on a laptop.

I also propose context menu change wherein we can have Copy option which inturn have sub menus like Copy, Copy Qualified name and Copy Absolute path instead of increasing the number of items in the context menu. Would it make sense?

I can create a PR once the requirement is clear.

**Comment by jukzi** [comment]
PR welcome for copy icon
